matthiasn/lotti

- .github/workflows/release.yml
- .github/workflows/test.yml
- Makefile
- package.json
> Test branch

- wisely/Makefile
- wisely/analysis_options.yaml
- wisely/lib/blocs/audio/player_cubit.dart
- wisely/lib/blocs/audio/recorder_cubit.dart
- wisely/lib/blocs/journal/journal_cubit.dart
- wisely/lib/blocs/journal_entities_cubit.dart
- wisely/lib/blocs/my_bloc_observer.dart
- wisely/lib/blocs/sync/imap_cubit.dart
- wisely/lib/blocs/sync/imap_tools.dart
- wisely/lib/blocs/sync/outbound_queue_db.dart
- wisely/lib/db/persistence.dart
- wisely/lib/health/health_service.dart
- wisely/lib/location.dart
- wisely/lib/main.dart
- wisely/lib/pages/editor.dart
- wisely/lib/sync/encryption.dart
- wisely/lib/sync/encryption_salsa.dart
- wisely/lib/sync/secure_storage.dart
- wisely/lib/sync/vector_clock.dart
- wisely/lib/theme.dart
- wisely/lib/utils/image_utils.dart
- wisely/lib/widgets/audio_recorder.dart
- wisely/test/encryption_salsa_test.dart
This PR fixes most warnings, from over 100 down to two. Most removed ones seemed very sensible.
> Reduce Dart Analysis Warnings

- wisely/lib/blocs/sync/imap_cubit.dart
This PR adds the most basic version of polling the inbox. This needs to work first, before working on observing the inbox, which likely won't always be stable, or even supported by the server.
> poll inbox

- wisely/lib/blocs/sync/imap_cubit.dart
- wisely/lib/blocs/sync/imap_state.dart
- wisely/lib/pages/settings.dart
- wisely/lib/widgets/sync/imap_status_widget.dart
- wisely/macos/Runner/Release.entitlements
- wisely/pubspec.yaml
Grant Egress network access to release sandbox.
> Release network access

- wisely/lib/blocs/sync/imap_cubit.dart
- wisely/pubspec.yaml
Store last seen offset, only fetch from there on resume.
> Sync: only fetch previously unseen messages

- wisely/lib/blocs/sync/imap_cubit.dart
- wisely/pubspec.yaml
This PR brings back the listener for new messages in the observed inbox, and removes redundant refetch of the last know message.
> bring back new message listener

- wisely/lib/widgets/journal_list_item.dart
- wisely/lib/widgets/map_widget.dart
- wisely/pubspec.yaml
Hide map when geo data invalid & full downscaled image with black background.
> Image display improvements

- wisely/lib/main.dart
- wisely/macos/Flutter/GeneratedPluginRegistrant.swift
- wisely/macos/Runner/DebugProfile.entitlements
- wisely/macos/Runner/Info.plist
- wisely/macos/Runner/Release.entitlements
- wisely/macos/Runner/RunnerDebug.entitlements
- wisely/pubspec.yaml
This PR integrates Sentry, and also fixes this crash reported by Sentry:
> Sentry integration

- wisely/lib/sync/encryption.dart
- wisely/lib/sync/encryption_salsa.dart
This PR adds some instrumentation for the slower functions around encryption/decryption.
> basic instrumentation for encryption-related functions

- wisely/lib/blocs/audio/player_cubit.dart
- wisely/lib/blocs/audio/recorder_cubit.dart
- wisely/lib/blocs/journal/health_cubit.dart
- wisely/lib/blocs/journal/journal_image_cubit.dart
- wisely/lib/blocs/journal/persistence_cubit.dart
- wisely/lib/blocs/journal/persistence_db.dart
- wisely/lib/blocs/sync/imap_cubit.dart
- wisely/lib/blocs/sync/outbound_queue_cubit.dart
- wisely/lib/location.dart
- wisely/lib/pages/editor.dart
- wisely/lib/pages/journal_page.dart
- wisely/lib/sync/secure_storage.dart
- wisely/lib/utils/image_utils.dart
- wisely/lib/widgets/journal_list_item.dart
- wisely/macos/Runner/Info.plist
- wisely/macos/Runner/RunnerDebug.entitlements
This PR enables sync send on desktop. Disabled check for connection status, that needs to be checked/fixed next. Also removing redundant logging.
> Bidirectional Sync

- wisely/lib/blocs/sync/outbound_queue_cubit.dart
Connections to the IMAP server should only be attempted/retried when online. Status is not reliable on macOS - assume connected on macOS instead.
> workaround on macOS for unreliable connections status

- .github/workflows/flutter-test.yml
- wisely/.gitignore
- wisely/Makefile
- wisely/lib/blocs/sync/outbound_queue_cubit.dart
- wisely/lib/main.dart
- wisely/pubspec.yaml
This PR adds Sentry setup for CI plus reporting the connectivity status.
> Sentry setup & connectivity reporting

- wisely/lib/blocs/journal/persistence_db.dart
- wisely/lib/blocs/sync/outbound_queue_db.dart
- wisely/lib/main.dart
- wisely/pubspec.yaml
- wisely/test/audio_widgets_test.dart
This PR ensures that the journal and outbound databases are initialized before they are accesses, addressing this error:
> ensure initialization of SQLite databases before use

- wisely/lib/blocs/audio/recorder_cubit.dart
- wisely/lib/blocs/journal/health_cubit.dart
- wisely/lib/blocs/journal/journal_image_cubit.dart
- wisely/lib/blocs/journal/persistence_cubit.dart
- wisely/lib/blocs/sync/imap_cubit.dart
- wisely/lib/blocs/sync/imap_out_cubit.dart
- wisely/lib/blocs/sync/imap_tools.dart
- wisely/lib/blocs/sync/outbound_queue_cubit.dart
- wisely/lib/blocs/sync/outbound_queue_db.dart
- wisely/pubspec.yaml
This PR improves insight into the application at runtime. This will make it easier to spot performance issues.
> add more instrumentation around potentially long running functions

- wisely/lib/blocs/journal/persistence_cubit.dart
- wisely/lib/blocs/sync/imap_cubit.dart
- wisely/lib/blocs/sync/imap_out_cubit.dart
- wisely/lib/blocs/sync/outbound_queue_cubit.dart
- wisely/lib/blocs/sync/outbound_queue_db.dart
- wisely/pubspec.yaml
This PR adds a bunch of try catch blocks, capturing exceptions into Sentry.
> additional exception capturing in Sentry

- wisely/lib/main.dart
- wisely/lib/theme.dart
- wisely/pubspec.yaml
This PR adds a version header:
> show version in header

- wisely/lib/blocs/audio/player_cubit.dart
- wisely/lib/blocs/audio/recorder_cubit.dart
- wisely/lib/blocs/journal/journal_image_cubit.dart
- wisely/lib/blocs/journal/persistence_db.dart
- wisely/lib/blocs/my_bloc_observer.dart
- wisely/lib/blocs/sync/imap_cubit.dart
- wisely/lib/blocs/sync/outbound_queue_db.dart
- wisely/lib/utils/image_utils.dart
- wisely/pubspec.yaml
This PR adds more try/catch blocks with Sentry capture.
> catching more exception with Sentry capture

- wisely/lib/blocs/journal/journal_image_cubit.dart
- wisely/lib/utils/image_utils.dart
- wisely/pubspec.yaml
This PR changes the image format for internal use to JPG. Unfortunately, HEIC caused issues in Release mode on macOS. Also it's questionable how well supported HEIC is on Linux and Windows.
> use JPG after issues with HEIC support

- package-lock.json
- package.json
- src/cljs/meins/electron/renderer/ui/entry/entry.cljs
This PR hides the story visibility within a task timeline.
> hide story select within task timeline

- wisely/lib/main.dart
- wisely/lib/pages/editor.dart
- wisely/lib/theme.dart
- wisely/lib/widgets/audio_recorder.dart
- wisely/lib/widgets/editor_widget.dart
- wisely/lib/widgets/journal_list_item.dart
- wisely/pubspec.lock
- wisely/pubspec.yaml
This PR refactors the entry editor to be used in the entry detail view as well, where it is now shown in a read-only version. Next, allow updates of existing entries.
> Entry updates, part 1

- wisely/lib/health/health_service.dart
- wisely/pubspec.yaml
This PR adapts activity queries to have an end date of at most now, as in the time of query.
> end date in activity queries

- wisely/ios/Podfile.lock
- wisely/lib/blocs/journal/journal_image_cubit.dart
- wisely/lib/blocs/journal/persistence_cubit.dart
- wisely/lib/blocs/journal/persistence_db.dart
- wisely/lib/blocs/sync/imap_cubit.dart
- wisely/lib/blocs/sync/outbound_queue_cubit.dart
- wisely/lib/blocs/sync/vector_clock_cubit.dart
- wisely/lib/classes/sync_message.dart
- wisely/lib/main.dart
- wisely/lib/pages/editor.dart
- wisely/lib/widgets/editor_widget.dart
- wisely/lib/widgets/entry_modal_widget.dart
- wisely/lib/widgets/entry_tools.dart
- wisely/lib/widgets/journal_list_item.dart
- wisely/pubspec.lock
- wisely/pubspec.yaml
This PR adds updating rich text entries, both in the local database as well as via sync. Conflicts are not handled yet, this will happen in a subsequent PR by comparing the vector clocks and checking for conflicts.
> Entry editor with update sync

- wisely/pubspec.lock
- wisely/pubspec.yaml
This PR updates a bunch of dependencies, except for `freezed` as that included breaking changes and will be updated in a subsequent PR.
> Dependencies

- wisely/lib/blocs/sync/imap/imap_client.dart
- wisely/lib/blocs/sync/imap/inbox_cubit.dart
- wisely/lib/blocs/sync/imap/outbox_cubit.dart
- wisely/lib/blocs/sync/outbound_queue_cubit.dart
- wisely/pubspec.yaml
This PR optimizes polling for sync.
> Mailclient optimization

- wisely/lib/blocs/journal/persistence_cubit.dart
- wisely/lib/sync/encryption.dart
- wisely/lib/sync/encryption_messages.dart
- wisely/pubspec.lock
- wisely/pubspec.yaml
This PR moves encryption and decryption to isolates instead of running in the main thread, which much improves UI responsiveness, for example when importing many entries from sync.
> Encryption and Decryption in Isolates

- wisely/lib/blocs/journal/health_cubit.dart
- wisely/lib/blocs/journal/persistence_cubit.dart
- wisely/lib/blocs/sync/imap/imap_client.dart
- wisely/lib/blocs/sync/imap/inbox_cubit.dart
- wisely/lib/blocs/sync/outbound_queue_cubit.dart
- wisely/pubspec.yaml
This PR reduces simultaneous fetches for the same sequence numbers.
> Sync optimize

- package-lock.json
- package.json
- src/cljs/meins/electron/main/import/audio.cljs
- src/cljs/meins/electron/main/import/images.cljs
- src/test/meins/shared/import_test.cljs
- src/test/meins/shared/test-json/test3.aac.json
- wisely/lib/blocs/journal/persistence_cubit.dart
- wisely/lib/blocs/sync/imap/inbox_cubit.dart
- wisely/lib/blocs/sync/imap/inbox_save_attachments.dart
- wisely/lib/blocs/sync/outbound_queue_cubit.dart
- wisely/lib/pages/editor.dart
- wisely/lib/widgets/editor_tools.dart
- wisely/lib/widgets/entry_modal_widget.dart
- wisely/pubspec.yaml
This PR adds a text editor for image and audio entries so that they can be updated with some text.
> Text editor for image and audio entries

- wisely/lib/blocs/journal/persistence_cubit.dart
- wisely/lib/blocs/journal/persistence_db.dart
- wisely/lib/classes/journal_entities.dart
- wisely/lib/pages/survey_page.dart
- wisely/lib/surveys/calculate.dart
- wisely/lib/surveys/cfq11_survey.dart
- wisely/lib/surveys/panas_survey.dart
- wisely/lib/widgets/entry_modal_widget.dart
- wisely/lib/widgets/journal_list_item.dart
- wisely/lib/widgets/survey_summary.dart
- wisely/pubspec.yaml
This PR adds persistence of surveys completions in the journal.
> Persist surveys

- package-lock.json
- package.json
- src/cljs/meins/electron/main/import/audio.cljs
- src/cljs/meins/electron/main/import/core.cljs
- src/cljs/meins/electron/main/import/health.cljs
- src/cljs/meins/electron/main/import/images.cljs
- src/cljs/meins/electron/main/import/text.cljs
- src/test/meins/shared/import_test.cljs
- src/test/meins/shared/test-files/text_test_entry.json
- src/test/meins/shared/test-files/text_test_entry_converted.edn
- wisely/lib/blocs/journal/persistence_cubit.dart
- wisely/lib/blocs/sync/imap/inbox_cubit.dart
- wisely/lib/blocs/sync/outbound_queue_cubit.dart
- wisely/lib/utils/audio_utils.dart
- wisely/lib/utils/file_utils.dart
- wisely/lib/utils/image_utils.dart
- wisely/pubspec.yaml
- wisely/test/file_utils_test.dart
This PR add the import of text entries from wisely into meins.
> Import text entries

- lotti/lib/blocs/sync/imap/inbox_cubit.dart
- lotti/lib/blocs/sync/imap/outbox_cubit.dart
- lotti/lib/blocs/sync/outbound_queue_cubit.dart
- lotti/pubspec.yaml
This PR changes to IMAP layer to reuse clients when possible, resulting in much faster read and write in sync.
> Reuse imap clients

- lotti/lib/blocs/sync/imap/inbox_cubit.dart
- lotti/lib/database/database.dart
- lotti/lib/database/tables.drift
- lotti/pubspec.yaml
This PR adds detecting conflicts and persisting them for later resolution by the user.
> Detect conflicts

- package.json
- src/cljs/meins/electron/main/import/health.cljs
This PR adds the import of `HealthDataType.SLEEP_IN_BED` in addition to `HealthDataType.SLEEP_ASLEEP`.
> import time in bed

- lotti/lib/blocs/sync/outbox_cubit.dart
- lotti/lib/blocs/sync/outbox_state.dart
- lotti/lib/database/sync_db.dart
- lotti/lib/widgets/pages/settings/measurables.dart
- lotti/lib/widgets/pages/settings/outbox_monitor.dart
- lotti/pubspec.yaml
This PR adds a segmented control in the outbox monitor to select been pending, error, and all items.
> Outbox monitor filter

- lotti/lib/database/database.dart
- lotti/pubspec.yaml
This PR adds alphabetical sorting to the definition of measurables.
> Sort measurables alphabetically

- lotti/lib/blocs/audio/recorder_cubit.dart
- lotti/lib/blocs/journal/persistence_cubit.dart
- lotti/lib/blocs/sync/imap/outbox_cubit.dart
- lotti/lib/blocs/sync/imap/outbox_save_imap.dart
- lotti/lib/database/database.dart
- lotti/lib/database/database.drift
- lotti/lib/main.dart
- lotti/lib/theme.dart
- lotti/lib/widgets/audio/audio_player.dart
- lotti/lib/widgets/audio/audio_recorder.dart
- lotti/lib/widgets/home.dart
- lotti/lib/widgets/journal/entry_detail_widget.dart
- lotti/lib/widgets/journal/journal_card.dart
- lotti/lib/widgets/misc/app_bar_version.dart
- lotti/lib/widgets/pages/add/add_page.dart
- lotti/lib/widgets/pages/add/editor_page.dart
- lotti/lib/widgets/pages/add/health_page.dart
- lotti/lib/widgets/pages/audio.dart
- lotti/lib/widgets/pages/journal_page.dart
- lotti/lib/widgets/pages/settings/settings_page.dart
- lotti/lib/widgets/sync/imap_status_widget.dart
- lotti/lib/widgets/sync/qr_reader_widget.dart
- lotti/lib/widgets/sync/qr_widget.dart
- lotti/pubspec.lock
- lotti/pubspec.yaml
This PR changes the journal page query to use streaming results so that the UI gets updated automatically on any changes.
> Use streaming query for journal

- lotti/lib/blocs/sync/outbox_cubit.dart
- lotti/lib/database/sync_db.dart
- lotti/lib/widgets/misc/app_bar_version.dart
- lotti/lib/widgets/pages/add/new_measurement_page.dart
- lotti/lib/widgets/pages/settings/outbox_monitor.dart
- lotti/lib/widgets/pages/settings/settings_page.dart
- lotti/pubspec.yaml
This PR changes the order in the sync outbox monitor to descending and adds a button for restarting the outbox.
> Sync monitor improvements

- lotti/lib/theme.dart
- lotti/lib/widgets/misc/app_bar_version.dart
- lotti/lib/widgets/pages/add/editor_page.dart
- lotti/lib/widgets/pages/add/health_page.dart
- lotti/lib/widgets/pages/add/new_measurement_page.dart
- lotti/lib/widgets/pages/add/survey_page.dart
- lotti/lib/widgets/pages/settings/measurables.dart
- lotti/lib/widgets/pages/settings/outbox_monitor.dart
- lotti/pubspec.yaml
This PR introduces some improvements to the outbox monitor UI, and in the app bar more broadly.
> Outbox sync style

- lotti/lib/blocs/audio/player_cubit.dart
- lotti/lib/blocs/audio/player_state.dart
- lotti/lib/blocs/audio/recorder_cubit.dart
- lotti/lib/widgets/audio/audio_player.dart
- lotti/pubspec.yaml
This PR adds controls for setting the playback speed. Also, it postpones the opening of the audio session until actually used so that music playback does not stop when opening the app.
> Audio improvements

- lotti/lib/theme.dart
- lotti/lib/widgets/journal/editor_widget.dart
- lotti/pubspec.lock
- lotti/pubspec.yaml
This PR changes the text styles in the editor to match the desktop application.
> Adapt editor styling for headlines and paragraph text

- lotti/lib/widgets/journal/editor_styles.dart
- lotti/lib/widgets/journal/editor_widget.dart
- lotti/lib/widgets/journal/entry_detail_widget.dart
- lotti/lib/widgets/journal/journal_card.dart
- lotti/lib/widgets/journal/text_viewer_widget.dart
- lotti/pubspec.yaml
This PR changes the display of entry text in the journal list to show formatted rich text.
> Show first lines of formatted entry in journal

- lotti/lib/widgets/journal/entry_detail_route.dart
- lotti/lib/widgets/journal/entry_detail_widget.dart
- lotti/lib/widgets/journal/entry_image_widget.dart
- lotti/lib/widgets/journal/journal_card.dart
- lotti/pubspec.yaml
This PR improves the user experience on mobile by aligning the text controls above the keyboard.
> Mobile editor UX

- lotti/lib/theme.dart
- lotti/lib/widgets/journal/editor_styles.dart
- lotti/lib/widgets/journal/editor_widget.dart
- lotti/lib/widgets/journal/text_viewer_widget.dart
- lotti/pubspec.yaml
This PR improves the styling of code block display in the journal cards.
> Improved styling: code block background

- lotti/lib/widgets/journal/entry_detail_widget.dart
- lotti/lib/widgets/journal/entry_image_widget.dart
- lotti/lib/widgets/journal/journal_card.dart
- lotti/lib/widgets/pages/journal_page.dart
- lotti/macos/Podfile.lock
- lotti/pubspec.lock
- lotti/pubspec.yaml
This PR improves the list tile for image entries.
> Add image card with improved & larger display using getwidget

- lotti/ios/Podfile.lock
- lotti/ios/Runner/Info.plist
- lotti/lib/blocs/journal/persistence_cubit.dart
- lotti/lib/database/database.dart
- lotti/lib/database/database.drift
- lotti/lib/services/badge_service.dart
- lotti/macos/Flutter/GeneratedPluginRegistrant.swift
- lotti/pubspec.lock
- lotti/pubspec.yaml
This PR adds a badge for the number of items that need are flagged import, which need some TLC, such as adding captions for photos, or a summary for an audio recording. Only on mobile at the moment.
> Add app icon badge with number of entries flagged import

- lotti/lib/widgets/journal/entry_detail_route.dart
- lotti/lib/widgets/journal/entry_detail_widget.dart
- lotti/pubspec.yaml
This PR fixes overwriting a currently in flight editing when the database changes, e.g. when receiving images via sync. The previous behavior made for a pretty debilitating user experience.
> Fix editor overwrite

- lotti/lib/widgets/journal/editor_styles.dart
- lotti/lib/widgets/journal/journal_card.dart
- lotti/lib/widgets/journal/text_viewer_widget.dart
- lotti/pubspec.yaml
This PR adds some improvements to the layout card to make them a little less unappealing.
> Improve journal card layout

- lotti/lib/widgets/journal/card_image_widget.dart
- lotti/lib/widgets/journal/editor_widget.dart
- lotti/lib/widgets/journal/entry_detail_widget.dart
- lotti/lib/widgets/journal/entry_image_widget.dart
- lotti/lib/widgets/journal/journal_card.dart
- lotti/lib/widgets/pages/add/editor_page.dart
- lotti/pubspec.lock
- lotti/pubspec.yaml
This PR adds an improved photo viewer with pinch & zoom in a fullscreen view.
> Photo view

- .github/workflows/flutter-linux-build.yml
- .github/workflows/flutter-test.yml
- lotti/Makefile
- lotti/README.md
- lotti/lib/blocs/audio/recorder_cubit.dart
- lotti/lib/blocs/journal/persistence_cubit.dart
- lotti/lib/blocs/sync/imap/inbox_cubit.dart
- lotti/lib/blocs/sync/outbox_cubit.dart
- lotti/lib/location.dart
- lotti/lib/utils/timezone.dart
- lotti/lib/widgets/pages/add/add_page.dart
- lotti/linux/.gitignore
- lotti/linux/CMakeLists.txt
- lotti/linux/flutter/CMakeLists.txt
- lotti/linux/flutter/generated_plugin_registrant.cc
- lotti/linux/flutter/generated_plugin_registrant.h
- lotti/linux/flutter/generated_plugins.cmake
- lotti/linux/main.cc
- lotti/linux/my_application.cc
- lotti/linux/my_application.h
- lotti/pubspec.yaml
This PR adds a basic Linux Desktop build and runs the build on every commit in a GitHub Action so that new Linux issues can be detected right away.
However, in order to be fully functional, a few issues need to be resolved:
- #663 
- #664 
- #665 
Help is much appreciated.
> Add Flutter Linux build

- lotti/lib/blocs/sync/imap/inbox_cubit.dart
- lotti/lib/blocs/sync/outbox_cubit.dart
- lotti/lib/services/notification_service.dart
- lotti/lib/widgets/journal/editor_widget.dart
- lotti/lib/widgets/misc/buttons.dart
- lotti/lib/widgets/sync/qr_widget.dart
- lotti/pubspec.yaml
This PR adds import and export of the SyncConfig via clipboard for sharing the dev configuration with my Windows and Linux virtual machines, plus some tweaks and fixes for running on these platforms. Linux appears to be running fine overall, minus the Linux-related issues. Windows works locally but doesn't sync yet.
> Sync config import and export via clipboard

- package-lock.json
- package.json
- src/cljs/meins/electron/main/import/audio.cljs
- src/cljs/meins/electron/main/import/images.cljs
- src/test/meins/shared/import_test.cljs
- src/test/meins/shared/test-files/starred_import.JPG.json
- src/test/meins/shared/test-files/starred_import.aac.json
This PR adds the import of the starred status into the meins desktop app.
> Import starred status

- lotti/lib/main.dart
- lotti/lib/widgets/pages/journal_page.dart
- lotti/pubspec.yaml
This PR adds improved error logging, plus some more sensible default filtering in the journal page view.
> Error logging

- lotti/lib/classes/measurables.dart
- lotti/lib/database/database.drift
- lotti/lib/widgets/journal/entry_tools.dart
- lotti/lib/widgets/journal/journal_card.dart
- lotti/lib/widgets/pages/add/new_measurement_page.dart
- lotti/lib/widgets/pages/settings/measurables.dart
- lotti/pubspec.yaml
This PR adds favorites for measurement types. Charts are only shown for these favorites in the add measurement page.
> Measurement favorites

- lotti/lib/database/database.dart
- lotti/lib/database/database.drift
- lotti/lib/main.dart
- lotti/lib/widgets/pages/settings/flags.dart
- lotti/lib/widgets/pages/settings/settings_page.dart
- lotti/pubspec.lock
This PR adds a setting flags page and the private flag. When it is activated, private entries are shown, otherwise they are hidden. This makes it easier to demo the app without showing anything private.
> Private db filter

- lotti/lib/blocs/journal/persistence_cubit.dart
- lotti/lib/database/database.dart
- lotti/lib/widgets/journal/entry_detail_header.dart
- lotti/lib/widgets/journal/journal_card.dart
- lotti/lib/widgets/journal/tags_widget.dart
- lotti/pubspec.yaml
This PR adds some UI and IX improvements to the tagging.
> Tags Part 3

- lotti/lib/widgets/pages/settings/outbox_badge.dart
- lotti/lib/widgets/pages/settings/settings_card.dart
- lotti/lib/widgets/pages/settings/settings_icon.dart
- lotti/lib/widgets/pages/settings/settings_page.dart
- lotti/pubspec.yaml
This PR adds a badge with the number of pending outbox items in the settings page.
> Add outbox counter badge

- lotti/lib/theme.dart
- lotti/lib/widgets/journal/entry_detail_header.dart
- lotti/lib/widgets/journal/tags_widget.dart
- lotti/pubspec.yaml
This PR adds some header style improvements.
> Header improvements

- lotti/lib/blocs/sync/imap/inbox_cubit.dart
- lotti/lib/blocs/sync/outbox_cubit.dart
- lotti/lib/database/database.drift
- lotti/lib/services/tags_service.dart
- lotti/pubspec.yaml
This PR adds some error logging to the sync mail client, and stops polling the outbound queue when it's empty, it will be resumed anyway on inserts.
> Mail error handling

- lotti/lib/widgets/journal/tags_widget.dart
- lotti/pubspec.yaml
This PR adds the removal of tags in the details page.
> Add tag removal

- lotti/lib/services/tags_service.dart
- lotti/lib/widgets/journal/tags_widget.dart
- lotti/pubspec.yaml
This PR adds Copy & Paste functionality for tags.
> Add tag copy & paste icons on details page

- lotti/lib/database/database.dart
- lotti/lib/database/database.drift
- lotti/lib/widgets/journal/tags_search_widget.dart
- lotti/lib/widgets/journal/tags_widget.dart
- lotti/lib/widgets/pages/journal_page.dart
- lotti/pubspec.yaml
This PR adds search for tags as and AND query using set intersection.
> Tag search

- lotti/lib/widgets/home.dart
- lotti/lib/widgets/pages/add/add_page.dart
- lotti/lib/widgets/pages/journal_page.dart
- lotti/lib/widgets/pages/settings/tags_page.dart
- lotti/pubspec.yaml
This PR moves the buttons for creating new entries to the main journal page.
> Move new buttons

- package.json
- src/cljs/meins/electron/main/import/core.cljs
This PR disables photo import from lotti into meins, not currently useful.
> Stop importing photos into meins

- lotti/lib/blocs/journal/journal_image_cubit.dart
- lotti/lib/widgets/home.dart
- lotti/lib/widgets/journal/entry_detail_route.dart
- lotti/lib/widgets/misc/add_actions.dart
- lotti/lib/widgets/pages/add/add_page.dart
- lotti/lib/widgets/pages/add/editor_page.dart
- lotti/lib/widgets/pages/add/new_measurement_page.dart
- lotti/lib/widgets/pages/audio.dart
- lotti/lib/widgets/pages/journal_page.dart
- lotti/pubspec.yaml
This PR adds the UI changes for creating linked items. The actual linking will happen in a subsequent PR.
> Create linked item

- lotti/lib/classes/entity_definitions.dart
- lotti/lib/database/conversions.dart
- lotti/lib/database/database.dart
- lotti/lib/database/database.drift
- lotti/lib/widgets/pages/settings/maintenance_page.dart
- lotti/pubspec.yaml
This PR removes the previous, less flexible tags data model, including database table and indices.
> Remove old tag data model

- lotti/lib/widgets/create/add_actions.dart
- lotti/lib/widgets/journal/entry_detail_route.dart
- lotti/lib/widgets/pages/journal_page.dart
- lotti/lib/widgets/pages/settings/settings_page.dart
- lotti/pubspec.lock
- lotti/pubspec.yaml
This PR changes the action buttons for creating a new entry from a horizontal to a radial layout.
> Use radial action buttons

- lotti/lib/blocs/journal/persistence_cubit.dart
- lotti/lib/blocs/sync/outbox_cubit.dart
- lotti/lib/database/database.dart
- lotti/lib/database/database.drift
- lotti/lib/widgets/create/add_tag_actions.dart
- lotti/lib/widgets/journal/entry_detail_linked.dart
- lotti/lib/widgets/pages/settings/tags_page.dart
- lotti/pubspec.yaml
This PR adds a section in entry details that shows where an entry is linked from.
> Linked from section

- lotti/lib/theme.dart
- lotti/lib/widgets/create/add_tag_actions.dart
- lotti/lib/widgets/journal/tags_search_widget.dart
- lotti/lib/widgets/journal/tags_view_widget.dart
- lotti/lib/widgets/journal/tags_widget.dart
- lotti/lib/widgets/pages/settings/tags/tag_details.dart
- lotti/lib/widgets/pages/settings/tags_page.dart
- lotti/pubspec.yaml
This PR adds person and story tags, with color coding.
> Add people and story tags

- lotti/lib/widgets/audio/audio_recorder.dart
- lotti/lib/widgets/create/add_actions.dart
- lotti/lib/widgets/journal/tags_widget.dart
- lotti/lib/widgets/pages/add/editor_page.dart
- lotti/pubspec.yaml
This PR adds a few small UI and UX improvements.
> UI & UX improvements

- lotti/lib/theme.dart
- lotti/lib/widgets/journal/editor_styles.dart
- lotti/lib/widgets/journal/journal_card.dart
- lotti/lib/widgets/journal/tags_search_widget.dart
- lotti/lib/widgets/journal/tags_view_widget.dart
- lotti/lib/widgets/pages/journal_page.dart
- lotti/pubspec.lock
- lotti/pubspec.yaml
This PR changes search for tags to use the floating search bar, instead of an extra search field within the body of the floating search results.
> Unify search

- lotti/lib/main.dart
- lotti/lib/widgets/pages/journal_page.dart
- lotti/pubspec.yaml
> Search styling

- lotti/lib/theme.dart
- lotti/lib/widgets/create/add_actions.dart
- lotti/lib/widgets/journal/entry_detail_footer.dart
- lotti/lib/widgets/journal/entry_detail_linked.dart
- lotti/lib/widgets/journal/entry_detail_linked_from.dart
- lotti/lib/widgets/journal/entry_detail_route.dart
- lotti/lib/widgets/journal/entry_detail_widget.dart
- lotti/lib/widgets/journal/tags_widget.dart
- lotti/lib/widgets/pages/add/new_task_page.dart
- lotti/lib/widgets/pages/journal_page.dart
- lotti/pubspec.yaml
This PR makes the design of the entry detail card a little less cumbersome.
> Entry card styling

- lotti/lib/database/database.dart
- lotti/lib/theme.dart
- lotti/lib/widgets/journal/entry_datetime_modal.dart
- lotti/lib/widgets/journal/entry_detail_footer.dart
- lotti/lib/widgets/journal/entry_detail_widget.dart
- lotti/lib/widgets/journal/entry_tools.dart
- lotti/lib/widgets/journal/journal_card.dart
- lotti/lib/widgets/journal/linked_duration.dart
- lotti/lib/widgets/pages/add/new_task_page.dart
- lotti/pubspec.yaml
This PR adds setting entry start and end date and showing the duration covered by an entry, plus the total progress vs the estimate, visualized using a progress bar.
> Entry duration setting

- lotti/lib/widgets/journal/editor_widget.dart
- lotti/lib/widgets/journal/entry_detail_widget.dart
- lotti/lib/widgets/pages/add/editor_page.dart
- lotti/lib/widgets/pages/add/new_task_page.dart
- lotti/pubspec.yaml
This PR changes the editor to use space more adaptively.
> Growing editor height

- lotti/lib/widgets/home.dart
- lotti/lib/widgets/journal/linked_duration.dart
- lotti/lib/widgets/pages/add/new_task_page.dart
- lotti/lib/widgets/pages/my_day.dart
- lotti/pubspec.lock
- lotti/pubspec.yaml
This PR creates a view that shows time spent today. Will need navigation between days in subsequent PRs.
> Calendar view for today

- lotti/lib/widgets/pages/my_day.dart
- lotti/pubspec.yaml
This PR adds some entry filtering to unclutter the day view.
> Entry filtering in day view

- lotti/lib/database/database.dart
- lotti/lib/main.dart
- lotti/lib/services/time_service.dart
- lotti/lib/theme.dart
- lotti/lib/widgets/home.dart
- lotti/lib/widgets/journal/duration_widget.dart
- lotti/lib/widgets/journal/editor_styles.dart
- lotti/lib/widgets/journal/entry_detail_footer.dart
- lotti/lib/widgets/journal/entry_detail_linked.dart
- lotti/lib/widgets/journal/entry_detail_linked_from.dart
- lotti/lib/widgets/journal/entry_tools.dart
- lotti/lib/widgets/journal/journal_card.dart
- lotti/lib/widgets/journal/linked_duration.dart
- lotti/lib/widgets/misc/time_recording_indicator.dart
- lotti/lib/widgets/pages/add/new_task_page.dart
- lotti/pubspec.yaml
This PR adds the recording of time on tasks.
> Time recording

- lotti/lib/widgets/journal/entry_detail_widget.dart
- lotti/lib/widgets/journal/journal_card.dart
- lotti/lib/widgets/journal/linked_duration.dart
- lotti/pubspec.yaml
This PR fixes the progress bar rendering so that it doesn't overshoot as easily.
> Fix task duration progress bar

- lotti/lib/blocs/journal/persistence_cubit.dart
- lotti/lib/widgets/home2.dart
- lotti/lib/widgets/journal/entry_detail_route.dart
- lotti/lib/widgets/journal/entry_detail_widget.dart
- lotti/lib/widgets/journal/journal_card.dart
- lotti/lib/widgets/misc/time_recording_indicator.dart
- lotti/lib/widgets/pages/my_day.dart
- lotti/pubspec.lock
- lotti/pubspec.yaml
This PR fixes changing task details, where previously, recently selected tags would be overwritten.
> Fix saving task details

- lotti/lib/blocs/audio/recorder_cubit.dart
- lotti/lib/blocs/journal/journal_image_cubit.dart
- lotti/lib/main.dart
- lotti/lib/utils/audio_utils.dart
- lotti/lib/utils/file_utils.dart
- lotti/lib/utils/screenshots.dart
- lotti/lib/widgets/create/add_actions.dart
- lotti/lib/widgets/journal/journal_card.dart
- lotti/macos/Flutter/GeneratedPluginRegistrant.swift
- lotti/macos/Podfile.lock
- lotti/pubspec.lock
- lotti/pubspec.yaml
This PR adds screenshots on macOS. Contributions very welcome to make the same work on Linux and Windows.
> Screenshots on mac

- lotti/lib/database/database.dart
- lotti/lib/utils/screenshots.dart
- lotti/lib/widgets/pages/settings/flags_page.dart
- lotti/lib/widgets/pages/settings/maintenance_page.dart
- lotti/pubspec.yaml
This PR adds the ability to select if the Lotti UI should be shown or hidden when taking a screenshot.
> Add config flag for hide during screenshot

- .github/workflows/flutter-linux-build.yml
- lotti/lib/database/database.dart
- lotti/lib/main.dart
- lotti/lib/utils/screenshots.dart
- lotti/macos/Flutter/GeneratedPluginRegistrant.swift
- lotti/macos/Podfile.lock
- lotti/pubspec.lock
- lotti/pubspec.yaml
This PR adds listening to `SHIFT-CMD-3` for taking screenshot. This feature can be enabled or disabled via a config flag in settings. Currently only on macOS, help wanted for the same functionality on Windows and Linux.
> Listen to SHIFT-CMD-3 for screenshots (on macOS only)

- lotti/lib/widgets/journal/tags_widget.dart
- lotti/pubspec.yaml
This PR reduces annoying UI jumpiness via setting a minimum height for the tags row so that the majority of the screen doesn't jump when adding the first tag.
> Reduce jumpiness via minHeight box constraints

- lotti/lib/theme.dart
- lotti/lib/widgets/home.dart
- lotti/lib/widgets/journal/duration_widget.dart
- lotti/lib/widgets/misc/audio_recording_indicator.dart
- lotti/lib/widgets/misc/time_recording_indicator.dart
- lotti/pubspec.yaml
This PR adds a bottom UI element that shows when audio is being recorded. Recording will stop on tap.
> Add audio recorder indicator that stays visible

- lotti/lib/logic/persistence_logic.dart
- lotti/lib/main.dart
- lotti/lib/services/link_service.dart
- lotti/lib/widgets/journal/editor_toolbar.dart
- lotti/lib/widgets/journal/editor_widget.dart
- lotti/lib/widgets/journal/entry_detail_widget.dart
- lotti/lib/widgets/pages/add/new_task_page.dart
- lotti/pubspec.yaml
This PR adds linking between already existing entries via `link from` and `link to` icons in the entry editor toolbar (on the right).
> Entry linking

- lotti/lib/sync/inbox_service.dart
- lotti/pubspec.yaml
This PR fixes a memory leak where on connection loss, the memory usage would spin out of control.
> Fix memory leak

- lotti/lib/widgets/journal/duration_widget.dart
- lotti/lib/widgets/journal/journal_card.dart
- lotti/pubspec.yaml
This PR improves the spacing in the entry header.
> Improve entry header spacing

- lotti/lib/widgets/journal/editor_widget.dart
- lotti/lib/widgets/pages/add/new_task_page.dart
- lotti/lib/widgets/pages/tasks_page.dart
- lotti/pubspec.yaml
This PR improves adding tasks:
- Focus on task title, not the editor
- Only have single add action
> Simplify and improve adding tasks

- lotti/lib/widgets/pages/tasks_page.dart
- lotti/pubspec.yaml
This PR adapts the floating action button for adding tasks to match the journal page and tag action buttons.
> Similar floating action button format for tasks

- lotti/lib/widgets/journal/linked_duration.dart
- lotti/pubspec.yaml
This PR adds changing the progress bar immediately when a new task estimate is saved.
> Use updated task in progress bar

- lotti/lib/widgets/journal/entry_detail_widget.dart
- lotti/lib/widgets/pages/add/new_task_page.dart
- lotti/lib/widgets/tasks/task_form.dart
- lotti/pubspec.yaml
This PR improves the UX when editing existing task.
> Only focus on task title on initial create

- lotti/lib/widgets/journal/journal_card.dart
- lotti/pubspec.yaml
This PR improves the layout in the journal card by expanding the text section to take maximum size available for image entries.
> Improved layout in journal card

- lotti/ios/Podfile.lock
- lotti/lib/widgets/journal/duration_widget.dart
- lotti/lib/widgets/pages/settings/tags/tag_details.dart
- lotti/lib/widgets/pages/settings/tags_page.dart
- lotti/macos/Podfile.lock
- lotti/pubspec.lock
- lotti/pubspec.yaml
This PR improves the management of tags:
- search function on tags page
- allow reassigning the tag type for existing tags
> Tag management improvement

- lotti/lib/database/database.drift
- lotti/pubspec.yaml
This PR adds hiding deleted tags from search.
> Hide deleted tags

- lotti/lib/database/database.dart
- lotti/lib/logic/persistence_logic.dart
- lotti/lib/main.dart
- lotti/lib/services/notification_service.dart
- lotti/lib/widgets/bottom_nav/tasks_badge_icon.dart
- lotti/pubspec.yaml
This PR changes the app badge and the bottom nav bar badge for the tasks tab to show the number of started tasks/WIP.
> Work in progress count

- lotti/lib/classes/task.dart
- lotti/lib/database/conversions.dart
- lotti/lib/database/database.dart
- lotti/lib/utils/task_utils.dart
- lotti/lib/widgets/bottom_nav/tasks_badge_icon.dart
- lotti/lib/widgets/journal/entry_detail_widget.dart
- lotti/lib/widgets/journal/journal_card.dart
- lotti/lib/widgets/journal/linked_duration.dart
- lotti/lib/widgets/misc/audio_recording_indicator.dart
- lotti/lib/widgets/pages/tasks_page.dart
- lotti/lib/widgets/tasks/task_form.dart
- lotti/pubspec.yaml
This PR adds filtering for task statuses in the tasks tab.
> Task filtering

- lotti/lib/main.dart
- lotti/lib/services/window_service.dart
- lotti/pubspec.yaml
This PR adds persisting and restoring the window position on desktop.
> Persist and restore window size and position on desktop

- lotti/lib/widgets/journal/journal_card.dart
- lotti/lib/widgets/tasks/task_status.dart
- lotti/pubspec.yaml
This PR extracts and repositions the task status widget in the journal card.
> Extract and reposition task status

- .github/workflows/flutter-linux-build.yml
- .github/workflows/flutter-test.yml
- .github/workflows/flutter-windows-build.yml
- lotti/pubspec.lock
- lotti/pubspec.yaml
- lotti/windows/flutter/generated_plugin_registrant.cc
- lotti/windows/flutter/generated_plugins.cmake
This PR upgrades the project to use Flutter 2.10.
> Upgrade to Flutter 2.10

- lotti/lib/services/window_service.dart
- lotti/pubspec.yaml
This PR fixes an issue where the window position was not restored correctly.
> Change window restore order

- lotti/lib/widgets/journal/tags_widget.dart
- lotti/pubspec.yaml
This PR improves the tag selection by limiting the number of results on mobile, which reduces jumpiness of the UI.
> Improve tag selection

- .github/workflows/test.yml
- lotti/lib/classes/entity_definitions.dart
- lotti/lib/database/conversions.dart
- lotti/lib/database/database.dart
- lotti/lib/database/database.drift
- lotti/lib/logic/persistence_logic.dart
- lotti/lib/theme.dart
- lotti/lib/widgets/charts/dashboard_barchart.dart
- lotti/lib/widgets/charts/measurement_barchart.dart
- lotti/lib/widgets/charts/utils.dart
- lotti/lib/widgets/home.dart
- lotti/lib/widgets/journal/entry_detail_footer.dart
- lotti/lib/widgets/journal/tags_view_widget.dart
- lotti/lib/widgets/journal/tags_widget.dart
- lotti/lib/widgets/pages/insights/dashboard_viewer.dart
- lotti/lib/widgets/pages/insights/dashboards_view_page.dart
- lotti/lib/widgets/pages/settings/dashboards/dashboard_details.dart
- lotti/lib/widgets/pages/settings/dashboards/dashboards_page.dart
- lotti/lib/widgets/pages/settings/settings_card.dart
- lotti/lib/widgets/pages/settings/settings_page.dart
- lotti/lib/widgets/pages/settings/tags/tags_page.dart
- lotti/lib/widgets/pages/tasks_page.dart
- lotti/lib/widgets/tasks/task_form.dart
- lotti/lib/widgets/tasks/task_status.dart
- lotti/pubspec.lock
- lotti/pubspec.yaml
This PR adds a basic dashboard type for showing selected measurable data types next to each other. Quantitative data from health import will follow.
> Dashboards

- lotti/ios/Podfile.lock
- lotti/lib/classes/entity_definitions.dart
- lotti/lib/database/conversions.dart
- lotti/lib/database/database.dart
- lotti/lib/database/database.drift
- lotti/lib/services/window_service.dart
- lotti/lib/theme.dart
- lotti/lib/widgets/charts/dashboard_barchart.dart
- lotti/lib/widgets/charts/dashboard_health_chart.dart
- lotti/lib/widgets/charts/dashboard_health_data.dart
- lotti/lib/widgets/charts/utils.dart
- lotti/lib/widgets/pages/insights/dashboard_viewer.dart
- lotti/lib/widgets/pages/settings/dashboards/dashboard_details.dart
- lotti/pubspec.lock
- lotti/pubspec.yaml
- lotti/test/chart_utils_test.dart
This PR add health charts in dashboards, with line and bar charts depending on data type. Still missing: time aggregation for workout minutes, better blood pressure chart, and more configurability, e.g. height and line/bar color based on data type.
> Health charts

- lotti/lib/database/database.dart
- lotti/lib/database/database.drift
- lotti/lib/widgets/charts/dashboard_health_bp_chart.dart
- lotti/lib/widgets/charts/dashboard_health_chart.dart
- lotti/lib/widgets/charts/dashboard_health_data.dart
- lotti/pubspec.yaml
This PR adds a specialized health chart for displaying blood pressure.
> Blood pressure chart

- lotti/ios/Podfile.lock
- lotti/lib/classes/entity_definitions.dart
- lotti/lib/database/database.dart
- lotti/lib/database/database.drift
- lotti/lib/widgets/charts/dashboard_barchart.dart
- lotti/lib/widgets/charts/dashboard_health_bp_chart.dart
- lotti/lib/widgets/charts/dashboard_health_chart.dart
- lotti/lib/widgets/charts/dashboard_survey_chart.dart
- lotti/lib/widgets/charts/dashboard_survey_data.dart
- lotti/lib/widgets/journal/journal_card.dart
- lotti/lib/widgets/misc/survey_summary.dart
- lotti/lib/widgets/pages/insights/dashboard_viewer.dart
- lotti/lib/widgets/pages/settings/dashboards/dashboard_details.dart
- lotti/macos/Podfile.lock
- lotti/pubspec.lock
- lotti/pubspec.yaml
This PR creates a basic survey chart for use in dashboards and survey journal entries, currently only in use for the journal cards. The use in dashboards with the respective configuration will follow in a subsequent PR.
> Survey charts

- lotti/lib/widgets/charts/dashboard_health_chart.dart
- lotti/lib/widgets/charts/dashboard_health_data.dart
- lotti/pubspec.yaml
- lotti/test/chart_utils_test.dart
This PR adds basic color coding based on reaching thresholds, for now only hardcoded for steps. Configurability for any type and with custom thresholds will come later.
> Add color success coding for steps bar chart

- lotti/lib/widgets/charts/dashboard_health_bp_chart.dart
- lotti/pubspec.yaml
This PR improves the blood pressure chart by giving it more vertical space, plus showing the normal ranges for systolic and diastolic pressures.
> Improve blood pressure chart: height and normal ranges

- lotti/lib/blocs/my_bloc_observer.dart
- lotti/lib/database/database.dart
- lotti/lib/location.dart
- lotti/lib/logic/persistence_logic.dart
- lotti/lib/main.dart
- lotti/lib/services/sync_config_service.dart
- lotti/lib/sync/imap_client.dart
- lotti/lib/sync/inbox_read.dart
- lotti/lib/widgets/charts/dashboard_survey_chart.dart
- lotti/lib/widgets/charts/dashboard_survey_data.dart
- lotti/lib/widgets/pages/insights/dashboards_view_page.dart
- lotti/lib/widgets/pages/settings/dashboards/dashboard_details.dart
- lotti/lib/widgets/pages/settings/dashboards/dashboards_page.dart
- lotti/lib/widgets/sync/imap_config.dart
- lotti/pubspec.yaml
This PR adds charts for surveys.
> Survey chart

- lotti/lib/services/link_service.dart
- lotti/pubspec.yaml
This PR adds minor improvements to the linking experience.
> Force feedback and delayed clear on link button press

- lotti/lib/widgets/charts/dashboard_barchart.dart
- lotti/lib/widgets/charts/dashboard_survey_chart.dart
- lotti/lib/widgets/charts/dashboard_survey_data.dart
- lotti/pubspec.yaml
This PR adds the creation of survey entries from the dashboard, similar to the creation of measurement entries directly from the dashboard (double click/tap or long press on the respective chart).
> Create survey from dashboard (double click or long press)

- lotti/lib/theme.dart
- lotti/lib/widgets/journal/entry_datetime_modal.dart
- lotti/lib/widgets/journal/entry_detail_widget.dart
- lotti/lib/widgets/pages/add/new_task_page.dart
- lotti/lib/widgets/tasks/detail_task_status.dart
- lotti/lib/widgets/tasks/task_form.dart
- lotti/pubspec.yaml
This PR hides the task form in entry details until the edit icon is tapped.
> Hide task form until tap

- lotti/lib/widgets/charts/dashboard_health_chart.dart
- lotti/lib/widgets/charts/dashboard_health_data.dart
- lotti/lib/widgets/charts/utils.dart
- lotti/pubspec.yaml
This PR adds a chart for aggregated sleep, imported from Apple Health.
> Sleep chart

- lotti/lib/theme.dart
- lotti/lib/widgets/journal/tags_widget.dart
- lotti/lib/widgets/tasks/detail_task_status.dart
- lotti/pubspec.yaml
This PR improves the really annoying jumpiness previously when adding tasks.
> Move adding tasks to modal bottom sheet

- lotti/lib/logic/persistence_logic.dart
- lotti/lib/widgets/journal/tags_widget.dart
- lotti/pubspec.yaml
- lotti/test/persistence_logic_test.dart
This PR takes the tag adding and removal out of the UI code and into the logic layer, plus adds tests.
> Tag add and remove refactoring

- lotti/lib/widgets/charts/dashboard_health_bmi_chart.dart
- lotti/lib/widgets/charts/dashboard_health_bp_chart.dart
- lotti/lib/widgets/charts/dashboard_health_chart.dart
- lotti/lib/widgets/charts/dashboard_health_config.dart
- lotti/lib/widgets/charts/dashboard_health_data.dart
- lotti/lib/widgets/pages/settings/dashboards/dashboard_details.dart
- lotti/pubspec.yaml
- lotti/test/chart_utils_test.dart
This PR makes the BMI chart adaptive by only showing the outer ranges when min or max are near those ranges.
> Adaptive BMI chart

- lotti/lib/classes/entity_definitions.dart
- lotti/lib/classes/journal_entities.dart
- lotti/lib/database/conversions.dart
- lotti/lib/database/database.dart
- lotti/lib/database/database.drift
- lotti/lib/logic/health_import.dart
- lotti/lib/logic/persistence_logic.dart
- lotti/lib/utils/file_utils.dart
- lotti/lib/widgets/charts/dashboard_workout_chart.dart
- lotti/lib/widgets/charts/dashboard_workout_config.dart
- lotti/lib/widgets/journal/entry_detail_footer.dart
- lotti/lib/widgets/journal/entry_detail_route.dart
- lotti/lib/widgets/journal/entry_detail_widget.dart
- lotti/lib/widgets/journal/helpers.dart
- lotti/lib/widgets/journal/journal_card.dart
- lotti/lib/widgets/pages/add/health_page.dart
- lotti/lib/widgets/pages/insights/dashboard_viewer.dart
- lotti/lib/widgets/pages/journal_page.dart
- lotti/lib/widgets/pages/my_day.dart
- lotti/lib/widgets/pages/settings/dashboards/dashboard_details.dart
- lotti/lib/widgets/tasks/detail_task_status.dart
- lotti/lib/widgets/tasks/task_form.dart
- lotti/pubspec.lock
- lotti/pubspec.yaml
This PR adds the import of workouts from Apple Health and some basic charts, for types `walking`, `running`, and `functionalStrengthTraining`. Please create issues or PRs for additional types, these can be found **[here](https://github.com/metaflowltd/flutter_health_fit/blob/30102b653cdd2af64509edb4643e809e40139e7c/lib/flutter_health_fit.dart#L130)**.
> Workout charts from health import

- lotti/lib/database/database.dart
- lotti/lib/database/database.drift
- lotti/lib/logic/health_import.dart
- lotti/lib/widgets/charts/dashboard_health_chart.dart
- lotti/lib/widgets/charts/dashboard_workout_chart.dart
- lotti/pubspec.yaml
This PR adds automatically fetching health data for the respective type when a health dashboard chart is initialized.
> Auto query health data

- lotti/lib/classes/entity_definitions.dart
- lotti/lib/widgets/charts/dashboard_measurables_chart.dart
- lotti/lib/widgets/charts/dashboard_survey_chart.dart
- lotti/lib/widgets/charts/utils.dart
- lotti/lib/widgets/pages/add/new_measurement_page.dart
- lotti/lib/widgets/pages/insights/dashboard_viewer.dart
- lotti/lib/widgets/pages/settings/measurables_page.dart
- lotti/pubspec.yaml
This PR adds a selection of aggregation types to measurables. Aggregation type none will be rendered as linechart, unlike the daily sums which are rendered as barcharts.
> Measurables linechart

- lotti/lib/classes/entity_definitions.dart
- lotti/lib/database/database.dart
- lotti/lib/database/database.drift
- lotti/lib/logic/persistence_logic.dart
- lotti/lib/services/tags_service.dart
- lotti/lib/widgets/charts/dashboard_story_chart.dart
- lotti/lib/widgets/charts/dashboard_story_data.dart
- lotti/lib/widgets/charts/dashboard_workout_chart.dart
- lotti/lib/widgets/charts/dashboard_workout_config.dart
- lotti/lib/widgets/charts/dashboard_workout_data.dart
- lotti/lib/widgets/pages/insights/dashboard_viewer.dart
- lotti/lib/widgets/pages/settings/dashboards/chart_multi_select.dart
- lotti/lib/widgets/pages/settings/dashboards/dashboard_details.dart
- lotti/lib/widgets/pages/settings/dashboards/dashboard_item_card.dart
- lotti/lib/widgets/pages/settings/maintenance_page.dart
- lotti/pubspec.yaml
This PR adds a basic time by story chart in dashboards. Does not count time in comments that do not have a story associated.
> Story time chart

- lotti/lib/database/database.dart
- lotti/lib/database/maintenance.dart
- lotti/lib/get_it.dart
- lotti/lib/logic/persistence_logic.dart
- lotti/lib/services/tags_service.dart
- lotti/lib/widgets/pages/settings/maintenance_page.dart
- lotti/pubspec.lock
- lotti/pubspec.yaml
This PR adds copying story tags over to new items when created as linked from an existing item.
> Inherit stories on linking

- lotti/lib/logic/health_import.dart
- lotti/lib/widgets/charts/dashboard_health_config.dart
- lotti/pubspec.yaml
This PR adds additional health sample types: body fat, walking heart rate, and BMI.
> Add health sample types

- lotti/lib/widgets/journal/editor_toolbar.dart
- lotti/pubspec.yaml
This PR cleans up the editor toolbar by removing a currently non-functional item, and more sensible ordering.
> Editor toolbar cleanup

- lotti/lib/widgets/charts/dashboard_measurables_chart.dart
- lotti/lib/widgets/charts/dashboard_workout_chart.dart
- lotti/lib/widgets/charts/dashboard_workout_data.dart
- lotti/lib/widgets/charts/utils.dart
- lotti/pubspec.yaml
This PR fixes data rendering in dashboards when there is little data.
> Fix rendering of sparse data

- lotti/lib/widgets/charts/dashboard_health_bmi_chart.dart
- lotti/lib/widgets/charts/dashboard_health_data.dart
- lotti/pubspec.yaml
- lotti/test/chart_utils_test.dart
This PR improves the rendering of percentages.
> Multiply percentages by 100 for improved rendering

- lotti/ios/Podfile.lock
- lotti/lib/logic/health_import.dart
- lotti/lib/widgets/charts/dashboard_health_bmi_chart.dart
- lotti/pubspec.yaml
This PR changes the health fetch behavior from only fetching the delta since a previous fetch to fetching 30 days if data type has never been imported.
> Fetch health data for 30 days when not fetched before

- lotti/lib/widgets/journal/editor_toolbar.dart
- lotti/lib/widgets/journal/entry_detail_footer.dart
- lotti/lib/widgets/journal/entry_detail_widget.dart
- lotti/pubspec.yaml
> Styling tweaks

- lotti/lib/pages/home_page.dart
- lotti/lib/widgets/audio/audio_recorder.dart
- lotti/lib/widgets/audio/audio_recording_indicator.dart
- lotti/lib/widgets/audio/vu_meter.dart
- lotti/lib/widgets/create/add_actions.dart
- lotti/pubspec.yaml
This PR fixes the path for the audio recorder page.
> Fix audio path

- lotti/lib/services/tags_service.dart
- lotti/lib/widgets/journal/tags_widget.dart
- lotti/pubspec.yaml
This PR pushes reading tags from the copied entry to clipboard fetch time.
> Change to fetching copied tags lazily

- lotti/lib/widgets/charts/dashboard_health_bmi_chart.dart
- lotti/lib/widgets/charts/dashboard_health_bp_chart.dart
- lotti/lib/widgets/charts/dashboard_health_chart.dart
- lotti/lib/widgets/charts/dashboard_measurables_chart.dart
- lotti/lib/widgets/charts/dashboard_story_chart.dart
- lotti/lib/widgets/charts/dashboard_survey_chart.dart
- lotti/lib/widgets/charts/dashboard_workout_chart.dart
- lotti/pubspec.lock
- lotti/pubspec.yaml
This PR adds showing data for a selected day in the measurables dashboard chart.
> Show day info in measurables chart

- lotti/lib/widgets/charts/dashboard_health_bmi_chart.dart
- lotti/pubspec.yaml
This PR improves the layout in the BMI chart header.
> Improve header

- lotti/lib/widgets/journal/journal_card.dart
- lotti/lib/widgets/tasks/detail_task_status.dart
- lotti/lib/widgets/tasks/linked_duration.dart
- lotti/lib/widgets/tasks/task_form.dart
- lotti/lib/widgets/tasks/task_status.dart
- lotti/macos/Podfile.lock
- lotti/pubspec.lock
- lotti/pubspec.yaml
This PR improves the layout in the task header.
> Task header improvements

- lotti/lib/pages/dashboards/dashboard_page.dart
- lotti/lib/pages/settings/dashboards/dashboard_details_page.dart
- lotti/pubspec.yaml
This PR adds bidirectional links between dashboards and their respective definition.
> Dashboard links

- lotti/lib/classes/entity_definitions.dart
- lotti/lib/get_it.dart
- lotti/lib/logic/image_import.dart
- lotti/lib/logic/persistence_logic.dart
- lotti/lib/main.dart
- lotti/lib/pages/dashboards/dashboard_page.dart
- lotti/lib/pages/settings/dashboards/dashboard_details_page.dart
- lotti/lib/services/notification_service.dart
- lotti/pubspec.lock
- lotti/pubspec.yaml
This PR adds notifications/reminders for reviewing dashboards to check for success on whatever the dashboard is measuring - and taking action such as exercises or taking medication if not.
> Dashboard review notifications

- lotti/lib/services/link_service.dart
- lotti/pubspec.lock
- lotti/pubspec.yaml
This PR adds copying over story tags when linking to another entry.
> Copy stories on linking

- lotti/lib/classes/entity_definitions.dart
- lotti/lib/database/conversions.dart
- lotti/lib/database/database.dart
- lotti/lib/database/maintenance.dart
- lotti/lib/pages/create/create_measurement_page.dart
- lotti/lib/pages/my_day.dart
- lotti/lib/pages/settings/measurables/measurable_details_page.dart
- lotti/lib/widgets/charts/dashboard_measurables_chart.dart
- lotti/lib/widgets/journal/journal_card.dart
- lotti/lib/widgets/journal/measurement_summary.dart
- lotti/pubspec.yaml
This PR changes the measurement type to be optional on a recording, and using only the ID to look up the latest version.
> Optional measurement type

- lotti/lib/pages/home_page.dart
- lotti/pubspec.yaml
This PR disables the day tab for now until making it more useful.
> Disable my day tab for now

- lotti/lib/blocs/charts/workout_chart_info_cubit.dart
- lotti/lib/widgets/charts/dashboard_workout_chart.dart
- lotti/pubspec.yaml
This PR adds showing info about a particular day after tapping the bar for the day, similar to other charts.
> Add selection info in workout chart

- lotti/lib/blocs/charts/bp_chart_info_cubit.dart
- lotti/lib/widgets/charts/dashboard_health_bp_chart.dart
- lotti/pubspec.yaml
This PR adds showing info about a blood pressure reading for a particular day after tapping the respective bar, similar to other charts.
> Add selection info in blood pressure chart

- lotti/lib/widgets/charts/dashboard_health_bp_chart.dart
- lotti/lib/widgets/charts/dashboard_measurables_chart.dart
- lotti/pubspec.yaml
This PR fixes the blood pressure display, which before would occasionally display the values in the wrong order.
> Fix bp order

- lotti/Makefile
- lotti/l10n.yaml
- lotti/lib/l10n/app_de.arb
- lotti/lib/l10n/app_en.arb
- lotti/lib/l10n/app_fr.arb
- lotti/lib/main.dart
- lotti/lib/pages/home_page.dart
- lotti/lib/pages/settings/logging_page.dart
- lotti/lib/services/notification_service.dart
- lotti/pubspec.lock
- lotti/pubspec.yaml
This PR adds `flutter_localizations`, with localized strings for the bottom navigation bar items.
> Localizations

- lotti/lib/l10n/app_de.arb
- lotti/lib/l10n/app_en.arb
- lotti/lib/theme.dart
- lotti/lib/widgets/tasks/detail_task_status.dart
- lotti/lib/widgets/tasks/task_form.dart
- lotti/lib/widgets/tasks/task_status.dart
- lotti/pubspec.yaml
This PR adds localizable strings for the tasks UI, with the English original and German translation.
> Add localization strings for tasks, with German and English versions

- lotti/lib/l10n/app_de.arb
- lotti/lib/l10n/app_en.arb
- lotti/lib/pages/settings/advanced_settings_page.dart
- lotti/lib/pages/settings/settings_page.dart
- lotti/lib/routes/settings_routes.dart
- lotti/linux/flutter/generated_plugin_registrant.cc
- lotti/linux/flutter/generated_plugins.cmake
- lotti/pubspec.yaml
This PR adds an advanced settings page and moves settings items for advanced usage and dev support over to the advanced page.
> Create advanced settings page and restructure

- lotti/lib/database/database.dart
- lotti/lib/l10n/app_de.arb
- lotti/lib/l10n/app_en.arb
- lotti/lib/pages/settings/dashboards/dashboard_details_page.dart
- lotti/pubspec.yaml
This PR adds a copy button for dashboard configurations. Both the dashboard and the used measurable data types are included in the serialized JSON, which is then copied to the clipboard. The import of a dashboard configuration will come in a later PR.
> Copy dashboard config

- lotti/lib/widgets/create/add_actions.dart
- lotti/pubspec.yaml
This PR changes create new text entry behavior to insert the new entry into the linked entries list directly instead of opening a separate page when called from an entry details page.
> Insert new text entry in linked entries list

- lotti/lib/database/database.dart
- lotti/lib/l10n/app_de.arb
- lotti/lib/l10n/app_en.arb
- lotti/lib/logic/persistence_logic.dart
- lotti/lib/widgets/journal/entry_detail_footer.dart
- lotti/lib/widgets/journal/entry_detail_linked.dart
- lotti/lib/widgets/journal/entry_details/delete_icon_widget.dart
- lotti/lib/widgets/journal/entry_details/entry_info_row.dart
- lotti/lib/widgets/journal/entry_details/switch_row_widget.dart
- lotti/lib/widgets/journal/entry_details_widget.dart
- lotti/pubspec.yaml
This PR simplifies the data source for the linked entries list and adds an explanatory hint and icon for the unlink action via dismissing.
> Simplify linked entries list and improve removing link

- lotti/lib/classes/task.dart
- lotti/lib/database/conversions.dart
- lotti/lib/l10n/app_de.arb
- lotti/lib/l10n/app_en.arb
- lotti/lib/pages/tasks_page.dart
- lotti/lib/utils/task_utils.dart
- lotti/lib/widgets/tasks/task_form.dart
- lotti/lib/widgets/tasks/task_status.dart
- lotti/pubspec.yaml
This PR adds the `GROOMED` task status for an improved task management workflow.
> Add groomed status for tasks

- lotti/lib/database/logging_db.dart
- lotti/lib/logic/persistence_logic.dart
- lotti/lib/widgets/create/add_actions.dart
- lotti/pubspec.yaml
This PR adds an action button for creating a running timer, which saves a click/tap for starting a timer.
> Add action button for creating a running timer

- lotti/lib/logic/persistence_logic.dart
- lotti/lib/services/time_service.dart
- lotti/lib/widgets/journal/duration_widget.dart
- lotti/lib/widgets/journal/entry_datetime_modal.dart
- lotti/pubspec.yaml
This PR add the automatic persistence of a running timer when starting a new one.
> Stop and persist old timer when creating a new one

- lotti/lib/logic/persistence_logic.dart
- lotti/pubspec.yaml
This PR changes new tasks to automatically be starred/favorited.
> Automatically set new tasks to starred

- lotti/lib/services/editor_state_service.dart
- lotti/lib/widgets/journal/editor/editor_tools.dart
- lotti/lib/widgets/journal/entry_details_widget.dart
- lotti/pubspec.yaml
This PR adds keeping track of selection/cursor position in each editor.
> Track text selection/cursor position

- lotti/lib/l10n/app_de.arb
- lotti/lib/pages/tasks_page.dart
- lotti/pubspec.yaml
This PR improves localization in tasks by translating the task filter icons.
> Translate task status filter buttons

- lotti/ios/Runner.xcodeproj/project.pbxproj
- lotti/ios/Runner/Info.plist
- lotti/ios/Runner/RunnerDebug.entitlements
- lotti/macos/Runner.xcodeproj/project.pbxproj
- lotti/macos/Runner/Info.plist
- lotti/pubspec.lock
- lotti/pubspec.yaml
This PR changes the iOS and macOS projects from separate identifiers to a universal app.
> Universal App ID

- lotti/lib/widgets/journal/journal_card.dart
- lotti/pubspec.yaml
This PR adds wrapping looong task titles.
> Wrap long task titles

- lotti/CHANGELOG.md
- lotti/Makefile
- lotti/ios/.gitignore
- lotti/ios/Gemfile
- lotti/ios/fastlane/Appfile
- lotti/ios/fastlane/Fastfile
- lotti/macos/.gitignore
- lotti/macos/Gemfile
- lotti/macos/fastlane/Appfile
- lotti/macos/fastlane/Fastfile
- lotti/pubspec.yaml
This PR adds configuration for using fastlane for publishing to TestFlight.
> Add fastlane

- .github/workflows/flutter-testflight.yml
- lotti/CHANGELOG.md
- lotti/Makefile
- lotti/ios/Runner.xcodeproj/project.pbxproj
- lotti/ios/fastlane/Fastfile
- lotti/ios/fastlane/Matchfile
- lotti/macos/Runner.xcodeproj/project.pbxproj
- lotti/macos/fastlane/Fastfile
- lotti/macos/fastlane/Matchfile
- lotti/pubspec.yaml
This PR adds using fastlane match for signing and certificates so that the `make all` task can run in a GitHub Action.
> Fastlane match for signing & certificate management

- .github/workflows/flutter-testflight.yml
- lotti/ios/fastlane/Fastfile
- lotti/ios/fastlane/Matchfile
- lotti/macos/fastlane/Fastfile
- lotti/macos/fastlane/Matchfile
This PR adds fastlane match in GitHub Actions. The build is currently disabled since it times out. Will need further investigation.
> Add fastlane match in GitHub Action

- lotti/CHANGELOG.md
- lotti/lib/theme.dart
- lotti/lib/widgets/journal/editor/editor_wrapper_widget.dart
- lotti/lib/widgets/journal/entry_details_widget.dart
- lotti/lib/widgets/journal/entry_image_widget.dart
- lotti/lib/widgets/sync/imap_config.dart
- lotti/lib/widgets/sync/qr_widget.dart
- lotti/pubspec.yaml
This PR adds some styling tweaks.
> Entry styling

- lotti/CHANGELOG.md
- lotti/lib/logic/persistence_logic.dart
- lotti/macos/Runner.xcodeproj/project.pbxproj
- lotti/pubspec.yaml
This PR fixes a `MissingPluginException` on Linux.
> Fix MissingPluginException on Linux

- lotti/CHANGELOG.md
- lotti/lib/location.dart
- lotti/lib/utils/timezone.dart
- lotti/pubspec.lock
- lotti/pubspec.yaml
This PR adds determining the geolocation for entries on Linux.
> Linux geolocation

- lotti/CHANGELOG.md
- lotti/ios/Podfile.lock
- lotti/lib/blocs/audio/player_cubit.dart
- lotti/lib/widgets/audio/audio_player.dart
- lotti/macos/Flutter/GeneratedPluginRegistrant.swift
- lotti/macos/Podfile.lock
- lotti/pubspec.lock
- lotti/pubspec.yaml
This PR adds sharing audio recordings via the platform share dialog. Tested on iOS with Signal and WhatsApp, and on macOS with email.
> Add audio share button

- lotti/CHANGELOG.md
- lotti/lib/widgets/journal/duration_widget.dart
- lotti/lib/widgets/journal/entry_details/entry_detail_footer.dart
- lotti/lib/widgets/journal/entry_details/share_button_widget.dart
- lotti/pubspec.yaml
This PR improves whitespace in the footer on mobile.
> Improve footer whitespace on mobile

- CHANGELOG.md
- lib/widgets/journal/entry_details/entry_detail_header.dart
- pubspec.yaml
This PR adds haptic feedback for setting and unsetting starred, private, flagged.
> Add haptic feedback for setting and unsetting starred, private, flagged

- lib/blocs/audio/player_cubit.dart
- lib/utils/image_utils.dart
- pubspec.lock
- pubspec.yaml
This PR fixes the handling of audio paths on Android, thus fixing the sync of audio files.
> Fix audio path on Android

- android/app/src/main/AndroidManifest.xml
- lib/logic/image_import.dart
- pubspec.yaml
This PR fixes photo location import.
> Fix photo import on Android

- .buildkite/pipeline_windows.yml
This PR adds building an **[MSIX](https://docs.microsoft.com/en-us/windows/msix/packaging-tool/tool-overview)** package. Uploading to GitHub Releases will follow, but first, signing will need to be figured out.
> CI: build MSIX 

- ios/Podfile.lock
- lib/pages/home_page.dart
- lib/routes/observer.dart
- lib/services/nav_service.dart
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
This PR improves restoring the last page on application restart by also persisting root tab routes, instead of only persisting the last detail page route.
> Route restore

- lib/logic/persistence_logic.dart
- lib/pages/settings/logging_page.dart
- pubspec.yaml
This PR postpones obtaining the geolocation for an entry. Sometimes, getting the geolocation can take multiple seconds, and waiting that long for an entry to show up is terrible UX. Also, entries did not show up at all previously when location access was disabled by the user.
> Location timeout

- CHANGELOG.md
- lib/main.dart
- pubspec.yaml
This PR changes the keyboard on iOS to a dark appearance.
> Dark keyboard

- CHANGELOG.md
- ios/Podfile.lock
- lib/logic/persistence_logic.dart
- pubspec.lock
- pubspec.yaml
This PR adds inheriting the private status from a linked parent.
> Inherit private status

- lib/pages/dashboards/dashboards_list_page.dart
- pubspec.yaml
This PR adds hiding inactive dashboards from the insights tab.
> Hide inactive dashboards

- .buildkite/pipeline.yml
- .buildkite/pipeline_linux.yml
- pubspec.yaml
This PR changes the pipelines to ignore when a release already exists.
> Consolidate GitHub Releases

- .github/workflows/flutter-testflight.yml
- README.md
- analysis_options.yaml
- lib/blocs/my_bloc_observer.dart
- lib/logic/health_import.dart
- lib/pages/home_page.dart
- lib/routes/observer.dart
- lib/widgets/journal/editor/editor_widget.dart
- pubspec.yaml
This PR adds a badge for CodeFactor, tightens the analysis settings and fixes reported issues.
> Add CodeFactor badge & fix issues

- CHANGELOG.md
- lib/pages/create/create_measurement_page.dart
- lib/pages/dashboards/dashboard_page.dart
- lib/widgets/charts/utils.dart
- lib/widgets/misc/survey_summary.dart
- pubspec.yaml
This PR adds pan and zoom in dashboards.
> Dashboard Pan & Zoom

- CHANGELOG.md
- lib/pages/dashboards/dashboard_page.dart
- pubspec.yaml
This PR adds disabling panning in dashboards when zooming is ongoing.
> Disable panning when zoom in progress

- CHANGELOG.md
- lib/pages/dashboards/dashboard_page.dart
- lib/widgets/charts/dashboard_health_bmi_chart.dart
- lib/widgets/charts/utils.dart
- pubspec.yaml
This PR improves the BMI chart by adding the display of minimum and maximum weights within the displayed range.
> Add min and max weight in BMI Chart

- lib/widgets/charts/dashboard_health_bmi_chart.dart
- pubspec.yaml
This PR improves the layout in the BMI chart.
> Improve layout in BMI chart

- CHANGELOG.md
- lib/pages/home_page.dart
- lib/widgets/app_bar/task_app_bar.dart
- lib/widgets/tasks/linked_duration.dart
- lib/widgets/tasks/task_form.dart
- pubspec.yaml
This PR adds an app bar for tasks, with the task title and the progress bar.
> Add task app bar with title and progress bar

- CHANGELOG.md
- lib/database/database.dart
- lib/database/editor_db.dart
- lib/database/editor_db.drift
- lib/database/logging_db.dart
- lib/get_it.dart
- lib/services/editor_state_service.dart
- lib/widgets/journal/editor/editor_wrapper_widget.dart
- lib/widgets/journal/entry_details_widget.dart
- pubspec.yaml
This PR adds persisting drafts in a database, and restoring drafts from the database on startup.
> Persist editor drafts

- lib/database/editor_db.dart
- lib/database/logging_db.dart
- lib/database/maintenance.dart
- lib/l10n/app_de.arb
- lib/l10n/app_en.arb
- lib/pages/settings/maintenance_page.dart
- lib/services/time_service.dart
- pubspec.lock
- pubspec.yaml
This PR adds maintenance tasks for deleting the editor drafts and logging database.
> Database cleanup maintenance

- .buildkite/pipeline.yml
This PR comments out the Android build, needs to be reverted when #972 is solved.
> CI: comment out android build

- lib/logic/health_import.dart
- pubspec.yaml
This PR prevents health data import queries into the future.
> Prevent future end dates

- lib/pages/settings/dashboards/dashboard_details_page.dart
- pubspec.yaml
This PR fixes creating and editing dashboards where previously (for some time) it was not possible any more to save dashboards with items. They were rather created with name and description but otherwise empty.
> Fix creation/editing of dashboard

- CHANGELOG.md
- lib/logic/health_import.dart
- pubspec.yaml
This PR fixes fetching activity data for the current day.
> Fix fetching intra-day activity delta

- pubspec.lock
- pubspec.yaml
This PR upgrades Dart and dependencies.
> Upgrade dart

- CHANGELOG.md
- lib/pages/settings/logging_page.dart
- lib/services/editor_state_service.dart
- lib/theme.dart
- pubspec.lock
- pubspec.yaml
This PR attempts to fix #990 by flushing the last known selection in the editor state, as that apparently causes an issue:
```
The provided text position is not in the current node
'package:flutter_quill/src/widgets/text_block.dart':
Failed assertion: line 565 pos 12:
'container.containsOffset(position.offset)'
```
> Fix editor save

- .buildkite/pipeline.yml
- lib/database/editor_db.dart
- lib/database/editor_db.drift
- lib/services/editor_state_service.dart
- lib/widgets/journal/editor/editor_toolbar.dart
- lib/widgets/journal/editor/editor_widget.dart
- lib/widgets/journal/entry_details_widget.dart
- pubspec.yaml
This PR further improves behavior around restoring editor drafts such that only drafts are restored for matching versions, not when outdated.
> Fix Editor Draft Persistence

- CHANGELOG.md
- lib/pages/home_page.dart
- lib/pages/journal_page.dart
- lib/pages/tasks_page.dart
- pubspec.yaml
This PR fixes the display on iPhone X and newer by wrapping the AutoTabsScaffold with a SafeArea, thus adding enough space on top.
> Wrap AutoTabsScaffold with SafeArea

- lib/pages/home_page.dart
- lib/routes/observer.dart
- lib/services/nav_service.dart
- lib/widgets/app_bar/dashboards_app_bar.dart
- lib/widgets/charts/empty_dashboards_widget.dart
- pubspec.lock
- pubspec.yaml
This PR fixes the navigation issue reported in #1015 by navigating to settings root when tapping the settings icon in the bottom navigation bar. Overall, navigation still feels a bit hacky and  could be improved.
> Fix Navigation Issue

- CHANGELOG.md
- lib/l10n/app_de.arb
- lib/l10n/app_en.arb
- lib/widgets/create/add_actions.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
This PR fixes issue #1017 by removing the timeout after which the items in the circular add button disappear, and adding tooltips. Instead, the action items will disappear again after either tapping a leaf item (with triggering the associated action) or tapping the root add item again.
> Improve entry creation UX

- CHANGELOG.md
- lib/logic/image_import.dart
- lib/logic/persistence_logic.dart
- lib/utils/screenshots.dart
- lib/widgets/create/add_actions.dart
- lib/widgets/misc/desktop_menu.dart
- lib/widgets/sync/qr_widget.dart
- pubspec.yaml
Also adds link to currently opened entity when in task or journal detail view. Resolves #1011.
> Take screenshot from application menu on macOS

- CHANGELOG.md
- lib/pages/dashboards/dashboard_page.dart
- lib/pages/home_page.dart
- lib/pages/settings/settings_page.dart
- lib/widgets/app_bar/dashboards_app_bar.dart
- lib/widgets/create/add_actions.dart
- pubspec.yaml
This PR improves a few more icons by using the outlined variant where not the case yet, and using more specific icons for dashboard settings.
> Improved icons

- CHANGELOG.md
- lib/blocs/sync/sync_config_cubit.dart
- lib/l10n/app_en.arb
- lib/pages/settings/sync/sync_assistant_slide_success.dart
- lib/sync/imap_client.dart
- lib/sync/inbox_service.dart
- lib/widgets/sync/imap_config.dart
- lib/widgets/sync/qr_reader_widget.dart
- lib/widgets/sync/qr_widget.dart
- pubspec.yaml
Resolves #1034 by using a default folder which is created when it does not exist yet.
> Use default IMAP sync folder, create if non-existing

- CHANGELOG.md
- lib/pages/settings/sync/sync_assistant_slide_intro_1.dart
- lib/pages/settings/sync/sync_assistant_slide_intro_2.dart
- lib/pages/settings/sync/sync_assistant_slide_intro_3.dart
- lib/pages/settings/sync/tutorial_utils.dart
- pubspec.lock
- pubspec.yaml
This PR improves the Sync Assistant by using auto sizing text to avoid overlap with other text elements.
> Use AutoSizeText in Sync Assistant

- CHANGELOG.md
- lib/widgets/charts/empty_dashboards_widget.dart
- pubspec.yaml
This PR improves the layout on small screens when dashboards are empty.
> Improve layout with AutoSizeText

- CHANGELOG.md
- lib/widgets/journal/entry_details_widget.dart
- lib/widgets/journal/entry_tools.dart
- lib/widgets/journal/helpers.dart
- lib/widgets/journal/journal_card.dart
- lib/widgets/journal/measurement_summary.dart
- pubspec.yaml
This PR improves the display of data entries on the entry details page.
> Improve data entries

- lib/logic/health_import.dart
- lib/widgets/journal/entry_details/health_summary.dart
- lib/widgets/journal/entry_details/measurement_summary.dart
- lib/widgets/journal/entry_details/survey_summary.dart
- lib/widgets/journal/entry_details/workout_summary.dart
- lib/widgets/journal/entry_details_widget.dart
- lib/widgets/journal/entry_tools.dart
- lib/widgets/journal/journal_card.dart
- pubspec.yaml
This PR improves the display of measurable, health and workout data by creating sensible strings as text and adding charts in entry details, plus charts for workouts and measurables in the journal list.
> Improve data display in journal entries

- lib/l10n/app_en.arb
- lib/pages/dashboards/dashboard_page.dart
- lib/pages/empty_scaffold.dart
- lib/pages/journal/entry_details_page.dart
- lib/pages/settings/dashboards/create_dashboard_page.dart
- lib/pages/settings/dashboards/dashboard_details_page.dart
- lib/pages/settings/logging_page.dart
- lib/pages/settings/measurables/measurable_create_page.dart
- lib/pages/settings/measurables/measurable_details_page.dart
- lib/pages/settings/tags/create_tag_page.dart
- lib/pages/settings/tags/tag_edit_page.dart
- lib/widgets/app_bar/task_app_bar.dart
- pubspec.lock
- pubspec.yaml
Fix for rendering non-existing dashboard.
> Render scaffold with empty body and app bar when dashboard non-existing

- lib/pages/tasks_page.dart
looks bad on ipad or macos window strech only 500px search
> modify tasks search input to be full width

- CHANGELOG.md
- lib/l10n/app_de.arb
- lib/l10n/app_en.arb
- lib/pages/create/create_measurement_page.dart
- lib/pages/settings/tags/tag_edit_page.dart
- lib/widgets/tasks/task_form.dart
- pubspec.lock
- pubspec.yaml
This PR adds an app bar for new measurements, with a save action that only appears when data was entered.
> New measurement app bar

- lib/pages/settings/sync/sync_assistant_nav.dart
- lib/widgets/sync/qr_widget.dart
- pubspec.yaml
This PR improves animations in the Sync assistant by using a `FadeInController`.
> Improve nav icon animations

- ios/Podfile
- ios/Podfile.lock
- lib/l10n/app_en.arb
- lib/widgets/sync/imap_config_mobile.dart
- lib/widgets/sync/imap_config_status.dart
- lib/widgets/sync/qr_reader_widget.dart
- lib/widgets/sync/qr_widget.dart
- pubspec.lock
- pubspec.yaml
This PR improves the Sync assistant on mobile by displaying the result of testing the connection to the IMAP server, plus some fixes.
> Improve Sync assistant on mobile

- CHANGELOG.md
- lib/pages/journal_page.dart
- lib/pages/tasks_page.dart
- pubspec.yaml
> Improve header margin on mobile

- CHANGELOG.md
- lib/pages/create/fill_survey_page.dart
- lib/routes/journal_routes.dart
- lib/surveys/run_surveys.dart
- lib/widgets/charts/dashboard_survey_chart.dart
- lib/widgets/create/add_actions.dart
- pubspec.yaml
This PR changes filling out surveys from dashboards directly, removing an intermediate step.
> Fill survey directly from dashboard

- CHANGELOG.md
- lib/pages/settings/dashboards/dashboard_details_page.dart
- lib/pages/settings/measurables/measurable_details_page.dart
- lib/pages/settings/tags/tag_edit_page.dart
- lib/widgets/journal/entry_details/survey_summary.dart
- pubspec.yaml
This PR fixes saving some form fields, which broke with the changes in #1063.
> Fix saving form data

- CHANGELOG.md
- lib/pages/create/create_measurement_page.dart
- pubspec.lock
- pubspec.yaml
This PR adds form validation in new measurements so that the save button only appears when data has been entered. Previously, the save button also appeared already after selecting a date and time different from now.
> Guarded save button

- CHANGELOG.md
- analysis_options.yaml
- lib/blocs/sync/sync_config_cubit.dart
- lib/database/logging_db.dart
- lib/main.dart
- lib/services/sync_config_service.dart
- lib/sync/inbox_service.dart
- lib/sync/outbox.dart
- lib/widgets/journal/entry_details/survey_summary.dart
- pubspec.lock
- pubspec.yaml
- test/sync_config/sync_config_cubit_test.dart
This PR adds tests for the Sync assistant cubit, with a coverage of 98.9%.
> Sync assistant tests

- CHANGELOG.md
- pubspec.yaml
- test/sync_config/sync_config_cubit_test.dart
- test/sync_config/sync_config_test_data.dart
- test/sync_config/sync_config_test_mocks.dart
- test/sync_config/sync_config_widgets_test.dart
- test/widget_test_utils.dart
This PR adds widget tests for the sync assistant.
> Sync assistant widget tests

- CHANGELOG.md
- lib/pages/settings/dashboards/dashboard_details_page.dart
- lib/pages/settings/dashboards/dashboards_page.dart
- lib/theme.dart
- lib/widgets/journal/entry_tools.dart
- lib/widgets/settings/dashboards/dashboard_definition_card.dart
- lib/widgets/settings/measurables/measurable_type_card.dart
- lib/widgets/tasks/task_form.dart
- pubspec.yaml
- test/widgets/settings/dashboard_definition_card_test.dart
This PR adds the display of private icon and review time in the dashboard definition card.
> More info in dashboard card

- CHANGELOG.md
- lib/pages/dashboards/dashboard_page.dart
- lib/theme.dart
- lib/widgets/charts/dashboard_measurables_chart.dart
- lib/widgets/settings/dashboards/dashboard_definition_card.dart
- lib/widgets/settings/measurables/measurable_type_card.dart
- pubspec.yaml
This PR fixes line wrapping for long title and description in dashboard definition card and measurable card, dashboard page and dashboard chart header.
> Fix display of long titles and descriptions

- CHANGELOG.md
- lib/pages/settings/dashboards/chart_multi_select.dart
- lib/pages/settings/dashboards/create_dashboard_page.dart
- lib/pages/settings/dashboards/dashboard_definition_page.dart
- lib/pages/settings/outbox/outbox_monitor.dart
- lib/routes/settings_routes.dart
- lib/widgets/app_bar/app_bar_version.dart
- lib/widgets/app_bar/auto_leading_button.dart
- lib/widgets/app_bar/dashboard_app_bar.dart
- lib/widgets/app_bar/task_app_bar.dart
- lib/widgets/app_bar/title_app_bar.dart
- lib/widgets/settings/dashboards/dashboard_definition_card.dart
- lib/widgets/sync/imap_config_utils.dart
- pubspec.yaml
- test/pages/settings/dashboards/dashboard_definition_page_test.dart
- test/pages/settings/dashboards/dashboard_definition_test_mocks.dart
- test/sync/widgets/imap_config_form_widget_test.dart
- test/sync/widgets/outbox_monitor_test.dart
This PR adds tests for the dashboard definition page.
> Dashboard definition test

- lib/pages/settings/dashboards/dashboard_definition_page.dart
- lib/pages/settings/dashboards/dashboard_item_card.dart
- pubspec.yaml
- test/pages/settings/dashboards/dashboard_definition_page_test.dart
- test/test_data.dart
> Dashboard definition tests #2

- CHANGELOG.md
- lib/pages/create/create_measurement_page.dart
- pubspec.yaml
- test/pages/create/create_measurement_page_test.dart
- test/pages/settings/dashboards/dashboard_definition_page_test.dart
- test/pages/settings/dashboards/dashboard_definition_test_mocks.dart
This PR adds making the CMD-S hotkey usable when creating new measurements, plus tests for the page.
> Add CMD-S hotkey in create measurement page & tests

- .buildkite/test_only_pipeline.yml
- CHANGELOG.md
- lib/utils/platform.dart
- lib/widgets/app_bar/app_bar_version.dart
- pubspec.yaml
- test/pages/settings/advanced_settings_page_test.dart
- test/pages/settings/mocks.dart
- test/pages/settings/settings_page_test.dart
This PR adds widget tests for `SettingsPage` and `AdvancedSettingsPage`.
> Settings tests

- CHANGELOG.md
- lib/pages/home_page.dart
- lib/pages/settings/measurables/measurable_details_page.dart
- lib/theme.dart
- lib/widgets/charts/dashboard_health_config.dart
- lib/widgets/journal/journal_card.dart
- pubspec.yaml
This PR adds a few styling improvements.
> Theme: colors & whitespace

- CHANGELOG.md
- lib/main.dart
- lib/services/nav_service.dart
- lib/services/sync_config_service.dart
- lib/services/vector_clock_service.dart
- lib/services/window_service.dart
- lib/sync/inbox_service.dart
- lib/sync/secure_storage.dart
- pubspec.yaml
This PR changes the use of SecureStorage to use dependency injection for easier testing.
> Use DI for SecureStorage (mockable)

- lib/pages/journal_page.dart
- lib/pages/tasks_page.dart
- lib/theme.dart
- lib/widgets/app_bar/dashboard_app_bar.dart
- lib/widgets/charts/dashboard_health_bmi_chart.dart
- lib/widgets/create/add_tag_actions.dart
- lib/widgets/tasks/task_form.dart
- lib/widgets/tasks/task_status.dart
- pubspec.yaml
This PR adds some styling tweaks in the bright color scheme.
> Styling tweaks in bright theme

- CHANGELOG.md
- lib/widgets/journal/editor/editor_toolbar.dart
- pubspec.lock
- pubspec.yaml
This PR adds improvements in the text editor by adding support for `inline code` and ~~strike-through~~.
> Add support for strikethrough and code inline styles

- CHANGELOG.md
- ios/Podfile.lock
- lib/logic/persistence_logic.dart
- lib/services/notification_service.dart
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
> Fix timezone in dashboard review notifications

- .buildkite/test_only_pipeline.yml
- CHANGELOG.md
- lib/themes/themes_service.dart
- lib/utils/file_utils.dart
- pubspec.yaml
- test/themes/utils_test.dart
This PR adds persisting updated color themes as JSON files in the document directory.
> Persist theme

- .github/workflows/flutter-linux-build.yml
- .github/workflows/flutter-linux-release.yml
- .github/workflows/flutter-test.yml
- CHANGELOG.md
- integration_test/home_integration_test.dart
- lib/database/common.dart
- lib/database/database.dart
- lib/database/editor_db.dart
- lib/database/logging_db.dart
- lib/database/maintenance.dart
- lib/database/sync_db.dart
- lib/location.dart
- lib/logic/persistence_logic.dart
- lib/utils/timezone.dart
- pubspec.yaml
- test/helpers/path_provider.dart
- test/logic/persistence_logic_test.dart
- test/pages/create/create_measurement_page_test.dart
This PR adds tests for persistence logic and database layer, using actual SQLite but with an in-memory database. Brings total coverage from 22% to above 30%.
> Tests for database and persistence logic

- CHANGELOG.md
- lib/l10n/app_en.arb
- lib/themes/theme.dart
- lib/widgets/journal/entry_datetime_modal.dart
- pubspec.yaml
This PR adds displaying the duration covered by the entry in the DateTime modal.
> Show duration in entry datetime modal

- CHANGELOG.md
- lib/blocs/charts/story_chart_info_cubit.dart
- lib/widgets/charts/dashboard_health_chart.dart
- lib/widgets/charts/dashboard_story_chart.dart
- lib/widgets/charts/dashboard_story_data.dart
- pubspec.yaml
This PR improves time by stories chart by adding `hh:mm` labels and bar selection via tap for more info.
> Improved story chart: hh:mm legend and select for more info

- CHANGELOG.md
- lib/sync/outbox_service.dart
- pubspec.yaml
This PR adds some logging in the outbox for debugging purposes.
> Logging in sync outbox

- CHANGELOG.md
- lib/l10n/app_en.arb
- lib/widgets/journal/entry_detail_linked.dart
- pubspec.yaml
This PR adds a confirmation dialog when unlinking entries.
> Confirm unlink

- CHANGELOG.md
- lib/widgets/charts/dashboard_story_chart.dart
- lib/widgets/charts/utils.dart
- lib/widgets/journal/entry_datetime_modal.dart
- pubspec.yaml
- test/widgets/charts/utils_test.dart
Fixes for the display of durations, plus tests.
> Fix duration display

- CHANGELOG.md
- lib/widgets/journal/entry_image_widget.dart
- pubspec.yaml
This PR fixes the close icon in fullscreen photo view and adds shadow behind the close button.
> Fix closing fullscreen photo & improved close icon button

- CHANGELOG.md
- lib/database/database.dart
- lib/database/database.drift
- lib/widgets/charts/stories/wildcard_story_chart.dart
- pubspec.yaml
This PR simplifies the query for time by stories matching a substring.
> Improve chart query for time by matching stories

- CHANGELOG.md
- lib/logic/persistence_logic.dart
- lib/pages/dashboards/dashboard_page.dart
- lib/pages/dashboards/dashboards_carousel_page.dart
- lib/pages/dashboards/dashboards_list_page.dart
- lib/pages/settings/dashboards/dashboards_page.dart
- lib/routes/dashboard_routes.dart
- lib/utils/sort.dart
- lib/widgets/app_bar/dashboards_app_bar.dart
- macos/Podfile.lock
- macos/Runner.xcodeproj/project.pbxproj
- pubspec.lock
- pubspec.yaml
This PR adds a carousel/slideshow view for dashboards.
> Dashboards slideshow/carousel

- CHANGELOG.md
- ios/Podfile.lock
- lib/blocs/journal/entry_cubit.dart
- lib/logic/persistence_logic.dart
- lib/services/time_service.dart
- pubspec.lock
- pubspec.yaml
- test/blocs/journal/entry_cubit_test.dart
- test/logic/persistence_logic_test.dart
- test/sync/client_runner_test.dart
This PR changes the behavior of the save button such that the progress of a running timer is saved, if applicable.
> Save timer progress

- CHANGELOG.md
- lib/blocs/journal/entry_cubit.dart
- lib/blocs/journal/entry_state.dart
- lib/map/cached_tile_provider.dart
- lib/sync/secure_storage.dart
- lib/widgets/journal/entry_details/entry_detail_footer.dart
- lib/widgets/journal/entry_details/entry_detail_header.dart
- lib/widgets/misc/map_widget.dart
- pubspec.lock
- pubspec.yaml
- test/blocs/journal/entry_cubit_test.dart
- test/widgets/journal/entry_details/delete_icon_widget_test.dart
- test/widgets/journal/entry_details/entry_datetime_widget_test.dart
- test/widgets/journal/entry_details/entry_detail_footer_test.dart
- test/widgets/journal/entry_details/entry_detail_header_test.dart
- test/widgets/journal/entry_details/share_button_widget_test.dart
- test/widgets/journal/tags/tag_add_test.dart
This PR moves toggling visibility of maps to a toggle icon in the entry header, which is more consistent with other toggles, and also works better on small screens.
> Improve Maps UX

- CHANGELOG.md
- lib/pages/home_page.dart
- lib/pages/journal/journal_page.dart
- lib/widgets/app_bar/dashboards_app_bar.dart
- lib/widgets/journal/entry_details/delete_icon_widget.dart
- lib/widgets/journal/entry_details/entry_detail_header.dart
- lib/widgets/journal/entry_details/share_button_widget.dart
- lib/widgets/journal/entry_details_widget.dart
- lib/widgets/journal/tags/tag_add.dart
- pubspec.yaml
This PR adds a few whitespace tweaks, moves the dashboards playback button to the left, and also moves the dashboards tab to the left.
> Styling, whitespace, dashboards title

- CHANGELOG.md
- lib/widgets/journal/editor/editor_styles.dart
- pubspec.lock
- pubspec.yaml
This PR changes the style of inline code.
> Inline code style

- CHANGELOG.md
- lib/pages/settings/flags_page.dart
- pubspec.lock
- pubspec.yaml
This PR fixes text wrap on the config flags page on small screens.
> Fix text wrap

- lib/pages/create/create_measurement_modal.dart
- lib/pages/create/create_measurement_page.dart
- lib/widgets/app_bar/dashboard_app_bar.dart
- lib/widgets/charts/dashboard_measurables_chart.dart
- pubspec.lock
- pubspec.yaml
- test/widgets/charts/dashboard_measurables_test.dart
This PR adds some tweaks around dashboard navigation.
> Navigation tweaks

- lib/pages/journal/entry_details_page.dart
- lib/pages/journal/journal_page.dart
- lib/widgets/create/add_actions.dart
- pubspec.lock
- pubspec.yaml
- test/mocks/mocks.dart
- test/widgets/create/add_actions_test.dart
- test/widgets/create/add_tag_actions_test.dart
This PR adds tests for the `RadialAddActionButtons` widget.
> Tests for RadialAddActionButtons

- CHANGELOG.md
- lib/widgets/journal/entry_details_widget.dart
- pubspec.lock
- pubspec.yaml
This PR enables capturing text on measurable and survey entry types.
> Text in measurables and surveys

- CHANGELOG.md
- lib/beamer/locations/dashboards_location.dart
- lib/l10n/app_de.arb
- lib/l10n/app_en.arb
- lib/logic/persistence_logic.dart
- lib/pages/create/create_measurement_dialog.dart
- lib/utils/entry_utils.dart
- pubspec.lock
- pubspec.yaml
- test/pages/create/create_measurement_dialog_test.dart
- test/utils/entry_utils_test.dart
This PR adds an optional comment field in the new measurement dialog.
> Measurable comment

- ios/Podfile.lock
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
This PR upgrades Flutter to version `3.3.0`.
> Upgrade Flutter & dependencies

- .github/workflows/flutter-analyze.yml
- .github/workflows/flutter-linux-build.yml
- .github/workflows/flutter-linux-release.yml
- .github/workflows/flutter-test.yml
- .github/workflows/flutter-testflight.yml
- .github/workflows/flutter-windows-build.yml
- CHANGELOG.md
- ios/Flutter/AppFrameworkInfo.plist
- lib/beamer/beamer_app.dart
- lib/sync/inbox/save_attachments.dart
- lib/utils/image_utils.dart
- lib/widgets/audio/audio_player.dart
- lib/widgets/misc/buttons.dart
- lib/widgets/misc/desktop_menu.dart
- pubspec.lock
- pubspec.yaml
- test/mocks/mocks.dart
- test/widget_test_utils.dart
- test/widgets/audio/audio_player_test.dart
- test/widgets/audio/audio_recorder_test.dart
This PR adds tests for the audio player and recorder widgets.
> Audio widget tests

- CHANGELOG.md
- pubspec.yaml
- test/pages/create/fill_survey_page_test.dart
This PR adds tests for filling surveys.
> Test: add tests for surveys

- CHANGELOG.md
- lib/beamer/locations/settings_location.dart
- lib/database/database.dart
- lib/database/database.drift
- lib/l10n/app_en.arb
- lib/pages/empty_scaffold.dart
- lib/pages/settings/about_page.dart
- lib/pages/settings/conflicts_page.dart
- lib/pages/settings/settings_card.dart
- lib/services/nav_service.dart
- lib/themes/theme.dart
- lib/widgets/journal/entry_details/measurement_summary.dart
- lib/widgets/journal/journal_card.dart
- lib/widgets/journal/text_viewer_widget.dart
- pubspec.yaml
- test/pages/settings/conflicts_page_test.dart
- test/test_data/test_data.dart
This PR repairs the conflicts resolution UI, plus introduces some UI changes.
> Sync conflicts

- CHANGELOG.md
- lib/services/window_service.dart
- lib/sync/client_runner.dart
- lib/sync/inbox/inbox_service.dart
- lib/sync/outbox_service.dart
- pubspec.yaml
This PR adds the detection of window focus in the Sync services so that the services resume properly after waking laptop.
> Sync: Detect when desktop app is resumed

- CHANGELOG.md
- lib/pages/journal/journal_page.dart
- lib/pages/settings/conflicts_page.dart
- lib/pages/tasks/tasks_page.dart
- lib/sync/inbox/process_message.dart
- lib/widgets/charts/dashboard_health_bmi_chart.dart
- lib/widgets/charts/dashboard_health_bp_chart.dart
- lib/widgets/charts/dashboard_health_chart.dart
- lib/widgets/charts/dashboard_measurables_chart.dart
- lib/widgets/charts/dashboard_workout_chart.dart
- lib/widgets/charts/stories/dashboard_story_chart.dart
- lib/widgets/charts/stories/wildcard_story_chart.dart
- lib/widgets/journal/entry_details/survey_summary.dart
- lib/widgets/journal/entry_details/workout_summary.dart
- lib/widgets/sync/qr_reader_widget.dart
- pubspec.lock
- pubspec.yaml
Changed order of layers fixes the issue, see https://github.com/google/charts/compare/master...matthiasn:charts:master
> Fix bars in bar chart overlapping domain axis

- CHANGELOG.md
- lib/pages/create/fill_survey_page.dart
- lib/pages/settings/dashboards/dashboard_definition_page.dart
- lib/pages/settings/dashboards/dashboard_item_card.dart
- lib/pages/settings/health_import_page.dart
- lib/surveys/run_surveys.dart
- lib/widgets/charts/dashboard_item_modal.dart
- lib/widgets/journal/entry_details/entry_datetime_widget.dart
- lib/widgets/journal/tags/tag_add.dart
- lib/widgets/misc/buttons.dart
- pubspec.yaml
This PR adapts the survey modal bottom sheet to use `modal_bottom_sheet`.
> Survey bottom sheet

- CHANGELOG.md
- assets/icons/filter.svg
- assets/icons/search.svg
- lib/classes/config.dart
- lib/pages/dashboards/dashboard_page.dart
- lib/themes/themes.dart
- lib/widgets/settings/settings_card.dart
- pubspec.yaml
- test/themes/themes_service_test.dart
This PR changes the interaction with the displayed time span in dashboards such that the number of days can be selected in a segmented control. The previous multitouch interaction with pan & zoom was cumbersome to use and is disabled for now.
> Segmented control for time span displayed in dashboard

- .github/workflows/flutter-analyze.yml
- .github/workflows/flutter-linux-build.yml
- .github/workflows/flutter-linux-release.yml
- .github/workflows/flutter-test.yml
- .github/workflows/flutter-testflight.yml
- .github/workflows/flutter-windows-build.yml
- CHANGELOG.md
- lib/classes/entity_definitions.dart
- lib/pages/dashboards/dashboard_page.dart
- lib/widgets/charts/dashboard_measurables_chart.dart
- lib/widgets/charts/utils.dart
- pubspec.yaml
- test/widgets/charts/dashboard_measurables_test.dart
This PR adds an hourly aggregation type in measurables charts.
> Hourly aggregation

- CHANGELOG.md
- lib/beamer/beamer_app.dart
- lib/pages/dashboards/dashboard_page.dart
- lib/widgets/charts/dashboard_measurables_chart.dart
- pubspec.yaml
This PR increases the height of measurement line charts. Also fixes the alignment of the time axis between different chart types.
> Chart height

- CHANGELOG.md
- lib/logic/health_import.dart
- lib/widgets/charts/dashboard_health_config.dart
- pubspec.lock
- pubspec.yaml
This PR adds import of the total distance (walking or running) per day.
> Add health query for cumulative_distance

- .github/workflows/flutter-analyze.yml
- .github/workflows/flutter-linux-build.yml
- .github/workflows/flutter-linux-release.yml
- .github/workflows/flutter-test.yml
- .github/workflows/flutter-testflight.yml
- .github/workflows/flutter-windows-build.yml
- CHANGELOG.md
- codecov.yml
- lib/widgets/journal/entry_details/share_button_widget.dart
- pubspec.lock
- pubspec.yaml
This PR upgrades Flutter to version `3.3.4` and upgrades all eligible dependencies.
> Upgrade Flutter from 3.3.3 to 3.3.4

- CHANGELOG.md
- lib/pages/habits/habits_page.dart
- lib/widgets/charts/stories/wildcard_story_chart.dart
- lib/widgets/charts/utils.dart
- lib/widgets/settings/habits/habits_type_card.dart
- pubspec.yaml
This PR fixes the time chart to include the current day, plus sorts the habits on the habits page by the time from which on the are shown as due.
> Fix time chart & sort habits

- CHANGELOG.md
- ios/Podfile.lock
- lib/database/database.dart
- lib/database/database.drift
- lib/get_it.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
This PR moves the `JournalDb` to a separate isolate, freeing up CPU resources on the main thread/isolate.
> Move JournalDb to separate isolate

- CHANGELOG.md
- lib/widgets/journal/entry_details_widget.dart
- lib/widgets/journal/entry_image_widget.dart
- pubspec.yaml
This PR improves the photo view on entry details by moving the image below the header, and positioning the image on a black background.
> Photo entry improvement

- CHANGELOG.md
- lib/widgets/app_bar/task_app_bar.dart
- lib/widgets/charts/dashboard_habits_chart.dart
- pubspec.yaml
This PR removes the "Task not found" message when task is still loading & improves spacing between habit success indicators.
> Fix loading message & spacing between habit success indicators

- CHANGELOG.md
- lib/logic/charts/story_data.dart
- lib/pages/habits/habits_page.dart
- lib/widgets/charts/dashboard_workout_data.dart
- lib/widgets/charts/utils.dart
- pubspec.lock
- pubspec.yaml
- test/logic/charts/story_data_test.dart
- test/pages/habits/habits_tab_page_test.dart
- test/test_data/test_data.dart
This PR adds a most basic version of displaying habit streaks by showing the following information in the header/app bar of the habits page: total number of habits, habits completed on the current day, short habit streaks of two days and longer habit streaks up until seven days (with the streaks analysed up until the previous days).
> Habit streaks

- CHANGELOG.md
- lib/sync/imap_client.dart
- lib/sync/inbox/inbox_service_isolate.dart
- lib/sync/inbox/process_message.dart
- lib/sync/outbox/outbox_imap.dart
- lib/sync/outbox/outbox_service_isolate.dart
- lib/utils/screenshots.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
- test/sync/outbox/outbox_imap_test.dart
- test/sync/outbox/outbox_service_test.dart
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
This PR adds [`retry`](https://pub.dev/packages/retry) for retrying IMAP operations with [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff).
> Sync retry

- CHANGELOG.md
- lib/widgets/charts/dashboard_habits_chart.dart
- pubspec.yaml
This PR makes the interaction with the habit completion add icon more consistent with the rest of the app on desktop.
> Improved habit completion add icon

- CHANGELOG.md
- lib/beamer/locations/journal_location.dart
- lib/beamer/locations/tasks_location.dart
- lib/blocs/habits/habits_cubit.dart
- lib/blocs/habits/habits_state.dart
- lib/pages/create/create_measurement_page.dart
- lib/pages/habits/habits_page.dart
- lib/pages/journal/entry_details_page.dart
- lib/pages/settings/conflicts_page.dart
- lib/pages/settings/dashboards/dashboards_page.dart
- lib/pages/settings/logging_page.dart
- lib/services/nav_service.dart
- lib/widgets/app_bar/dashboards_app_bar.dart
- lib/widgets/charts/dashboard_habits_chart.dart
- lib/widgets/journal/card_image_widget.dart
- lib/widgets/journal/entry_details_widget.dart
- lib/widgets/journal/tags/tag_add.dart
- lib/widgets/journal/tags/tags_modal.dart
- pubspec.yaml
- test/widgets/journal/journal_card_test.dart
- test/widgets/journal/tags/tag_add_test.dart
- test/widgets/journal/tags/tags_modal_widget_test.dart
This PR fixes flickering on mobile when managing tags.
> Fix flicker in tags modal

- CHANGELOG.md
- lib/widgets/charts/dashboard_habits_chart.dart
- lib/widgets/charts/dashboard_habits_data.dart
- pubspec.lock
- pubspec.yaml
This PR refactors habit data processing for better separation between UI and logic.
> Refactor habits

- CHANGELOG.md
- lib/pages/create/complete_habit_dialog.dart
- pubspec.lock
- pubspec.yaml
This PR improves the habit capture dialog.
> Habit capture

- CHANGELOG.md
- ios/Podfile.lock
- lib/blocs/journal/entry_cubit.dart
- lib/widgets/tasks/task_form.dart
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
This PR adds saving tasks via typing `CMD-S` in the task title field.
> Task save via CMD-S in task title

- CHANGELOG.md
- lib/pages/create/complete_habit_dialog.dart
- pubspec.yaml
This PR add recording the duration between opening habit and completing habit (unless date in the past is selected).
> Record duration between opening habit and completing habit

- CHANGELOG.md
- lib/classes/entity_definitions.dart
- lib/l10n/app_en.arb
- lib/logic/persistence_logic.dart
- lib/pages/create/complete_habit_dialog.dart
- lib/pages/settings/habits/habit_details_page.dart
- pubspec.yaml
- test/logic/persistence_logic_test.dart
- test/pages/create/complete_habit_dialog_test.dart
- test/pages/settings/habits/habit_details_page_test.dart
This PR adds defining an optional default story for habit completions. When defined, the habit completion will appear on the respective timeline.
> Habit story

- CHANGELOG.md
- lib/blocs/habits/habits_cubit.dart
- lib/classes/entity_definitions.dart
- lib/widgets/settings/habits/habit_autocomplete_widget.dart
- pubspec.lock
- pubspec.yaml
This PR adds more work to habit autocomplete rules. Will be used later.
> Habit autocomplete rules

- CHANGELOG.md
- lib/pages/create/complete_habit_dialog.dart
- lib/themes/theme.dart
- pubspec.lock
- pubspec.yaml
This PR adds showing the habit description when completing a habit to revisit instructions relevant to the habit. When present, links can be clicked. This can for example be useful for meditation videos on YouTube or whatnot.
> Show habit description when completing habit, with clickable links

- CHANGELOG.md
- lib/blocs/settings/habits/habit_settings_cubit.dart
- lib/blocs/settings/habits/habit_settings_state.dart
- lib/logic/habits/autocomplete_update.dart
- lib/pages/settings/habits/habit_details_page.dart
- lib/widgets/settings/habits/habit_autocomplete_widget.dart
- pubspec.yaml
- test/blocs/habits/autocomplete_update_data.dart
- test/blocs/habits/autocomplete_update_test.dart
> Habit autocomplete rule creator experiments

- CHANGELOG.md
- ios/Podfile.lock
- lib/pages/create/create_measurement_dialog.dart
- lib/utils/measurable_utils.dart
- lib/widgets/create/suggest_measurement.dart
- macos/Podfile
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
- test/pages/create/create_measurement_dialog_test.dart
- test/utils/measurable_utils_test.dart
- test/widgets/create/measurement_suggestions_test.dart
This PR adds suggesting measurables from previously used values, ranked by popularity.
> Suggest measurable value from frequently used

- CHANGELOG.md
- lib/blocs/habits/habits_cubit.dart
- lib/blocs/habits/habits_state.dart
- lib/widgets/charts/habits/habit_completion_rate_chart.dart
- pubspec.lock
- pubspec.yaml
This PR fixes the habit completion percentage when private habits are hidden.
> Fix habit percentage

- CHANGELOG.md
- lib/pages/habits/habits_page.dart
- lib/themes/theme.dart
- lib/widgets/charts/habits/habit_completion_rate_chart.dart
- lib/widgets/habits/habit_page_app_bar.dart
- pubspec.yaml
This PR improves whitespace in the habit page header:
> Habit chart whitespace improvements

- CHANGELOG.md
- lib/widgets/charts/dashboard_health_bp_chart.dart
- pubspec.yaml
This PR improves the blood pressure chart by adding indicator lines for targets 120 mmHg systolic and 80 mmHg diastolic, which appear to be generally accepted values for a normal & healthy blood pressure.
> Improved blood pressure chart with 120/80 indicators

- CHANGELOG.md
- lib/beamer/locations/journal_location.dart
- lib/database/database.dart
- lib/database/database.drift
- lib/pages/journal/infinite_journal_page.dart
- lib/pages/tasks/tasks_page.dart
- lib/utils/platform.dart
- lib/widgets/journal/journal_card.dart
- pubspec.lock
- pubspec.yaml
- test/pages/journal/infinite_journal_page_test.dart
This PR improves the journal page by changing to infinite scroll, instead of rendering a fixed number of items in advance. Needs further refactoring, and removal of the old page once testing is done.
> Infinite scroll

- CHANGELOG.md
- lib/pages/journal/entry_details_page.dart
- lib/widgets/charts/habits/habit_completion_rate_chart.dart
- lib/widgets/habits/habit_page_app_bar.dart
- pubspec.yaml
- Disable smooth curved lines in habits chart: sharp lines are not overshooting
- Improved chart layout and CTA (tap chart for daily breakdown)
> Habit completion chart improvements:

- CHANGELOG.md
- lib/sync/encryption.dart
- lib/utils/screenshots.dart
- pubspec.yaml
This PR adds a short delay when recording a screenshot. Also reduces allocations in sync.
> Screenshot delay

- CHANGELOG.md
- lib/blocs/habits/habits_cubit.dart
- lib/blocs/habits/habits_state.dart
- lib/widgets/charts/habits/habit_completion_rate_chart.dart
- pubspec.yaml
This PR fixes the calculation of the habit completion rate for new habits prior to them becoming active.
> Fix completion rate by taking into account from when on to count a habit

- CHANGELOG.md
- lib/widgets/journal/editor/editor_widget.dart
- pubspec.lock
- pubspec.yaml
This PR limits the editor height so that editor toolbar always stays visible.
> Editor height

- CHANGELOG.md
- lib/beamer/beamer_app.dart
- lib/pages/settings/dashboards/dashboards_page.dart
- lib/pages/settings/habits/habits_page.dart
- lib/pages/settings/measurables/measurables_page.dart
- lib/pages/settings/tags/tags_page.dart
- pubspec.yaml
This PR fixes an issue with the keyboard showing briefly and then disappearing again on mobile. Removing the `MediaQuery.of(context)` in `lib/beamer/beamer_app.dart` solves the problem.
> Fix disappearing keyboard on mobile

- CHANGELOG.md
- lib/pages/settings/dashboards/dashboards_page.dart
- lib/pages/settings/definitions_list_page.dart
- lib/pages/settings/habits/habits_page.dart
- lib/pages/settings/measurables/measurables_page.dart
- lib/pages/settings/tags/tags_page.dart
- lib/themes/theme.dart
- lib/themes/themes.dart
- lib/widgets/journal/editor/editor_toolbar.dart
- lib/widgets/tasks/task_form.dart
- pubspec.yaml
This PR extracts the searchable list type used in settings pages for habits, dashboards, measurable data types, and tags.
> Extract searchable page for entity definitions

- CHANGELOG.md
- lib/beamer/beamer_app.dart
- lib/pages/journal/infinite_journal_page.dart
- lib/pages/settings/definitions_list_page.dart
- lib/themes/theme.dart
- lib/widgets/app_bar/definitions_list_app_bar.dart
- lib/widgets/misc/search_widget.dart
- pubspec.yaml
The PR replace the floating search bar on the new infinite journal page and on the settings pages for different entities.
> Replace floating search bar

- CHANGELOG.md
- lib/pages/settings/dashboards/dashboard_definition_page.dart
- lib/pages/settings/measurables/measurable_details_page.dart
- pubspec.yaml
This PR simplifies settings for both defining measurable data types and dashboards by removing items that are either not used or not all that useful.
> Simplify settings

- CHANGELOG.md
- lib/beamer/beamer_app.dart
- lib/pages/settings/habits/habit_details_page.dart
- lib/widgets/app_bar/definitions_list_app_bar.dart
- lib/widgets/app_bar/journal_sliver_appbar.dart
- lib/widgets/search/search_widget.dart
- pubspec.yaml
This PR fixes the issue that the keyboard could not be dismissed once the search field had focus until typing anything by always showing the clear/close icon.
Also fixes clearing story selection in habit definition.
> Fix keyboard dismissal in search field by always showing the X icon

- CHANGELOG.md
- ios/Podfile.lock
- lib/pages/habits/habits_page.dart
- lib/widgets/charts/habits/dashboard_habits_chart.dart
- lib/widgets/habits/habit_streaks.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
This PR removes the rather useless habit streaks section on the habits page, which mostly added noise.
> Remove streaks section

- CHANGELOG.md
- lib/widgets/journal/editor/editor_styles.dart
- lib/widgets/journal/entry_details/duration_widget.dart
- lib/widgets/journal/entry_details/entry_datetime_modal.dart
- lib/widgets/journal/entry_details/entry_datetime_widget.dart
- lib/widgets/journal/journal_card.dart
- lib/widgets/tasks/linked_duration.dart
- macos/Podfile.lock
- pubspec.yaml
This PR fixes the issue with unreadable code/monospace fonts in the entry text editor, and consolidates monospace font styles more broadly.
Resolves #1320.
> Fix code font color

- CHANGELOG.md
- lib/widgets/journal/entry_details_widget.dart
- pubspec.yaml
> Add missing habit summary in entry details view

- CHANGELOG.md
- lib/blocs/habits/habits_cubit.dart
- lib/blocs/habits/habits_state.dart
- lib/widgets/charts/habits/habit_completion_rate_chart.dart
- lib/widgets/habits/habit_page_app_bar.dart
- pubspec.yaml
> Toggle between zero-based and adaptive charts

- CHANGELOG.md
- lib/widgets/habits/habit_page_app_bar.dart
- pubspec.yaml
This PR improves the adaptive habit completion chart by only showing the toggle icon when that leads to discernible differences.
Resolves #1335
> Improve adaptive charts toggle

- CHANGELOG.md
- lib/pages/create/complete_habit_dialog.dart
- pubspec.lock
- pubspec.yaml
This PR fixes an issue where the habit title would overflow for long titles instead of properly breaking into multiple lines.
> Fix line break

- CHANGELOG.md
- lib/classes/entity_definitions.dart
- lib/widgets/charts/habits/dashboard_habits_data.dart
- pubspec.lock
- pubspec.yaml
This PR adds some opacity for not-yet-recorded habit fails, such that they can be discerned from recorded fails.
Resolves #1344.
> Failed vs missing completion

- CHANGELOG.md
- lib/database/journal_db/config_flags.dart
- lib/l10n/app_de.arb
- lib/l10n/app_en.arb
- lib/l10n/app_fr.arb
- lib/l10n/app_ro.arb
- lib/main.dart
- lib/pages/settings/flags_page.dart
- lib/utils/consts.dart
- lib/utils/screenshots.dart
- pubspec.yaml
- test/database/database_test.dart
- test/pages/create/complete_habit_dialog_test.dart
- test/pages/create/create_measurement_dialog_test.dart
- test/pages/create/create_measurement_page_test.dart
- test/pages/journal/entry_detail_page_test.dart
- test/pages/settings/advanced_settings_page_test.dart
- test/pages/settings/dashboards/dashboard_definition_page_test.dart
- test/pages/settings/habits/habit_details_page_test.dart
- test/pages/settings/habits/habits_page_test.dart
- test/pages/settings/logging_page_test.dart
- test/pages/settings/measurables/measurable_details_page_test.dart
- test/pages/settings/measurables/measurables_page_test.dart
- test/pages/settings/tags/create_tag_page_test.dart
- test/pages/settings/tags/tag_edit_page_test.dart
- test/pages/settings/tags/tags_page_test.dart
This PR removes config flags that are no longer useful.
Resolves #1346.
> Config flags cleanup

- CHANGELOG.md
- lib/beamer/locations/journal_location.dart
- lib/blocs/audio/recorder_cubit.dart
- lib/blocs/audio/recorder_state.dart
- lib/widgets/audio/audio_recorder.dart
- lib/widgets/create/add_actions.dart
- pubspec.yaml
- test/widgets/create/add_actions_test.dart
> Fix audio recorder

- CHANGELOG.md
- lib/logic/health_import.dart
- lib/pages/settings/dashboards/dashboard_item_card.dart
- lib/widgets/charts/dashboard_health_config.dart
- lib/widgets/charts/dashboard_workout_config.dart
- pubspec.yaml
- test/pages/settings/dashboards/dashboard_definition_page_test.dart
- test/widgets/charts/dashboard_health_data_test.dart
- test/widgets/charts/utils_test.dart
- test/widgets/journal/entry_details/workout_summary_test.dart
> Workout labels

- .github/workflows/flutter-windows-build.yml
- CHANGELOG.md
- lib/logic/health_import.dart
- lib/pages/settings/outbox/outbox_badge.dart
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
> Fix health data import

- .github/workflows/flutter-analyze.yml
- .github/workflows/flutter-linux-build.yml
- .github/workflows/flutter-linux-release.yml
- .github/workflows/flutter-test.yml
- .github/workflows/flutter-testflight.yml
- .github/workflows/flutter-windows-build.yml
- CHANGELOG.md
- lib/pages/create/complete_habit_dialog.dart
- pubspec.lock
- pubspec.yaml
> Fix null display

- CHANGELOG.md
- lib/beamer/beamer_app.dart
- lib/pages/create/create_measurement_dialog.dart
- lib/pages/create/fill_survey_page.dart
- lib/pages/settings/about_page.dart
- lib/pages/settings/dashboards/dashboard_definition_page.dart
- lib/pages/settings/dashboards/dashboard_item_card.dart
- lib/themes/theme.dart
- lib/widgets/charts/dashboard_health_bp_chart.dart
- lib/widgets/charts/time_series/time_series_line_chart.dart
- lib/widgets/journal/tags/tags_view_widget.dart
- lib/widgets/journal/text_viewer_widget.dart
- lib/widgets/settings/settings_card.dart
- lib/widgets/sync/qr_widget.dart
- pubspec.yaml
> Set mainfont in theme & enable Material Design 3

- CHANGELOG.md
- lib/beamer/beamer_app.dart
- lib/pages/create/complete_habit_dialog.dart
- lib/pages/create/create_measurement_dialog.dart
- lib/themes/theme.dart
- lib/widgets/app_bar/journal_sliver_appbar.dart
- lib/widgets/app_bar/task_app_bar.dart
- lib/widgets/audio/audio_player.dart
- lib/widgets/journal/tags/tag_widget.dart
- lib/widgets/journal/tags/tags_view_widget.dart
- lib/widgets/search/entry_type_filter.dart
- lib/widgets/search/filter_choice_chip.dart
- lib/widgets/search/task_status_filter.dart
- lib/widgets/tasks/linked_duration.dart
- lib/widgets/tasks/task_form.dart
- lib/widgets/tasks/task_status.dart
- pubspec.yaml
- test/widgets/journal/tags/tag_widget_test.dart
This PR fixes a few issues that arose after updating to Material Design 3, plus adds some improvements.
> Design fixes

- CHANGELOG.md
- ios/Runner/Info.plist
- lib/beamer/beamer_app.dart
- lib/pages/create/complete_habit_dialog.dart
- lib/themes/themes.dart
- lib/widgets/journal/entry_details/share_button_widget.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
This PR adds a few design tweaks and fixes.
> Design tweaks and fixes

- CHANGELOG.md
- lib/pages/create/create_measurement_dialog.dart
- lib/themes/theme.dart
- lib/widgets/create/suggest_measurement.dart
- pubspec.lock
- pubspec.yaml
- test/widgets/create/measurement_suggestions_test.dart
> Improve data capture dialog

- CHANGELOG.md
- lib/pages/create/complete_habit_dialog.dart
- lib/pages/create/create_measurement_dialog.dart
- lib/themes/theme.dart
- pubspec.yaml
This PR fixes a few small UI bugs:
- Habit fail button color
- Save button color
- Clipped save button on measurement page
> Fix small UI bugs

- CHANGELOG.md
- lib/beamer/locations/journal_location.dart
- lib/pages/settings/dashboards/dashboard_item_card.dart
- lib/pages/settings/outbox/outbox_badge.dart
- lib/surveys/run_surveys.dart
- lib/widgets/badges/flagged_badge.dart
- lib/widgets/badges/tasks_badge_icon.dart
- lib/widgets/journal/entry_details/entry_datetime_widget.dart
- lib/widgets/journal/tags/tags_modal.dart
- pubspec.lock
- pubspec.yaml
> Remove unnecessary dependencies

- CHANGELOG.md
- lib/widgets/journal/entry_details/entry_datetime_widget.dart
- lib/widgets/journal/entry_tools.dart
- lib/widgets/journal/journal_card.dart
- pubspec.lock
- pubspec.yaml
- test/pages/journal/entry_detail_page_test.dart
- test/pages/journal/infinite_journal_page_test.dart
- test/widgets/journal/entry_details/entry_datetime_widget_test.dart
- test/widgets/journal/entry_details/entry_detail_footer_test.dart
- test/widgets/journal/journal_card_test.dart
> Remove seconds from timestamps

- CHANGELOG.md
- lib/pages/create/fill_survey_page.dart
- pubspec.yaml
> Fix background colors in survey modal bottom sheets

- CHANGELOG.md
- lib/beamer/beamer_app.dart
- lib/services/tags_service.dart
- lib/surveys/run_surveys.dart
- lib/themes/theme.dart
- lib/widgets/charts/dashboard_item_modal.dart
- lib/widgets/journal/entry_details/entry_datetime_modal.dart
- lib/widgets/journal/entry_details/entry_datetime_widget.dart
- lib/widgets/journal/entry_details/survey_summary.dart
- lib/widgets/journal/tags/tag_add.dart
- lib/widgets/journal/tags/tags_modal.dart
- pubspec.yaml
This PR fixes the tags modal & improves typography by replacing monospace font usage with main font & tabularFigures font feature.
Resolves #1398
> Tags modal improvement

- CHANGELOG.md
- ios/Podfile.lock
- lib/widgets/journal/entry_details/entry_datetime_modal.dart
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
- test/widgets/journal/entry_details/entry_datetime_widget_test.dart
> Fix datetime modal

- CHANGELOG.md
- lib/beamer/beamer_app.dart
- lib/pages/dashboards/dashboard_page.dart
- lib/pages/dashboards/dashboards_carousel_page.dart
- lib/pages/dashboards/dashboards_list_page.dart
- lib/pages/dashboards/how_to_use_page.dart
- lib/pages/habits/habits_page.dart
- lib/pages/journal/entry_details_page.dart
- lib/themes/theme.dart
- lib/widgets/charts/habits/dashboard_habits_chart.dart
- lib/widgets/journal/editor/editor_widget.dart
- lib/widgets/journal/entry_detail_linked.dart
- lib/widgets/journal/entry_detail_linked_from.dart
- lib/widgets/journal/entry_details/entry_detail_header.dart
- lib/widgets/journal/entry_details_widget.dart
- lib/widgets/journal/journal_card.dart
- lib/widgets/journal/tags/tags_list_widget.dart
- lib/widgets/tasks/task_form.dart
- pubspec.yaml
This PR adapts the habit layout to use cards, plus adapts whitespace around cards throughout the app.
> New habit layout

- CHANGELOG.md
- lib/l10n/app_de.arb
- lib/l10n/app_en.arb
- lib/themes/theme.dart
- lib/widgets/app_bar/journal_sliver_appbar.dart
- lib/widgets/journal/editor/editor_widget.dart
- lib/widgets/search/entry_type_filter.dart
- lib/widgets/search/filter_choice_chip.dart
- lib/widgets/search/task_status_filter.dart
- pubspec.yaml
> Journal filter & placeholder text

- .buildkite/pipeline.yml
- CHANGELOG.md
- lib/widgets/charts/habits/dashboard_habits_chart.dart
- pubspec.yaml
This PR improves the habit completion icon:
> Improve habit completion icon

- CHANGELOG.md
- lib/blocs/habits/habits_cubit.dart
- lib/blocs/habits/habits_state.dart
- lib/l10n/app_en.arb
- lib/pages/habits/habits_page.dart
- lib/widgets/misc/segmented_control.dart
- pubspec.yaml
> Add search field for habits

- CHANGELOG.md
- lib/blocs/habits/habits_cubit.dart
- lib/blocs/habits/habits_state.dart
- lib/pages/habits/habits_page.dart
- lib/widgets/habits/habits_filter.dart
- pubspec.yaml
This PR adds habits filtering functionality, with a bottom sheet that appears after tapping the habits by categories donut chart.
Resolves #1422
> Habits filter

- CHANGELOG.md
- lib/blocs/habits/habits_cubit.dart
- pubspec.yaml
This PR contains a quick fix for fetching habits for the entire possible range of habit completions that can be displayed.
> Fix 180 days in habit completion rate chart

- CHANGELOG.md
- lib/blocs/settings/categories/category_settings_cubit.dart
- lib/blocs/settings/categories/category_settings_state.dart
- lib/database/conversions.dart
- lib/pages/settings/categories/category_details_page.dart
- pubspec.lock
- pubspec.yaml
Resolves #1427.
Resolves #1429.
> Fix category save

- CHANGELOG.md
- lib/widgets/tasks/linked_duration.dart
- pubspec.yaml
- test/pages/journal/entry_detail_page_test.dart
> Task time display

- CHANGELOG.md
- lib/blocs/settings/categories/category_settings_cubit.dart
- pubspec.yaml
> Fix category color save

- CHANGELOG.md
- lib/l10n/app_de.arb
- lib/l10n/app_en.arb
- lib/widgets/misc/datetime_bottom_sheet.dart
- pubspec.lock
- pubspec.yaml
Resolved #1442.
Also renames the field.
> Fix habit start date

- CHANGELOG.md
- lib/blocs/habits/habits_cubit.dart
- lib/widgets/charts/utils.dart
- pubspec.yaml
- test/sync/outbox/outbox_service_test.dart
> Fix habit completion chart display range issue

- CHANGELOG.md
- lib/blocs/habits/habits_cubit.dart
- pubspec.yaml
> Categories filter applies to all sections, not only currently due habits

- CHANGELOG.md
- lib/logic/image_import.dart
- pubspec.yaml
> Fix picking multiple images only picking one image

- CHANGELOG.md
- lib/services/notification_service.dart
- lib/utils/location.dart
- pubspec.yaml
> Remove pointless request for notification permission

- CHANGELOG.md
- lib/pages/create/create_measurement_dialog.dart
- lib/themes/theme.dart
- lib/widgets/create/suggest_measurement.dart
- pubspec.yaml
- test/widgets/create/measurement_suggestions_test.dart
> Fix unselectable suggestion in measurement dialog

- CHANGELOG.md
- lib/pages/create/complete_habit_dialog.dart
- lib/pages/create/create_measurement_dialog.dart
- lib/pages/settings/dashboards/dashboard_definition_page.dart
- lib/pages/settings/dashboards/dashboard_item_card.dart
- lib/themes/theme.dart
- lib/widgets/charts/dashboard_measurables_line_chart.dart
- pubspec.yaml
> Fix data capture

- .github/workflows/flutter-analyze.yml
- .github/workflows/flutter-linux-build.yml
- .github/workflows/flutter-linux-release.yml
- .github/workflows/flutter-test.yml
- .github/workflows/flutter-testflight.yml
- .github/workflows/flutter-windows-build.yml
- CHANGELOG.md
- lib/widgets/app_bar/dashboards_app_bar.dart
- lib/widgets/charts/habits/dashboard_habits_chart.dart
- pubspec.lock
- pubspec.yaml
This PR brings back the Windows build, creating an unsigned `msix` installer in Releases that can then be uploaded on the Microsoft store for signing and distribution.
Resolves #1466.
> Windows build

- CHANGELOG.md
- lib/pages/create/complete_habit_dialog.dart
- lib/widgets/charts/dashboard_health_bp_chart.dart
- lib/widgets/charts/time_series/time_series_line_chart.dart
- lib/widgets/habits/habit_completion_card.dart
- pubspec.lock
- pubspec.yaml
> Improve charts

- CHANGELOG.md
- README.md
- lib/pages/create/create_measurement_dialog.dart
- pubspec.yaml
This PR adds styling improvements in the data capture dialog.
> Data capture dialog style improvements

- CHANGELOG.md
- lib/blocs/audio/recorder_cubit.dart
- lib/classes/audio_note.dart
- lib/logic/image_import.dart
- lib/logic/persistence_logic.dart
- lib/utils/location.dart
- pubspec.yaml
This PR is an attempt to resolve #1470 by removing the concept of locations from audio note altogether. Location can saved on inserting into the database.
> Fix location permission

- .buildkite/pipeline.yml
- CHANGELOG.md
- lib/services/window_service.dart
- pubspec.yaml
This PR changes the initial size of the window on make to be displayed in portrait mode more similar to the presentation on mobile. This is particularly useful when taking screenshots in the Fluttium test runs.
> Change initial size on macOS

- CHANGELOG.md
- lib/l10n/app_en.arb
- lib/pages/dashboards/dashboards_list_page.dart
- lib/pages/habits/habits_page.dart
- lib/widgets/app_bar/dashboards_app_bar.dart
- lib/widgets/app_bar/definitions_list_app_bar.dart
- lib/widgets/app_bar/journal_sliver_appbar.dart
- lib/widgets/habits/habit_page_app_bar.dart
- lib/widgets/search/search_widget.dart
- pubspec.yaml
- test/pages/settings/dashboards/dashboard_definition_page_test.dart
This PR improves the look of the app bar by introducing a SliverAppBar that shrinks and disappears when scrolling up.
> Dashboard page header

- CHANGELOG.md
- lib/pages/create/complete_habit_dialog.dart
- lib/pages/dashboards/dashboards_list_page.dart
- lib/widgets/app_bar/dashboards_app_bar.dart
- lib/widgets/dashboards/dashboard_widget.dart
- lib/widgets/habits/habit_page_app_bar.dart
- lib/widgets/settings/settings_icon.dart
- pubspec.yaml
> Settings icon on Habits page

- CHANGELOG.md
- lib/pages/settings/measurables/measurable_details_page.dart
- pubspec.yaml
This PR changes the style of the measurable data type details page.
> Measurable setting page layout

- .buildkite/pipeline.yml
- CHANGELOG.md
- Makefile
- lib/widgets/categories/select_color_field.dart
- lib/widgets/habits/habit_completion_card.dart
- pubspec.yaml
- test_flows/habit_flow.yaml
This PR adds more test entities in the Fluttium habits flow, some backfilling for more compelling screenshots, and pushing the screenshots to the [`lotti-docs`](https://github.com/matthiasn/lotti-docs) repository.
> Commit & push Fluttium screenshots

- CHANGELOG.md
- ios/Runner.xcodeproj/project.pbxproj
- lib/blocs/journal/entry_cubit.dart
- lib/widgets/journal/entry_details/delete_icon_widget.dart
- lib/widgets/journal/entry_details/entry_detail_header.dart
- lib/widgets/journal/entry_details_widget.dart
- pubspec.yaml
- test/widgets/journal/entry_details/delete_icon_widget_test.dart
> Fix navigation after deleting linked entry

- CHANGELOG.md
- lib/blocs/journal/entry_cubit.dart
- lib/widgets/journal/editor/editor_toolbar.dart
- pubspec.yaml
> Fix editor losing focus after interacting with the editor toolbar

- CHANGELOG.md
- docs/MANUAL.md
- lib/pages/create/complete_habit_dialog.dart
- lib/themes/theme.dart
- lib/widgets/habits/habit_completion_card.dart
- pubspec.yaml
> Dashboard in habit completion now above the dialog

- docs/MANUAL.md
- lib/pages/create/complete_habit_dialog.dart
- lib/widgets/habits/habit_completion_card.dart
- pubspec.yaml
This PR fixes clipping the habit completion dialog on mobile when the keyboard appears.
> Fix clipped dialog on mobile

- .buildkite/pipeline.yml
- CHANGELOG.md
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
This PR bumps the version after merging #1522, upgrades all other eligible dependencies, and speeds up the Buildkite CI pipeline by reducing the number of steps.
> Smaller apk sizes

- CHANGELOG.md
- docs/MANUAL.md
- lib/pages/create/complete_habit_dialog.dart
- lib/themes/theme.dart
- lib/widgets/habits/habit_completion_card.dart
- pubspec.lock
- pubspec.yaml
- test_flows/habit_flow.yaml
This PR improves the layout of the habit completion dialog such that it works better with with associated dashboards.
> Improve habit completion bottom sheet

- CHANGELOG.md
- docs/MANUAL.md
- lib/pages/create/complete_habit_dialog.dart
- lib/surveys/run_surveys.dart
- lib/widgets/habits/habit_completion_card.dart
- lib/widgets/habits/habits_filter.dart
- pubspec.yaml
- test_flows/habit_flow.yaml
It turns out the issue was using `useRootNavigator: true` in `showModalBottomSheet`. When removing that, screenshots work as expected.
Resolves #1526.
> Fix screenshots of habit completion dialog in Fluttium flow

- CHANGELOG.md
- lib/widgets/habits/habit_completion_card.dart
- pubspec.yaml
This PR fixes the height of the habit completion bottom sheet on mobile.
> Fix habit completion bottom sheet height

- CHANGELOG.md
- lib/main.dart
- lib/pages/settings/flags_page.dart
- lib/services/window_service.dart
- pubspec.lock
- pubspec.yaml
Resolves #1532.
Also brings back config flag for allowing invalid certificates (for debugging and testing).
> Desktop: preserve window size position

- docs/MANUAL.md
- lib/get_it.dart
- pubspec.lock
- pubspec.yaml
- test/sync/inbox/inbox_service_test.dart
- test/sync/outbox/outbox_service_test.dart
- test/widgets/sync/imap_config_form_widget_test.dart
> Fix app startup

- CHANGELOG.md
- lib/blocs/audio/player_cubit.dart
- lib/blocs/audio/recorder_cubit.dart
- lib/logic/persistence_logic.dart
- lib/services/asr_service.dart
- lib/widgets/audio/audio_recorder.dart
- lib/widgets/journal/entry_details_widget.dart
- pubspec.yaml
This PR adds automatic transcript on macOS.
> Automatically transcribe audio on macOS

- CHANGELOG.md
- ios/Podfile.lock
- lib/blocs/settings/speech/speech_settings_cubit.dart
- lib/database/settings_db.dart
- lib/pages/settings/speech/speech_settings_page.dart
- lib/services/asr_service.dart
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
- test/blocs/settings/speech/speech_settings_cubit_test.dart
- test/pages/settings/speech/speech_settings_page_test.dart
Model selection persistence & model deletion.
> Manage whisper models II

- CHANGELOG.md
- Makefile
- lib/l10n/app_de.arb
- lib/l10n/app_en.arb
- pubspec.lock
- pubspec.yaml
This PR renames the previous `Journal` tab to `Logbook` as that better describes the content.
> Rename Journal tab to Logbook

- CHANGELOG.md
- ios/Runner/AppDelegate.swift
- ios/Runner/LibWhisper.swift
- ios/Runner/Transcribe.swift
- lib/services/asr_service.dart
- macos/Runner/LibWhisper.swift
- macos/Runner/MainFlutterWindow.swift
- macos/Runner/Transcribe.swift
- pubspec.yaml
> Speech recognition in any language supported by Whisper

- CHANGELOG.md
- lib/beamer/locations/settings_location.dart
- lib/pages/settings/definitions_list_page.dart
- lib/pages/settings/habits/habits_page.dart
- lib/widgets/habits/habit_page_app_bar.dart
- lib/widgets/settings/habits/habits_type_card.dart
- pubspec.yaml
This PR adds passing habits substring match filter when navigating to habit settings.
> Pass filter when navigating from habits to habit settings

- CHANGELOG.md
- lib/logic/persistence_logic.dart
- lib/services/asr_service.dart
- lib/widgets/audio/audio_player.dart
- pubspec.yaml
This PR adds deleting individual audio transcripts.
> Delete individual transcripts

- CHANGELOG.md
- lib/blocs/settings/speech/speech_settings_cubit.dart
- lib/blocs/settings/speech/speech_settings_state.dart
- lib/blocs/settings/speech/speech_settings_state.freezed.dart
- lib/map/cached_tile_provider.dart
- lib/widgets/misc/map_widget.dart
- lib/widgets/settings/speech/whisper_model_card.dart
- pubspec.lock
- pubspec.yaml
- test/blocs/settings/speech/speech_settings_cubit_test.dart
> Display Whisper model sizes

- .github/workflows/flutter-analyze.yml
- .github/workflows/flutter-linux-release.yml
- .github/workflows/flutter-test.yml
- .github/workflows/flutter-windows-build.yml
- .github/workflows/fluttium.yml
- CHANGELOG.md
- l10n.yaml
- pubspec.lock
- pubspec.yaml
The app defaulted to German (`de`) when the system was set to a non-supported language. That behavior was not intentional and only happened because of alphabetical order.
Resolves #1566.
> Fix default language, should be English

- CHANGELOG.md
- lib/widgets/categories/select_color_field.dart
- pubspec.yaml
> Fix category opacity

- CHANGELOG.md
- lib/pages/settings/dashboards/dashboard_definition_page.dart
- lib/widgets/charts/habits/dashboard_habits_chart.dart
- lib/widgets/habits/habit_completion_card.dart
- lib/widgets/misc/timespan_segmented_control.dart
- pubspec.yaml
- test/widgets/charts/dashboard_habits_test.dart
The previous habits chart didn't look great. This PR replaces it with the habit completion card instead.
> Use habit completion card as habit chart in dashboard

- CHANGELOG.md
- lib/blocs/settings/speech/speech_settings_cubit.dart
- pubspec.lock
- pubspec.yaml
> Fix display of Whisper model sizes

- CHANGELOG.md
- lib/pages/create/complete_habit_dialog.dart
- lib/themes/theme.dart
- lib/widgets/charts/dashboard_chart.dart
- lib/widgets/charts/dashboard_health_bmi_chart.dart
- lib/widgets/charts/dashboard_health_bp_chart.dart
- lib/widgets/charts/dashboard_health_chart.dart
- lib/widgets/charts/dashboard_measurables_chart.dart
- lib/widgets/charts/dashboard_measurables_line_chart.dart
- lib/widgets/charts/dashboard_survey_chart.dart
- lib/widgets/charts/dashboard_workout_chart.dart
- lib/widgets/charts/stories/wildcard_story_chart.dart
- lib/widgets/date_time/datetime_bottom_sheet.dart
- lib/widgets/habits/habit_completion_card.dart
- pubspec.yaml
- test/pages/create/complete_habit_dialog_test.dart
Resolves #1584 (together with #1585)
> Color schemes

- CHANGELOG.md
- lib/pages/settings/dashboards/chart_multi_select.dart
- lib/pages/settings/measurables/measurable_details_page.dart
- lib/widgets/charts/dashboard_item_modal.dart
- lib/widgets/modal/modal_action_sheet.dart
- pubspec.yaml
This PR fixes additional theming issues that were introduced recently with the theming refactoring.
> Delete dialog color

- CHANGELOG.md
- lib/beamer/beamer_app.dart
- lib/database/journal_db/config_flags.dart
- lib/pages/settings/flags_page.dart
- lib/utils/consts.dart
- pubspec.yaml
- test/database/database_test.dart
> Add config flag for following system brightness

- CHANGELOG.md
- lib/pages/create/complete_habit_dialog.dart
- lib/themes/colors.dart
- lib/widgets/charts/habits/dashboard_habits_data.dart
- lib/widgets/charts/habits/habit_completion_rate_chart.dart
- lib/widgets/charts/time_series/time_series_line_chart.dart
- lib/widgets/habits/habit_completion_card.dart
- pubspec.yaml
This PR improves habit completion chart colors, which recently degraded with the new theming approach.
> Improve habit completion chart colors

- CHANGELOG.md
- lib/pages/create/complete_habit_dialog.dart
- lib/pages/create/create_measurement_dialog.dart
- lib/themes/theme.dart
- lib/widgets/habits/habit_completion_card.dart
- pubspec.lock
- pubspec.yaml
> Bottom sheet and dialog improvements

- CHANGELOG.md
- docs/MANUAL.md
- lib/pages/dashboards/dashboards_list_page.dart
- lib/widgets/dashboards/dashboards_app_bar.dart
- pubspec.yaml
This PR improves the dashboards page sliver app bar.
> Improved dashboards page header

- CHANGELOG.md
- lib/widgets/charts/dashboard_health_bp_chart.dart
- pubspec.yaml
> Fix BP chart header

- CHANGELOG.md
- lib/utils/file_utils.dart
- pubspec.lock
- pubspec.yaml
> Fix folders on linux

- CHANGELOG.md
- lib/pages/create/complete_habit_dialog.dart
- lib/pages/create/create_measurement_dialog.dart
- lib/pages/settings/categories/category_details_page.dart
- lib/pages/settings/dashboards/chart_multi_select.dart
- lib/pages/settings/dashboards/dashboard_definition_page.dart
- lib/pages/settings/form_text_field.dart
- lib/pages/settings/habits/habit_details_page.dart
- lib/pages/settings/measurables/measurable_details_page.dart
- lib/pages/settings/tags/tag_edit_page.dart
- lib/themes/theme.dart
- lib/widgets/categories/select_color_field.dart
- lib/widgets/date_time/datetime_field.dart
- lib/widgets/habits/habit_category.dart
- lib/widgets/habits/habit_dashboard.dart
- lib/widgets/journal/entry_details/save_button.dart
- lib/widgets/search/search_widget.dart
- lib/widgets/settings/dashboards/dashboard_category.dart
- lib/widgets/tasks/task_form.dart
- pubspec.yaml
- test/pages/settings/tags/tag_edit_page_test.dart
This PR makes the input field text styles more consistent and increases the font sizes of the entity name fields.
> Input field styling

- CHANGELOG.md
- lib/blocs/settings/speech/speech_settings_cubit.dart
- pubspec.yaml
> Update whisper model size after completed download

- CHANGELOG.md
- lib/blocs/journal/journal_page_cubit.dart
- pubspec.yaml
- test/pages/journal/infinite_journal_page_test.dart
> Update tasks page when task created

- CHANGELOG.md
- lib/widgets/search/search_widget.dart
- pubspec.yaml
> Fix border in search widget

- CHANGELOG.md
- lib/themes/theme.dart
- lib/widgets/date_time/datetime_bottom_sheet.dart
- lib/widgets/journal/editor/editor_toolbar.dart
- lib/widgets/journal/entry_details/entry_datetime_modal.dart
- pubspec.yaml
Resolves #1615. Also improves typography in the picker.
> Improve typography in DateTime modal

- CHANGELOG.md
- lib/widgets/audio/audio_player.dart
- lib/widgets/audio/audio_recorder.dart
- lib/widgets/audio/vu_meter.dart
- lib/widgets/journal/entry_details/delete_icon_widget.dart
- lib/widgets/journal/entry_details/entry_detail_header.dart
- pubspec.yaml
- test/pages/journal/entry_detail_page_test.dart
- test/widgets/audio/audio_player_test.dart
- test/widgets/journal/entry_details/delete_icon_widget_test.dart
- test/widgets/journal/entry_details/entry_detail_header_test.dart
This PR improves the styling of the audio recording dialog.
> Audio recorder and player icons and style

- CHANGELOG.md
- lib/pages/create/complete_habit_dialog.dart
- lib/pages/create/create_measurement_dialog.dart
- lib/pages/settings/categories/category_details_page.dart
- lib/pages/settings/dashboards/dashboard_definition_page.dart
- lib/pages/settings/definitions_list_page.dart
- lib/pages/settings/habits/habit_details_page.dart
- lib/pages/settings/measurables/measurable_details_page.dart
- lib/pages/settings/tags/create_tag_page.dart
- lib/pages/settings/tags/tag_edit_page.dart
- lib/pages/settings/tags/tags_page.dart
- lib/services/tags_service.dart
- lib/widgets/charts/dashboard_measurables_chart.dart
- lib/widgets/charts/dashboard_measurables_line_chart.dart
- lib/widgets/charts/dashboard_survey_chart.dart
- lib/widgets/create/add_actions.dart
- lib/widgets/create/add_tag_actions.dart
- lib/widgets/journal/entry_details/delete_icon_widget.dart
- lib/widgets/journal/entry_image_widget.dart
- lib/widgets/journal/tags/tag_widget.dart
- lib/widgets/settings/entity_detail_card.dart
- pubspec.yaml
- test/widgets/create/add_actions_test.dart
- test/widgets/create/add_tag_actions_test.dart
- test/widgets/journal/entry_details/delete_icon_widget_test.dart
- test/widgets/journal/tags/tag_widget_test.dart
- test/widgets/journal/tags/tags_modal_widget_test.dart
> New tag from search

- CHANGELOG.md
- lib/widgets/journal/entry_details/save_button.dart
- pubspec.yaml
> Unfocus keyboard on entry/task save

- CHANGELOG.md
- lib/sync/inbox/inbox_service_isolate.dart
- pubspec.yaml
This PR adds some additional logging for debugging sync.
> Log sync email subject for debugging

- CHANGELOG.md
- lib/beamer/beamer_app.dart
- lib/pages/journal/entry_details_page.dart
- lib/widgets/journal/entry_details/save_button.dart
- pubspec.yaml
This is the next attempt at improving the keyboard dismiss behavior.
> Keyboard dismiss behavior

- CHANGELOG.md
- lib/pages/create/create_measurement_dialog.dart
- pubspec.lock
- pubspec.yaml
This PR adds hiding the suggestions with previous measurement values after starting to type.
> Hide measurement suggestions when input dirty

- lib/widgets/journal/entry_details/entry_detail_header.dart
- lib/widgets/journal/entry_details/save_button.dart
- pubspec.yaml
This PR improves the entry header spacing and ensures that the save button is visible even on the smallest screens by placing the icons in a horizontal scrollview.
> feat: improve entry header

- ios/Podfile.lock
- lib/widgets/journal/editor/editor_toolbar.dart
- lib/widgets/journal/editor/editor_tools.dart
- lib/widgets/journal/editor/editor_widget.dart
- lib/widgets/journal/text_viewer_widget.dart
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- macos/Flutter/GeneratedPluginRegistrant.swift
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
This PR updates `flutter_quill` to the latest version.
> chore: upgrade quill

- lib/beamer/beamer_app.dart
- lib/themes/theme.dart
- lib/widgets/nav_bar/nav_bar_item.dart
- pubspec.lock
- pubspec.yaml
This PR adapts the layout of the bottom navigation bar, with new icons reflecting selected/unselected states.
> design: nav bar

- lib/widgets/app_bar/sliver_title_bar.dart
- pubspec.yaml
This PR fixes the app bar by centering the title.
> fix: center app bar title

- lib/beamer/beamer_app.dart
- lib/database/journal_db/config_flags.dart
- lib/pages/settings/flags_page.dart
- lib/services/nav_service.dart
- lib/utils/consts.dart
- lib/widgets/create/add_actions.dart
- pubspec.yaml
- test/database/database_test.dart
- test/pages/journal/entry_detail_page_test.dart
- test/pages/journal/infinite_journal_page_test.dart
- test/pages/settings/tags/tags_page_test.dart
- test/services/nav_service_test.dart
- test/widgets/create/add_actions_test.dart
This PR removes the config flag for task management & instead always enables it.
> feat: remove config flag for task management, always enable

- lib/l10n/app_en.arb
- lib/sync/matrix/matrix_service.dart
- lib/utils/audio_utils.dart
- lib/utils/image_utils.dart
- lib/widgets/journal/entry_details/entry_detail_header.dart
- pubspec.yaml
This PR adds syncing attachments via a Matrix home server. Works fine in my testing setup, and very fast.
> feat: Matrix-based Sync - Part II

- lib/blocs/audio/player_cubit.dart
- lib/blocs/audio/player_state.dart
- lib/blocs/audio/player_state.freezed.dart
- lib/widgets/audio/audio_player.dart
- pubspec.lock
- pubspec.yaml
- test/widgets/audio/audio_player_test.dart
Improve styling of transcripts list.
> feat: audio UI cleanup

- lib/database/database.drift
- lib/database/database.g.dart
- lib/database/maintenance.dart
- lib/l10n/app_en.arb
- lib/pages/settings/speech/speech_settings_page.dart
- pubspec.yaml
This PR adds a maintenance task for transcribing all audio entries that have not previously been transcribed.
> feat: maintenance task for transcribing audio without transcript

- lib/pages/journal/entry_details_page.dart
- lib/widgets/journal/editor/editor_toolbar.dart
- lib/widgets/journal/editor/editor_widget.dart
- pubspec.lock
- pubspec.yaml
This PR adds scrolling the entry details view such that text editors in focus are ensured to be visible.
> feat: scroll to make texteditor visible on mobile

- lib/database/database.dart
- lib/database/maintenance.dart
- lib/l10n/app_en.arb
- lib/pages/settings/advanced/maintenance_page.dart
- lib/sync/matrix/matrix_service.dart
- lib/sync/outbox/outbox_service.dart
- lib/widgets/sync/matrix/incoming_stats.dart
- lib/widgets/sync/matrix/matrix_settings.dart
- pubspec.yaml
This PR adds matrix sync stats on the respective settings page.
> feat: add Matrix Sync stats & logging

- lib/blocs/journal/entry_cubit.dart
- lib/l10n/app_en.arb
- lib/pages/settings/health_import_page.dart
- lib/widgets/misc/buttons.dart
- pubspec.lock
- pubspec.yaml
- test/pages/settings/health_import_page_test.dart
This PR changes the date range selection for health imports to use the same controls as elsewhere.
> feat: date range in health import without lib

- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- lib/blocs/audio/recorder_cubit.dart
- lib/blocs/sync/sync_config_cubit.dart
- lib/services/asr_service.dart
- lib/sync/connectivity.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
This PR upgrades a few dependencies.
> chore: upgrade dependencies

- lib/widgets/app_bar/journal_sliver_appbar.dart
- lib/widgets/search/entry_type_filter.dart
- pubspec.lock
- pubspec.yaml
Similar to #1698 but for the entries/logbook tab.
> feat: entries filter in modal sheet

- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
- ios/Runner/AppDelegate.swift
- lib/blocs/settings/speech/speech_settings_state.dart
- lib/pages/settings/speech/speech_settings_page.dart
- lib/services/asr_service.dart
- macos/Runner.xcodeproj/project.pbxproj
- macos/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- macos/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
- macos/Runner/MainFlutterWindow.swift
- pubspec.yaml
- test/blocs/settings/speech/speech_settings_cubit_test.dart
This PR adds language detection. Currently requires pinning to a specific WhisperKit commit until new version is release.
> feat: detect language

- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
- ios/Runner/AppDelegate.swift
- lib/blocs/audio/player_cubit.dart
- lib/widgets/audio/audio_player.dart
- macos/Runner.xcodeproj/project.pbxproj
- macos/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- macos/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
- macos/Runner/MainFlutterWindow.swift
- pubspec.yaml
- test/widgets/audio/audio_player_test.dart
This PR simplifies the audio player UX.
> feat: simplify audio player

- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/AppDelegate.swift
- ios/Runner/WhisperKitRunner.swift
- lib/blocs/audio/recorder_cubit.dart
- lib/blocs/journal/journal_page_cubit.dart
- lib/services/asr_service.dart
- lib/sync/inbox/inbox_service.dart
- lib/widgets/app_bar/journal_sliver_appbar.dart
- lib/widgets/audio/audio_recorder.dart
- lib/widgets/audio/transcription_progress_modal.dart
- lib/widgets/journal/editor/editor_styles.dart
- lib/widgets/misc/wolt_modal_config.dart
- lib/widgets/search/task_status_filter.dart
- macos/Runner.xcodeproj/project.pbxproj
- macos/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- macos/Runner/MainFlutterWindow.swift
- macos/Runner/WhisperKitRunner.swift
- pubspec.yaml
- test/pages/create/record_audio_page_test.dart
- test/widgets/audio/audio_recorder_test.dart
This PR adds real-time transcription updates such that when the transcription is running, a modal opens and shows the progress of the transcription until it's done. When it's finally done, the modal closes after three seconds but can also be closed by the user by dismissing the tab. This provides a better UX by showing feedback that the transcription is running.
What remains is better handling of the initialization of the model. It seems as if [specialization](https://github.com/argmaxinc/WhisperKit/issues/17) still occasionally happens on first run of the app despite no new model having been downloaded.
> feat: progressive transcription updates

- ios/Runner/WhisperKitRunner.swift
- lib/blocs/audio/player_cubit.dart
- lib/services/asr_service.dart
- lib/widgets/audio/audio_player.dart
- macos/Runner/WhisperKitRunner.swift
- pubspec.yaml
This PR adds the transcription preview modal when triggered from the transcription icon in an audio entry.
> feat: show transcription preview when triggered from entry

- .github/workflows/archive/build-android.yml
- .github/workflows/archive/release.yml
- .github/workflows/archive/test.yml
- .github/workflows/archive/testflight-ios.yml
- .github/workflows/flutter-matrix-test.yml
- integration_test/run_matrix_tests.sh
This PR adds running the Matrix integration test in GitHub actions.
> ci: run Matrix integration test in GitHub Actions

- integration_test/matrix_service_test.dart
- lib/database/logging_db.dart
- lib/sync/matrix/client.dart
- lib/sync/matrix/config.dart
- lib/sync/matrix/consts.dart
- lib/sync/matrix/key_verification_runner.dart
- lib/sync/matrix/matrix_service.dart
- lib/sync/matrix/process_message.dart
- lib/sync/matrix/room.dart
- lib/sync/matrix/send_message.dart
- lib/sync/matrix/stats.dart
- lib/sync/utils.dart
- lib/widgets/sync/matrix/incoming_stats.dart
- lib/widgets/sync/matrix/matrix_settings.dart
This PR adds refactoring in the Matrix service to make it more maintainable and easier to reason about. Next will be the actual processing of incoming messages.
> refactor: Matrix service 

- integration_test/matrix_service_test.dart
- lib/sync/matrix/matrix_service.dart
- lib/sync/matrix/timeline.dart
- pubspec.yaml
This PR adds an initial fetch of Matrix messages on startup, since the notification for new messages does not appear to be triggered in all circumstances.
> feat: fetch messages on startup

- lib/services/asr_service.dart
- lib/widgets/audio/transcription_progress_modal.dart
- pubspec.yaml
This PR adds improvements of the audio transcription progress modal:
- Spacing
- Show error when file does not exist & close modal after 5s
> feat: error state & styling in transcription progress modal

- lib/classes/audio_note.g.dart
- lib/classes/check_list_item.g.dart
- lib/classes/config.g.dart
- lib/classes/entity_definitions.g.dart
- lib/classes/geolocation.g.dart
- lib/classes/journal_entities.g.dart
- lib/classes/task.g.dart
- lib/database/database.drift
- lib/database/database.g.dart
- lib/database/maintenance.dart
- lib/l10n/app_en.arb
- lib/pages/settings/advanced/maintenance_page.dart
- lib/pages/settings/advanced_settings_page.dart
- lib/pages/settings/settings_page.dart
- lib/sync/ui/re_sync_modal.dart
- lib/widgets/misc/buttons.dart
- pubspec.yaml
This PR adds a maintenance modal for re-syncing messages in a user defined interval, and removes the previous option with fixed counts.
> feat: add maintenance modal for re-sync in interval

- lib/sync/matrix/matrix_service.dart
- lib/sync/matrix/room.dart
- pubspec.yaml
This PR adds accepting room invites. UI will follow.
> feat: accept room invite

- lib/blocs/habits/habits_cubit.dart
- lib/sync/matrix/timeline.dart
- pubspec.lock
- pubspec.yaml
This PR fixes an issue where the last read marker for the sync room could not be set.
> fix: setReadMarker & matrix update

- lib/blocs/journal/journal_page_cubit.dart
- pubspec.lock
- pubspec.yaml
- test/pages/journal/infinite_journal_page_test.dart
This PR adds persisting the filter selections on task and journal pages.
> feat: persist task status and entry types filter

- lib/blocs/journal/entry_cubit.dart
- lib/database/database.dart
- pubspec.yaml
- test/logic/persistence_logic_test.dart
- test/pages/dashboards/dashboard_page_test.dart
- test/pages/journal/entry_detail_page_test.dart
- test/pages/journal/infinite_journal_page_test.dart
This PR introduces the new entry update mechanism in the cubit for the detail page, resulting in less frequent re-render and this smoother scrolling.
> feat: improve entry updates

- lib/blocs/audio/recorder_cubit.dart
- lib/widgets/audio/audio_recorder.dart
- lib/widgets/audio/audio_recording_indicator.dart
- pubspec.yaml
- test/pages/create/record_audio_page_test.dart
- test/widgets/audio/audio_recorder_test.dart
- test/widgets/audio/audio_recording_indicator_test.dart
This PR fixes an. issue where entry test would not be updated after completing speech recognition.
> fix: entry update after completing speech recognition

- lib/database/maintenance.dart
- lib/l10n/app_en.arb
- lib/pages/settings/advanced/maintenance_page.dart
- pubspec.yaml
This PR adds a maintenance task for deleting the sync database.
> feat: add maintenance task for deleting sync db

- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- lib/pages/create/complete_habit_dialog.dart
- lib/pages/create/create_measurement_dialog.dart
- lib/pages/dashboards/dashboard_page.dart
- lib/pages/journal/entry_details_page.dart
- lib/pages/settings/dashboards/dashboard_definition_page.dart
- lib/services/entities_cache_service.dart
- lib/widgets/dashboards/dashboard_widget.dart
- lib/widgets/tasks/linked_duration.dart
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
- test/pages/create/complete_habit_dialog_test.dart
- test/pages/create/create_measurement_dialog_test.dart
- test/pages/dashboards/dashboard_page_test.dart
- test/widgets/charts/dashboard_measurables_test.dart
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
This PR adds entity caching for habit definitions and improves the use of cached dashboard definitions which results in faster (occasionally much faster) loading of habit completion dialogs. Also updates dependencies, and removes a bunch of unused dependencies.
> feat: entity caching

- lib/blocs/journal/journal_page_cubit.dart
- lib/blocs/journal/journal_page_state.dart
- lib/blocs/journal/journal_page_state.freezed.dart
- lib/widgets/search/task_status_filter.dart
- pubspec.lock
- pubspec.yaml
This PR adds a filter by category section on the tasks page.
> feat: category filter on tasks page

- lib/widgets/search/entry_type_filter.dart
- lib/widgets/search/filter_choice_chip.dart
- pubspec.yaml
This PR fixes the task status filter chip text color to be black on light backgrounds and white on dark backgrounds.
> fix: filter chip text color

- lib/blocs/journal/journal_page_cubit.dart
- lib/blocs/journal/journal_page_state.dart
- lib/blocs/journal/journal_page_state.freezed.dart
- lib/blocs/journal/journal_page_state.g.dart
- pubspec.yaml
This PR adds persisting the category selection on the tasks tab.
> feat: persist category selection on tasks tab

- lib/blocs/journal/journal_page_cubit.dart
- lib/blocs/journal/journal_page_state.dart
- lib/blocs/journal/journal_page_state.freezed.dart
- lib/blocs/journal/journal_page_state.g.dart
- lib/database/conversions.dart
- lib/database/database.dart
- lib/database/database.drift
- lib/database/database.g.dart
- lib/database/maintenance.dart
- lib/l10n/app_en.arb
- lib/pages/settings/advanced/maintenance_page.dart
- lib/widgets/search/task_status_filter.dart
- pubspec.yaml
- test/logic/persistence_logic_test.dart
This PR improves task filtering when empty category is selected.
> feat: improve task filtering

- lib/features/tasks/state/time_by_category_controller.dart
- lib/features/tasks/state/time_by_category_controller.g.dart
- lib/features/tasks/ui/time_by_category_chart.dart
- lib/pages/journal/infinite_journal_page.dart
- lib/pages/settings/advanced/about_page.dart
- lib/themes/theme.dart
- lib/utils/date_utils_extension.dart
- lib/widgets/journal/entry_details_widget.dart
- lib/widgets/misc/timespan_segmented_control.dart
- pubspec.yaml
This PR moves the time chart to the tasks tab inside an `ExpansionTile`. Also adds selector to the time range (14, 30, 90 days) plus improves styling.
> feat: improve time chart & move to tasks tab

- lib/beamer/locations/tasks_location.dart
- lib/database/database.drift
- lib/database/database.g.dart
- lib/features/tasks/state/day_view_controller.dart
- lib/features/tasks/state/day_view_controller.g.dart
- lib/features/tasks/ui/pages/day_view_page.dart
- lib/features/tasks/ui/time_by_category_chart.dart
- pubspec.yaml
This PR increases the time range fetched in the calendar view to 90 days, and fixes links to older tasks.
> feat: fetch 90 days in calendar

- lib/features/tasks/state/day_view_controller.dart
- lib/widgets/journal/entry_tools.dart
- pubspec.yaml
This PR adds the display of workout entries in the calendar view.
> feat: display workout with title and summary in calendar view

- ios/Podfile.lock
- ios/Runner/WhisperKitRunner.swift
- lib/blocs/audio/recorder_cubit.dart
- lib/blocs/audio/recorder_state.dart
- lib/blocs/audio/recorder_state.freezed.dart
- lib/classes/journal_entities.dart
- lib/classes/journal_entities.freezed.dart
- lib/classes/journal_entities.g.dart
- lib/features/tasks/state/day_view_controller.g.dart
- lib/logic/persistence_logic.dart
- lib/services/asr_service.dart
- lib/widgets/audio/audio_recorder.dart
- lib/widgets/audio/transcription_progress_modal.dart
- macos/Podfile.lock
- macos/Runner/WhisperKitRunner.swift
- pubspec.lock
- pubspec.yaml
- test/pages/create/record_audio_page_test.dart
- test/widgets/audio/audio_recorder_test.dart
- test/widgets/audio/audio_recording_indicator_test.dart
This PR adds selecting the language when recording audio, since language auto detection doesn't alway have the highest accuracy, and might translate a non-English recording to English instead of transcribing in the source language.
> feat: language selection when recording audio

- lib/beamer/beamer_app.dart
- lib/beamer/beamer_delegates.dart
- lib/beamer/locations/calendar_location.dart
- lib/beamer/locations/tasks_location.dart
- lib/features/tasks/state/day_view_controller.dart
- lib/features/tasks/state/day_view_controller.g.dart
- lib/features/tasks/state/time_by_category_controller.dart
- lib/features/tasks/ui/pages/day_view_page.dart
- lib/features/tasks/ui/time_by_category_chart.dart
- lib/l10n/app_en.arb
- lib/pages/journal/infinite_journal_page.dart
- lib/services/nav_service.dart
- lib/themes/theme.dart
- pubspec.lock
- pubspec.yaml
- test/services/nav_service_test.dart
This PR adds a calendar tab, making the new day view more easily accessible.
> feat: calendar tab

- lib/l10n/app_en.arb
- lib/widgets/app_bar/journal_sliver_appbar.dart
- lib/widgets/search/filter_choice_chip.dart
- lib/widgets/search/task_category_filter.dart
- lib/widgets/search/task_filter_icon.dart
- lib/widgets/search/task_list_toggle.dart
- lib/widgets/search/task_status_filter.dart
- pubspec.yaml
This PR improves the design of task status and category filter chips, including aligning their appearance.
> feat: improve task filter chip design

- lib/widgets/events/event_form.dart
- pubspec.yaml
This PR adds category assignment in Event entities.
> feat: add category assignment in events

- ios/Podfile.lock
- lib/widgets/categories/category_field.dart
- lib/widgets/dashboards/dashboards_card.dart
- lib/widgets/search/filter_choice_chip.dart
- lib/widgets/search/task_category_filter.dart
- lib/widgets/search/task_status_filter.dart
- lib/widgets/settings/categories/categories_type_card.dart
- lib/widgets/settings/dashboards/dashboard_definition_card.dart
- lib/widgets/settings/habits/habits_type_card.dart
- lib/widgets/settings/settings_card.dart
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
This PR improves some layout/spacing.
> feat: category assignment & filter spacing

- lib/features/calendar/state/calendar_event.dart
- lib/features/calendar/state/day_view_controller.dart
- lib/features/calendar/state/day_view_controller.g.dart
- lib/features/calendar/ui/pages/day_view_page.dart
- pubspec.yaml
This PR improves the calendar view by opening the linked task if one exists.
> feat: open task from calendar

- lib/features/calendar/ui/pages/day_view_page.dart
- pubspec.yaml
This PR adds calendar scaling via multitouch gesture.
> feat: set calendar scale with multitouch gesture

- ios/Podfile.lock
- lib/beamer/beamer_app.dart
- lib/features/journal/state/save_button_controller.g.dart
- lib/features/tasks/state/task_app_bar_controller.g.dart
- lib/logic/persistence_logic.dart
- lib/widgets/misc/desktop_menu.dart
- pubspec.lock
- pubspec.yaml
This PR fixes the German localization of the app. Unfortunately, German not being supported in [`research_package`](https://pub.dev/packages/research_package) led to silent crashes, instead of not simply falling back to English.
> fix: German localization

- lib/features/journal/state/entry_controller.dart
- pubspec.lock
- pubspec.yaml
- test/features/journal/state/entry_controller_test.dart
This PR contains a fix for the task form occasionally flickering.
> fix: flickering task form

- lib/features/journal/state/entry_controller.dart
- lib/features/journal/ui/pages/entry_details_page.dart
- lib/features/journal/ui/widgets/entry_details_widget.dart
- pubspec.yaml
- improve whitespace in entry/task header
- reduce re-renders when typing
> feat: entry improvements

- lib/database/database.g.dart
- lib/database/editor_db.g.dart
- lib/database/fts5_db.g.dart
- lib/database/logging_db.g.dart
- lib/database/settings_db.g.dart
- lib/database/sync_db.g.dart
- pubspec.lock
- pubspec.yaml
This PR updates the [`drift`](https://pub.dev/packages/drift) persistence library.
> chore: update drift

- ios/Podfile.lock
- lib/main.dart
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- macos/Flutter/GeneratedPluginRegistrant.swift
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
This PR fixes an issue with recurring paste popups. Also incidentally improves paste behavior.
> feat: improve paste

- lib/beamer/beamer_app.dart
- lib/blocs/audio/recorder_cubit.dart
- lib/blocs/audio/recorder_state.dart
- lib/blocs/audio/recorder_state.freezed.dart
- lib/widgets/audio/audio_recorder.dart
- lib/widgets/audio/audio_recording_indicator.dart
- pubspec.yaml
- test/widgets/audio/audio_recording_indicator_test.dart
This PR fixes the audio recording indicator which wasn't shown any longer. Also changes the behavior from stopping the recording to navigating back to the audio recording page.
> fix: audio recording indicator

- lib/services/nav_service.dart
- lib/widgets/app_bar/title_app_bar.dart
- lib/widgets/create/add_actions.dart
- pubspec.yaml
- test/widgets/audio/audio_recording_indicator_test.dart
- test/widgets/create/add_actions_test.dart
This PR improves navigation after creating new tasks from an existing task entry.
> feat: improve navigation

- lib/beamer/beamer_app.dart
- lib/blocs/theming/theming_cubit.dart
- lib/blocs/theming/theming_state.dart
- lib/blocs/theming/theming_state.freezed.dart
- lib/database/journal_db/config_flags.dart
- lib/pages/settings/flags_page.dart
- lib/utils/consts.dart
- pubspec.yaml
- test/database/database_test.dart
This PR adds showing or hiding tooltips based on a config flag.
> feat: show or hide tooltips based on config flag

- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
- macos/Runner.xcodeproj/project.pbxproj
- macos/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- macos/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
- pubspec.lock
- pubspec.yaml
Thus PR upgrades WhisperKit to use the latest commit, plus upgrades Flutter dependencies.
> chore: upgrade WhisperKit & dart dependencies

- lib/database/database.dart
- lib/database/database.drift
- lib/database/database.g.dart
- lib/database/maintenance.dart
- pubspec.yaml
- test/pages/settings/about_page_test.dart
This PR extends the maintenance task for re-syncing entries to also re-sync associated links.
> feat: re-sync links

- lib/widgets/search/task_category_filter.dart
- pubspec.yaml
This PR improves the task categories filter to show selected categories together with the favorite categories at the top, without having to expand to show all categories.
> feat: improve task categories filter

- ios/Runner/WhisperKitRunner.swift
- macos/Runner/WhisperKitRunner.swift
- pubspec.yaml
This PR fixes the language selection in ASR (automatic speech recognition) which previously wasn't always honored.
> fix: language selection in ASR

- ios/Podfile.lock
- ios/Runner/WhisperKitRunner.swift
- macos/Flutter/GeneratedPluginRegistrant.swift
- macos/Podfile.lock
- macos/Runner/WhisperKitRunner.swift
- pubspec.lock
- pubspec.yaml
This pull request includes improved error handling during audio transcription, ensuring the model is loaded before transcription. Also upgrades dependencies.
* [`ios/Runner/WhisperKitRunner.swift`](diffhunk://#diff-b0660f7ba70066e41b67e449fbf85ac0f5b4c7a171972d14eeb4809e3cda53c5R29-R48): Added error handling for the transcription process and ensured the model is loaded before starting transcription. [[1]](diffhunk://#diff-b0660f7ba70066e41b67e449fbf85ac0f5b4c7a171972d14eeb4809e3cda53c5R29-R48) [[2]](diffhunk://#diff-b0660f7ba70066e41b67e449fbf85ac0f5b4c7a171972d14eeb4809e3cda53c5L55-R69)
* [`macos/Runner/WhisperKitRunner.swift`](diffhunk://#diff-c659b929fa0cfd29064719f3124a8910c2b4ff5c3dd37a879b480a080381cd74R29-R48): Mirrored the changes from the iOS implementation to handle errors and …
> feat: improved ASR error handling 

- lib/features/surveys/definitions/cfq11_survey.dart
- lib/features/surveys/definitions/panas_survey.dart
- lib/features/surveys/tools/run_surveys.dart
- lib/features/surveys/ui/fill_survey_page.dart
- lib/widgets/misc/wolt_modal_config.dart
- pubspec.lock
- pubspec.yaml
This pull request includes several changes to the survey definitions and their associated UI components, as well as updates to the modal configuration and dependencies. The most important changes include refactoring survey definitions to use `final` variables, updating the modal sheet implementation, and modifying the `SurveyWidget` constraints.
Survey Definitions Refactoring:
* [`lib/features/surveys/definitions/cfq11_survey.dart`](diffhunk://#diff-fd717930b9daed5b1a1549438065ba5b7f50e0e44a7e7aa4a50650078f77d9acL3-R19): Refactored to use `final` variables for `cfq11AnswerFormat`, `cfq11CompletionStep`, `cfq11InstructionStep`, and `cfq11SurveyTask`. Removed unused image choice definitions. [[1]](diffhunk://#diff-fd717930b9daed5b1a1549438065ba5b7f50e0e44a7e7aa4a50650078f77d9acL3-R19) …
> feat: wolt modal sheet surveys

- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
- macos/Podfile.lock
- macos/Runner.xcodeproj/project.pbxproj
- macos/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- macos/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
- pubspec.lock
- pubspec.yaml
This pull request updates the version of the `whisperkit` dependency across multiple project files and increments the version number in the `pubspec.yaml` file.
Dependency version updates:
* [`ios/Runner.xcodeproj/project.pbxproj`](diffhunk://#diff-413fd2395fd4377132c8c1135c9bc9ab215c6f97322d27717a487223bd03e2c7L616-R616): Updated `whisperkit` version from `0.9.0` to `0.9.2`.
* [`ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved`](diffhunk://#diff-2bbba4945556820d8d37758665ea4779d8016b7020a2601d0ee9cfcadc97ecb4L27-R28): Updated `whisperkit` version and revision to `0.9.2` and `b100f22cddf4748d63d5798c14bcf27f9de50dce`, respectively.
* [`macos/Runner.xcodeproj/project.pbxproj`](diffhunk://#diff-ec40d5406d2e5b54c265f64285bf1f073febb06b92a906239f8905a6244e68efL711-R711): Updated …
> chore: dependencies

- lib/beamer/beamer_app.dart
- lib/features/sync/matrix/matrix_service.dart
- lib/features/sync/outbox/outbox_service.dart
- lib/features/user_activity/state/user_activity_service.dart
- pubspec.yaml
- test/logic/persistence_logic_test.dart
This pull request includes several changes to improve user activity tracking and performance optimizations across different services. The key changes involve updating the `UserActivityService` to streamline activity updates, integrating activity tracking into the `MyBeamerApp` widget, and adjusting delays in the `MatrixService` and `OutboxService` for better responsiveness.
Enhancements to user activity tracking:
* [`lib/beamer/beamer_app.dart`](diffhunk://#diff-350ebc719538001d1544da4250b6cf3bc2390b3308862d2232af08e8f69b1f34R15): Added `UserActivityService` to track user interactions through various pointer events, ensuring activity updates are called on multiple pointer actions. [[1]](diffhunk://#diff-350ebc719538001d1544da4250b6cf3bc2390b3308862d2232af08e8f69b1f34R15) …
> feat: pause sync until one second after last interaction

- lib/features/tasks/state/checklist_item_controller.dart
- lib/features/tasks/ui/checkbox_item_widget.dart
- lib/features/tasks/ui/checkbox_item_wrapper.dart
- lib/widgets/create/add_actions.dart
- pubspec.yaml
This pull request includes several updates and improvements to the task management feature and some cleanup in the codebase. The most important changes include renaming methods for better clarity, updating widget lifecycle methods, and removing unused code.
Improvements to task management feature:
* [`lib/features/tasks/state/checklist_item_controller.dart`](diffhunk://#diff-b67049d2cea2eb5ee0c7e31c9f2749ab0f2a62fbc1225a3d2d80320037f28caeL56-R56): Renamed the `toggleChecked` method to `updateChecked` for better clarity.
* [`lib/features/tasks/ui/checkbox_item_widget.dart`](diffhunk://#diff-7822c21b918f4ae68737efc3cf79fd3fbaff2a0bf4ab7df4e7d2330f42aa40c3L39-R45): Updated the widget lifecycle method from `didChangeDependencies` to `didUpdateWidget` to ensure the state is updated when the …
> feat: update checklist items, e.g. via sync

- darwin/WhisperKitRunner.swift
- ios/Podfile.lock
- lib/features/ai/ui/ai_prompt_icon_widget.dart
- lib/features/calendar/ui/time_by_category_chart_card.dart
- lib/features/journal/ui/widgets/entry_details/entry_detail_header.dart
- lib/features/speech/ui/widgets/speech_modal/speech_modal.dart
- lib/features/speech/ui/widgets/transcription_progress_modal.dart
- lib/features/sync/ui/matrix_settings_modal.dart
- lib/features/sync/ui/re_sync_modal.dart
- lib/widgets/app_bar/journal_sliver_appbar.dart
- lib/widgets/search/task_filter_icon.dart
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
This pull request includes several changes to improve the user experience and code performance. The most significant changes include adding asynchronous dispatches to the main queue in `WhisperKitRunner` and making modals dismissible by tapping the barrier in various UI components.
Improvements to `WhisperKitRunner`:
* [`darwin/WhisperKitRunner.swift`](diffhunk://#diff-74eb0d0b5078d2320c72b464e1dde74da99435124a1a56d4c847c2b18beaf6c6R46-R49): Added `DispatchQueue.main.async` to ensure UI updates are performed on the main thread when initializing the model, handling failed model loading, transcribing audio, and handling errors. [[1]](diffhunk://#diff-74eb0d0b5078d2320c72b464e1dde74da99435124a1a56d4c847c2b18beaf6c6R46-R49) [[2]](diffhunk://#diff-74eb0d0b5078d2320c72b464e1dde74da99435124a1a56d …
> fix: actions modal pop

- lib/features/tasks/state/checklist_controller.dart
- lib/features/tasks/ui/checklist_widget.dart
- lib/widgetbook.dart
- pubspec.yaml
This pull request includes several changes to the checklist functionality and a version update. The key changes involve modifying the return type of the `createChecklistItem` method, updating the `ChecklistWidget` to handle asynchronous item creation, and ensuring the widget maintains state. 
* [`lib/features/tasks/state/checklist_controller.dart`](diffhunk://#diff-1711b0d53facde4027f9d5f33d515a4f6ce3e212c0bed0b130e20c6d4fb76d6fL89-R89): Changed the return type of `createChecklistItem` from `Future<void>` to `Future<String?>`, allowing it to return the created item's ID. [[1]](diffhunk://#diff-1711b0d53facde4027f9d5f33d515a4f6ce3e212c0bed0b130e20c6d4fb76d6fL89-R89) [[2]](diffhunk://#diff-1711b0d53facde4027f9d5f33d515a4f6ce3e212c0bed0b130e20c6d4fb76d6fR120-R123)
* …
> fix: checklist update after adding item

- lib/features/journal/ui/widgets/entry_details_widget.dart
- lib/features/tasks/state/checklist_controller.dart
- lib/features/tasks/state/checklist_item_controller.dart
- lib/features/tasks/ui/checkbox_item_wrapper.dart
- lib/features/tasks/ui/checklist_widget.dart
- lib/features/tasks/ui/checklist_wrapper.dart
- lib/features/tasks/ui/checklists_widget.dart
- pubspec.lock
- pubspec.yaml
This pull request includes several changes to improve the checklist functionality in the application, including refactoring, new features for drag-and-drop, and updating dependencies.
* [`lib/features/tasks/state/checklist_controller.dart`](diffhunk://#diff-1711b0d53facde4027f9d5f33d515a4f6ce3e212c0bed0b130e20c6d4fb76d6fL59-R119): Refactored `updateTitle` and `updateItemOrder` methods to use a new `updateChecklist` method. Added new methods `dropChecklistItem` and `unlinkItem` to handle drag-and-drop operations.
* [`lib/features/tasks/state/checklist_item_controller.dart`](diffhunk://#diff-b67049d2cea2eb5ee0c7e31c9f2749ab0f2a62fbc1225a3d2d80320037f28caeL81): Removed unnecessary `debugPrint` statement in `updateTitle` method and added a new `moveToChecklist` method to support moving items …
> feat: move checklist items

- lib/features/tasks/state/checklist_controller.dart
- pubspec.lock
- pubspec.yaml
This pull request includes a couple of changes to improve the functionality and update the version of the project.
Functional improvements:
* [`lib/features/tasks/state/checklist_controller.dart`](diffhunk://#diff-1711b0d53facde4027f9d5f33d515a4f6ce3e212c0bed0b130e20c6d4fb76d6fR78-R81): Added a check to return early if the `fromChecklistId` matches the `entryId` to prevent accidentally removing checklist items from a checklist.
* [`pubspec.yaml`](diffhunk://#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25L4-R4): Updated the project version from `0.9.537+2756` to `0.9.537+2757`.
> fix: drop on same checklist

- ios/Podfile.lock
- lib/blocs/journal/journal_page_cubit.dart
- lib/classes/journal_entities.dart
- lib/database/database.dart
- lib/features/ai/ui/ai_response_preview.dart
- lib/features/journal/ui/widgets/entry_details_widget.dart
- lib/features/journal/ui/widgets/journal_card.dart
- lib/features/tasks/repository/checklist_repository.dart
- lib/features/tasks/state/checklist_controller.dart
- lib/features/tasks/state/checklist_controller.g.dart
- lib/features/tasks/state/checklist_item_controller.dart
- lib/features/tasks/state/checklist_item_controller.g.dart
- lib/features/tasks/ui/checklist_item_widget.dart
- lib/features/tasks/ui/checklist_item_wrapper.dart
- lib/features/tasks/ui/checklist_widget.dart
- lib/logic/persistence_logic.dart
- lib/widgetbook.dart
- lib/widgets/search/entry_type_filter.dart
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
This pull request introduces several changes to support the addition of `Checklist` and `ChecklistItem` features, along with some refactoring and improvements to existing code. The changes include updates to the database queries, UI components, and state management logic.
Key changes include:
* Added `Checklist` and `ChecklistItem` to the list of entry types in `journal_page_cubit.dart` and their corresponding display names in `entry_type_filter.dart`. [[1]](diffhunk://#diff-33f77896ed78898e42dd43a1ddeb6fda349c8ca55068b2ec7c71a45a6aa833b3R378-R379) [[2]](diffhunk://#diff-fa8f1adc84b5f5e7514a1396420735be7c25a7c251fc3b21962d550fdb8ed52dR114-R115)
* Enhanced the `JournalEntityExtension` to handle `Checklist` and `ChecklistItem` by adding their linked IDs to the affected IDs set.
* Updated …
> feat: improve checklists

- .github/workflows/flutter-matrix-test.yml
- integration_test/docker/docker-compose.yml
- integration_test/matrix_service_test.dart
This pull request includes updates to dependencies and improvements to the integration test setup for better performance and debugging.
Dependency updates:
* [`.github/workflows/flutter-matrix-test.yml`](diffhunk://#diff-a3eb9f37f4106d7a1f4eb6a059ba44f2838e6528da58440cc6c906c0c0067482L28-R28): Updated `xvfb-action` from version 1.6 to 1.7.
* [`integration_test/docker/docker-compose.yml`](diffhunk://#diff-68d0427f85c2c556dc7e52f3b6b94ac0def13a21e447722c4ade556decdc0150L24-R24): Updated `dendrite-monolith` image from version 0.13.6 to 0.13.8.
* [`integration_test/docker/docker-compose.yml`](diffhunk://#diff-68d0427f85c2c556dc7e52f3b6b94ac0def13a21e447722c4ade556decdc0150L45-R45): Updated `toxiproxy` image from version 2.9.0 to 2.11.0.
Integration test improvements:
* …
> test: improve Matrix tests

- lib/features/journal/state/entry_controller.dart
- lib/features/tasks/ui/checklist_wrapper.dart
- lib/features/tasks/ui/checklists_widget.dart
- pubspec.yaml
This pull request introduces several updates to the `lib/features/tasks` and `lib/features/journal` modules, focusing on enhancing the checklist functionality and improving the user interface for task management. The most important changes include adding a new method to update checklist order, modifying the `ChecklistWrapper` widget to support padding, and converting `ChecklistsWidget` to a stateful widget to support reordering.
* [`lib/features/journal/state/entry_controller.dart`](diffhunk://#diff-073fb67f5d87a4ca641101e845ee4b45cc2cdb2ee4a6cd4698bb94093921c235R386-R409): Added `updateChecklistOrder` method to update the order of checklists based on provided IDs.
* [`lib/features/tasks/ui/checklist_wrapper.dart`](diffhunk://#diff-21b9654498b69658c827307eb0869ea55b8a74a02599acc65feb9c1e46 …
> feat: reorder checklists

- lib/features/ai/state/ollama_prompt_checklist.dart
- pubspec.yaml
This pull request includes updates to the `lib/features/ai/state/ollama_prompt_checklist.dart` and `pubspec.yaml` files. The most important changes include updating the large language model used in the AI checklist response to [Tülu3](https://allenai.org/tulu) and incrementing the version number of the project.
Updates to AI checklist response:
* [`lib/features/ai/state/ollama_prompt_checklist.dart`](diffhunk://#diff-8ca77a1ec7e12d65dbe8ac0ff67cf3c4b870bded4e9e1c523679ae16c4f1529dL36-R36): Changed the language model from `llama3.1` to `tulu3:latest` for better performance and accuracy.
Version increment:
* [`pubspec.yaml`](diffhunk://#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25L4-R4): Incremented the project version from `0.9.539+2760` to `0.9.540+2761` to …
> feat: use Tülu3 model for checklist creation

- lib/beamer/beamer_app.dart
- lib/features/ai/ui/ai_prompt_icon_widget.dart
- lib/features/habits/ui/widgets/habits_search.dart
- lib/features/journal/ui/widgets/editor/editor_toolbar.dart
- lib/features/journal/ui/widgets/editor/editor_widget.dart
- lib/features/journal/ui/widgets/entry_details/duration_widget.dart
- lib/features/journal/ui/widgets/entry_details/entry_datetime_widget.dart
- lib/features/journal/ui/widgets/entry_details_widget.dart
- lib/features/journal/ui/widgets/journal_card.dart
- lib/themes/theme.dart
- lib/widgets/misc/time_recording_indicator.dart
- pubspec.yaml
This pull request includes multiple changes across various files to enhance the UI and improve consistency in the application. The most important changes include adjustments to padding and margins, modifications to widget properties, and updates to theme configurations.
* [`lib/features/journal/ui/widgets/editor/editor_widget.dart`](diffhunk://#diff-558b2c8ca968b697db88d7a84042919d64183136d91d94657bd1d2668b49ac7eL17-R17): Adjusted padding and border properties for a more refined look. [[1]](diffhunk://#diff-558b2c8ca968b697db88d7a84042919d64183136d91d94657bd1d2668b49ac7eL17-R17) [[2]](diffhunk://#diff-558b2c8ca968b697db88d7a84042919d64183136d91d94657bd1d2668b49ac7eL43-R48)
* [`lib/features/journal/ui/widgets/entry_details/entry_datetime_widget.dart`](diffhunk://#diff-6c47dc5ee590077317bfc3 …
> feat: improve styling & whitespace

- lib/blocs/habits/habits_cubit.dart
- lib/database/common.dart
- lib/features/calendar/state/day_view_controller.dart
- lib/features/calendar/state/time_by_category_controller.dart
- pubspec.yaml
From Copilot:
This pull request includes several changes aimed at improving the visibility settings and adding logging capabilities for database operations. The most important changes include setting `_isVisible` to `false` in multiple files, adding a new import for logging, and introducing a `LogInterceptor` class for database query logging.
Visibility settings changes:
* [`lib/blocs/habits/habits_cubit.dart`](diffhunk://#diff-2d1ab1a40de156b2d0cf1c294e16505cc07aa782affd791aa99015de6c792018L222-R222): Changed `_isVisible` from `true` to `false` in `HabitsCubit` class.
* [`lib/features/calendar/state/day_view_controller.dart`](diffhunk://#diff-fddf24c58c793441d1323fcdb3df79771a2942952ae5896db99b340b2ba7c361L28-R28): Changed `_isVisible` from `true` to `false` in `DayViewController` class. …
> feat: database query logging

- lib/features/journal/ui/widgets/journal_card.dart
- lib/features/tasks/repository/checklist_repository.dart
- lib/features/tasks/state/checklist_controller.dart
- lib/features/tasks/ui/checklist_widget.dart
- lib/features/tasks/ui/checklist_wrapper.dart
- lib/l10n/app_en.arb
- pubspec.yaml
From Copilot:
This pull request includes several changes to enhance the functionality of the checklist feature in the application. The changes primarily focus on adding category support to checklist items, improving the user interface, and updating localization files.
* [`lib/features/journal/ui/widgets/journal_card.dart`](diffhunk://#diff-83cffd946045977273d7f4ff6e4ec3c4b7c44a4e25b296436582954522988d38L256-R271): Added logic to retrieve and use category information for checklist items, including displaying the category color.
* [`lib/features/tasks/repository/checklist_repository.dart`](diffhunk://#diff-d4a7735e04e589704f78c8e3a66d25d19ee39464c6598922f360fd9346db50baR38-R42): Updated methods to include `categoryId` when creating checklist items and checklists. …
> feat: add delete icon for checklist & color coded checkboxes

- lib/classes/journal_entities.dart
- lib/database/maintenance.dart
- lib/l10n/app_en.arb
- lib/pages/settings/advanced/maintenance_page.dart
- pubspec.yaml
This pull request introduces several important changes to the project, including adding new features, improving error handling, and updating the user interface. The most significant changes are outlined below:
* Added a new method `addCategoriesToChecklists` in the `Maintenance` class to assign categories to checklists and their items. This method also logs the number of tasks, tasks with categories, updated checklists, and updated checklist items.
* Added a new maintenance option "Assign categories to checklists" in the `MaintenancePage` class to trigger the `addCategoriesToChecklists` method.
* Updated the `SendExtension` on `MatrixService` to throw exceptions for various error conditions, such as unverified Matrix devices, missing configuration, failed text message sending, and failed …
> feat: checklist categories migration

- ios/Podfile.lock
- lib/features/sync/matrix/matrix_service.dart
- lib/features/sync/matrix/timeline.dart
- lib/features/sync/outbox/outbox_service.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
This pull request includes multiple changes to integrate the `connectivity_plus` package for monitoring connectivity changes and to ensure the app responds appropriately. Additionally, some updates were made to the dependencies and plugin registration files.
* [`lib/features/sync/matrix/matrix_service.dart`](diffhunk://#diff-b2562ebc9d3428cc2fbbe7bd13441c53eb853840e84b9e1f4b99c96e73d91a66R3): Added `connectivity_plus` import and implemented connectivity change listener to enqueue requests when connectivity is available. [[1]](diffhunk://#diff-b2562ebc9d3428cc2fbbe7bd13441c53eb853840e84b9e1f4b99c96e73d91a66R3) [[2]](diffhunk://#diff-b2562ebc9d3428cc2fbbe7bd13441c53eb853840e84b9e1f4b99c96e73d91a66R50-R61)
* [`lib/features/sync/outbox/outbox_service.dart`](diffhunk://#diff-faf3f488a7f4fded6bc …
> feat: network detection

- ios/Podfile.lock
- lib/blocs/journal/journal_page_cubit.dart
- lib/classes/entity_definitions.dart
- lib/classes/entity_definitions.freezed.dart
- lib/classes/entity_definitions.g.dart
- lib/classes/journal_entities.dart
- lib/classes/journal_entities.freezed.dart
- lib/classes/journal_entities.g.dart
- lib/database/conversions.dart
- lib/features/ai/state/ollama_task_summary.dart
- lib/features/ai/state/ollama_task_summary.g.dart
- lib/features/ai/ui/ai_response_summary.dart
- lib/features/ai/ui/task_summary/ai_task_summary_list_tile.dart
- lib/features/ai/ui/task_summary/ai_task_summary_view.dart
- lib/features/journal/ui/widgets/entry_details_widget.dart
- lib/features/journal/ui/widgets/journal_card.dart
- lib/logic/persistence_logic.dart
- lib/themes/theme.dart
- lib/utils/file_utils.dart
- lib/utils/modals.dart
- lib/widgets/search/entry_type_filter.dart
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
From Copilot:
This pull request introduces a new `AiResponseData` class and integrates it into various parts of the codebase. The changes include adding serialization and deserialization methods, updating entity definitions, and modifying the UI to display AI responses.
Key changes include:
* [`lib/classes/entity_definitions.dart`](diffhunk://#diff-12d73a6dcf56f3577ee89eb34699623f680d766ff7834495e35f7e6057e075e3R166-R180): Added `AiResponseData` class with fields like `model`, `systemMessage`, `prompt`, `thoughts`, `response`, and `temperature`.
* [`lib/classes/entity_definitions.freezed.dart`](diffhunk://#diff-bf4d5c2418af3952dc9cb27c46b578bc959d051d47b27b5899e273cea79dc5a5R5477-R5735): Added serialization and deserialization methods for `AiResponseData`.
* …
> feat: use DeepSeek-R1 locally

- lib/features/ai/repositories/ollama_repository.dart
- lib/features/ai/repositories/ollama_repository.g.dart
- lib/features/ai/state/ollama_task_summary.dart
- lib/features/ai/state/ollama_task_summary.g.dart
- pubspec.lock
- pubspec.yaml
- test/features/ai/state/ollama_task_summary_test.dart
From Copilot:
This pull request introduces a new `OllamaRepository` class to handle AI model interactions and integrates it with the existing state management and testing infrastructure. The most important changes include the creation of the repository, modifications to state management to use this repository, and the addition of tests for the new functionality.
* [`lib/features/ai/repositories/ollama_repository.dart`](diffhunk://#diff-6bd48902fa31bbf08bbb610c2d3f4698aaec5835505106ee3049963edff741e0R1-R35): Created `OllamaRepository` class to handle AI model interactions, including a method to generate text completions.
* [`lib/features/ai/repositories/ollama_repository.g.dart`](diffhunk://#diff-0cc5a8f6c364fb336284c3ccadaa89b63f5f07f48d9b91aff042135349bb5f59R1-R27): Generated Riverpod …
> test: add task summary tests

- lib/features/dashboards/ui/widgets/charts/dashboard_measurables_chart_info.dart
- lib/pages/create/create_measurement_dialog.dart
- pubspec.lock
- pubspec.yaml
From Copilot:
This pull request includes several changes to the `lotti` project, focusing on UI improvements and dependency updates. The most important changes are related to the modal dialog implementation and visual adjustments.
UI Improvements:
* [`lib/features/dashboards/ui/widgets/charts/dashboard_measurables_chart_info.dart`](diffhunk://#diff-7c9a517a46bd1a51edee2a6733b0d93720e37846829924caac27666f39e269e2L27-R36): Replaced the usage of `showDialog` with `ModalUtils.showSinglePageModal` for better modal handling and added padding and navbar height parameters.
* [`lib/pages/create/create_measurement_dialog.dart`](diffhunk://#diff-a350f3b76f109fb583dcfa73e0235d0801e6d09fbab053ff78a5e5cdf23910a8L104-R104): Removed the shape property and set the background color to transparent for a …
> fix: theming issue

- lib/features/categories/ui/widgets/category_field.dart
- lib/features/journal/repository/journal_repository.dart
- lib/logic/persistence_logic.dart
- lib/widgets/settings/settings_card.dart
- pubspec.yaml
From Copilot:
This pull request includes several changes to the `lib/features/categories/ui/widgets/category_field.dart` file to enhance the category selection feature, as well as updates to the `lib/features/journal/repository/journal_repository.dart`, `lib/logic/persistence_logic.dart`, and `lib/widgets/settings/settings_card.dart` files to support these enhancements. Additionally, the version number in `pubspec.yaml` has been incremented.
Enhancements to category selection:
* [`lib/features/categories/ui/widgets/category_field.dart`](diffhunk://#diff-f646f96452ba3bda944c07b4b941c34f47ae66283f4532f413d9fd05b4478fdcR43): Added `initialCategoryId` parameter to `CategoryField` and `_CategorySelectionContent` classes to allow pre-selection of a category. …
> feat: implement clearing previous category selection

- lib/features/categories/ui/widgets/category_selection_modal_content.dart
- pubspec.yaml
This PR is fixing the category filter list.
> fix: used filtered list

- ios/Podfile.lock
- lib/features/journal/ui/widgets/entry_details/entry_detail_footer.dart
- lib/features/journal/ui/widgets/entry_details/header/entry_detail_header.dart
- lib/features/journal/ui/widgets/entry_details_widget.dart
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
- test/features/journal/ui/pages/entry_detail_page_test.dart
- test/test_data/test_data.dart
From Copilot:
This pull request includes several changes to the `entry_details` components in the `journal` feature, focusing on improving the layout and conditional rendering logic for various widgets. Additionally, there is a minor version bump in the `pubspec.yaml` file.
Improvements to `entry_details` components:
* [`lib/features/journal/ui/widgets/entry_details/entry_detail_footer.dart`](diffhunk://#diff-129a8b74256dd5252279c1e07527cc204b111ba9cdf0947d4b8c32beb1bfef21R42-R50): Added conditional rendering for `SaveButton` and `SizedBox` based on the `inLinkedEntries` flag.
* [`lib/features/journal/ui/widgets/entry_details/header/entry_detail_header.dart`](diffhunk://#diff-daa5674187c7a4aff0ab5f34c4342f4d9c9ad504ca9cd6a9b4cb55b5c7108ad6R63-R68): Added `CategorySelectionIconButton` …
> feat: adjust entry layout

- lib/features/ai/state/latest_summary_controller.dart
- lib/features/ai/state/latest_summary_controller.g.dart
- lib/features/ai/ui/ai_response_summary.dart
- lib/features/ai/ui/latest_ai_summary.dart
- lib/features/journal/repository/journal_repository.dart
- lib/features/journal/state/linked_entries_controller.dart
- lib/features/journal/state/linked_entries_controller.g.dart
- lib/features/journal/ui/pages/entry_details_page.dart
- lib/features/journal/ui/widgets/entry_detail_linked.dart
- lib/features/journal/ui/widgets/entry_detail_linked_from.dart
- lib/features/journal/ui/widgets/entry_details_widget.dart
- lib/features/tasks/state/checklist_controller.dart
- lib/features/tasks/state/checklist_controller.g.dart
- lib/features/tasks/ui/checklists/checklist_item_widget.dart
- lib/features/tasks/ui/checklists/checklist_suggestions_widget.dart
- lib/features/tasks/ui/checklists/checklist_wrapper.dart
- lib/features/tasks/ui/checklists/checklists_widget.dart
- lib/l10n/app_en.arb
- pubspec.lock
- pubspec.yaml
This PR adds checklist/action item suggestions derived from AI task summaries.
From Copilot:
This pull request introduces several new features and improvements to the AI summary and journal entry functionalities, including new controllers, UI components, and repository methods.
* **`latest_summary_controller.dart`**: Added `LatestSummaryController` and `ChecklistItemSuggestionsController` to manage AI summary updates and checklist item suggestions.
* **`journal_repository.dart`**: Introduced `getLinkedEntities` method to fetch entities linked to a specific ID.
* **`latest_ai_summary.dart`**: Created `LatestAiSummary` widget to display the latest AI summary for a given item.
* **`ai_response_summary.dart`**: Enhanced `AiResponseSummary` with a `ShaderMask` to apply a gradient effect.
* …
> feat: checklist item suggestion

- .github/workflows/flutter-test.yml
From Copilot:
This pull request includes updates to the `.github/workflows/flutter-test.yml` file to enhance the Flutter test workflow by adding code coverage and updating the Codecov action.
Changes to the Flutter test workflow:
* [`.github/workflows/flutter-test.yml`](diffhunk://#diff-b50233b18ba85f68ec7cc7bdb17ce903d73ac28c744cfe23d6916445bb2aa2e5L28-R32): Modified the Flutter test command to include code coverage (`flutter test --coverage`).
* [`.github/workflows/flutter-test.yml`](diffhunk://#diff-b50233b18ba85f68ec7cc7bdb17ce903d73ac28c744cfe23d6916445bb2aa2e5L28-R32): Updated the Codecov action from version 3 to version 5 and added necessary configuration parameters including the Codecov token and repository slug.
> ci: update codecov action

- integration_test/matrix_service_test.dart
- lib/features/ai/state/action_item_suggestions.dart
- lib/features/tasks/ui/checklists/checklist_suggestions_widget.dart
- lib/l10n/app_en.arb
- pubspec.yaml
- test/features/ai/state/action_item_suggestions_test.dart
This pull request includes several changes to the `ChecklistSuggestionsWidget` in the `lib/features/tasks/ui/checklists/checklist_suggestions_widget.dart` file, as well as updates to localization and versioning. The most important changes involve adding a new modal for action item suggestions and updating UI elements to reflect this new functionality.
Enhancements to `ChecklistSuggestionsWidget`:
* Added import for `ActionItemSuggestionsView` and `ModalUtils` to `checklist_suggestions_widget.dart` to support the new modal functionality.
* Introduced a `showThoughtsModal` method in `_ChecklistSuggestionsWidgetState` to display a modal with action item suggestions.
* Updated the `CircularProgressIndicator` to be wrapped in a `GestureDetector` that triggers the `showThoughtsModal` method …
> feat: peek into thinking process

- lib/database/journal_db/config_flags.dart
- lib/features/ai/model/cloud_inference_config.dart
- lib/features/ai/model/cloud_inference_config.freezed.dart
- lib/features/ai/model/cloud_inference_config.g.dart
- lib/features/ai/repository/cloud_inference_repository.dart
- lib/features/ai/repository/cloud_inference_repository.g.dart
- lib/features/ai/state/action_item_suggestions.dart
- lib/features/ai/state/action_item_suggestions.g.dart
- lib/features/ai/state/task_summary_controller.dart
- lib/features/ai/state/task_summary_controller.g.dart
- lib/features/ai/ui/task_summary/action_item_suggestions_view.dart
- lib/features/ai/ui/task_summary/ai_task_summary_view.dart
- lib/pages/settings/flags_page.dart
- lib/utils/consts.dart
- pubspec.lock
- pubspec.yaml
- test/database/database_test.dart
- test/features/ai/state/action_item_suggestions_test.dart
- test/features/ai/state/task_summary_controller_test.dart
From Copilot:
This pull request introduces a new feature for cloud inference, adding configuration, repository, and state management for it. The most important changes include the introduction of a new configuration flag, the creation of a `CloudInferenceConfig` model, and updates to the `ActionItemSuggestionsController` and `TaskSummaryController` to utilize cloud inference.
* [`lib/features/ai/model/cloud_inference_config.dart`](diffhunk://#diff-7b6dd3448a378f9cabaf4f1929f0a2654e41ccb65faf8d8d130f2068516be57fR1-R15): Added a new `CloudInferenceConfig` model with `baseUrl` and `apiKey` fields.
* [`lib/features/ai/repository/cloud_inference_repository.dart`](diffhunk://#diff-64ddb4da404a5c1b05d6a6ebedfb69a1008cf17d70c0067a368753dfc068413fR1-R60): Created a new repository for handling …
> feat: add cloud inference

- lib/features/ai/ui/task_summary/action_item_suggestions_view.dart
- lib/features/tasks/repository/checklist_repository.dart
- lib/features/tasks/state/checklist_controller.dart
- lib/features/tasks/ui/checklists/checklist_suggestions_widget.dart
- lib/features/tasks/ui/checklists/checklist_wrapper.dart
- pubspec.lock
- pubspec.yaml
This pull request includes a few small changes to improve the user interface and update the project version.
* [`lib/features/ai/ui/task_summary/action_item_suggestions_view.dart`](diffhunk://#diff-cab4f06613b3e491f3b745a31b0d77a8192c10979a342b487ba1adca6218b1f4R23): Added the `reverse: true` property to `SingleChildScrollView` to reverse the scroll direction.
* [`pubspec.yaml`](diffhunk://#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25L4-R4): Updated the project version from `0.9.581+2938` to `0.9.581+2939`.
> feat: auto scroll in item suggestions view

- ios/Podfile.lock
- lib/features/manual/widget/showcase_with_widget.dart
- lib/main.dart
- lib/pages/settings/form_text_field.dart
- lib/pages/settings/habits/habit_create_page.dart
- lib/pages/settings/habits/habit_details_page.dart
- lib/themes/theme.dart
- pubspec.lock
- pubspec.yaml
- test/pages/settings/habits/habit_details_page_test.dart
Implemented an onboarding showcase to guide users through key features of the app. Highlights important UI elements step by step with tooltips for a smooth user experience.
> feat: implement onboarding showcase with step by step guide

- lib/features/ai/repository/cloud_inference_repository.dart
- pubspec.yaml
This pull request includes changes to the `lib/features/ai/repository/cloud_inference_repository.dart` and `pubspec.yaml` files. The most important changes involve modifying the `CloudInferenceRepository` class and updating the version number in the project configuration.
Changes to `CloudInferenceRepository`:
* Removed the `maxTokens` parameter from the model configuration.
Project configuration update:
* Updated the version number in `pubspec.yaml` from `0.9.581+2942` to `0.9.581+2943`.
> feat: remove max tokens limitation

- lib/features/tasks/ui/checklists/checklist_suggestions_widget.dart
- pubspec.yaml
This pull request includes a few changes to the `checklist_suggestions_widget.dart` file and an update to the version number in `pubspec.yaml`. The most important changes are:
UI Improvements:
* [`lib/features/tasks/ui/checklists/checklist_suggestions_widget.dart`](diffhunk://#diff-09822002c9ab9abe8db6e52b55e9a0cf9c3fc9909f7f7a17bdf5f50e2ad18bccL107-R107): Modified the icon logic to display the `Icons.assistant_rounded` only when `checklistItems` is empty and `isOutdated` is false. Otherwise, it displays the `Icons.refresh` icon.
Version Update:
* [`pubspec.yaml`](diffhunk://#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25L4-R4): Updated the version number from `0.9.582+2947` to `0.9.582+2948`.
> feat: consistent icon use

- ios/Podfile.lock
- lib/features/ai/repository/prompts.dart
- pubspec.yaml
This pull request includes updates to the task output format and a version bump for the `lotti` project.
Changes to task output format:
* [`lib/features/ai/repository/prompts.dart`](diffhunk://#diff-16344e54d34573c1cc91d3477b5e4793e5ae30b07cb28a20a6139b5b6a66ea3fR61-R82): Added instructions to use emojis for individual list item bullet points in task outputs, such as ✅ for completed items, 💡 for learnings, and 🤯 for annoyances.
* [`pubspec.yaml`](diffhunk://#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25L4-R4): Incremented the version from `0.9.584+2956` to `0.9.585+2957`.
> feat: enhance TLDR output with emojis

- ios/Podfile.lock
- lib/features/ai/state/image_analysis.dart
- lib/features/ai/state/task_summary_controller.dart
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
This pull request includes several changes to the AI image analysis and task summary controllers, as well as a minor version update in the `pubspec.yaml` file. The most important changes involve updates to the image analysis prompt, model selection logic, and handling of AI response data.
Changes to AI image analysis:
* [`lib/features/ai/state/image_analysis.dart`](diffhunk://#diff-5f211bf0facb245629dcb4d7f3940febdadc50f56bec019053b479291617f9e9L43-R45): Modified the prompt to focus more on content and relevant information, and updated the model selection logic to use a different model for cloud inference. [[1]](diffhunk://#diff-5f211bf0facb245629dcb4d7f3940febdadc50f56bec019053b479291617f9e9L43-R45) [[2]](diffhunk://#diff-5f211bf0facb245629dcb4d7f3940febdadc50f56bec019053b479291617f9e9L55 …
> feat: increase use of Gemma 3 

- lib/features/manual/widget/showcase_text_style.dart
- lib/features/manual/widget/showcase_with_widget.dart
Improved showcase container styling: optimized colors for light/dark mode and adjusted text color.
> fix: showcase colors

- test/features/ai/ui/ai_response_summary_modal_test.dart
- test/features/calendar/state/day_view_controller_test.dart
- test/features/calendar/state/time_by_category_controller_test.dart
This pull request includes several new test files and test cases to improve the coverage for different features within the application. The most important changes include adding tests for AI response summary modal, day view controller, and time by category controller. These tests ensure the correct rendering of UI components, state management, and interaction with mock services.
* Added tests to verify the presence of UI elements and correct rendering of tabs in `AiResponseSummaryModalContent`.
* Implemented mock clipboard functionality for testing purposes.
* Added tests to verify the initial state and updates of calendar entries in `day_view_controller`.
* Implemented mock services and listeners to simulate state changes and notifications.
* Added tests to verify the initial state and …
> test: improve coverage

- lib/features/ai/state/checklist_suggestions_controller.dart
- lib/features/ai/state/checklist_suggestions_controller.g.dart
- lib/features/ai/state/latest_summary_controller.g.dart
- lib/features/ai/ui/latest_ai_response_summary.dart
- lib/features/journal/state/entry_controller.g.dart
- lib/features/tasks/ui/checklists/checklist_suggestions_widget.dart
- lib/features/tasks/ui/checklists/checklists_widget.dart
- pubspec.yaml
- test/features/tasks/ui/checklists/checklist_item_widget_test.dart
This pull request includes significant changes to the `ChecklistSuggestionsController` and related files, as well as some UI adjustments and new tests. The primary focus is on modifying the `ChecklistSuggestionsController` to handle nullable data types and enhancing the UI components for better user experience.
* Modified the `build` method and related types to handle nullable `ChecklistItemData`. (`lib/features/ai/state/checklist_suggestions_controller.dart`, `lib/features/ai/state/checklist_suggestions_controller.g.dart`) [[1]](diffhunk://#diff-605e8c30d3fd52f10c946b4771532a21fa1d5df300496095c407bb0ae4284efbL13-R13) [[2]](diffhunk://#diff-605e8c30d3fd52f10c946b4771532a21fa1d5df300496095c407bb0ae4284efbL22-R24) [[3]](diffhunk://#diff-23c680ab53cd227e837f5c51f792c3704b05724a24dbf901504579e …
> feat: simply & declutter checklists section

- lib/features/ai/state/latest_summary_controller.dart
- lib/features/ai/ui/animation/ai_running_animation.dart
- lib/features/ai/ui/task_summary/action_item_suggestions_view.dart
- lib/features/ai/ui/task_summary/ai_task_summary_view.dart
- lib/features/journal/ui/pages/entry_details_page.dart
- lib/utils/modals.dart
- pubspec.lock
- pubspec.yaml
This pull request introduces a new animation feature to indicate AI processes running in the background. It includes changes to several UI components to integrate this feature, as well as some minor updates to dependencies and configurations.
Integration of AI running animation:
* [`lib/features/ai/ui/animation/ai_running_animation.dart`](diffhunk://#diff-94d5f75a51890cc8e7290cfadf7a6edcce6538e257071b4dd8d50ce73292d3e9R1-R60): Added a new `AIRunningAnimation` widget that uses the `SiriWave` package to display a waveform animation during AI processes.
* [`lib/features/ai/ui/task_summary/action_item_suggestions_view.dart`](diffhunk://#diff-cab4f06613b3e491f3b745a31b0d77a8192c10979a342b487ba1adca6218b1f4R4): Updated to include the `AIRunningAnimation` widget at the bottom of the view. …
> feat: add animation while inference is active

- lib/features/ai/state/image_analysis.g.dart
- lib/features/ai/state/inference_status_controller.dart
- lib/features/ai/state/inference_status_controller.g.dart
- lib/features/ai/state/latest_summary_controller.g.dart
- lib/features/ai/ui/animation/ai_running_animation.dart
- lib/features/ai/ui/image_analysis/ai_image_analysis_view.dart
- lib/features/ai/ui/task_summary/action_item_suggestions_view.dart
- lib/features/ai/ui/task_summary/ai_task_summary_view.dart
- lib/features/journal/state/entry_controller.g.dart
- lib/features/journal/ui/pages/entry_details_page.dart
- lib/features/speech/ui/widgets/transcription_progress_modal.dart
- lib/features/tasks/ui/task_form.dart
- lib/widgets/settings/config_flag_card.dart
- pubspec.lock
- pubspec.yaml
- test/features/ai/state/inference_status_controller_test.dart
- test/features/ai/ui/animation/ai_running_animation_test.dart
This pull request introduces several changes to improve the AI inference status handling and UI components within the application. The most significant changes include the addition of the `InferenceRunningController`, modifications to the `AiRunningAnimation` component, and various UI updates to utilize the new controller.
* Added `InferenceRunningController` to manage and track the running status of AI inferences. This includes the implementation of the controller, its provider, and associated methods. (`lib/features/ai/state/inference_status_controller.dart`, `lib/features/ai/state/inference_status_controller.g.dart`) [[1]](diffhunk://#diff-fe8f590e3ea1d6e219d97db31cafb87e8c4dcfb417eb317ce56f5fb48a533be2R28-R49) [[2]](diffhunk://#diff-5234d926d415ffef26fa1e95717e17d0254313b051165b69a134d …
> feat: task & AI layout tweaks

- pubspec.lock
- pubspec.yaml
This pull request includes updates to the `pubspec.yaml` file for the Lotti project, addressing both versioning and dependency updates.
* Incremented the project version from `0.9.597+2996` to `0.9.597+2997`.
Dependency update:
* Updated the `matrix` package dependency from version `0.38.0` to `0.39.1`.
> chore: upgrade matrix & other dependencies

- lib/features/ai/model/cloud_inference_config.dart
- lib/features/ai/model/cloud_inference_config.freezed.dart
- lib/features/ai/model/cloud_inference_config.g.dart
- lib/features/ai/repository/gemini_cloud_inference_repository.dart
- lib/features/ai/repository/gemini_cloud_inference_repository.g.dart
- lib/features/ai/state/audio_transcription.dart
- lib/features/ai/state/audio_transcription.g.dart
- lib/features/ai/state/consts.dart
- lib/features/ai/ui/ai_popup_menu.dart
- lib/features/ai/ui/audio_transcription/audio_transcription_progress_list_tile.dart
- lib/features/ai/ui/audio_transcription/audio_transcription_progress_view.dart
- lib/features/journal/state/entry_controller.dart
- lib/features/journal/ui/widgets/entry_details/header/entry_detail_header.dart
- lib/features/tasks/repository/checklist_repository.dart
- lib/features/tasks/ui/pages/task_details_page.dart
- lib/l10n/app_en.arb
- pubspec.lock
- pubspec.yaml
- test/features/ai/ui/audio_transcription/audio_transcription_progress_list_tile_test.dart
- test/features/tasks/repository/checklist_repository_test.dart
This pull request introduces a new feature for audio transcription using the Gemini API. It includes updates to the `CloudInferenceConfig` model to support the Gemini API key, the addition of a new repository for handling Gemini cloud inference operations, and a state management implementation for audio transcription. Below are the most important changes grouped by theme:
* Added a new `geminiApiKey` field to the `CloudInferenceConfig` model and updated its factory constructor, JSON serialization, and copy methods to include the new field. (`lib/features/ai/model/cloud_inference_config.dart`, `lib/features/ai/model/cloud_inference_config.freezed.dart`, `lib/features/ai/model/cloud_inference_config.g.dart`) [[1]](diffhunk://#diff-7b6dd3448a378f9cabaf4f1929f0a2654e41ccb65faf8d8d130f2068516be …
> feat: add gemini client

- lib/features/categories/ui/widgets/category_selection_icon_button.dart
- lib/features/categories/ui/widgets/category_selection_modal_content.dart
- lib/features/categories/ui/widgets/category_type_card.dart
- lib/widgets/app_bar/title_app_bar.dart
- pubspec.yaml
- test/features/categories/ui/widgets/category_selection_modal_content_test.dart
This pull request introduces several updates to improve the UI and functionality of category selection, refactor components for better usability, and add comprehensive tests. The key changes include replacing `GestureDetector` with `IconButton` for better accessibility, enhancing the `CategorySelectionModalContent` to handle the initial category, and adding tests for category selection behavior.
* Replaced `GestureDetector` with `IconButton` in `CategorySelectionIconButton` and `BackWidget` to improve accessibility and align with Material Design guidelines. (`lib/features/categories/ui/widgets/category_selection_icon_button.dart`, `lib/widgets/app_bar/title_app_bar.dart`) [[1]](diffhunk://#diff-1f16f7b503e3ef603ab20716cf94e337cc1f204ae641aac5fef4bf366e408d65L26-R27) …
> feat: highlight selected category in selection modal

- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- lib/features/speech/ui/widgets/transcription_progress.dart
- lib/features/speech/ui/widgets/transcription_progress_modal.dart
- lib/logic/health_import.dart
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
This pull request introduces several updates to the project, including improvements to health data handling, migration to new Markdown and health-related libraries, and dependency updates. The most significant changes involve replacing the `flutter_health_fit` library with the `health` library, updating the Markdown rendering library, and revising the project's dependencies and permissions handling.
* Replaced `flutter_health_fit` with the `health` library, updating methods for fetching health data such as steps, distance, and flights climbed. Introduced a new helper method `sumNumericHealthValues` to process health data points. [[1]](diffhunk://#diff-4877222ef65545fb50be2ed152f444e77fc1d78f2773b84aae90e9a1e31951b7R16-R25) [[2]](diffhunk://#diff-4877222ef65545fb50be2ed152f444e77fc1d78f2773 …
> feat: replace health fork with upstream

- lib/features/dashboards/ui/widgets/charts/dashboard_health_bp_chart.dart
- lib/features/dashboards/ui/widgets/charts/time_series/time_series_bar_chart.dart
- lib/features/dashboards/ui/widgets/charts/time_series/time_series_line_chart.dart
- lib/features/dashboards/ui/widgets/charts/time_series/time_series_multiline_chart.dart
- pubspec.lock
- pubspec.yaml
This pull request includes updates to the tooltip styling in multiple chart widgets and dependency upgrades in the `pubspec.yaml` file. The most important changes are grouped into UI improvements and dependency updates.
* Replaced the `tooltipRoundedRadius` property with `tooltipBorderRadius` using `BorderRadius.circular(8)` for consistent tooltip styling across the following chart widgets:
- `DashboardHealthBpChart` (`lib/features/dashboards/ui/widgets/charts/dashboard_health_bp_chart.dart`)
- `TimeSeriesBarChart` (`lib/features/dashboards/ui/widgets/charts/time_series/time_series_bar_chart.dart`)
- `TimeSeriesLineChart` (`lib/features/dashboards/ui/widgets/charts/time_series/time_series_line_chart.dart`)
- `TimeSeriesMultiLineChart` …
> chore: upgrade major versions of matrix and fl_chart

- lib/database/database.dart
- lib/l10n/app_en.arb
- lib/pages/settings/advanced/maintenance_page.dart
- lib/widgets/modal/modal_action_sheet.dart
- Delete both media files (images/audio) and their JSON metadata
- Handle errors gracefully with logging
- Ensure files are deleted before database cleanup
- Increase font size for purge button text (14 -> 24.6)
This change ensures that when purging deleted items, both the database entries
and their associated files are completely removed from the system, preventing
orphaned files from accumulating.
> feat: enhance purge deleted functionality and Improve maintenance page UI.

- lib/features/journal/util/entry_tools.dart
- pubspec.yaml
This pull request includes a bug fix in the `entryTextForWorkout` function and a version update in the `pubspec.yaml` file. The changes ensure better handling of null values and prepare the application for the next build.
* [`lib/features/journal/util/entry_tools.dart`](diffhunk://#diff-6c6058346e66ff59b15b84aecfbeada4a23611374fb6ea7287b9cd265afe51ffR89-R92): Updated the `entryTextForWorkout` function to handle cases where `data.energy` is null by assigning a default value of `0`. This prevents potential runtime errors and ensures the energy value is always formatted correctly.
* [`pubspec.yaml`](diffhunk://#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25L4-R4): Incremented the application version from `0.9.606+3036` to `0.9.606+3037` to reflect the new changes in …
> fix: trying to format null value

- lib/pages/settings/advanced/maintenance_page.dart
- lib/widgets/modal/confirmation_modal.dart
Added styles to the modal sheet for better user experience.
- lib/pages/settings/advanced/maintenance_page.dart
- lib/widgets/modal/confirmation_modal.dart
> feat: styling modal UI

- lib/database/database.dart
- lib/features/sync/state/purge_controller.dart
- lib/features/sync/ui/purge_modal.dart
- lib/features/sync/ui/sync_modal.dart
- lib/l10n/app_en.arb
- lib/pages/settings/advanced/maintenance_page.dart
- lib/utils/modals.dart
- lib/widgets/modal/confirmation_modal.dart
- test/features/sync/state/purge_controller_test.dart
- test/features/sync/ui/sync_modal_progress_test.dart
- Modified the implementation of modal sheets for both purge delete and sync entities operations
- Created a unified approach using SyncModal to handle both operations
- Added OperationType enum to distinguish between sync and purge operations
- Created PurgeController with proper state management using Riverpod
- Implemented progress tracking and error handling
- Added comprehensive tests for the purge controller
- Fixed progress indicators to show proper percentage (0% to 100%)
- Standardized completion icons (checkmark for sync, delete icon for purge)
Added unit tests for PurgeController
Verified state progression and error handling
> feat: Add comprehensive progress indicator and tests

- lib/features/speech/state/recorder_cubit.dart
- lib/get_it.dart
- test/features/speech/state/recorder_cubit_test.dart
> fix: stop audio playback before recording

- lib/features/sync/repository/sync_maintenance_repository.dart
- lib/features/sync/state/sync_maintenance_controller.dart
- lib/utils/modals.dart
- test/features/sync/repository/sync_maintenance_repository_test.dart
- test/features/sync/state/sync_maintenance_controller_test.dart
- test/features/sync/ui/sync_modal_test.dart
> fix: sync progress indicator granular and accurate progress feedback

- lib/beamer/beamer_app.dart
- lib/features/journal/state/entry_controller.g.dart
- lib/features/speech/state/recorder_cubit.dart
- lib/features/sync/state/login_form_controller.g.dart
- lib/features/sync/state/matrix_config_controller.g.dart
- lib/features/sync/state/matrix_login_controller.g.dart
- lib/features/sync/state/matrix_room_provider.g.dart
- lib/features/sync/state/matrix_stats_provider.g.dart
- lib/features/sync/state/matrix_unverified_provider.g.dart
- lib/l10n/app_localizations.dart
- lib/l10n/app_localizations_de.dart
- lib/l10n/app_localizations_en.dart
- lib/l10n/app_localizations_es.dart
- lib/l10n/app_localizations_fr.dart
- lib/l10n/app_localizations_ro.dart
- lib/pages/settings/dashboards/dashboard_definition_page.dart
- lib/pages/settings/flags_page.dart
- lib/widgets/sync/matrix/incoming_verification_modal.dart
- pubspec.lock
- pubspec.yaml
- test/features/ai/ui/animation/ai_running_animation_test.dart
- test/features/speech/state/recorder_cubit_test.dart
> fix: recording playback conflict

- fastwhisper_server/.gitignore
- fastwhisper_server/Dockerfile
- fastwhisper_server/README.md
- fastwhisper_server/fastwhisper_server.py
- fastwhisper_server/fastwhisper_server_mac.spec
- fastwhisper_server/requirements.txt
- fastwhisper_server/test_fastwhisper.py
feat: add FastWhisper server implementation (python only)
> feat: add FastWhisper server implementation (python only)

- fastwhisper_server/.gitignore
- fastwhisper_server/requirements-insanely-fast-whisper.txt
- fastwhisper_server/test_insanely_fast_whisper.py
This pull request introduces a new testing script for an optimized Whisper-based ASR pipeline, adds corresponding dependencies, and updates the `.gitignore` file. The changes focus on enabling efficient transcription with hardware-specific optimizations and providing a comprehensive testing setup.
* [`fastwhisper_server/test_insanely_fast_whisper.py`](diffhunk://#diff-76cc7090fc450630eaae0e912bf7cb2ff8d2afbad2371bf0a47c14d90d2d99f4R1-R379): Added a new script to test automatic speech recognition using Whisper models. The script includes features such as device optimization, batch size adjustments, model validation, and transcription with optional timestamped outputs. It supports multiple Whisper model variants and provides CLI options for customization.
* …
> feat: add test script for insanely fast whisper

- .gitignore
- fastwhisper_server.py
- fastwhisper_server/README.md
- fastwhisper_server/fastwhisper_server.py
- fastwhisper_server/requirements-apple-silicon.txt
- warnings, language param, streaming, config, error handling, type hints
> fix: improve FastWhisper server

- lib/features/ai/README.md
- lib/features/ai/repository/unified_ai_inference_repository.dart
- lib/features/ai/ui/settings/ai_settings_page.dart
- lib/features/ai/util/preconfigured_prompts.dart
- pubspec.yaml
- test/features/ai/repository/unified_ai_inference_repository_test.dart
- test/features/ai/ui/settings/widgets/enhanced_preconfigured_prompt_modal_test.dart
- test/features/ai/util/preconfigured_prompts_test.dart
Adds context-aware AI prompts for image analysis and audio transcription. When images/audio are linked to tasks, the AI uses
task context to provide more relevant, focused responses.
- Added `Image Analysis in Task Context` prompt - extracts only task-relevant information from images
- Added `Audio Transcription with Task Context` prompt - improves transcription accuracy using task context
- Smart prompt filtering - context-aware prompts only appear when media is linked to a task
- Conditional `{{task}}` placeholder replacement - only fetches task data when needed
- Async prompt filtering to check entity relationships
- Updated from 4 to 6 preconfigured prompts
- Added comprehensive tests for both context-aware prompts
- Updated existing tests to handle 6 prompts instead of 4
- Updated …
> feat: context for audio transcripts

- lib/features/ai/ui/unified_ai_popup_menu.dart
- lib/features/journal/README.md
- lib/features/journal/state/entry_controller.dart
- lib/features/journal/ui/widgets/create/create_entry_action_list_tile.dart
- lib/themes/theme.dart
- pubspec.yaml
- test/features/journal/state/entry_controller_test.dart
- test/features/journal/ui/widgets/create/create_entry_action_list_tile_test.dart
This pull request introduces several changes across multiple files, focusing on improving user interaction, enhancing documentation, and refining UI behavior. Key updates include replacing `ListTile` with `InkWell` for better tap handling, revising toolbar visibility logic, and adding comprehensive documentation for the journal feature.
* [`lib/features/ai/ui/unified_ai_popup_menu.dart`](diffhunk://#diff-695658c0bc7423a2ea318fb3c1ffc5c6c4152ca1781893cac1e0f86f89363812L144-R146): Replaced `ListTile` with `InkWell` in `UnifiedAiPromptsList` to enable custom tap handling logic via `onTap` on the `InkWell` wrapper. [[1]](diffhunk://#diff-695658c0bc7423a2ea318fb3c1ffc5c6c4152ca1781893cac1e0f86f89363812L144-R146) [[2]](diffhunk://#diff-695658c0bc7423a2ea318fb3c1ffc5c6c4152ca1781893cac1e0f86f8936 …
> feat: interaction improvements

- lib/features/ai/README.md
- lib/features/ai/repository/unified_ai_inference_repository.dart
- lib/logic/health_import.dart
- pubspec.yaml
- test/features/ai/repository/unified_ai_inference_integration_test.dart
- test/features/ai/repository/unified_ai_inference_repository_test.dart
- test/features/journal/state/image_paste_controller_test.dart
This pull request introduces enhancements to the `UnifiedAiInferenceRepository` class and its associated test suite to improve handling of concurrent modifications and stale data during AI inference processing. Key changes include adding safeguards to ensure the current entity state is used during post-processing, refining logging for better error tracking, and expanding test coverage to validate these improvements.
* **Avoid stale data overwrites**: Added a private method `_getCurrentEntityState` to fetch the latest entity state and handle errors gracefully. This method is now used during post-processing to ensure the most up-to-date entity state is utilized. (`lib/features/ai/repository/unified_ai_inference_repository.dart`)
* **Concurrent modification protection**: Updated logic for …
> fix: concurrency issue when running inference

- lib/features/ai/ui/unified_ai_popup_menu.dart
- lib/features/ai/ui/unified_ai_progress_view.dart
- lib/themes/theme.dart
- lib/widgets/modal/animated_modal_item.dart
- lib/widgets/modal/animated_modal_item_controller.dart
- lib/widgets/modal/animated_modal_item_with_icon.dart
- lib/widgets/modal/modern_modal_action_item.dart
- lib/widgets/modal/modern_modal_entry_type_item.dart
- lib/widgets/modal/modern_modal_prompt_item.dart
- lib/widgets/modal/modern_modal_utils.dart
- pubspec.lock
- pubspec.yaml
- test/widgets/modal/animated_modal_item_resource_leak_test.dart
- test/widgets/modal/animated_modal_item_test.dart
- test/widgets/modal/animated_modal_item_with_icon_test.dart
- test/widgets/modal/modal_items_animation_integration_test.dart
This pull request introduces significant improvements to modal item animations and styling, refactors existing modal components to use shared animation logic, and adds new utility constants for spacing. The most important changes include the addition of new animated modal item components, refactoring of modal action items to leverage these components, and enhancements to animation controllers.
* Added a new `AnimatedModalItem` widget, which provides hover and tap animations for modal items. This includes customizable scale, opacity, and elevation effects. (`lib/widgets/modal/animated_modal_item.dart`)
* Introduced `AnimatedModalItemController` to encapsulate animation logic for hover and tap effects, enabling better reusability and testing. …
> feat: modal styling

- lib/features/manual/widget/showcase_with_widget.dart
- lib/features/sync/ui/matrix_settings_modal.dart
- lib/pages/settings/advanced/maintenance_page.dart
- lib/pages/settings/advanced_settings_page.dart
- lib/pages/settings/settings_page.dart
- lib/widgets/settings/animated_settings_cards.dart
- pubspec.yaml
This pull request introduces updates to enhance the user interface by replacing the `ModernSettingsCard` components with `AnimatedModernSettingsCard` components across multiple pages. Additionally, it refines the layout and spacing in the `ShowcaseWithWidget` component. These changes aim to improve visual consistency and interactivity throughout the application.
* Replaced `ModernSettingsCard` and `ModernSettingsCardWithIcon` with `AnimatedModernSettingsCard` and `AnimatedModernSettingsCardWithIcon` in `lib/pages/settings/advanced/maintenance_page.dart`, `lib/pages/settings/advanced_settings_page.dart`, and `lib/pages/settings/settings_page.dart` to provide animated interactions for settings cards. [[1]](diffhunk://#diff-9629a2a007ae47f07a96d05d0ee0e3dfb0800201a7ae590bbdc1e4dd6a24d205L13-R …
> feat: use card animations in settings

- lib/features/journal/ui/widgets/list_cards/animated_modern_task_card.dart
- lib/features/journal/ui/widgets/list_cards/card_wrapper_widget.dart
- lib/widgets/modal/animated_modal_item.dart
- pubspec.yaml
- test/features/journal/ui/widgets/list_cards/animated_modern_task_card_test.dart
- test/features/journal/ui/widgets/list_cards/card_wrapper_widget_test.dart
This pull request introduces `AnimatedModernTaskCard`, an enhanced version of `ModernTaskCard` with hover and tap animations, and integrates it into relevant parts of the codebase. It also modifies the `AnimatedModalItem` widget to support custom margins and updates related tests to reflect the new functionality.
* [`lib/features/journal/ui/widgets/list_cards/animated_modern_task_card.dart`](diffhunk://#diff-4eec0118cab0eaeb2f4175b5c80a688be326893d59ffc32600ae0f2cec4b8228R1-R39): Added the `AnimatedModernTaskCard` widget, which wraps `ModernTaskCard` with hover and tap animations using `AnimatedModalItem`. It includes custom behavior for margins to avoid duplication.
* [`lib/features/journal/ui/widgets/list_cards/card_wrapper_widget.dart`](diffhunk://#diff-0e05adac50d036253f338a216c7b54d81 …
> feat: use card animations in tasks list

- lib/themes/theme.dart
- lib/widgets/modal/README.md
- lib/widgets/modal/animated_modal_item.dart
- lib/widgets/modal/animated_modal_item_with_icon.dart
- lib/widgets/modal/modern_modal_entry_type_item.dart
- pubspec.lock
- pubspec.yaml
- test/widgets/modal/animated_modal_item_with_icon_test.dart
- test/widgets/modal/modal_items_animation_integration_test.dart
This pull request introduces a comprehensive update to the modal components in the application, focusing on improving reusability, maintainability, and animation consistency. The changes include new documentation, enhancements to the `AnimatedModalItem` and `AnimatedModalItemWithIcon` components, and refactoring of the `ModernModalEntryTypeItem` component to utilize shared animation logic.
* [`lib/widgets/modal/README.md`](diffhunk://#diff-6879702aacaf8f8d85f6cb0ddaee84b3d83937d9461679a1bc0a2699276964fdR1-R280): Added detailed documentation for all modal components, including architecture, features, best practices, and testing instructions. This provides developers with clear guidance on using and extending modal components.
* [`lib/widgets/modal/animated_modal_item.dart`](diffhunk://#diff …
> refactor: modal components & added README

- lib/features/ai/ui/unified_ai_popup_menu.dart
- pubspec.yaml
This pull request includes updates to improve the user interface and functionality of the speech recording features, as well as minor changes to the app's metadata. The most important changes include adjustments to the visual design of the VU meter, updates to tests to reflect these changes, and minor UI behavior tweaks.
* Adjusted the height of the `AnalogVuMeter` widget to maintain a 2.5:1 ratio instead of 2:1 (`lib/features/speech/ui/widgets/recording/analog_vu_meter.dart`).
* Updated the `VuMeterPainter` class to use a new `_needlePositionVertical` constant, reducing hardcoded values and improving maintainability (`lib/features/speech/ui/widgets/recording/vu_meter_painter.dart`) [[1]](diffhunk://#diff-b1f6ed1f4877f9079779a7eaa79fe203a5f511803937b84d78ae8fbdb2058c55R25-R31) …
> fix: duplicate inference runs
