matthiasn/lotti

wisely/assets/sqlite/create_outbound_db.sql
wisely/lib/blocs/audio/recorder_cubit.dart
wisely/lib/blocs/journal/journal_cubit.dart
wisely/lib/blocs/sync/imap_cubit.dart
wisely/lib/blocs/sync/imap_tools.dart
wisely/lib/blocs/sync/outbound_queue_cubit.dart
wisely/lib/blocs/sync/outbound_queue_db.dart
wisely/lib/blocs/sync/outbound_queue_state.dart
wisely/lib/classes/sync_message.dart
wisely/lib/main.dart
wisely/lib/utils/image_utils.dart
wisely/macos/Flutter/GeneratedPluginRegistrant.swift
wisely/pubspec.yaml

This PR adds an outbound queue for sync messages, which are persisted to the database first, and then only processed one by one when the device is connected to a network. It would be possible later to only upload large files when on wifi. For now, I want them always saved right away. Every 10 seconds the the queue cubit looks for an as yet unprocessed item, and on successful save updates the record status. This is retried ten times. On success, the next dispatch is started right away, same on every enqueuing. A mutex prevents running multiple at the same time, so that not worst case hundreds are started at the same time when importing a bunch of photos.

Sync outbound queue

---

package-lock.json
package.json
src/cljs/meins/electron/main/import.cljs
src/cljs/meins/electron/main/menu.cljs

This PR replaces separate selection of audio and image import directories with a single directory picker for the flutter container `Documents` directory.

Simplify import directory picker

---

wisely/lib/blocs/sync/imap_cubit.dart
wisely/pubspec.yaml

This PR increases the polling frequency and restarts the mailbox observation, which seems to be a bit unreliable at its current state.

poll for new messages every 30s, restart mailbox observation

---

wisely/lib/blocs/sync/imap_cubit.dart
wisely/lib/blocs/sync/outbound_queue_cubit.dart
wisely/pubspec.yaml

This PR reduces logging of the connection status, it will only do so when not connection, as successful connections are the norm and not worth cluttering Sentry.

only log connection status when not connected

---

wisely/lib/blocs/sync/outbound_queue_cubit.dart
wisely/pubspec.yaml

This PR fixes the reporting of the connection status. It's only worth reporting when there is no connection, whereas previously, the test was the opposite way to report when the status was not `ConnectivityResult.none`.

fix connection status reporting

---

wisely/Makefile
wisely/analysis_options.yaml
wisely/lib/classes/journal_entities.dart
wisely/lib/widgets/journal_list_item.dart

This PR introduces a simpler `JournalEntity` union type so that the sometimes cumbersome nesting can be removed. Requires including the output of the `freezed` generator in the Dart analysis - otherwise, missing implementation would not be reported at dev time.

Refactor journal entities

---

Makefile
package-lock.json
package.json
src/cljs/meins/electron/main/import/images.cljs

This PR removes the conversion to JPG within the import routine in meins - images now come as JPG anyway. HEIC was causing issues on desktop in release versions only - and in dev, was way, way slower to load than JPG. In terms of space usage, that's a shame, but proper support of the archive image format is more important.

Remove conversion on import

---

wisely/lib/blocs/sync/imap_out_cubit.dart
wisely/lib/blocs/sync/imap_tools.dart
wisely/lib/blocs/sync/outbound_queue_db.dart
wisely/pubspec.yaml

This PR fixes an issue with missing attachments. The problem was that on (relatively rare) retry, the `encryptedFilePath` was not kept but rather overwritten with `NULL`. On the next retry, sending was initiated for the entry itself, but not for the attachment.

Fix missing attachment on retry

---

wisely/lib/blocs/sync/imap_cubit.dart
wisely/pubspec.yaml

This PR disables restarting the folder watch for now until focusing on the IMAP client again. This will get rid of a bunch of errors reported by Sentry.

disable restarting folder watch

---

wisely/lib/blocs/journal/health_cubit.dart
wisely/pubspec.yaml

This PR limits health query end dates to be at most now (as in the query time). Going into the future doesn't make sense - there cannot be evidence for future events yet. This also makes the import into meins easier.

limit health queries: up to the query time

---

wisely/ios/Podfile.lock
wisely/lib/blocs/journal/persistence_cubit.dart
wisely/lib/blocs/sync/imap_cubit.dart
wisely/lib/blocs/sync/outbound_queue_cubit.dart
wisely/lib/classes/sync_message.dart
wisely/pubspec.lock
wisely/pubspec.yaml

This PR adds detecting the foreground/background status on mobile so that the polling for sync messages can be resumed when the app comes back into the foreground.

Resume polling after sleep

---

wisely/pubspec.lock
wisely/pubspec.yaml

This PR upgrades `freezed`. Unfortunately a breaking change in the serialization format. Hopefully, this will be a one time thing, now that the library has reached `1.0.0`.

upgrade freezed

---

wisely/pubspec.lock
wisely/pubspec.yaml

Version 3.3.1 returned weight as pounds, while still indicating a unit of kilograms. I created an [issue](https://github.com/cph-cachet/flutter-plugins/issues/460) in the health lib. For now, locking the version to `3.2.1` fixes the issue.

fix weight import by locking health lib to 3.2.1

---

package-lock.json
package.json
src/cljs/meins/electron/main/import/core.cljs
src/cljs/meins/electron/main/menu.cljs

This PR improves the UX when importing media entries from the flutter desktop version into meins (the ClojureScript desktop version) by setting the documents folder in the application container once, and then going forward allow importing with a single click in the menu, instead of having to find the respective folder time and again.

persist flutter container documents path

---

wisely/lib/main.dart
wisely/lib/pages/linear_survey_page.dart
wisely/lib/surveys/linear_survey_objects.dart
wisely/pubspec.lock
wisely/pubspec.yaml

This PR adds the [`research_package`](https://github.com/cph-cachet/research.package) library for building surveys/questionnaires. In this first step, there's a page with the CFQ11 as one example, but results are not handled yet. Also, page by page is a bit cumbersome to use, it takes too long to navigate from page to page. Subsequent PRs will improve the UX, and deal with persisting results.

Questionnaires

---

wisely/lib/widgets/buttons.dart
wisely/lib/widgets/editor_toolbar.dart
wisely/lib/widgets/editor_widget.dart
wisely/lib/widgets/entry_modal_widget.dart
wisely/pubspec.yaml

This PR removes the use of the `QuillToolbar.basic` and instead adds a custom toolbar, which will be more flexible going forward. This also fixes the issue with the line break between toolbar and the save button. Also, the toolbar is moved directly above the keyboard on mobile.

Custom editor toolbar

---

lotti/ios/Flutter/Base.xcconfig
lotti/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
lotti/macos/Runner/Configs/AppInfo.xcconfig
lotti/pubspec.yaml

This PR concludes the renaming effort.

rename PRODUCT_BUNDLE_IDENTIFIER in iOS and macOS

---

lotti/assets/sqlite/create_outbound_db.sql
lotti/lib/blocs/sync/imap/outbox_cubit.dart
lotti/lib/blocs/sync/outbound_queue_cubit.dart
lotti/lib/blocs/sync/outbound_queue_db.dart
lotti/lib/blocs/sync/outbound_queue_state.dart
lotti/lib/sync/encryption.dart
lotti/pubspec.yaml
lotti/test/encryption_string_test.dart

This PR changes the outbound queue to store plain text messages, and also postpone the file encryption to when the message will be sent. Thus, items can be inserted with a lot less CPU load, and will later only cause CPU load for one entry at a time. In terms of security, this does not make a difference, as `outbound.db` and `journal.db` enjoy the same level of protection. In case SQLite databases in this app will be encrypted, these two database files need to be treated the same way.

postpone encryption, enqueue unencrypted

---

lotti/lib/blocs/journal/persistence_db.dart
lotti/pubspec.yaml

This PR adds a check in the entry persistence from sync if entry to update actually exists. If not, it is created. This ensures that entries are created e.g. when previous create messages got lost in the sync mailbox, for whatever reasons, such as space limitations.

create new entry from update message when not existing

---

lotti/ios/Podfile.lock
lotti/lib/blocs/sync/imap/inbox_cubit.dart
lotti/lib/drift_db/database.dart
lotti/macos/Flutter/GeneratedPluginRegistrant.swift
lotti/macos/Podfile.lock
lotti/pubspec.lock
lotti/pubspec.yaml

This PR lays the foundation for checking and persisting conflicts (until manual resolution by the user). Drift is used as the ORM - it is getting too tedious to write the database mappers by hand. Also it is very attractive to benefit from more comprehensive compile time checks. Not functional yet, but merging anyway as the Drift foundation will be useful elsewhere.

basic drift database with conflicts table

---

lotti/lib/database/conversions.dart
lotti/lib/database/database.dart
lotti/pubspec.yaml

This PR changes the database layer to use an `upsert` instead of separate `insert` and `update` functions, which is simpler and viable since the update is also operating with the entire entity, instead of updating just a few fields.

refactor & upsert

---

package-lock.json
package.json
src/cljs/meins/electron/main/import/measurement.cljs

This PR prevents measurement entries from being imported without value.

Only import measurement when defined in mapping file

---

lotti/lib/widgets/journal/entry_tools.dart
lotti/lib/widgets/journal/journal_card.dart
lotti/lib/widgets/pages/add/new_measurement_page.dart
lotti/lib/widgets/pages/settings/measurables.dart
lotti/pubspec.yaml

This PR fixes parsing decimal numbers e.g. for German locale where the comma is used as the decimal separator.

Fix parsing numbers with comma as decimal separator

---

lotti/ios/Podfile.lock
lotti/macos/Podfile.lock
lotti/pubspec.lock
lotti/pubspec.yaml

This PR upgrades Flutter itself, plus a bunch of dependencies, some of which also needed upgrading because of the new Flutter version.

Upgrade Flutter to 2.8, upgrade dependencies

---

lotti/lib/blocs/sync/imap/inbox_cubit.dart
lotti/pubspec.yaml

This PR addresses the issue that photo attachments were not saved yet when the insert into the database happened, leading to black squares instead of thumbnails in the journal. This is fixed by awaiting the file persistence before database insert.

Finish saving photos before insert into database

---

lotti/lib/blocs/sync/outbox_cubit.dart
lotti/pubspec.yaml

This PR adds restarting polling of the outbox queue when a network status change is detected and this status is anything other than `none`. Also, the pending messages query now fetches multiple results so that the client reuse path can be reached.

Restart polling

---

lotti/ios/Flutter/Debug.xcconfig
lotti/lib/blocs/journal/persistence_cubit.dart
lotti/lib/blocs/sync/outbox_cubit.dart
lotti/lib/blocs/sync/outbox_state.dart
lotti/lib/database/conversions.dart
lotti/lib/database/database.dart
lotti/lib/database/database.drift
lotti/lib/sync/vector_clock.dart
lotti/lib/widgets/journal/editor_widget.dart
lotti/lib/widgets/journal/entry_detail_widget.dart
lotti/lib/widgets/journal/journal_card.dart
lotti/lib/widgets/pages/add/new_measurement_page.dart
lotti/lib/widgets/pages/settings/conflicts.dart
lotti/lib/widgets/pages/settings/outbox_monitor.dart
lotti/lib/widgets/pages/settings/settings_page.dart
lotti/pubspec.yaml

This PR adds a basic conflict resolution mechanism that shows the local version, with editable text, and the conflicting version from sync in read-only mode so that the user can manually merge the text. Then, when clicking the save button, a new version is created that takes the counter of the originating host into account and creates a new version that's strictly higher than both the local entry and the conflicting one. The conflict is then resolved automatically when such an entry is either persisted locally, or, on a remote host, received via sync.

Conflict resolution

---

lotti/lib/blocs/journal/persistence_cubit.dart
lotti/lib/classes/journal_entities.dart
lotti/lib/database/conversions.dart
lotti/lib/database/database.drift
lotti/lib/widgets/journal/entry_detail_widget.dart
lotti/lib/widgets/journal/entry_tools.dart
lotti/lib/widgets/journal/journal_card.dart
lotti/pubspec.yaml

This PR adds an entry footer with a delete button, which currently marks an entry as deleted without further confirmation by the user. There should be a confirmation prompt here. Entries aren't deleted completely - for that, either an `Empty Bin` or eviction after a certain amount of time need to be implemented, probably both.
Also, a toggle text button with the lat/lon coordinates for the display of the map is added and the map hidden by default.

Entry improvements

---

lotti/lib/main.dart
lotti/pubspec.yaml

This PR fixes an issue with the measurements definition page where the `intl` localizations were not initialized yet.

Initialize localizations

---

lotti/lib/classes/measurables.dart
lotti/lib/database/conversions.dart
lotti/lib/database/database.dart
lotti/lib/database/database.drift
lotti/lib/widgets/pages/settings/measurables.dart
lotti/pubspec.yaml

This PR adds a delete button for measurable types. Same as for journal entries, the database entities are marked as deleted, but not removed. Cleanup, e.g. empty bin, can be implemented later.

Add delete button for measurable types

---

lotti/lib/blocs/journal/persistence_cubit.dart
lotti/lib/database/database.dart
lotti/lib/main.dart
lotti/lib/theme.dart
lotti/lib/widgets/journal/entry_datetime_modal.dart
lotti/lib/widgets/journal/entry_detail_route.dart
lotti/lib/widgets/journal/entry_detail_widget.dart
lotti/lib/widgets/journal/journal_card.dart
lotti/lib/widgets/pages/add/new_measurement_page.dart
lotti/macos/Runner/Info.plist
lotti/pubspec.lock
lotti/pubspec.yaml

This PR adds a bottom modal/toaster for setting the start and end dates of the entry. This functionality is accessible by tapping the entry date in the footer of the details page.

Set entry start and end dates

---

lotti/lib/widgets/form_builder/cupertino_datepicker.dart
lotti/lib/widgets/pages/add/new_measurement_page.dart
lotti/pubspec.yaml

This PR uses a "fork" of `FormBuilderCupertinoDateTimePicker` by just copying the file from the [repo](https://github.com/danvick/flutter_form_builder/blob/master/packages/form_builder_extra_fields/lib/src/fields/form_builder_cupertino_date_time_picker.dart) and slightly modifying it. It wasn't possible to use the published version here unfortunately because of collisions in required dependencies. This then allows removing the very ugly `FormBuilderDateTimePicker`.

Cupertino date picker

---

lotti/lib/widgets/charts/measurement_barchart.dart
lotti/pubspec.yaml

This PR adapts the measurements bar chart with the aggregates by day to use the time series variant, which specifically comes with a much nicer legend.

Change bar chart to timeseries variant

---

package-lock.json
package.json
src/cljs/meins/electron/main/import/images.cljs
src/test/meins/shared/import_test.cljs
src/test/meins/shared/test-files/flagged_import.JPG.json
src/test/meins/shared/test-files/flagged_import_removed.JPG.json

This PR adds ignoring of photos flagged as `import`. Similar to #637 but for photos, not audio.

Ignore images as long as import flag is set

---

package.json
src/cljs/meins/electron/main/import/audio.cljs

This PR fixes audio import when encountering corrupt JSON file.

Catch errors so imports can proceed after corrupt file encountered

---

lotti/lib/blocs/audio/player_cubit.dart
lotti/lib/blocs/audio/recorder_cubit.dart
lotti/lib/blocs/journal/health_cubit.dart
lotti/lib/blocs/journal/persistence_cubit.dart
lotti/lib/blocs/sync/imap/imap_client.dart
lotti/lib/blocs/sync/imap/inbox_cubit.dart
lotti/lib/blocs/sync/imap/inbox_save_attachments.dart
lotti/lib/blocs/sync/imap/outbox_cubit.dart
lotti/lib/blocs/sync/imap/outbox_save_imap.dart
lotti/lib/blocs/sync/outbox_cubit.dart
lotti/lib/database/insights_db.dart
lotti/lib/database/insights_db.drift
lotti/lib/main.dart
lotti/lib/sync/encryption.dart
lotti/lib/widgets/pages/settings/insights_page.dart
lotti/lib/widgets/pages/settings/settings_page.dart
lotti/macos/Flutter/GeneratedPluginRegistrant.swift
lotti/pubspec.lock
lotti/pubspec.yaml

This PR removes Sentry and replaces it with an insights database on the device where events and exceptions can be logged, and later analyzed if necessary. The interface will need work, feels a bit cumbersome. Includes a very basic logging view widget, which updates automatically when new events are recorded. Will require filtering to become useful. Would be even more useful with sync for such log/insight event, so that events from mobile can be properly seen on desktop, potentially with a detail page that allows drilling into one or more attached data samples.

Log db & remove Sentry

---

lotti/lib/widgets/journal/journal_card.dart
lotti/pubspec.yaml

This PR limits the maximum image width in the journal image card, for example for panoramas.

Limit width to half the screen width in journal card

---

lotti/lib/widgets/journal/text_viewer_widget.dart
lotti/pubspec.lock
lotti/pubspec.yaml

This PR upgrades `flutter_quill` to the latest version. For now, this requires using a fork of `delta_markdown`, which can be changed back to a published version when [this PR](https://github.com/friebetill/delta_markdown/pull/5) is merged.

Upgrade flutter quill

---

lotti/lib/database/database.dart
lotti/lib/services/notification_service.dart
lotti/lib/widgets/bottom_nav/flagged_badge_icon.dart
lotti/lib/widgets/home.dart
lotti/pubspec.lock
lotti/pubspec.yaml

This PR improves badges and notifications for flagged entries that need annotation. Removes the notification on mobile, that's pointless as it won't receive anything in the background anyway. Then adds a badge in the bottom nav bar with the number of flagged items.

Improve badges notifications

---

lotti/lib/widgets/home.dart
lotti/pubspec.yaml

This PR removes the useless tooltips on desktop that show exactly the same as the text under each icon already shows. Incidentally, this also fixes the flicker on the badge when the mouse pointer enters or leaves the desktop app.

Remove tooltips in bottom nav bar - fixes flickering badge

---

lotti/pubspec.lock
lotti/pubspec.yaml

This PR pins the version of `flutter_health_fit` to make the build more predictable. This is a workaround until the library is published, also see [this issue](https://github.com/metaflowltd/flutter_health_fit/issues/40).

Pin version of flutter_health_fit

---

lotti/lib/blocs/audio/recorder_cubit.dart
lotti/pubspec.yaml

This PR changes the lifecycle of the audio recorder to create a new instance of `FlutterSoundRecorder` on ever recording. This should improve stability. Before, the `FlutterSoundRecorder` would sometimes become unresponsive after resuming from the background.

Create new audio recorder for every recording

---

lotti/lib/blocs/sync/imap/inbox_cubit.dart
lotti/lib/blocs/sync/outbox_cubit.dart
lotti/pubspec.yaml

This commit adds restarting the IMAP inbox listener on detected network connectivity changes when the status is anything other than `ConnectivityResult.none`.

Restart IMAP inbox on network reconnect

---

.github/workflows/flutter-linux-build.yml

This PR reduces the build time for the Flutter Linux build by about 2 minutes.

Remove apt-get update

---

lotti/lib/classes/journal_entities.dart
lotti/lib/classes/measurables.dart
lotti/lib/database/conversions.dart
lotti/lib/database/database.drift
lotti/pubspec.yaml

This PR adds a private flag for journal entries and measurement definitions which will make it easier to demonstrate the app while neither having to create (dull) test data nor having to reveal what is private. Setting the status and filtering will come in a subsequent PR.

Add private status in data model

---

lotti/lib/blocs/journal/persistence_cubit.dart
lotti/lib/database/database.dart
lotti/lib/database/database.drift
lotti/lib/theme.dart
lotti/lib/widgets/journal/entry_detail_widget.dart
lotti/lib/widgets/journal/journal_card.dart
lotti/lib/widgets/pages/journal_page.dart
lotti/pubspec.lock
lotti/pubspec.yaml

This PR adds controls for filtering by starred and private entries. The difference is that activating the starred filter shows only starred entries as opposed to all entries, starred and not starred. The private filter works the other way around. By default, private entries are hidden and are only shown when the filter is activated, in addition to the entries that are not private. The mechanics might still change, the UI will almost certainly change after gaining some experience with these controls.

Starred and private filter controls

---

lotti/lib/widgets/journal/entry_detail_header.dart
lotti/lib/widgets/journal/entry_detail_widget.dart
lotti/pubspec.yaml

This PR prevents overwriting the entry text when setting starred or private statuses.

Move entry details header to separate widget

---

lotti/lib/widgets/pages/journal_page.dart
lotti/pubspec.yaml

This PR adds hiding the private entries only switch when showing private data is disabled in the settings, and resets the displayed stream accordingly.

Hide private switch

---

lotti/lib/blocs/journal/persistence_cubit.dart
lotti/lib/widgets/pages/journal_page.dart
lotti/pubspec.yaml

This PR removes recording the geolocation when recording past measurements (longer than one minute ago), as we cannot know where the device actually was at the time.

Don't record geolocation when adding historic measurements

---

lotti/lib/widgets/pages/settings/outbox_monitor.dart
lotti/pubspec.yaml

This PR adds a simplistic way of retrying a sync outbox send by tapping on an errored item.

Reset outbox item via tap

---

lotti/lib/blocs/journal/journal_image_cubit.dart
lotti/pubspec.yaml

This PR changes the imports to use edited photos from the camera roll, not the original, so that the imports are rotated, cropped etc as expected. Also increase the number of photos that can be selected to 40.

Import edited files, increase number

---

lotti/lib/widgets/create/add_actions.dart
lotti/pubspec.yaml

This PR adds an expand button for showing all action buttons, but normally hide them to save space. The horizontal layout isn't ideal, radial might work better. [`radial_button`](https://pub.dev/packages/radial_button) could be an option.

Mobile plus button

---

lotti/lib/database/database.dart
lotti/pubspec.yaml

This PR adds a check to only sync new entries, not existing ones, e.g. from health.

Avoid creating sync entry for existing entity

---

package.json
src/cljs/meins/electron/main/menu.cljs

This PR disables screenshots in `meins` by default. This is not required any longer, since Lotti can now take screenshots.

Disable screenshots in meins by default

---

lotti/lib/widgets/journal/editor_widget.dart
lotti/pubspec.yaml

This PR removes the default height limitation for the entry editor, which does not serve a purpose any more, and makes scrolling long tex entries cumbersome because of the resulting nested scrolls.

Remove limit for editor maximum height by default

---

lotti/lib/blocs/audio/recorder_cubit.dart
lotti/lib/widgets/audio/audio_recorder.dart
lotti/lib/widgets/create/add_actions.dart
lotti/pubspec.yaml

This PR moves passing a linked entry from stopping the recording to starting the recording. This allows linking when stopping the recording from the new bottom recording indicator.

Pass linked entry on recording start, not stop

---

lotti/lib/database/database.dart
lotti/lib/services/notification_service.dart
lotti/pubspec.yaml

This PR adds a switch for desktop notifications in the form of a config flag. These notifications can become overwhelming when a lot of entries get imported from sync.

Add config flag for showing desktop notifications

---

lotti/integration_test/home_integration_test.dart
lotti/ios/Podfile.lock
lotti/lib/widgets/create/add_tag_actions.dart
lotti/lib/widgets/journal/entry_detail_widget.dart
lotti/lib/widgets/pages/settings/tags/tag_details.dart

This test adds an integration test for adding and deleting a tag. Needs more work in terms of structuring the tests. Also, unclear at this point how to enter text in `quill_editor` within a test. Also, tests crashing when using multiple `testWidgets`, hence only one that's way too long.

Add integration test for adding and deleting tag

---

lotti/lib/widgets/journal/linked_duration.dart
lotti/pubspec.yaml

This PR fixes the progress bar for tasks, which was previously clipped by a few pixels on the left when progress was at zero.

Fix clipped progress indicator

---

lotti/lib/logic/health_import.dart
lotti/lib/widgets/charts/dashboard_health_bmi_chart.dart
lotti/lib/widgets/charts/dashboard_health_chart.dart
lotti/lib/widgets/charts/dashboard_health_data.dart
lotti/pubspec.yaml

Add BMI chart as an additional health types. Requires at least one `HealthDataType.HEIGHT` recording to be present in Apple Health (should be the same on Android but not tested).

Add BMI chart

---

lotti/lib/widgets/journal/entry_detail_widget.dart
lotti/pubspec.yaml

This PR fixes saving changed text in a task, without having opened/edited title, estimate, or status.

Re-enable updating task text only

---

lotti/lib/widgets/charts/dashboard_health_bmi_chart.dart
lotti/lib/widgets/charts/dashboard_health_chart.dart
lotti/lib/widgets/charts/dashboard_measurables_chart.dart
lotti/lib/widgets/charts/dashboard_story_chart.dart
lotti/lib/widgets/charts/dashboard_survey_chart.dart
lotti/lib/widgets/charts/dashboard_workout_chart.dart
lotti/pubspec.yaml

This PR changes the rendering of charts to always be rendered, even when no existing data available. This makes initial data entry more convenient when starting with a new dashboard with new measurable types.

Render charts even when empty

---

lotti/lib/pages/home_page.dart
lotti/lib/widgets/misc/time_recording_indicator.dart
lotti/pubspec.yaml

This PR brings back the time recording indicator, rendered right above the bottom tab bar in the left corner. This widget is positioned there in a stack by the builder of the `AutoTabsScaffold`.

Time recording indicator

---

lotti/lib/logic/persistence_logic.dart
lotti/lib/pages/add/new_measurement_page.dart
lotti/lib/pages/create/create_measurement_page.dart
lotti/lib/routes/journal_routes.dart
lotti/lib/widgets/charts/dashboard_measurables_chart.dart
lotti/lib/widgets/create/add_actions.dart
lotti/pubspec.yaml

This PR changes new measurements from the radial action button to use `autoroute`. Currently unclear why this doesn't work when opening from dashboards.

Use measurement route in create action

---

lotti/lib/routes/settings_routes.dart
lotti/lib/widgets/journal/tags_search_widget.dart
lotti/lib/widgets/journal/tags_view_widget.dart
lotti/lib/widgets/journal/tags_widget.dart
lotti/pubspec.yaml

This PR improves tag management by allowing double tap on a tag chip to get to the tag definition directly, e.g. for changing a general tag to a story of person tag.

Navigate to tag definition from tag chip on entry details

---

lotti/lib/pages/settings/measurables/measurable_details_page.dart
lotti/pubspec.yaml

This PR fixes scroll on the measurables detail page, which broke when migrating to `auto_route`.

Make the measurables detail page scrollable again

---

lotti/lib/logic/health_import.dart
lotti/pubspec.yaml

This PR changes health imports to process data by day in ascending order so that a failure in the process would not interfere with subsequent delta fetches.

Change health import to sorted by day

---

lotti/lib/classes/entity_definitions.dart
lotti/lib/database/database.dart
lotti/lib/database/maintenance.dart
lotti/lib/pages/settings/maintenance_page.dart
lotti/pubspec.yaml

This PR adds a maintenance task for migrating measurements to have the data type ID assigned. In a subsequent step, the full data type can then be removed from measurement so that they are only stored in one place.

Measurement data migration

---

lotti/lib/database/conversions.dart
lotti/lib/database/database.drift
lotti/pubspec.yaml

This PR fixes the sort order for measurables after filling the unique name database column with the ID. Instead of sorting at database level, this can also happen in the mapper as there will be a limited number of measurables.

Fix ordering measurables

---

lotti/lib/logic/persistence_logic.dart
lotti/pubspec.yaml

This PR fixes the creation of tags for entries from sync in the case that they had tags assigned from creation, as is the case when story tags are copied over from a linked entry.

Fix creation of tagged entries from sync

---

lotti/lib/blocs/audio/recorder_cubit.dart
lotti/lib/widgets/audio/audio_recorder.dart
lotti/pubspec.yaml

This PR fixes a crash where pressing record in the UI again and then stop would crash the app. Instead, pressing record again stops the recording now and returns the user to the journal view.

Stop recording when pressing record again

---

lotti/lib/pages/settings/measurables/measurables_page.dart
lotti/pubspec.yaml

This PR adds search in `Settings > Measurables`, similar to dashboards and tags.

Add search in measurables page

---

lotti/lib/database/database.dart
lotti/lib/database/stream_helpers.dart
lotti/pubspec.yaml

This PR add a stateful stream filter function that compares the previous event on the stream with the latest, and filters those that are found equal using deep collection equality. This allows exactly once deliver on a stream instead of at least once previously, which lead to plenty of costly re-renders.

Add duplicate filter for db streams to ensure exactly once delivery

---

lotti/lib/widgets/charts/dashboard_health_chart.dart
lotti/lib/widgets/charts/dashboard_measurables_chart.dart
lotti/pubspec.yaml

This PR improves the data display in dashboards so zero bound display is only used where it makes sense.

Improve dashboard charts: zeroBound only where it makes sense

---

lotti/ios/Runner/Info.plist
lotti/macos/Runner/Info.plist
lotti/pubspec.yaml

This PR adds the supported localizations in both `ios/Info.plist` and `macos/Info.plist`.

Add localizations in iOS and macOS Info.plist files

---

lotti/lib/database/conversions.dart
lotti/lib/database/database.dart
lotti/lib/database/database.drift
lotti/lib/database/editor_db.dart
lotti/lib/database/editor_db.drift
lotti/lib/get_it.dart
lotti/lib/pages/journal/entry_details_page.dart
lotti/lib/services/editor_state_service.dart
lotti/lib/widgets/journal/editor_toolbar.dart
lotti/lib/widgets/journal/editor_tools.dart
lotti/lib/widgets/journal/editor_widget.dart
lotti/lib/widgets/journal/entry_detail_footer.dart
lotti/lib/widgets/journal/entry_detail_linked.dart
lotti/lib/widgets/journal/entry_details_widget.dart
lotti/pubspec.lock
lotti/pubspec.yaml

This PR changes the rendering of entries with linked entries (such as tasks) to show linked entries in edit mode. It introduces the `EditorStateService` which the editor now exclusively interacts with. This service tracks if an entry is unsaved, which so far is only used to create a stream for each open editor, with a boolean that is used to determine if the editor save button should displayed in red. Going forward, the tracked changes can also be used for temporarily persisting unsaved changes in entry text, e.g. so that they don't get lost if the user navigates elsewhere (or the application is closed),

Entry timeline

---

lotti/lib/services/editor_state_service.dart
lotti/lib/widgets/journal/entry_details_widget.dart
lotti/pubspec.yaml

This PR adds using a draft for the editor state initialization if a draft exists, or otherwise the persisted version. At this stage, drafts do not survive app restart. For that, the `EditorStateService` can be backed by database persistence later on.

Editor state store unsaved

---

lotti/lib/widgets/journal/duration_widget.dart
lotti/pubspec.yaml

This PR removes the display of the duration for image entries since they don't make sense. Photos are snapshots. If anything, the sensible duration of a photo is their exposure time, but knowing that is not very useful in this context.

Remove durations for photos - photos are snapshots

---

lotti/lib/get_it.dart
lotti/lib/main.dart
lotti/lib/pages/dashboards/dashboards_list_page.dart
lotti/lib/pages/home_page.dart
lotti/lib/pages/my_day.dart
lotti/lib/pages/settings/advanced_settings_page.dart
lotti/lib/pages/settings/dashboards/dashboard_details_page.dart
lotti/lib/pages/settings/dev_playground_page.dart
lotti/lib/pages/settings/logging_page.dart
lotti/lib/pages/settings/settings_page.dart
lotti/lib/pages/tasks_page.dart
lotti/lib/routes/observer.dart
lotti/lib/routes/settings_routes.dart
lotti/lib/services/nav_service.dart
lotti/lib/widgets/charts/dashboard_survey_chart.dart
lotti/lib/widgets/create/add_actions.dart
lotti/lib/widgets/journal/journal_card.dart
lotti/lib/widgets/journal/tags_widget.dart
lotti/lib/widgets/misc/time_recording_indicator.dart
lotti/pubspec.yaml

This PR adds a first, rather naive, attempt at persisting the latest route and restoring that on next application start, such as after a potentially automatic update. No history is persisted yet. When going back from whatever the last route was, the user will land on the journal page. This can be improved later.

Navigation persistence  #1

---

lotti/lib/widgets/journal/duration_widget.dart
lotti/pubspec.yaml

This reverts commit 514e004b306367a151f7b6cc5071f4a1a5ccebd0. The durations on images are useful, after all.

Revert "Remove durations for photos - photos are snapshots"

---

lotti/lib/sync/inbox_service.dart
lotti/lib/sync/outbox.dart
lotti/pubspec.yaml

This PR disables sync when it is not configured, saving CPU cycles and battery for useless periodic function calls.

Disable sync when not configured

---

lotti/CHANGELOG.md
lotti/Makefile
lotti/lib/pages/create/create_text_entry_page.dart
lotti/lib/widgets/journal/editor/editor_widget.dart
lotti/lib/widgets/tasks/task_form.dart
lotti/pubspec.yaml

This PR changes the text editor autofocus default to false for improved scrolling in tasks.

Remove autofocus from task editor

---

.buildkite/pipeline.yml
Makefile
macos/fastlane/Fastfile
pubspec.yaml

This PR adds a retry mechanism for the fastlane upload for macOS, as that has failed multiple times before because apparently, `iTMSTransporter` cannot handle concurrent uploads to TestFlight.

Add upload retry for macOS build for iTMSTransporter failures

---

CHANGELOG.md
Makefile
ios/fastlane/Fastfile
pubspec.yaml

This PR adds TestFlight upload retries for the iOS build, similar to #922 for macOS.

Add upload retry for iOS build for iTMSTransporter failures

---

.buildkite/pipeline.yml
README.md
pubspec.yaml

This PR adds the publication of prereleases of the macOS desktop version on GitHub Releases.

Publish macOS prerelease on GitHub Releases via Buildkite

---

.buildkite/pipeline.yml
macos/Podfile.lock
pubspec.yaml

This PR adds a workaround for an `Rsync` warning about vanished files, which is inconsequential here but returns exit code **`24`** and is therefore interpreted as a failure.

CI: soft fail on exit code 24

---

CHANGELOG.md
lib/widgets/journal/entry_details_widget.dart
pubspec.yaml

This PR adds a workaround for #939 by showing audio recordings as journal cards that navigate to a detail page from which the audio can be played. This is not ideal but at least it works at all.

Workaround for multiple audio player in linked entries list

---

CHANGELOG.md
pubspec.lock
pubspec.yaml

This PR upgrades the `enough_mail` library after the release of https://github.com/Enough-Software/enough_mail/pull/181 so that it is no longer required to use a fork. This involves overrides for the time being, probably until the next Flutter version.

Upgrade enough_mail

---

CHANGELOG.md
lib/pages/dashboards/dashboard_page.dart
lib/pages/home_page.dart
lib/widgets/misc/app_bar_version.dart
lib/widgets/misc/dashboard_app_bar.dart
pubspec.lock
pubspec.yaml

This PR adds hiding the bottom navigation bar on dashboard detail pages so that more data can be shown at the same time, and moves the dashboard title into the app bar.

Hide bottom nav on dashboard detail

---

CHANGELOG.md
lib/logic/persistence_logic.dart
lib/utils/screenshots.dart
lib/widgets/create/add_actions.dart
pubspec.yaml

This PR changes screenshots by postponing fetching a geolocation for the screenshot entry. This much improves screenshot delay when the location is not in the cache.

Postpone obtaining geolocation for faster screenshots

---

lib/main.dart
lib/services/nav_service.dart
lib/widgets/misc/desktop_menu.dart
pubspec.yaml

This PR adds a basic menu on macOS, for now allowing to create new tasks and entries via the menu, and via key shortcuts `CMD-N` for a new entry and `CMD-T` for a new task.

Add desktop menu for macOS

---

CHANGELOG.md
ios/Runner/Info.plist
pubspec.yaml

This PR disables file browsing on iOS so that files no longer show up in the Files app.

Disable file browsing on iOS

---

.buildkite/pipeline.yml
.github/workflows/flutter-linux-build.yml
.github/workflows/flutter-linux-release.yml
.github/workflows/flutter-test.yml
.github/workflows/flutter-testflight.yml
.github/workflows/flutter-windows-build.yml
CHANGELOG.md
ios/Podfile.lock
lib/logic/health_import.dart
pubspec.lock
pubspec.yaml

This PR fixes the Android build as reported in #972 by removing the offending library, [`flutter_health_fit`](https://github.com/metaflowltd/flutter_health_fit). The cumulative imports of steps and flights of stairs are replaced with functionality from [`health`](https://pub.dev/packages/health), which is preferable anyway since it's properly released. 
Flights of stairs use a [fork](https://github.com/matthiasn/flutter-plugins) of the library, will create a PR for that later after some deduplication. Cleanup and deduplication should also happen in the imports in a later refactoring.

Fix Android build by removing flutter_health_fit

---

CHANGELOG.md
lib/logic/health_import.dart
pubspec.yaml

This PR changes activity imports so that only start dates up until the query time take place.

Prevent activity import for dateFrom in the future

---

CHANGELOG.md
lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/pages/settings/dashboards/dashboard_details_page.dart
lib/widgets/app_bar/dashboard_app_bar.dart
lib/widgets/app_bar/task_app_bar.dart
pubspec.yaml

This PR adapts dashboard and task headers to still render a modified app bar when the underlying item had been deleted so that the user can still navigate elsewhere instead of being stuck when the app tries to restore the last active route.

Dashboard not found header

---

CHANGELOG.md
lib/pages/journal_page.dart
lib/pages/settings/dashboards/dashboards_page.dart
lib/pages/settings/measurables/measurables_page.dart
lib/pages/settings/tags/tags_page.dart
lib/pages/tasks_page.dart
pubspec.yaml

This PR fixes #995 by setting the search hints to normal font weight, as apparently, the used font does not contain glyphs for the `ă` character in weight `w300`.

Fix font weight in search hints for Romanian, see #995

---

.github/workflows/flutter-windows-build.yml

This PR fixes builds on Windows GitHub Actions, following the instructions from https://github.com/actions/virtual-environments/issues/1177.

Enable symlinks in Windows GitHub Action

---

CHANGELOG.md
lib/pages/home_page.dart
lib/pages/journal_page.dart
lib/pages/tasks_page.dart
lib/widgets/app_bar/empty_app_bar.dart
pubspec.lock
pubspec.yaml

This PR improves the filtering on the Journal and Tasks pages. On the Tasks page, now open, groomed, and in-progress tasks are shown by default, since otherwise newly created tasks didn't show up, which from feedback was unintuitive. In a subsequent PR, the search bar should permanently show the choice chips to make the possible interactions more obvious.
In the Journal page, all entries are now shown by default, and the useless and space-consuming header is removed. In a subsequent PR, the search bar widget can be made bigger to permanently show the choice chips, for similar reasons as for the tasks.

Improve filtering on Journal and Task pages

---

CHANGELOG.md
lib/pages/journal_page.dart
pubspec.yaml

This PR improves the Journal search bar widget by permanently showing the choice chips and switches, instead of only showing them when tapping the search bar.

Move choice chips and switches into persistent header on Journal page

---

CHANGELOG.md
Makefile
pubspec.yaml

This PR adds a make task for tagging and pushing using the version from `pubspec.yaml`.

Add make task for tag from version in pubspec.yaml and push

---

CHANGELOG.md
lib/utils/screenshots.dart
pubspec.yaml

This PR changes the image file format for screenshots to JPG since PNG files can become very large on high resolution screens.

Save screenshots on desktop as JPG

---

CHANGELOG.md
lib/sync/inbox_service.dart
pubspec.yaml

This PR fixes #1032 by ignoring messages that do not fit the expected subject line of the alphanumeric host ID hash, followed by colon, followed by one or more digits: `[a-z0-9]{40}:[0-9]+`.

Ignore messages not matching expected subject

---

CHANGELOG.md
lib/logic/health_import.dart
pubspec.yaml

Fixes #1035 by preventing the import of health data on desktop platforms, where the native functionality doesn't exist.

Prevent fetching health data on mobile

---

CHANGELOG.md
lib/database/conversions.dart
lib/database/database.drift
pubspec.yaml

This PR fixes an issue where previously, dashboard items, once deleted, could not be created again, as the name column has a unique constraint. The field is not used anyway, so just using the ID here, and not setting the constraint on new databases.

Fix recreating deleted dashboard with same name

---

CHANGELOG.md
lib/database/database.dart
lib/database/database.drift
lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/pages/settings/maintenance_page.dart
pubspec.yaml

This PR adds a maintenance task for purging previously deleted items of all kinds (dashboards, tags, measurables, journal entries).

Add maintenance task for purging deleted items

---

CHANGELOG.md
lib/l10n/app_en.arb
lib/pages/settings/maintenance_page.dart
lib/services/sync_config_service.dart
lib/sync/inbox_service.dart
pubspec.yaml

This PR fixes processing of valid sync messages. Previously, the criteria for detecting valid sync messages were too strict and ignored sync of entity definitions since they currently don't have a vector clock for detecting concurrent edits, which arguably is not as important as for text entries. Also adds a maintenance task for reprocessing previously ignored sync messages. This maintenance task is available under `Settings > Advanced Settings > Maintenance > Reprocess sync messages`

Fix dashboard sync

---

CHANGELOG.md
lib/pages/dashboards/dashboards_list_page.dart
lib/pages/settings/dashboards/dashboards_page.dart
lib/utils/sort.dart
pubspec.yaml

This PR fixes sorting dashboards alphabetically. Previously, the sort order was determined by the name field in the database.

Sort dashboards alphabetically

---

CHANGELOG.md
lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/pages/create/create_measurement_page.dart
lib/pages/settings/measurables/measurables_page.dart
lib/routes/settings_routes.dart
lib/widgets/journal/entry_details/workout_summary.dart
pubspec.yaml

This PR improves first-time user experience for new measurements when no measurable data types are defined by adding a link to create measurable data type.
Resolves #1023

Improve first-time user experience for measurables

---

.github/workflows/flutter-linux-build.yml
.github/workflows/flutter-linux-release.yml
.github/workflows/flutter-test.yml
.github/workflows/flutter-testflight.yml
.github/workflows/flutter-windows-build.yml
CHANGELOG.md
lib/location.dart
lib/logic/persistence_logic.dart
pubspec.yaml

This PR fixes retrieving the geolocation for an entry on Linux using `GeoClueManager` and `GeoClueClient`, adapted from this [example](https://github.com/canonical/geoclue.dart/blob/main/example/client.dart).
Resolves #664

Fix entry location on Linux

---

CHANGELOG.md
lib/utils/timezone.dart
pubspec.yaml

This PR fixes #665 by reading the timezone name from `/etc/timezone` on Linux.

Read timezone name from /etc/timezone on Linux

---

CHANGELOG.md
lib/l10n/app_en.arb
lib/l10n/app_fr.arb
lib/pages/create/create_measurement_page.dart
lib/pages/dashboards/dashboard_page.dart
lib/pages/dashboards/dashboards_list_page.dart
lib/pages/home_page.dart
lib/pages/journal/entry_details_page.dart
lib/pages/settings/advanced_settings_page.dart
lib/pages/settings/conflicts.dart
lib/pages/settings/dashboards/dashboard_details_page.dart
lib/pages/settings/dashboards/dashboards_page.dart
lib/pages/settings/dev_playground_page.dart
lib/pages/settings/flags_page.dart
lib/pages/settings/health_import_page.dart
lib/pages/settings/logging_page.dart
lib/pages/settings/maintenance_page.dart
lib/pages/settings/measurables/measurable_details_page.dart
lib/pages/settings/measurables/measurables_page.dart
lib/pages/settings/outbox_monitor.dart
lib/pages/settings/settings_page.dart
lib/pages/settings/sync/sync_assistant_page.dart
lib/pages/settings/tags/tag_edit_page.dart
lib/pages/settings/tags/tags_page.dart
lib/theme.dart
lib/widgets/app_bar/title_app_bar.dart
pubspec.yaml

This PR adds indicating unsaved changes in dashboards, measurables, tags by moving the save button to the actions section in the app bar, and only displaying it (in red) when there are unsaved changes.
Huge PR because of requiring to move the app bars into individual scaffolds, which wrap large widgets.
Resolves #1009

Indicate unsaved changes for dashboards, measurables, tags

---

CHANGELOG.md
lib/widgets/journal/journal_card.dart
pubspec.yaml

This PR fixes empty text in image entries rendered as a grey box in release mode. The underlying cause was using an `Expanded` widget in the wrong place.

Fix empty text rendered as grey box in release mode

---

CHANGELOG.md
lib/widgets/journal/journal_card.dart
pubspec.yaml

This PR removes the useless leading insight icon in measurement cards.

Remove leading insights icon in measurement card

---

CHANGELOG.md
lib/pages/create/create_measurement_page.dart
lib/routes/dashboard_routes.dart
lib/routes/journal_routes.dart
lib/widgets/charts/dashboard_measurables_chart.dart
lib/widgets/journal/entry_datetime_modal.dart
pubspec.yaml

This PR fixes the navigation when creating a new measurement from the dashboard, where previously saving a measurement would not take the user back to the dashboard but its parent, the dashboard list. Also fixes entry datetime modal where save would also close the entry, not only the modal. The error was introduced by using the router from `getIt` for better testability.

Fix navigation 

---

.buildkite/pipeline.yml
pubspec.yaml

This PR adds `--asc-provider` in the call to `altool`, now required because of multiple teams.

Fix DMG signing in pipeline

---

lib/database/common.dart
lib/database/database.dart
lib/database/maintenance.dart
lib/pages/home_page.dart
lib/pages/journal_page.dart
lib/pages/settings/flags_page.dart
lib/pages/settings/maintenance_page.dart
lib/pages/tasks_page.dart
pubspec.yaml
test/database/database_test.dart

This PR adds a new stream function for watching active config flags, which makes it easier to use multiple flags in any one page. Previously, nested StreamControllers would have been required to achieve the same.

Add stream for watching active config flags

---

CHANGELOG.md
lib/pages/settings/dashboards/dashboard_definition_page.dart
pubspec.yaml

This PR fixes a glitch where dashboards could not be saved after only reordering charts but nothing else.
Fixes #1135

Fix save button not appering in dashboard config - fixes #1135

---

CHANGELOG.md
lib/pages/home_page.dart
pubspec.yaml

This PR changes the bottom navigation bar to be visible on the dashboard details page.
Resolves #1133.

Show bottom navigation bar on dashboard page

---

CHANGELOG.md
lib/pages/dashboards/dashboard_page.dart
lib/pages/dashboards/dashboards_list_page.dart
lib/widgets/app_bar/dashboard_app_bar.dart
pubspec.yaml
test/journal_test_data/test_data.dart
test/pages/settings/dashboards/dashboard_definition_page_test.dart

This PR changes the behavior of the dashboards tab when there is only a single defined dashboard. In that case, that dashboard will be shown, instead of the dashboards list with a single entry.

Show dashboard directly instead of list if only one is defined

---

.buildkite/test_only_pipeline.yml
.github/workflows/flutter-analyze.yml
Makefile

This PR moves the `flutter analyze` step into a separate GitHb Actions for better parallelization.

CI: move analyze step to separate GitHub Action

---

lib/widgets/charts/utils.dart
lib/widgets/journal/duration_widget.dart
pubspec.lock
pubspec.yaml

This PR fixes the time chart to include entries of today by setting end of range to beginning of tomorrow, instead of end of today.

Time chart fix

---

CHANGELOG.md
lib/blocs/sync/sync_config_cubit.dart
lib/services/sync_config_service.dart
lib/services/vector_clock_service.dart
lib/sync/inbox/inbox_service.dart
lib/sync/utils.dart
pubspec.yaml
test/blocs/sync/sync_config_cubit_test.dart
test/logic/persistence_logic_test.dart
test/mocks/sync_config_test_mocks.dart
test/widgets/sync/imap_config_mobile_test.dart

This PR fixes an issue where the last read IMAP UID would reset itself and the sync would start again from the oldest sync message in the mailbox. Thanks to the vector clock variant, this did not cause issues with data integrity, but did cause delays in sync, plus high CPU utilization.

Fix sync client last read UID resetting itself

---

lib/sync/inbox/inbox_service.dart
pubspec.yaml

This PR changes the Sync inbox to fetch every 15 seconds in any case, even when the observing client believes it is still online to fix sync messages not being picked up after resuming the app. Workaround, needs further investigation.

Fetch every 15 seconds in all cases

---

CHANGELOG.md
Makefile
pubspec.lock
pubspec.yaml

This PR fixes mysterious errors in the build such as
```
/usr/local/Caskroom/flutter/3.0.5/flutter/packages/flutter/lib/src/semantics/semantics.dart:3768:11: Error: 'VoidCallback' isn't a type.
final VoidCallback? callback = _customSemanticsActions[action];
^^^^^^^^^^^^
/usr/local/Caskroom/flutter/3.0.5/flutter/packages/flutter/lib/src/semantics/semantics.dart:4017:36: Error: The getter 'SemanticsFlag' isn't defined for the class 'SemanticsConfiguration'.
- 'SemanticsConfiguration' is from 'package:flutter/src/semantics/semantics.dart' ('/usr/local/Caskroom/flutter/3.0.5/flutter/packages/flutter/lib/src/semantics/semantics.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'SemanticsFlag'.
bool get scopesRoute => …
```

Fix build by removing sort_arb_files task

---

CHANGELOG.md
ios/Podfile.lock
lib/blocs/journal/entry_cubit.dart
lib/widgets/journal/duration_widget.dart
lib/widgets/journal/entry_datetime_modal.dart
lib/widgets/journal/entry_details/delete_icon_widget.dart
lib/widgets/journal/entry_details/entry_detail_footer.dart
lib/widgets/journal/entry_details/entry_detail_header.dart
lib/widgets/journal/tags_widget.dart
lib/widgets/misc/desktop_menu.dart
pubspec.lock
pubspec.yaml
test/blocs/journal/entry_cubit_test.dart
test/widgets/journal/entry_details/workout_summary_test.dart

This PR decouples widgets and persistence logic. Any interactions with the latter now go through `EntryCubit`.

Refactor: decouple widgets from persistence logic

---

CHANGELOG.md
lib/widgets/journal/entry_details/delete_icon_widget.dart
lib/widgets/journal/entry_details/entry_datetime_widget.dart
lib/widgets/journal/entry_details/entry_detail_footer.dart
lib/widgets/journal/entry_details/entry_detail_header.dart
lib/widgets/journal/entry_details/share_button_widget.dart
lib/widgets/journal/entry_details_widget.dart
pubspec.yaml
test/widgets/journal/entry_details/entry_datetime_widget_test.dart
test/widgets/journal/entry_details/entry_detail_footer_test.dart
test/widgets/journal/entry_details/entry_detail_header_test.dart

This PR improves the layout of entry details by moving the entry date to the footer so that there is enough space in the header for the save button even on small screens. Delete and share icons move to the other icons at the top.

Rearrange entry details layout

---

lib/widgets/app_bar/task_app_bar.dart
lib/widgets/journal/entry_details/entry_datetime_modal.dart
pubspec.yaml
test/pages/journal/entry_detail_page_test.dart
test/widgets/journal/entry_details/entry_datetime_widget_test.dart

Previously, changing either the start or end date of an entry and then saving would close the entry itself, not just the modal. This PR fixes that.

Close datetime modal on save

---

CHANGELOG.md
lib/logic/create/create_entry.dart
lib/pages/create/create_measurement_page.dart
lib/pages/dashboards/dashboard_page.dart
lib/pages/dashboards/dashboards_list_page.dart
lib/pages/home_page.dart
lib/pages/journal/entry_details_page.dart
lib/pages/settings/advanced_settings_page.dart
lib/pages/settings/flags_page.dart
lib/pages/settings/logging_page.dart
lib/pages/settings/measurables/measurables_page.dart
lib/pages/settings/settings_page.dart
lib/pages/tasks/tasks_page.dart
lib/services/nav_service.dart
lib/services/notification_service.dart
lib/widgets/app_bar/dashboards_app_bar.dart
lib/widgets/charts/dashboard_measurables_chart.dart
lib/widgets/create/add_actions.dart
lib/widgets/journal/journal_card.dart
lib/widgets/journal/tags/tag_widget.dart
lib/widgets/misc/time_recording_indicator.dart
pubspec.lock
pubspec.yaml
test/widgets/charts/dashboard_measurables_test.dart

This PR changes the bottom navigation bar to use [`salomon_bottom_bar`](https://pub.dev/packages/salomon_bottom_bar) which looks more modern and takes up less vertical space. The PR also fixes the transition between pages by using `navigateNamed` instead of `pushNamed`. Previously, the bottom bar would slide in and out of the page with the subpage, whereas now, it stays in place as expected.

Use salomon_bottom_bar

---

CHANGELOG.md
lib/surveys/run_surveys.dart
lib/widgets/charts/dashboard_health_bmi_chart.dart
lib/widgets/charts/dashboard_health_bp_chart.dart
lib/widgets/charts/dashboard_health_chart.dart
lib/widgets/charts/dashboard_measurables_chart.dart
lib/widgets/charts/dashboard_survey_chart.dart
lib/widgets/charts/dashboard_workout_chart.dart
pubspec.lock
pubspec.yaml

This PR makes filling surveys more intuitive by adding a more obvious plus icon in the dashboard, instead of having to double tab.

Add surveys with plus icon in dashboard, not double tap

---

CHANGELOG.md
lib/blocs/journal/entry_cubit.dart
lib/logic/persistence_logic.dart
pubspec.lock
pubspec.yaml
test/logic/persistence_logic_test.dart

This PR changes assigning a story tag to assign the story to linked comments as well, e.g. for having a story assigned to a task assigned to time recordings on that task, too.

Assign story to comments

---

CHANGELOG.md
lib/widgets/journal/tags/tag_add.dart
lib/widgets/journal/tags/tags_modal.dart
lib/widgets/settings/settings_card.dart
pubspec.lock
pubspec.yaml
test/widgets/journal/tags/tags_modal_widget_test.dart

This PR fixes an issue when assigning stories on mobile where tapping into the search field would lead to the modal being dismissed. For now, behavior on desktop stays as it was, where clicking outside the modal would close it, whereas now on mobile, it needs to be dragged down. Fine for now, this whole interaction is not ideal and likely to change soon.

Fix story assignment on mobile

---

CHANGELOG.md
lib/logic/health_import.dart
lib/pages/settings/health_import_page.dart
lib/widgets/charts/dashboard_health_config.dart
lib/widgets/charts/dashboard_health_data.dart
lib/widgets/charts/dashboard_measurables_chart.dart
lib/widgets/charts/utils.dart
pubspec.lock
pubspec.yaml

This PR fixes sleep import by adding additional sleep types `CORE`, `DEEP`, and `REM`. Sleep import broke after upgrading to iOS 16 in combination with watchOS 9, or rather the now deprecated generic type `ASLEEP` is not retrieved any longer. In addition to recording the specific sleep type, the generic type is recorded as well for backwards comparability.

Add sleep types CORE, DEEP, REM

---

CHANGELOG.md
lib/database/database.dart
lib/database/database.drift
lib/get_it.dart
pubspec.yaml

For some reason the app startup only fails on desktop with an error the first index, idx_journal_created_at, exists already. Not a problem on mobile, or with new database files.

Remove index creation from Drift file

---

CHANGELOG.md
lib/database/database.dart
lib/database/database.drift
lib/database/journal_db/config_flags.dart
lib/get_it.dart
lib/widgets/charts/dashboard_habits_chart.dart
pubspec.yaml
test/database/database_test.dart
test/logic/persistence_logic_test.dart

This PR brings back the creation of indices by changing the `onCreate` of the migration strategy to run async. Follow up to #1235

Bring back index creation in journal database

---

CHANGELOG.md
lib/blocs/habits/habits_cubit.dart
lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/pages/settings/habits/habit_details_page.dart
pubspec.yaml
test/pages/settings/habits/habit_details_page_test.dart

This PR simplifies enabling and disabling habits. A habit starts out as active, and can be set inactive by toggling a switch, and vice versa. Previously, a date range in which the habit was active needed to be defined, with at least the `activeFrom` field required, which proved to complicated without adding benefits.

Habit active toggle

---

CHANGELOG.md
lib/widgets/audio/audio_player.dart
pubspec.yaml
test/widgets/audio/audio_player_test.dart

This PR improves the audio playback widget by allowing to toggle through different speeds instead of requiring multiple buttons.

Audio playback speed toggle instead of individual icon button

---

.github/workflows/flutter-analyze.yml
.github/workflows/flutter-linux-build.yml
.github/workflows/flutter-linux-release.yml
.github/workflows/flutter-test.yml
.github/workflows/flutter-testflight.yml
.github/workflows/flutter-windows-build.yml
CHANGELOG.md
lib/classes/entity_definitions.dart
lib/pages/settings/habits/habit_details_page.dart
lib/widgets/settings/habits/habit_autocomplete_widget.dart
pubspec.lock
pubspec.yaml
test/classes/entity_definitions_test.dart

This PR refines the data structure for defining habit autocomplete rules by allowing multiple child rules within rules with multiple children such as AND and OR, effectively using them like a prefix notation as used in a LISP. 
Also starts a UI component for visualizing habit auto completion rules, which will be used in a next step.

Habit autocomplete definition data structure and visualization

---

CHANGELOG.md
lib/pages/settings/habits/habit_details_page.dart
pubspec.yaml

This PR fixes the display of the expected date from which on success is expected for a particular habit (and show red otherwise). Before, this date could be defined but was not shown again in settings.

Show expected habit success when defined

---

CHANGELOG.md
lib/blocs/habits/habits_cubit.dart
lib/blocs/habits/habits_state.dart
lib/pages/habits/habits_page.dart
pubspec.yaml

This PR adds a progress bar on the habits page showing the percentage of habits to checked off today, where both success and skip constitute a completion. The idea behind skip is that I skip a habit when outside circumstances do not allow me to complete a habit. Example: let's say I want to establish a habit of playing ping pong. When I could have done it but didn't, it's a **fail**. But when outside circumstances didn't allow it, maybe because I couldn't find someone to play with, or there's too much snow on the ping pong table, it's a **skip** that doesn't break a habit chain.

Add habit progress bar

---

CHANGELOG.md
lib/blocs/habits/habits_cubit.dart
lib/pages/create/create_measurement_dialog.dart
lib/pages/dashboards/dashboard_page.dart
lib/pages/habits/habits_page.dart
lib/themes/theme.dart
lib/widgets/charts/habits/habit_completion_rate_chart.dart
lib/widgets/misc/timespan_segmented_control.dart
pubspec.yaml

- Remove autofocus on measurement value field
- Unify segmented time span controls on dashboard and habit pages
- Increase analyzed habit completion time span to 90 days
- Show date in habit completion rate chart tooltip

Habit completion chart improvements

---

CHANGELOG.md
lib/l10n/app_en.arb
lib/widgets/journal/editor/editor_toolbar.dart
lib/widgets/journal/editor/editor_widget.dart
lib/widgets/journal/entry_detail_linked.dart
lib/widgets/journal/entry_details_widget.dart
pubspec.yaml

This PR improves the UX when unlinking entries, e.g. from a task. Before, a Dismissible was used but that interfered with text selection on mobile. Now, an icon in the editor toolbar is used instead, next to link-to and link-from icons. The whole UX around entry linking needs more thought, but this removes the biggest annoyance at the moment.

Unlink icon in editor toolbar instead of using Dismissable

---

.github/workflows/flutter-analyze.yml
.github/workflows/flutter-linux-build.yml
.github/workflows/flutter-linux-release.yml
.github/workflows/flutter-test.yml
.github/workflows/flutter-testflight.yml
.github/workflows/flutter-windows-build.yml
CHANGELOG.md
lib/themes/theme.dart
lib/widgets/journal/entry_detail_linked.dart
lib/widgets/journal/entry_detail_linked_from.dart
lib/widgets/journal/entry_details/entry_detail_header.dart
lib/widgets/journal/entry_details_widget.dart
lib/widgets/journal/tags/tags_view_widget.dart
pubspec.lock
pubspec.yaml

This PR moves the header down below images in image entries so that the SAVE button stays within the visible field of view. Also fixes some bugs.

Change header position for image entries

---

CHANGELOG.md
lib/blocs/journal/entry_cubit.dart
lib/blocs/journal/entry_state.dart
lib/widgets/journal/editor/editor_widget.dart
lib/widgets/journal/entry_details/entry_detail_header.dart
pubspec.yaml
test/blocs/journal/entry_cubit_test.dart
test/widgets/journal/entry_details/delete_icon_widget_test.dart
test/widgets/journal/entry_details/entry_datetime_widget_test.dart
test/widgets/journal/entry_details/entry_detail_footer_test.dart
test/widgets/journal/entry_details/entry_detail_header_test.dart
test/widgets/journal/entry_details/share_button_widget_test.dart
test/widgets/journal/tags/tag_add_test.dart
test/widgets/journal/tags/tags_modal_widget_test.dart

This PR removes the useless text editor show/hide toggle icon, which turned out to be not useful, and if anything annoying and/or confusing.

Remove useless entry text toggle icon

---

CHANGELOG.md
lib/blocs/habits/habits_cubit.dart
lib/blocs/habits/habits_state.dart
lib/pages/habits/habits_page.dart
lib/themes/theme.dart
lib/widgets/charts/habits/habit_completion_rate_chart.dart
pubspec.yaml

This PR introduces a stacked representation of habit success, skipped, and failed. The red line represents the total of tracked habits (success, skipped, and fail) whereas the area above up to 100% represents the habits that failed implicitly, by not being tracked at all. Tracked failures are preferable to implicit habits because from a behavioural perspective, they at least acknowledge failure, presenting a chance to form implementation intentions (should be tracked). Code needs refactoring at some point, this was the easiest to transform from single line chart per completion type. But for experimenting with improving overall success rate, this will do.
An alternative could be using individual line charts as described [here](https://everydayanalytics.ca/2014/08/stacked-area-graphs-are-not …

Stacked habit success chart

---

CHANGELOG.md
lib/blocs/habits/habits_cubit.dart
lib/blocs/habits/habits_state.dart
lib/widgets/charts/habits/habit_completion_rate_chart.dart
lib/widgets/habits/habit_page_app_bar.dart
pubspec.lock
pubspec.yaml

This PR improves the habits chart by rendering the info for a selected day (tap/horizontal drag on mobile, hover on desktop) at the top of the chart, as the previous approach with the tooltip was pretty useless on mobile.

Improved habit chart info

---

CHANGELOG.md
lib/beamer/locations/journal_location.dart
lib/blocs/journal/journal_page_cubit.dart
lib/blocs/journal/journal_page_state.dart
lib/l10n/app_de.arb
lib/pages/journal/infinite_journal_page.dart
lib/themes/theme.dart
lib/widgets/app_bar/journal_sliver_appbar.dart
lib/widgets/misc/multi_select.dart
lib/widgets/misc/search_widget.dart
macos/Podfile.lock
pubspec.lock
pubspec.yaml
test/pages/journal/infinite_journal_page_test.dart

This PR adapts the journal page to use a CustomScrollView so that the header can be animated when scrolling up. Also remove this floating search bar for which the author must have deleted the GitHub project... 🤦 
Also, the journal page widget is reduced in complexity by moving logic into `JournalPageCubit`. This needs to be completed by moving all the fetch logic into the cubit.

Adapt journal page to use CustomScrollView & replace search header

---

CHANGELOG.md
build.yaml
lib/beamer/locations/journal_location.dart
lib/blocs/journal/journal_page_cubit.dart
lib/blocs/journal/journal_page_state.dart
lib/database/fts5_db.dart
lib/database/fts5_db.drift
lib/database/maintenance.dart
lib/get_it.dart
lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/logic/persistence_logic.dart
lib/pages/journal/infinite_journal_page.dart
lib/pages/settings/maintenance_page.dart
lib/services/entities_cache_service.dart
lib/widgets/app_bar/journal_sliver_appbar.dart
lib/widgets/journal/entry_details/measurement_summary.dart
lib/widgets/journal/journal_card.dart
pubspec.lock
pubspec.yaml
test/blocs/journal/journal_page_cubit_test.dart
test/logic/persistence_logic_test.dart
test/mocks/mocks.dart
test/pages/dashboards/dashboard_page_test.dart
test/pages/journal/entry_detail_page_test.dart
test/pages/journal/infinite_journal_page_test.dart
test/widgets/journal/entry_details/measurement_summary_test.dart
test/widgets/journal/journal_card_test.dart

This PR adds full-text search on the journal page and some search header improvements. Still work in progress and being tested. Working well and fast so far.
Note that if you already had a version running before this change got released, you will need to run a maintenance task if you want existing entries to be indexed as well:
`Settings > Advanced > Maintenance > Recreate full-text index`
Please note that there is nor visual feedback except for on the logging page. This is available at:
`Settings > Advanced > Maintenance > Logs`

Add full-text search using SQLITE with the FTS5 extension

---

CHANGELOG.md
lib/pages/create/create_measurement_dialog.dart
lib/widgets/create/suggest_measurement.dart
pubspec.yaml
test/widgets/create/measurement_suggestions_test.dart

This PR improves the capture dialog by showing suggested popular values in the dialog also when selecting a different date. Before, the suggestions would disappear when selecting a different date or comment, for no good reason.

Show popular values in capture dialog for past dates

---

CHANGELOG.md
codecov.yml
lib/widgets/journal/entry_detail_linked.dart
pubspec.lock
pubspec.yaml

This PR fixes unlinking entries, e.g. for linking a time recording entry to a separate task when realizing that the time log belongs elsewhere. Example: I work on a feature but end up fixing CI. Then I'd want to associate a log entry where I describe the fix with its own task.

Fix unlink

---

CHANGELOG.md
lib/blocs/journal/entry_cubit.dart
lib/widgets/journal/entry_details/delete_icon_widget.dart
pubspec.yaml

This PR fixes navigating back when deleting an entry. Solution was pretty simple, just call `beamBack` on the beamer delegate:
`journalBeamerDelegate.beamBack();`
Resolves #1318

Fix navigate back after entry deletion

---

CHANGELOG.md
lib/blocs/journal/journal_page_cubit.dart
lib/widgets/search/entry_type_filter.dart
pubspec.yaml

This PR adds an all button in the entry type filter, which will select all types unless all are selected already, in which case it will clear the selection. Also adds a long press gesture on the individual choice chips which will clear the selection except for the long pressed item.
Resolves #1324.

Improve search header

---

CHANGELOG.md
lib/blocs/journal/journal_page_cubit.dart
lib/themes/theme.dart
lib/widgets/search/entry_type_filter.dart
lib/widgets/search/filter_choice_chip.dart
lib/widgets/search/task_status_filter.dart
pubspec.yaml

This PR adapts the task filter to offer the same functionality of the entry types filter as introduced in #1325, plus extracts code that is reusable in both.

Improve search header for tasks

---

CHANGELOG.md
lib/blocs/journal/entry_cubit.dart
lib/widgets/journal/entry_details/duration_widget.dart
lib/widgets/journal/journal_card.dart
pubspec.yaml

This PR fixes an issue where occasionally, the task title would be cleared accidentally, which as a user was really painful and annoying.
The solution and learning is to stop carelessly (or recklessly) overwriting form field values with empty defaults when form field access could return null value, no matter how rarely that happens (usually, the form would be fully initialized). The type system was pretty clear here.
Resolves #1327.

Fix issue where task title could disappear

---

CHANGELOG.md
lib/beamer/locations/journal_location.dart
pubspec.yaml

This one-liner PR fixes a routing issue where audio notes could only be taken at top level but not as comments to other entries because the unique page key requirement was violated and a new page with a similar ID could not be created.
Fixes #1329.

Fix recording audio note as comment to other entry types

---

CHANGELOG.md
ios/Podfile.lock
ios/Runner/Info.plist
lib/blocs/audio/recorder_cubit.dart
lib/widgets/create/add_actions.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
macos/Flutter/GeneratedPluginRegistrant.swift
macos/Podfile.lock
macos/Runner.xcodeproj/project.pbxproj
macos/Runner/DebugProfile.entitlements
macos/Runner/Info.plist
macos/Runner/Release.entitlements
pubspec.lock
pubspec.yaml
test/widgets/create/add_actions_test.dart
windows/flutter/generated_plugin_registrant.cc
windows/flutter/generated_plugins.cmake

This PR replaces [`flutter_sound`](https://pub.dev/packages/flutter_sound) with the [`record`](https://pub.dev/packages/record) library. This solves both the outdated library issue where the upgrade did not work, and also the missing support on desktop platforms.
Resolves #976.
Resolves #1339.

Audio recording on macOS

---

CHANGELOG.md
lib/database/database.drift
pubspec.yaml

This PR changes the sort order of habit completions to `created_at` in ascending order, which fixes the reported habit completion percentages in the completion rate chart, such that LAST ONE WINS as expected.
Resolves #1342.

Fix updating habit completion sort order

---

CHANGELOG.md
lib/database/settings_db.dart
lib/database/settings_db.drift
lib/get_it.dart
lib/l10n/app_en.arb
lib/main.dart
lib/pages/settings/maintenance_page.dart
lib/services/nav_service.dart
lib/services/sync_config_service.dart
lib/services/vector_clock_service.dart
lib/services/window_service.dart
lib/sync/inbox/inbox_service.dart
lib/sync/inbox/inbox_service_isolate.dart
lib/sync/inbox/messages.dart
lib/sync/outbox/messages.dart
lib/sync/outbox/outbox_service.dart
lib/sync/outbox/outbox_service_isolate.dart
lib/sync/utils.dart
pubspec.yaml
test/blocs/journal/entry_cubit_test.dart
test/blocs/journal/journal_page_cubit_test.dart
test/logic/persistence_logic_test.dart
test/pages/settings/tags/tags_page_test.dart
test/services/nav_service_test.dart
test/sync/inbox/inbox_service_test.dart
test/sync/outbox/outbox_service_test.dart

This PR moves all config items that were previously stored in SecureStorage but that are not actually secrets to SQLite to fix a mysterious locking issue.
Resolves #1362

Move non-secrets from SecretStorage to SQLite

---

.github/workflows/flutter-analyze.yml
.github/workflows/flutter-linux-build.yml
.github/workflows/flutter-linux-release.yml
.github/workflows/flutter-test.yml
.github/workflows/flutter-testflight.yml
.github/workflows/flutter-windows-build.yml
CHANGELOG.md
ios/Podfile
ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/Runner/Info.plist
lib/beamer/beamer_app.dart
lib/logic/health_import.dart
lib/pages/create/fill_survey_page.dart
lib/widgets/badges/flagged_badge.dart
lib/widgets/misc/desktop_menu.dart
macos/Flutter/GeneratedPluginRegistrant.swift
macos/Podfile.lock
macos/Runner.xcodeproj/project.pbxproj
macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
pubspec.lock
pubspec.yaml
test/helpers/path_provider.dart

This PR upgrades dependencies to work with Flutter 3.7.1, including a fixed version of `flutter_quill`.
Supersedes #1357.
Required by #1358.

Upgrade to Flutter 3.7.1

---

CHANGELOG.md
lib/widgets/journal/editor/editor_toolbar.dart
lib/widgets/tasks/linked_duration.dart
pubspec.yaml
test/pages/journal/entry_detail_page_test.dart
test/test_data/test_data.dart

This PR replaces the `ProgressBar` for media playback with `LinearProgressIndicator` from Flutter, plus improves the editor toolbar styling.
Resolves #1390

Task progress indicator

---

CHANGELOG.md
lib/pages/empty_scaffold.dart
lib/pages/settings/about_page.dart
lib/widgets/app_bar/journal_sliver_appbar.dart
lib/widgets/app_bar/task_app_bar.dart
lib/widgets/misc/tasks_counts.dart
lib/widgets/search/entry_type_filter.dart
pubspec.lock
pubspec.yaml
test/pages/settings/about_page_test.dart

This PR declutters the task search header by removing task stats to the about page. The stats are occasionally useful but do not need to be seen all the time.

Task improvements

---

.buildkite/pipeline.yml
CHANGELOG.md
lib/beamer/locations/journal_location.dart
lib/pages/settings/dashboards/dashboard_item_card.dart
lib/surveys/run_surveys.dart
lib/widgets/journal/entry_details/entry_datetime_widget.dart
lib/widgets/journal/tags/tag_add.dart
pubspec.yaml
test/widgets/journal/tags/tag_add_test.dart

This PR refactors the tags modal to use the default modal implementation, which feels very natural to use, throughout the codebase, and removes the use of a separate beamer page for this particular modal, which turned out to be way more complicated than necessary.
Resolves #1394.

Improved Tags Modal

---

CHANGELOG.md
lib/database/conversions.dart
lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/pages/habits/habits_page.dart
lib/pages/settings/categories/category_details_page.dart
lib/widgets/habits/habit_category.dart
lib/widgets/habits/habits_filter.dart
pubspec.lock
pubspec.yaml

This PR adds a small visualisation with a donut chart showing the distribution of open habits by category. In the next step, this small chart can be used as a button for opening a filter of habit categories to limit what is shown and make the list of open habits less intimidating.
Also adds some fixes around categories, such as preventing the creation of duplicate habits, and enabling scrolling in the category selection bottom sheet (toaster).

Open habits visualisation by category

---

CHANGELOG.md
lib/widgets/audio/audio_player.dart
lib/widgets/journal/entry_details_widget.dart
lib/widgets/journal/journal_card.dart
pubspec.yaml
test/mocks/mocks.dart
test/widgets/audio/audio_player_test.dart

This PR changes the navigation to the audio player(s). Previously, when trying to play audio in the list of linked entries, e.g. on a task, required navigation to a new details page for the audio entry. This was cumbersome and annoying. Now instead, the audio player is shown inline.

Show audio player inline in linked entries

---

CHANGELOG.md
lib/pages/settings/sync/sync_assistant_page.dart
lib/sync/inbox/process_message.dart
lib/themes/theme.dart
lib/widgets/sync/imap_config_form.dart
lib/widgets/sync/imap_config_status.dart
pubspec.lock
pubspec.yaml

This PR fixes a condition where sync would get stuck when a participant node would encounter a message that does not match the latest sync key. This would happen when regenerating a new sync key, and then creating another message, e.g. on another device, that was not updated with the latest key.
Resolves #1493.

Fix Sync getting stuck

---

.github/workflows/flutter-linux-release.yml
.github/workflows/flutter-test.yml
CHANGELOG.md
ios/Podfile.lock
lib/blocs/audio/player_cubit.dart
lib/main.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
macos/Flutter/GeneratedPluginRegistrant.swift
macos/Podfile
macos/Podfile.lock
macos/Runner.xcodeproj/project.pbxproj
pubspec.lock
pubspec.yaml
test/pages/dashboards/dashboard_page_test.dart
test/pages/journal/infinite_journal_page_test.dart
test/utils/utils.dart
test/widgets/journal/journal_card_test.dart
windows/flutter/generated_plugin_registrant.cc
windows/flutter/generated_plugins.cmake

Resolves #1510 by replacing `[just_audio`](https://pub.dev/packages/just_audio) with [`media_kit`](https://pub.dev/packages/media_kit) since the former did not support Linux.

Add audio playback on Linux

---

.buildkite/pipeline.yml
CHANGELOG.md
pubspec.yaml

Thanks to @alexmercerind, this PR results in reasonably sized APKs by architecture instead of one large 130 MB APK for all platforms:
Resolves #1515.

Split APKs by architecture to reduce APK size

---

pubspec.yaml

Hi!
This is a follow-up on https://github.com/matthiasn/lotti/pull/1516#issuecomment-1523925037.
I made some changes upstream. This should bring size of all your APK(s) under (or around) 20 MB.

Bump package:media_kit

---

pubspec.yaml

Resolves #1524.
<hr>
I apologize for the inconvenience. Most of our focus has been on video libraries & audio libraries got less attention & testing.
Now I've resolved it. Aiming to address every corner before 1.0.0.
**Off-Topic:** My own personal [project uses package:media_kit (for audio)](https://harmonoid.com/) on Windows & GNU/Linux. I need to find some time & update it to use media_kit on Android too. package:media_kit started from desktop platforms first.

Bump package:media_kit_libs_android_audio

---

CHANGELOG.md
pubspec.lock
pubspec.yaml

This PR bumps `package:media_kit_libs_android_audio` to the latest version and thus fixes startup on device, as tested both in emulator and on device.

Fix android startup

---

CHANGELOG.md
lib/main.dart
lib/utils/file_utils.dart
linux/CMakeLists.txt
pubspec.lock
pubspec.yaml
windows/runner/Runner.rc

This PR changes app data storage on Windows from the general `Documents` folder to an app-specific folder.
Existing data needs to be moved after installing the latest version.
Resolves #1534.

Windows: app-specific data folder

---

CHANGELOG.md
lib/database/sync_db.dart
lib/pages/settings/categories/category_details_page.dart
lib/pages/settings/conflicts_page.dart
lib/pages/settings/dashboards/dashboard_definition_page.dart
lib/pages/settings/habits/habit_details_page.dart
lib/pages/settings/measurables/measurable_details_page.dart
lib/surveys/calculate.dart
lib/widgets/journal/entry_detail_linked.dart
lib/widgets/journal/entry_details/delete_icon_widget.dart
lib/widgets/modal/modal_action_sheet.dart
lib/widgets/modal/modal_sheet_action.dart
lib/widgets/search/tasks_segmented_control.dart
lib/widgets/sync/qr_widget.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
macos/Flutter/GeneratedPluginRegistrant.swift
macos/Podfile.lock
pubspec.lock
pubspec.yaml
windows/flutter/generated_plugin_registrant.cc
windows/flutter/generated_plugins.cmake

This PR removes the `adaptive_dialog` library, which was causing problems in the attempt to upgrade to Flutter 3.10.

Remove `adaptive_dialog` library

---

CHANGELOG.md
lib/blocs/audio/player_cubit.dart
lib/blocs/audio/recorder_cubit.dart
lib/services/asr_service.dart
pubspec.yaml

Resolves #1564 by only allowing one transcript at a time, and enqueuing transcription jobs in an in-memory queue.

Fix crashes when attempting simultaneous transcriptions

---

LICENSE

The GNU AFFERO license used previously doesn't make sense any more since it's not a deployed service but an actual piece of distributed software.

Change license to GNU GENERAL PUBLIC LICENSE

---

CHANGELOG.md
lib/beamer/beamer_app.dart
lib/beamer/locations/dashboards_location.dart
lib/beamer/locations/habits_location.dart
lib/beamer/locations/journal_location.dart
lib/beamer/locations/settings_location.dart
lib/beamer/locations/tasks_location.dart
lib/main.dart
lib/pages/create/complete_habit_dialog.dart
lib/pages/empty_scaffold.dart
lib/pages/journal/entry_details_page.dart
lib/pages/settings/sliver_box_adapter_page.dart
lib/pages/settings/theming_page.dart
lib/themes/theme.dart
lib/widgets/app_bar/task_app_bar.dart
lib/widgets/app_bar/title_app_bar.dart
lib/widgets/create/add_actions.dart
lib/widgets/habits/habit_completion_card.dart
lib/widgets/journal/journal_card.dart
lib/widgets/search/filter_choice_chip.dart
pubspec.lock
pubspec.yaml

This PR adds a shimmer animation to the habit success button, plus improves animations between page transitions. Also improves some styles.

Button & transition animation

---

lib/widgets/journal/entry_details/entry_detail_header.dart
pubspec.yaml
test/widgets/journal/entry_details/entry_detail_header_test.dart

The entry headers looked way too cluttered, showing too many options at the same time, on all entries, potentially leading to tens of icon buttons on the screen that can be hidden by default.
This PR declutters the UI by hiding most of these icons by default, and only making them visible after tapping an ellipse icon.

feat: declutter entry header, hide most icons by default

---

lib/main.dart
lib/pages/empty_scaffold.dart
lib/services/editor_state_service.dart
lib/widgets/journal/editor/editor_styles.dart
lib/widgets/journal/editor/editor_widget.dart
lib/widgets/journal/journal_card.dart
lib/widgets/journal/text_viewer_widget.dart
pubspec.lock
pubspec.yaml

This PR improves the entry text preview in journal cards by using the same quill editor widget for rendering the preview, only in read-only mode.

feat: improve entry preview in journal cards

---

lib/widgets/journal/editor/editor_toolbar.dart
pubspec.yaml
test/widgets/journal/editor/editor_widget_test.dart

This PR reduces the jumpiness of abruptly displaying the editor toolbar on focus. Instead, the vertical size, scale, and opacity are animated to full height and opacity over the course of 800ms.

feat: animate the editor toolbar vertical size on entry

---

lib/l10n/app_en.arb
lib/pages/settings/advanced/maintenance_page.dart
lib/services/sync_config_service.dart
pubspec.yaml

This PR adds a maintenance task for skipping e.g. corrupted sync messages.

feat: maintenance task for skipping sync message

---

lib/sync/outbox/outbox_service.dart
lib/sync/outbox/outbox_service_isolate.dart
pubspec.yaml

Instead of restarting after network reconnect inside the outbox isolate, if there's a disconnect of the network, kill the isolate altogether, and then restart it on next reconnect.

feat: improve sync restart on reconnect

---

lib/get_it.dart
lib/l10n/app_en.arb
lib/services/ai_service.dart
lib/widgets/journal/entry_detail_linked.dart
lib/widgets/journal/entry_details/entry_detail_header.dart
lib/widgets/journal/entry_details_widget.dart
pubspec.lock
pubspec.yaml

I was working on habit tracking, in particular for grouping habits, and then got a bit side-tracked, in a good way. I wanted to check out [Ollama](https://ollama.ai) anyway and thought, why not quickly (2 minutes, first try) dictate my feature idea, have Lotti transcribe the audio, and then prompt a capable [llama:13b](https://ollama.ai/library/llama2) model running locally in [Ollama](https://ollama.ai). The result blew me away:
```
a) Acceptance Criteria for Defining Habit Groups:
1. The user should be able to define a subset of habits as a "habit group" for the purpose of tracking success rate.
2. The habit group should be defined by selecting a specific set of habits from the full list of habits.
3. The user should be able to name the habit group and see it listed in the app's …
```

feat: integrate Ollama for interacting with a locally running LLM

---

lib/features/ai/state/ollama_prompt.dart
lib/features/ai/ui/ai_prompt_icon_widget.dart
lib/features/ai/ui/ai_response_preview.dart
lib/get_it.dart
lib/main.dart
lib/widgets/journal/entry_details/entry_detail_header.dart
pubspec.lock
pubspec.yaml

This PR introduces streaming responses from the large language model so that when tapping the prompt I do not have to wait for 10-20 seconds but rather I get to see the results streaming it immediately which makes for a much more interesting user experience.
Also in this PR I'm introducing [riverpod](https://pub.dev/packages/riverpod) which will be the state management solution going forward in this project.
This is how it looks like:

feat: display response stream from LLM prompt

---

lib/get_it.dart
lib/logic/ai/ai_logic.dart
lib/logic/persistence_logic.dart
pubspec.lock
pubspec.yaml
test/logic/persistence_logic_test.dart
test/mocks/mocks.dart

This PR adds generating Embeddings using the 13b parameters Llama model. Currently, the resulting vector of length `5120` is only printed to the console. In subsequent PRs, I plan on storing those in a vector database in order to replace the rather useless full-text search.

feat: embeddings

---

lib/database/journal_db/config_flags.dart
lib/pages/settings/flags_page.dart
lib/services/asr_service.dart
lib/utils/consts.dart
pubspec.yaml
test/database/database_test.dart

This PR adds a config flag for enabling/disabling automatic transcription of audio recordings (after finishing the recording). The reason for that is that I prefer running the whisper medium model which in my experience (and for my voice) is far superior than the smaller variants. However, while it works on mobile, it takes too long and uses too much battery, so I'd rather postpone the transcription and run it on the desktop later.

feat: add flag for enabling/disabling ASR per device

---

ios/Flutter/AppFrameworkInfo.plist
lib/blocs/journal/journal_page_cubit.dart
lib/blocs/journal/journal_page_state.dart
lib/blocs/journal/journal_page_state.freezed.dart
lib/pages/journal/infinite_journal_page.dart
lib/widgets/app_bar/journal_sliver_appbar.dart
lib/widgets/journal/journal_card.dart
lib/widgets/search/task_status_filter.dart
pubspec.yaml
test/pages/journal/infinite_journal_page_test.dart

This PR adds a narrower list view for tasks that is shown by default, only showing the task title and status, and a segmented button in the task page header for toggling between those views. 
The idea here is that previously, too much scrolling was needed to go through tasks, and that most of the displayed information wasn't helpful in a list representation.

feat: show tasks as list with only title and status by default

---

lib/blocs/audio/recorder_cubit.dart
lib/classes/journal_entities.dart
lib/classes/journal_entities.freezed.dart
lib/classes/journal_entities.g.dart
lib/logic/persistence_logic.dart
lib/services/asr_service.dart
lib/sync/inbox/process_message.dart
pubspec.lock
pubspec.yaml

This PR adapts the speech recognition such that when on the creator, auto transcribe was disabled and it is enabled on the receiver side, the ASR using Whisper will start automatically. This is in particular a scenario where ASR is disabled on mobile, where it might use too much battery.

feat: automatically transcribe when ASR active on receiver

---

lib/beamer/beamer_app.dart
lib/widgets/nav_bar/nav_bar.dart
pubspec.yaml

This PR adds a micro interaction as a small size animation of the bottom navigation bar items, where on select, the icon and label group shrinks, pauses, and grows back to original size, over the course of 160ms. This behavior is inspired by the Spotify app on iOS. Code comes from forking Flutter's own `BottomNavigationBar`. Could be cleaned up, as not everything is used here.

feat: animate size of nav bar icons, Spotify style

---

pubspec.lock
pubspec.yaml

This PR fixes a build issue where the `build_runner` would not work with `dart_style: 2.3.4`.

fix: build issue

---

lib/blocs/journal/entry_cubit.dart
lib/widgets/journal/editor/editor_widget.dart
lib/widgets/tasks/task_form.dart
pubspec.lock
pubspec.yaml

This PR fixes a keyboard lister issue where the registered `CMD-r` for refreshing the journal list page would also be triggered when just typing `r`, and thus swallowing the keypress event such that no `r` could be typed in any text input. This bug must have recently been introduced in `hotkey_manager` as reported [here](https://github.com/leanflutter/hotkey_manager/issues/52) and is fixed in `v0.2.1`, so the update alone fixes the problem.
This PR also does other dependency upgrades, and some refactoring around event handling.

fix: keyboard listener issue

---

integration_test/matrix_service_test.dart
integration_test/run_matrix_tests.sh
lib/sync/matrix/matrix_service.dart
pubspec.yaml

This PR adds creating a new Matrix test user in each run of the Matrix integration test such that the tests don't have to deal with old state such as unverified devices from previous interrupted test runs (when for example the logout was never reached) or also already exiting rooms that a hardcoded test user would have created in previous test runs.

test: create Matrix user in test script

---

integration_test/matrix_service_test.dart
integration_test/run_matrix_tests.sh
lib/services/sync_config_service.dart
lib/sync/matrix/key_verification_runner.dart
lib/sync/matrix/matrix_service.dart
lib/sync/secure_storage.dart
lib/widgets/sync/matrix/incoming_verification_modal.dart
lib/widgets/sync/matrix/matrix_settings.dart
lib/widgets/sync/matrix/verification_modal.dart
pubspec.yaml

This PR adds an integration test for [Matrix](https://spec.matrix.org/v1.10/) device verification, and some refactoring to enable that. In order to run it, you need to do the following:
1. clone [dendrite](https://github.com/matrix-org/dendrite) and build it, see top level README there.
2. Copy `./integration_test/dendrite` from here into `./build/docker` in `dendrite` and start the Docker Compose setup according to the respective docs using the copied `docker-compose.yml`. Feel free to change the shared secret in `dendrite.yaml` as you see fit.
3. Run `./integration_test/run_matrix_tests.sh` from project root here, which will [create a user](https://matrix-org.github.io/dendrite/administration/createusers) in the locally running dendrite instance, and then run the integration test …

test: Matrix device verification

---

ios/Podfile.lock
lib/widgets/app_bar/habit_page_app_bar.dart
macos/Podfile.lock
pubspec.lock
pubspec.yaml

This PR adds a quick improvement to the habits tab where the habit completions chart now always stays visible, and only the tab title shrinks and eventually disappears when scrolling down, as opposed to previously when the chart would disappear as well. The reason behind this change is that the gratification from seeing the chart improve when successfully completing a habit was missing when there were more open habits for the day than would fit the screen, and the page was scrolled down so much that the chart had disappeared. That made it even more annoying that so many habits were still open in the first place.
When not scrolled down (similar to before this change):
When scrolled down now:

feat: improve Habits tab

---

integration_test/matrix_service_test.dart
integration_test/run_matrix_tests.sh

This PR adds configuration to the integration tests as environment variables:
- `TEST_SERVER`
- `TEST_PASSWORD`
- `SLOW_NETWORK`
This allows connecting to a remote server instead of a locally running dendrite instance, and then also simulating bad network. For that case, e.g. when using Apple's [Network Link Conditioner](https://nshipster.com/network-link-conditioner/), `SLOW_NETWORK=true` can be specified which increases delays in the test by a factor of 10.
I tested with the probably worst predefined profile **Edge** and the test for client verification are still passing, just taking longer at almost four minutes:

test: add config ENVs for TEST_SERVER, TEST_PASSWORD, SLOW_NETWORK

---

lib/widgets/app_bar/journal_sliver_appbar.dart
lib/widgets/search/filter_choice_chip.dart
lib/widgets/search/search_widget.dart
lib/widgets/search/task_status_filter.dart
lib/widgets/settings/settings_card.dart
pubspec.lock
pubspec.yaml

This PR moves the filtering in the tasks tab to a modal sheet. For the sheet, the neat [wolt_modal_sheet](https://pub.dev/packages/wolt_modal_sheet) library is used, which promises to make building appealing bottom sheets much easier than with Flutter's built-in API. Being a Wolt user, I also quite enjoy the design, has been the most visually pleasing app of its kind for me for quite some time. Not much of its functionality is used here yet, but I plan on making good use of especially the multi-page functionality and the smooth transitions between them.
What especially stood out for me was the really well done [Figma file](https://www.figma.com/file/jRQUhvi44bkUxRxSWGhSXO/Wolt-Modal-Sheet-Specs?type=design&node-id=1-3&mode=design&t=52EssN7MlQlyqQOv-0) for collaborating with designers. …

feat: move tasks filter into modal sheet

---

.gitignore
integration_test/README.md
integration_test/matrix_service_test.dart
integration_test/run_matrix_tests.sh

This PR adds instructions for running the Matrix integration test under adverse networking conditions, here with a delay of `1000 ms` and a slow connection of `100 KB/s`.

test: degraded network support instructions

---

.github/workflows/flutter-matrix-test.yml
integration_test/README.md
integration_test/matrix_service_test.dart
integration_test/setup_toxiproxy_docker.sh

This PR adds running the Matrix integration test with simulated bas network.

ci: run Matrix test with simulated bad network

---

integration_test/matrix_service_test.dart
lib/sync/matrix/matrix_service.dart

This PR changes the Matrix client persistence directory for the integration test to a temporary directory such that the tests always start with a clean slate. I was running into an issue where tests failed because of some inconsistent state, presumably from a test that I had stopped midway.

test: use fresh Matrix persistence directory on every run

---

integration_test/matrix_service_test.dart
lib/sync/matrix/matrix_service.dart
lib/sync/matrix/process_message.dart
lib/sync/matrix/room.dart
lib/sync/matrix/send_message.dart
lib/sync/matrix/timeline.dart
lib/widgets/sync/matrix/incoming_verification_modal.dart
lib/widgets/sync/matrix/unverified_devices.dart
pubspec.yaml

This PR changes the Matrix setup in the integration test to utilizing a user per device involved in synchronization between Lotti instances (e.g. on my desktop and on my mobile device, plus maybe tablet or whatever other device). The reason for that is that this makes it easier to listen for new messages, as in unread for that user. I also like the idea of users being a throwaway concept in a zero trust environment.

feat: use Matrix user per device and add invites

---

lib/utils/image_utils.dart
pubspec.yaml

This PR disables image resizing on import. The API of [`flutter_image_compress`](https://pub.dev/packages/flutter_image_compress) is rather confusing here. Apparently, setting min dimensions larger than the source image disables resizing 🤷

feat: no image resizing

---

ios/Runner.xcodeproj/project.pbxproj
ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
macos/Runner.xcodeproj/project.pbxproj
macos/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
macos/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
pubspec.yaml

This PR upgrades WhisperKit to the latest version [`0.6.0`](https://github.com/argmaxinc/WhisperKit/releases/tag/v0.6.0).

chore: upgrade WhisperKit

---

integration_test/matrix_service_test.dart
ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
lib/pages/settings/flags_page.dart
lib/sync/matrix/client.dart
lib/sync/matrix/matrix_service.dart
pubspec.lock
pubspec.yaml

This PR replaces the deprecated `HiveCollectionsDatabase` with the new `MatrixSdkDatabase` which uses SQLite under the hood.

feat: replace deprecated Matrix database

---

integration_test/matrix_service_test.dart
lib/blocs/journal/journal_page_cubit.dart
lib/database/common.dart
lib/database/database.dart
lib/database/journal_db/config_flags.dart
lib/database/logging_db.dart
lib/database/settings_db.dart
lib/database/sync_db.dart
lib/get_it.dart
lib/logic/ai/ai_logic.dart
lib/main.dart
lib/pages/settings/flags_page.dart
lib/services/db_notification.dart
lib/utils/consts.dart
pubspec.lock
pubspec.yaml
test/blocs/journal/entry_cubit_test.dart
test/blocs/journal/journal_page_cubit_test.dart
test/database/database_test.dart
test/logic/persistence_logic_test.dart
test/mocks/mocks.dart
test/pages/journal/infinite_journal_page_test.dart
test/themes/themes_service_test.dart
test/themes/utils_test.dart
test/widgets/journal/editor/editor_widget_test.dart
test/widgets/journal/entry_details/entry_datetime_widget_test.dart
test/widgets/journal/entry_details/entry_detail_footer_test.dart
test/widgets/journal/entry_details/entry_detail_header_test.dart
test/widgets/journal/entry_details/share_button_widget_test.dart

This PR removes the previous setup for running `drift` in isolates. Also, it adds a notification service for database updates, with a stream that can then be listened to by widgets, BloCs or providers for changes to the database. Unlike listening to a stream for a potentially expensive query, which then runs automatically when using drift subscriptions, it then allows listeners to re-fetch at their own leisure.

refactor: database updates via stream

---

integration_test/matrix_service_test.dart
lib/blocs/journal/journal_page_cubit.dart
lib/blocs/journal/journal_page_state.dart
lib/blocs/journal/journal_page_state.freezed.dart
lib/database/database.dart
lib/database/database.drift
lib/database/database.g.dart
lib/features/journal/state/entry_controller.dart
lib/features/journal/state/entry_controller.g.dart
lib/pages/journal/infinite_journal_page.dart
lib/services/db_notification.dart
lib/widgets/journal/journal_card.dart
pubspec.yaml
test/blocs/journal/entry_cubit_test.dart
test/blocs/journal/journal_page_cubit_test.dart
test/database/database_test.dart
test/logic/persistence_logic_test.dart
test/pages/journal/infinite_journal_page_test.dart
test/themes/themes_service_test.dart
test/themes/utils_test.dart
test/widget_test_utils.dart
test/widgets/journal/editor/editor_widget_test.dart
test/widgets/journal/entry_details/entry_datetime_widget_test.dart
test/widgets/journal/entry_details/entry_detail_footer_test.dart
test/widgets/journal/entry_details/entry_detail_header_test.dart
test/widgets/journal/entry_details/share_button_widget_test.dart

This PR adds a Riverpod provider for entries. The initial idea here was to use this for display in the infinite scroll pages, but that's actually not feasible because it results in yank, which is quite unpleasant. But this will still be usable or useful when going on to entry detail pages. Also, this PR adds improved reloading behavior when there are incoming messages from sync.

feat: entry provider & improved reload

---

ios/Podfile.lock
lib/features/journal/state/entry_controller.dart
macos/Podfile.lock
pubspec.lock
pubspec.yaml

Upgrading `photo_manager` to `3.1.0` broke image import, where no new photos would be available for selection. This PR downgrades to `0.3.0` again, which fixes the issue.
Also reported here: https://github.com/fluttercandies/flutter_photo_manager/issues/1125

chore: revert photo_manager to 3.0.0

---

lib/widgets/journal/tags/tag_widget.dart
pubspec.yaml

This PR improves navigation back to a task or entry when double tapping a tag to navigate to the tag settings page. Previously, when saving the tag, the app would navigate to the tags list page.

feat: navigate back from tag settings page to task/entry

---

lib/pages/habits/habits_page.dart
pubspec.yaml

This PR fixes an issue with unexpectedly high CPU utilization around `20%` when the app was doing nothing at all (noticed on macOS desktop). The issue was that a `CircularProgressIndicator` was shown on the habits tab when that wasn't actually visible. Removing that results in idle CPU load under `1%`, as one should expect.

fix: idle CPU load 

---

lib/sync/outbox/outbox_service.dart
pubspec.lock
pubspec.yaml

This PR re-enables the sync outbox. For now, this only enqueues items. In a next PR, the actual send attempt will be started from the outbox, and retried, e.g. when the network is back.

feat: re-enable enqueuing in sync outbox

---

lib/services/window_service.dart
lib/sync/matrix/matrix_service.dart
lib/sync/matrix/send_message.dart
lib/sync/outbox/outbox_service.dart
pubspec.yaml

This PR re-enables the sync outbox, such that outgoing messages are perished in the sync database, and then sent later when possible, such as when the network is back. The detection of the network being back is still pending and will be added back in a later PR.

feat: re-enable sync outbox

---

integration_test/matrix_service_test.dart
lib/sync/matrix/matrix_service.dart
lib/sync/matrix/send_message.dart
lib/sync/outbox/outbox_service.dart
pubspec.yaml

This PR adds incrementing the retries count when sending messages such that a retries are only performed a finite number of times (10x) before continuing with the next sync message. Also include some refactoring to move the sending of messages and files to an extension instead of in a global function.

feat: increment retry count when failing

---

ios/Runner.xcodeproj/project.pbxproj
ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
lib/features/journal/state/entry_controller.dart
macos/Runner.xcodeproj/project.pbxproj
macos/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
pubspec.lock
pubspec.yaml

This PR is intended to improve automatically scrolling to whichever text editor is currently in focus. The experience was a bit jumpy before, and I assume the issue was that whenever the listener fires, the entry would be scrolled into view, even if the editor was in fact not actually in focus. Instead, `hasFocus` is used to determine the actual focussed state.

feat: scrolling improvement

---

ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
lib/blocs/journal/entry_state.dart
lib/blocs/journal/entry_state.freezed.dart
lib/features/journal/state/entry_controller.dart
lib/features/journal/state/entry_controller.g.dart
lib/widgets/journal/editor/editor_toolbar.dart
lib/widgets/journal/editor/editor_widget.dart
lib/widgets/journal/entry_details/save_button.dart
lib/widgets/journal/entry_image_widget.dart
macos/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
pubspec.yaml
test/features/journal/state/entry_controller_test.dart

This PR improves the zooming behavior of images, plus some animation tweaks around the editor toolbar.

feat: image zoom improvements

---

lib/widgets/journal/entry_details_widget.dart
lib/widgets/tasks/task_form.dart
pubspec.yaml

This PR replaces the use of a `StreamBuilder` in the entry details card by using a `ConsumerWidget` instead.

refactor: replace StreamBuilder with controller

---

lib/features/journal/state/journal_card_controller.dart
lib/features/journal/state/journal_card_controller.g.dart
lib/widgets/journal/editor/editor_widget.dart
lib/widgets/journal/entry_details_widget.dart
lib/widgets/journal/journal_card.dart
pubspec.lock
pubspec.yaml
test/widgets/journal/journal_card_test.dart

This PR changes the journal cards to listen to changes via a controller vs. via a stream builder that directly listens to database changes (and which was called with updates that weren't changes too often).
Also includes some scrolling on focus behavior on mobile.

refactor: journal card controller

---

lib/logic/health_import.dart
pubspec.yaml

This PR adds preventing fetching health data too often. For example, when a dashboard includes step count, and other cumulative data, those would be fetched every single time a dashboard with that data opens. That would for example be the case when a dashboard is shown as part of a habit completion. In my case, every completion of a habit that includes a bigger dashboard with health data would create 10 pointless entries that would still need to be persisted and synced.

feat: fetch same health data type at most once every 10 min

---

lib/widgets/journal/entry_details_widget.dart
pubspec.yaml

This PR disables automatically scrolling to an entry in focus when the keyboard appears since that lead to annoying behavior on mobile. Behavior will likely come back when I find a better solution.

fix: disable auto scroll when keyboard appears until better solution

---

lib/blocs/journal/journal_page_cubit.dart
lib/blocs/journal/journal_page_state.dart
lib/blocs/journal/journal_page_state.freezed.dart
lib/logic/create/create_entry.dart
lib/logic/persistence_logic.dart
lib/widgets/create/add_actions.dart
lib/widgets/search/task_status_filter.dart
pubspec.yaml

This PR adds:
- auto assigning existing category when creating a new task linked to an existing task
- filter chip specifically for tasks with unassigned category

feat: auto assign category & filter for tasks with unassigned category

---

lib/blocs/journal/journal_page_cubit.dart
lib/database/conversions.dart
lib/database/database.dart
lib/database/database.drift
lib/database/database.g.dart
pubspec.yaml
test/logic/persistence_logic_test.dart
test/pages/journal/infinite_journal_page_test.dart

This PR adds filtering tasks by category in the database. This avoids the problem of paging where a single page might contain few or none pf the selected categories, resulting in not showing all existing tasks for a particular category.

feat: add categories filter in database

---

lib/pages/habits/habits_page.dart
lib/pages/settings/advanced/logging_page.dart
pubspec.yaml
test/pages/settings/logging_page_test.dart

This PR adds hiding the habit completion cards when the habits page is invisible. The problem was that the `StreamBuilder` used in `HabitCompletionCard` stays alive even when invisible and thus causing expensive re-renders even when the habits page is not visible. For example, when processing sync messages, in one sample it took 33 seconds to process 10 messages prior to this change, and less than 4 seconds after this change. The whole area of when to re-render anything when there's a change in the database, e.g. when receiving messages from sync, still needs more thought, but at least this is already a good improvement.

feat: hide habit completion cards when page invisible

---

ios/Runner.xcodeproj/project.pbxproj
ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
lib/blocs/habits/habits_cubit.dart
lib/database/conversions.dart
lib/database/database.dart
lib/database/database.drift
lib/database/database.g.dart
lib/features/habits/state/habit_completion_controller.dart
lib/features/habits/state/habit_completion_controller.g.dart
lib/features/tasks/state/time_by_category_controller.dart
lib/features/tasks/state/time_by_category_controller.g.dart
lib/features/tasks/ui/time_by_category_chart.dart
lib/pages/create/complete_habit_dialog.dart
lib/pages/settings/advanced/about_page.dart
lib/utils/date_utils_extension.dart
lib/widgets/charts/dashboard_health_data.dart
lib/widgets/charts/dashboard_workout_data.dart
lib/widgets/charts/habits/dashboard_habits_data.dart
lib/widgets/charts/time_series/time_series_bar_chart.dart
lib/widgets/charts/utils.dart
lib/widgets/habits/habit_completion_card.dart
macos/Runner.xcodeproj/project.pbxproj
macos/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
macos/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
pubspec.lock
pubspec.yaml
test/pages/habits/habits_tab_page_test.dart
test/pages/settings/about_page_test.dart
test/widgets/charts/dashboard_habits_test.dart

This PR adds a first iteration of visualizing time per category using a stream graph. It's WIP, therefore the chart is not shown at the final position but rather in the somewhat hidden about page. I imagine using this visualization in the tasks tab instead such that I always have a visualization of my time sinks in view.
This is how that currently looks like:
The chart above shows the past 30 days of my time recorded per category. The colors are the colors selected for the respective categories. Note that there's a chart legend that appears when tapping on a particular day. But since that shows the names of my categories and I'm not sharing them, that's not in the screenshot. Will post screenshots with test data in a subsequent PR.
Please note that the implementation in this PR is very …

feat: time visualization

---

ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
lib/database/database.dart
lib/database/database.drift
lib/database/database.g.dart
lib/features/tasks/state/time_by_category_controller.dart
lib/features/tasks/state/time_by_category_controller.g.dart
lib/get_it.dart
lib/main.dart
pubspec.yaml
test/pages/settings/about_page_test.dart

This PR fixes the previously slow database queries by improving query and data processing time until display by a factor of roughly 30x.
There was an `n+1` problem where each entry would individually fetch linked entries to determine its category. Typically, a time tracking entry would not have a set category but the task it is linked from does, so this related task would be fetched individually. In my case of fetching 30 days worth of time, there would have been over 1K database queries for this reason. Instead, with this change, all related ids are collected and all the links fetched at once, creating a lookup table, and similarly for the targeted tasks. This results in 3 queries in total, instead of over 1K. This approach reduces the total time until chart display from 15 seconds to …

fix: much faster time visualization database query

---

lib/pages/journal/infinite_journal_page.dart
pubspec.yaml

This PR adds automatic assignment of a task's category when only a single category is selected in the tasks filter.

feat: automatically assign new task category when only one selected

---

lib/logic/create/create_entry.dart
lib/services/time_service.dart
lib/widgets/create/add_actions.dart
lib/widgets/journal/entry_detail_linked.dart
lib/widgets/journal/entry_details/duration_widget.dart
lib/widgets/journal/entry_details/entry_detail_footer.dart
lib/widgets/journal/entry_details_widget.dart
lib/widgets/journal/journal_card.dart
lib/widgets/misc/time_recording_indicator.dart
pubspec.yaml
test/widgets/create/add_actions_test.dart
test/widgets/journal/entry_details/entry_detail_footer_test.dart

This PR fixes a rather annoying issue where occasionally, the task or event forms would flicker when typing. Turns out the problem was instances of `GlobalKey` used in multiple places. The solution is proper routing to a singlet instance for each of the respective widgets.

fix: flickering task or event form

---

ios/Runner/WhisperKitRunner.swift
lib/database/journal_db/config_flags.dart
lib/pages/settings/flags_page.dart
lib/services/asr_service.dart
lib/utils/consts.dart
macos/Runner/WhisperKitRunner.swift
pubspec.yaml
test/database/database_test.dart

This PR adds the initialization of the WhisperKit model on app startup if the related config flag ist set to `true`. This is not the default as on first startup, the model would be downloaded, which is multiple GB in size for the large model on the desktop.

feat: initialize WhisperKit on app startup (with config flag)

---

lib/blocs/journal/journal_page_cubit.dart
pubspec.yaml
test/pages/journal/infinite_journal_page_test.dart

This PR improves the tasks filter modal by showing all tasks for any category when no category is selected, which is much more useful than showing no tasks at all when the category selection is empty. Otherwise, one would have to select every single category one by one to see tasks of any category.

feat: show all tasks when no category is selected

---

lib/blocs/settings/categories/category_settings_cubit.dart
lib/classes/entity_definitions.dart
lib/classes/entity_definitions.freezed.dart
lib/classes/entity_definitions.g.dart
lib/pages/settings/categories/category_details_page.dart
lib/services/entities_cache_service.dart
lib/widgets/search/task_category_filter.dart
lib/widgets/settings/categories/categories_type_card.dart
pubspec.lock
pubspec.yaml

This PR adds a favorite flag in category definitions, which is then used to only show favorite categories by default when filtering tasks. A `...` button is also added which allows expanding the categories to choose from in the filter to all active categories.

feat: favorite categories

---

lib/features/sync/matrix/matrix_service.dart
pubspec.yaml

Follow-up to #1809, increasing the wait time since scroll with physics can take longer than a second.

feat: increase wait time after scroll

---

ios/Runner/WhisperKitRunner.swift
lib/database/journal_db/config_flags.dart
lib/pages/settings/flags_page.dart
lib/services/asr_service.dart
lib/utils/consts.dart
macos/Runner/WhisperKitRunner.swift
pubspec.yaml
test/database/database_test.dart

This reverts #1802 which appears to have introduced occasional crashes, potentially after longer system inactivity or awakening from sleep, but these crashes didn't really appear often enough to see a clear pattern. But since they never happened before this change, it's easiest not to waste time on debugging and just revert instead.

Revert "feat: initialize WhisperKit on app startup (with config flag)"

---

lib/database/database.g.dart
lib/database/editor_db.g.dart
lib/database/fts5_db.g.dart
lib/database/logging_db.g.dart
lib/database/settings_db.g.dart
lib/database/sync_db.g.dart
pubspec.lock
pubspec.yaml

This PR reverts #1819 because of so far inexplicable and annoying freezes in the mobile app, which never happened before. The only way to get out was to kill the app and restart. Installing an older version from TestFlight immediately fixed the issue.

chore: revert drift update & update dependencies

---

ios/Podfile.lock
lib/features/sync/matrix/send_message.dart
macos/Podfile.lock
pubspec.lock
pubspec.yaml

This PR adds awaiting the sending of binary files (audio files and images). Previously, sending files would silently fail when there was an issue (such as bad connectivity) and only sending the entry itself would be repeated. However, sending the entry itself was much less likely to fail in the first place, being at most single kilobytes, whereas binary files can be much larger. With this change, sending binary files will now be retried up to ten times as well.

feat: retry binary file sync

---

lib/beamer/beamer_app.dart
lib/blocs/audio/player_cubit.dart
lib/widgets/audio/audio_player.dart
lib/widgets/audio/audio_recording_indicator.dart
lib/widgets/misc/time_recording_indicator.dart
pubspec.yaml

This PR fixes navigation when going back to a running audio recording from the recording indicator at the bottom.
Also improves the start of an audio transcription from the audio player. Previously, starting a transcription would have stopped an ongoing playback. This is not the case any longer.

fix: audio recording navigation

---

lib/beamer/beamer_app.dart
lib/services/nav_service.dart
pubspec.yaml
test/services/nav_service_test.dart

This PR reorganizes the tabs to move tasks all the way to the left, and the calendar/time view right next to it.

feat: reorganize tabs

---

lib/features/tasks/ui/task_form.dart
lib/widgets/events/event_form.dart
pubspec.yaml

This PR adds an attempt to fix disappearing task or event forms by preventing the form to be rendered in the first place when there's not `FormKey` from the controller yet.

fix: disappearing task and event forms

---

lib/features/ai/state/ollama_prompt.dart
lib/features/ai/state/ollama_prompt_checklist.dart
lib/features/ai/ui/ai_prompt_icon_widget.dart
lib/features/ai/ui/ai_response_preview.dart
lib/features/journal/ui/widgets/entry_details/entry_detail_header.dart
lib/l10n/app_en.arb
pubspec.yaml

This PR adds an experimental feature for creating checklist from any freeform text (such as transcribed audio recordings) which Llama3 is prompted with, together with a system message that tells it to assume the text describes a task, something that needs to get done, and then to create JSON output with matching checklist items. 
The results look promising:
Text: "I need to update the dependencies of a mobile app and for that first identify which dependencies to upgrade, run an automatic upgrade, then release macOS, release iOS and create a pull request."
Text: "Okay, so I want to bake a cake and it should be some cake with fruit of the season. The season is fall and for example there are apples and plums available."
Note that this is a preview. Checklists are not actually created yet, …

feat: Llama3 generated checklists preview

---

ios/Podfile.lock
lib/features/journal/ui/widgets/entry_details/delete_icon_widget.dart
lib/features/journal/ui/widgets/entry_details/entry_detail_header.dart
lib/features/journal/ui/widgets/entry_details/share_button_widget.dart
lib/features/journal/ui/widgets/tags/tag_add.dart
lib/l10n/app_en.arb
macos/Podfile.lock
pubspec.lock
pubspec.yaml
test/widgets/journal/entry_details/delete_icon_widget_test.dart
test/widgets/journal/tags/tag_add_test.dart

This pull request focuses on refactoring various widgets in the journal UI to use `ListTile` instead of `IconButton`, and introduces a new modal sheet for extended header actions. The key changes include renaming widgets, updating their implementations, and adding new localizations.
* [`lib/features/journal/ui/widgets/entry_details/delete_icon_widget.dart`](diffhunk://#diff-0037e6b32746e213e43484c4a39f745c01f6e03f669a761bf6c40de78787ee2aL8-R9): Renamed `DeleteIconWidget` to `DeleteIconListTile` and changed its implementation from `IconButton` to `ListTile`. [[1]](diffhunk://#diff-0037e6b32746e213e43484c4a39f745c01f6e03f669a761bf6c40de78787ee2aL8-R9) [[2]](diffhunk://#diff-0037e6b32746e213e43484c4a39f745c01f6e03f669a761bf6c40de78787ee2aL46-R54)
* …

feat: modal bottom sheet for extended entry actions

---

lib/widgets/charts/utils.dart
pubspec.yaml

This pull request includes several changes to the `lib/widgets/charts/utils.dart` file and a version update in `pubspec.yaml`. The most important changes include the addition of a new import statement and a modification to the `daysInRange` function to ensure unique day strings.
Changes to `lib/widgets/charts/utils.dart`:
* Added `dart:collection` import to the file. (`lib/widgets/charts/utils.dart`)
* Modified the `daysInRange` function to return a list of unique day strings using `LinkedHashSet`. (`lib/widgets/charts/utils.dart`)
* Incremented the version number in `pubspec.yaml` from `0.9.526+2714` to `0.9.526+2715`. (`pubspec.yaml`)

fix: duplicate days in charts on day DST ends

---

lib/blocs/habits/habits_cubit.dart
pubspec.yaml

This pull request includes a few changes to improve the functionality of the `getDays` method and update the project version.
Improvements to `getDays` method:
* [`lib/blocs/habits/habits_cubit.dart`](diffhunk://#diff-2d1ab1a40de156b2d0cf1c294e16505cc07aa782affd791aa99015de6c792018L438-R442): Modified the `getDays` method to ensure that the `rangeStart` uses `now.dayAtMidnight` for more accurate day calculations.
Project version update:
* [`pubspec.yaml`](diffhunk://#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25L4-R4): Updated the project version from `0.9.527+2718` to `0.9.527+2719`.

fix: habits chart after end of DST

---

lib/features/calendar/ui/pages/day_view_page.dart
lib/features/journal/state/entry_controller.dart
lib/features/journal/ui/widgets/entry_details/entry_detail_header.dart
lib/features/speech/state/recorder_cubit.dart
lib/features/speech/ui/widgets/audio_player.dart
lib/features/speech/ui/widgets/speech_modal/language_dropdown.dart
lib/features/speech/ui/widgets/speech_modal/speech_modal.dart
lib/features/speech/ui/widgets/speech_modal/transcribe_button.dart
lib/features/speech/ui/widgets/speech_modal/transcripts_list.dart
lib/features/speech/ui/widgets/speech_modal/transcripts_list_item.dart
lib/features/sync/matrix/send_message.dart
lib/l10n/app_en.arb
lib/logic/persistence_logic.dart
pubspec.lock
pubspec.yaml

This pull request includes several changes to the speech functionality and refactoring some UI components. The most important changes include adding a new speech modal, updating the audio player widget, and refactoring icon configurations.
* [`lib/features/speech/ui/widgets/speech_modal/speech_modal.dart`](diffhunk://#diff-dcc204929b18120d674f977b7c6487a5d8361da3f8bbc4c590f7c953e2ea9487R1-R93): Added a new `SpeechModal` class to display a modal for speech functionalities, including transcription and language selection.
* [`lib/features/speech/ui/widgets/speech_modal/language_dropdown.dart`](diffhunk://#diff-b618875a44c980408f99ffd3c72691c66d0c07597158b8c857ee0d71c13fac31R1-R58): Introduced a `LanguageDropdown` widget for selecting the language in the speech modal.
* …

feat: language assignment

---

lib/database/maintenance.dart
lib/features/tasks/state/checklist_controller.g.dart
lib/features/tasks/state/checklist_item_controller.g.dart
lib/l10n/app_en.arb
lib/pages/settings/advanced/maintenance_page.dart
pubspec.lock
pubspec.yaml

This pull request introduces a new feature to sync categories in the maintenance section of the application. The changes include adding a new method to handle the synchronization process, updating the localization file, and modifying the settings page to include this new feature.
* [`lib/database/maintenance.dart`](diffhunk://#diff-3181a930a3fc0b654a42fa7e456f4dfa84a2f85258cc79a07387dca90852cd66R148-R161): Added a new method `syncCategories` to the `Maintenance` class to handle the synchronization of categories. This method retrieves categories from the database and enqueues sync messages for each category.
* [`lib/l10n/app_en.arb`](diffhunk://#diff-9796fde3771f42a3a759ccc941731d83f96037a661e47dde27ce81d3447a69c2R159): Added a new localization string `maintenanceSyncCategories` for the …

feat: add maintenance task for resyncing categories

---

integration_test/matrix_service_test.dart
lib/features/sync/matrix/last_read.dart
lib/features/sync/matrix/matrix_service.dart
lib/features/sync/matrix/timeline.dart

This pull request includes several changes to the `integration_test/matrix_service_test.dart`, `lib/features/sync/matrix/last_read.dart`, `lib/features/sync/matrix/matrix_service.dart`, and `lib/features/sync/matrix/timeline.dart` files. The changes primarily focus on improving dependency injection and adding support for overridden databases in various components.
Improvements to dependency injection and support for overridden databases:
* [`integration_test/matrix_service_test.dart`](diffhunk://#diff-e5a55efa9a1b47bf1cfbc486a12993b5ce794be50641fbd1abbda132b7ddbe7fL56-L59): Removed redundant singleton registrations and added delayed initialization for `UpdateNotifications` and `UserActivityService`. [[1]](diffhunk://#diff-e5a55efa9a1b47bf1cfbc486a12993b5ce794be50641fbd1abbda132b7ddbe7fL56- …

test: add timeout in matrix test

---

lib/features/tasks/state/task_progress_controller.dart
lib/features/tasks/ui/linked_duration.dart
lib/services/time_service.dart
pubspec.yaml

This pull request includes several changes to improve the functionality and performance of the task progress feature, as well as some minor cleanup and version update.
* [`lib/features/tasks/state/task_progress_controller.dart`](diffhunk://#diff-2da69635ef99953c40fad916edf5865f880d5a5b80daea2e9a39a637aa1e6e4bR40-R43): Added a check to ensure that the `_timeService.linkedFrom` ID matches the `entryId` before processing the `journalEntity` in the `_timeServiceSubscription` listener.
* [`lib/features/tasks/ui/linked_duration.dart`](diffhunk://#diff-c891b98fa54e4a178b12f6c86b356b29d038dec83db935cb0a50678b9b59ad8eL23-R26): Modified the `LinkedDuration` widget to return an empty `SizedBox` if the state is `null` or the `estimate` is zero, preventing unnecessary UI updates.
* …

fix: time recording progress indicator

---

ios/Podfile.lock
lib/services/time_service.dart
macos/Podfile.lock
pubspec.lock
pubspec.yaml

This pull request includes a small change to the `pubspec.yaml` file and a minor update to the `TimeService` class in `lib/services/time_service.dart`.
* Updated the version number in `pubspec.yaml` from `0.9.542+2765` to `0.9.542+2766` to reflect the new changes.
* Added a comment to ignore the unused local variable warning for the `i` variable in the `TimeService` class and removed the underscore from the variable name.

chore: upgrade dependencies

---

lib/features/ai/state/ollama_prompt.dart
lib/features/journal/repository/journal_repository.dart
lib/features/journal/state/entry_controller.dart
lib/features/speech/repository/speech_repository.dart
lib/features/speech/state/asr_service.dart
lib/features/speech/state/recorder_cubit.dart
lib/features/speech/ui/widgets/speech_modal/transcripts_list_item.dart
lib/features/tasks/state/checklist_controller.dart
lib/features/tasks/state/checklist_item_controller.dart
lib/logic/create/create_entry.dart
lib/logic/image_import.dart
lib/logic/persistence_logic.dart
lib/services/time_service.dart
pubspec.yaml
test/features/journal/state/entry_controller_test.dart
test/logic/persistence_logic_test.dart
test/widgets/journal/entry_details/delete_icon_widget_test.dart

This pull request introduces significant changes to the codebase, primarily focusing on the refactoring of persistence logic by moving it into dedicated repository classes. The changes improve the organization and maintainability of the code. The most important changes include the creation of the `JournalRepository` and `SpeechRepository` classes, and the refactoring of various classes to use these new repositories instead of directly using `PersistenceLogic`.
Repository creation and refactoring:
* Created `JournalRepository` class to handle journal-related database operations, including methods for creating, updating, and deleting journal entries. (`lib/features/journal/repository/journal_repository.dart`)
* Created `SpeechRepository` class to handle speech-related database operations, …

refactor: extract persistence logic

---

lib/features/calendar/ui/pages/day_view_page.dart
pubspec.yaml

This pull request includes changes to the `lib/features/calendar/ui/pages/day_view_page.dart` and `pubspec.yaml` files. The changes involve removing icon configurations from the day view widget, which does seem to fix the previously non-functional and differently styled left navigation button.
Changes to `day_view_page.dart`:
* Removed `leftIconConfig` and `rightIconConfig` from the `_DayViewWidgetState` class.
Changes to `pubspec.yaml`:
* Updated the project version from `0.9.545+2779` to `0.9.546+2780`.

fix: left icon navigation icon in day view not working

---

lib/features/journal/repository/journal_repository.dart
lib/features/journal/state/linked_from_entries_controller.dart
lib/features/journal/state/linked_from_entries_controller.g.dart
lib/features/journal/ui/pages/entry_details_page.dart
lib/features/journal/ui/widgets/entry_detail_linked_from.dart
pubspec.yaml

This pull request introduces improvements to the journal module. The most significant changes include the addition of a new method in the `JournalRepository`, the creation of a new `LinkedFromEntriesController` class, and updates to the `LinkedFromEntriesWidget` to use Riverpod for state management.
* [`lib/features/journal/repository/journal_repository.dart`](diffhunk://#diff-001fbe4c939fb8084bdbcd1691a4bbe931c8bc39e39095f375c9b18f24ace751R216-R223): Added a new method `getLinkedToEntities` to fetch journal entities linked to a specific entity.
* [`lib/features/journal/state/linked_from_entries_controller.dart`](diffhunk://#diff-a7809f3531f4a2c829e6ed85da8618e4fc97e59994746458d1b40176f20c08f6R1-R48): Introduced a new `LinkedFromEntriesController` class to manage state and handle updates …

refactor: replace StreamBuilder

---

lib/features/ai/ui/ai_prompt_icon_widget.dart
lib/features/journal/ui/widgets/create/create_entry_action_modal.dart
lib/features/journal/ui/widgets/entry_details/header/extended_header_modal.dart
lib/features/journal/ui/widgets/tags/tags_modal.dart
lib/features/sync/matrix/process_message.dart
lib/services/db_notification.dart
lib/themes/theme.dart
pubspec.yaml

This pull request includes updates to the notification system to handle synchronization events separately, as well as a version bump for the project.
* [`lib/features/sync/matrix/process_message.dart`](diffhunk://#diff-516296985799d96f1a86244d20a4ac6ba3b90d268b1ee528cc1f8f6d62fd38bcL51-R61): Updated `processMatrixMessage` and `entryLink` methods to include a `fromSync` parameter when calling `updateNotifications.notify`.
* [`lib/services/db_notification.dart`](diffhunk://#diff-72c616bb37b79ef3dad4470d8ea99adc0acbca2db53e8c727c04c6ffa7579bcbR8-R24): Modified the `UpdateNotifications` class to handle a separate set of affected IDs for sync events and introduced a new timer for these events. [[1]](diffhunk://#diff-72c616bb37b79ef3dad4470d8ea99adc0acbca2db53e8c727c04c6ffa7579bcbR8-R24) …

feat: only publish sporadic update notifications from sync

---

lib/features/tasks/ui/time_recording_icon.dart
pubspec.lock
pubspec.yaml

This pull request includes changes to the `lib/features/tasks/ui/time_recording_icon.dart` file and the `pubspec.yaml` configuration file. The main focus is on removing the `avatar_glow` dependency and its usage in the codebase.
* [`lib/features/tasks/ui/time_recording_icon.dart`](diffhunk://#diff-a527c7a200928901da93e05cf8aed001e0b7a50cffe7311e5b8f71b141e2131bL1): Removed the import statement for `avatar_glow` package.
* [`lib/features/tasks/ui/time_recording_icon.dart`](diffhunk://#diff-a527c7a200928901da93e05cf8aed001e0b7a50cffe7311e5b8f71b141e2131bL35-L41): Removed the `AvatarGlow` widget from `TimeRecordingIcon` class and replaced it with `ColorIcon`.
* [`lib/features/tasks/ui/time_recording_icon.dart`](diffhunk://#diff-a527c7a200928901da93e05cf8aed001e0b7a50cffe7311e5b8f71b141e2131bL …

feat: remove expensive animation

---

lib/features/sync/outbox/outbox_service.dart
lib/widgets/charts/dashboard_health_chart.dart
pubspec.yaml

This PR adds small delays of non-critical functionality to improve rendering performance.
From GitHub Copilot:
This pull request includes several changes to improve the functionality and performance of the `lotti` application. The most important changes include adding a delay in the `OutboxService`, modifying the initialization of the `DashboardHealthChart` to account for test environments, and updating the application version.
Performance improvements:
* [`lib/features/sync/outbox/outbox_service.dart`](diffhunk://#diff-faf3f488a7f4fded6bcc246677a38fa8ff54b6133ce00418a05ee11ed1f6ac6cR48): Added a 200-millisecond delay in the `enqueueMessage` method to improve synchronization timing.
Test environment handling:
* [`lib/widgets/charts/dashboard_health_chart.dart`](diffhunk://#diff-213b9ff416a …

feat: add delays for less lag

---

ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
macos/Runner.xcodeproj/project.pbxproj
macos/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
pubspec.lock
pubspec.yaml

This pull request includes updates to version numbers and dependencies for both iOS and macOS projects, as well as a minor version update for the `pubspec.yaml` file. The most important changes include updating the `whisperkit` package version and its corresponding revision.
Dependency updates:
* [`ios/Runner.xcodeproj/project.pbxproj`](diffhunk://#diff-413fd2395fd4377132c8c1135c9bc9ab215c6f97322d27717a487223bd03e2c7L616-R616): Updated `whisperkit` package version from `0.9.4` to `0.10.1`.
* [`ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved`](diffhunk://#diff-6dd9bba242a295a8b13064d176cb756ffb0b74a544fe2ef58341f6a0e3290e9aL27-R28): Updated `whisperkit` package version from `0.9.4` to `0.10.1` and its revision to `63d955bc99e4dce9ba3e733f2f8815b9a9f53eee`.
* …

chore: upgrade Flutter dependencies & WhisperKit

---

lib/classes/journal_entities.dart
lib/database/database.dart
lib/features/calendar/ui/time_by_category_chart_card.dart
lib/features/dashboards/state/health_chart_controller.dart
lib/features/dashboards/state/health_chart_controller.g.dart
lib/features/dashboards/state/measurables_controller.g.dart
lib/features/speech/ui/widgets/transcription_progress_modal.dart
lib/features/sync/ui/homeserver_config_page.dart
lib/features/sync/ui/matrix_logged_in_config_page.dart
lib/features/sync/ui/matrix_stats_page.dart
lib/features/sync/ui/room_config_page.dart
lib/features/sync/ui/unverified_devices_page.dart
lib/logic/persistence_logic.dart
lib/utils/modals.dart
lib/widgets/charts/dashboard_health_bp_chart.dart
lib/widgets/charts/dashboard_health_chart.dart
lib/widgets/charts/time_series/time_series_bar_chart.dart
lib/widgets/charts/time_series/time_series_line_chart.dart
lib/widgets/misc/wolt_modal_config.dart
pubspec.yaml

This PR replaces the StreamBuilder previously used in health charts with a riverpod controller, with caching which improves UX by reducing latency on reload. Also less load on the database as the StreamBuilder doesn't rebuild on every database insert. Also adds some small chart improvements.
From GitHub Copilot:
This pull request includes several changes aimed at enhancing the functionality and consistency of the codebase. The most important changes include adding new methods for handling quantitative entries, updating the padding configuration for modal widgets, and introducing new controllers for health data.
* [`lib/classes/journal_entities.dart`](diffhunk://#diff-033cb11f85b85b702b7d046dfe9420035dd9024230f3da59f6ad864bb48132a7R222-R226): Added handling for `QuantitativeEntry` in the …

feat: use controller in health charts & chart improvements

---

lib/database/database.dart
lib/database/database.drift
lib/database/database.g.dart
lib/widgets/charts/dashboard_health_bp_chart.dart
pubspec.yaml
test/widgets/charts/dashboard_health_test.dart

From GitHub Copilot:
This pull request includes several changes to the `lib/database` and `lib/widgets/charts` directories, as well as updates to the `pubspec.yaml` and test files. The primary focus is on refactoring database queries and updating the `DashboardHealthBpChart` widget to use Riverpod for state management.
Database refactoring:
* Removed the `watchQuantitativeByTypes` method and its corresponding SQL query from `lib/database/database.dart`, `lib/database/database.drift`, and `lib/database/database.g.dart`. This method and query were used to fetch quantitative entries by types within a date range. [[1]](diffhunk://#diff-58403ca793c79f9cac8520ba22f0b9cb3527232f194f5feefdda0a1089aff2b1L743-L752) [[2]](diffhunk://#diff-f15738f2bc6c1b31110fb4764da8e38d087199352136230dff90e7af2390d3 …

refactor: use controller in BP chart

---

lib/database/database.dart
lib/get_it.dart
lib/widgets/charts/dashboard_health_bmi_chart.dart
lib/widgets/misc/desktop_menu.dart
pubspec.yaml
test/database/database_test.dart
test/logic/persistence_logic_test.dart
test/pages/dashboards/dashboard_page_test.dart
test/pages/journal/entry_detail_page_test.dart
test/widgets/charts/dashboard_health_test.dart

From GitHub Copilot:
This pull request involves significant refactoring and cleanup of the `JournalDb` class, as well as updates to the `DashboardHealthBmiChart` widget. The changes include the removal of several stream methods from `JournalDb`, modifications to the `DashboardHealthBmiChart` to use Riverpod for state management, and updates to various tests to reflect these changes.
* Removed multiple stream methods from the `JournalDb` class, including `watchJournalEntitiesByTag`, `watchJournalByTagIds`, `watchLinkedEntities`, `watchLinkedEntityIds`, `watchLinkedToEntities`, `watchFlaggedImport`, `watchActiveConfigFlagNames`, and `watchQuantitativeByType`. [[1]](diffhunk://#diff-58403ca793c79f9cac8520ba22f0b9cb3527232f194f5feefdda0a1089aff2b1L350-L375) …

refactor: remove stream builder & stream queries

---

lib/blocs/journal/journal_page_cubit.dart
lib/l10n/app_en.arb
lib/widgets/search/task_category_filter.dart
pubspec.yaml

From Copilot:
This pull request includes several changes to enhance the task category filtering functionality and update the project version. The most important changes include adding a new method to select all categories, updating localization strings, and modifying the task category filter widget.
Enhancements to task category filtering:
* [`lib/blocs/journal/journal_page_cubit.dart`](diffhunk://#diff-33f77896ed78898e42dd43a1ddeb6fda349c8ca55068b2ec7c71a45a6aa833b3R199-R205): Added a new method `selectedAllCategories` to select all task categories.
* [`lib/widgets/search/task_category_filter.dart`](diffhunk://#diff-29c84a73f13e7666ad8fee568e05bca76c0479eeb955d6c0cc55a576b05012efR74-R79): Added a new `FilterChoiceChip` to allow users to select all task categories.
Localization updates:
* …

feat: add button for selecting all category ids, including not set

---

lib/blocs/habits/habits_cubit.dart
lib/database/database.dart
lib/database/database.drift
lib/database/database.g.dart
lib/services/db_notification.dart
pubspec.yaml

This PR makes queries faster by adding composite indices and reducing the timespan in the habit completions query to what is actually selected, not 180 days, which both reduces the time needed for the database query and for deserializing the contained JSON and running computations on the result.
From Copilot:
This pull request includes multiple changes to the `habits_cubit.dart` and `database` files to improve performance and functionality. The most important changes include removing the `rxdart` dependency, modifying the `startWatching` method to simplify the logic, updating the database schema version, and adding new indices to the database.
Improvements to `habits_cubit.dart`:
* Removed `rxdart` dependency from `lib/blocs/habits/habits_cubit.dart` and simplified the `startWatching` …

feat: use composite SQLite indices

---

lib/features/journal/ui/widgets/entry_details/habit_summary.dart
lib/features/journal/ui/widgets/entry_details_widget.dart
lib/features/journal/ui/widgets/helpers.dart
lib/features/journal/ui/widgets/journal_card.dart
pubspec.yaml

From Copilot:
This pull request includes several changes to the `lib/features/journal/ui/widgets` directory to improve the flexibility and functionality of the `HabitSummary` and other related widgets. The most important changes include adding a new padding property, improving text wrapping, and updating the checklist item rendering.
* Added a new `paddingBottom` property to the `HabitSummary` class to allow for more flexible padding configuration. (`lib/features/journal/ui/widgets/entry_details/habit_summary.dart`) [[1]](diffhunk://#diff-ef813b4a3fc8664e1f65f9dbb47db0d73863b387c3aef23736cd7f0383d38f5fR14) [[2]](diffhunk://#diff-ef813b4a3fc8664e1f65f9dbb47db0d73863b387c3aef23736cd7f0383d38f5fR23)
* Updated the `Padding` widget within `HabitSummary` to utilize the new `paddingBottom` …

feat: add color coding in checklist card & spacing

---

lib/database/database.dart
lib/database/database.drift
lib/database/database.g.dart
lib/features/calendar/state/day_view_controller.dart
lib/features/calendar/state/day_view_controller.g.dart
lib/features/calendar/state/time_by_category_controller.dart
lib/features/calendar/state/time_by_category_controller.g.dart
lib/features/tasks/state/checklist_controller.g.dart
pubspec.lock
pubspec.yaml

From Copilot:
This pull request introduces new functionality for retrieving sorted calendar entries within a specified date range and updates related code to use this new functionality. The changes span multiple files, including database queries and controller classes.
Key changes include:
* Added a new method `sortedCalendarEntries` to the `JournalDb` class to fetch sorted calendar entries within a date range (`lib/database/database.dart`).
* Introduced a new SQL query `sortedCalenderEntriesInRange` to select entries from the `journal` table based on date range and entry type (`lib/database/database.drift`).
* Added the `sortedCalenderEntriesInRange` method to the generated database class to support the new query (`lib/database/database.g.dart`).
* Updated `DayViewController` to use the …

feat: bring back workouts in calendar view

---

lib/features/dashboards/state/workout_chart_controller.dart
pubspec.yaml

From Copilot:
This pull request includes updates to the `workout_chart_controller.dart` and `pubspec.yaml` files. The most important changes involve adding a new import and initializing a health data fetch operation in the `WorkoutChartDataController` constructor.
Initialization improvements:
* [`lib/features/dashboards/state/workout_chart_controller.dart`](diffhunk://#diff-3502a1418b6ea04b8b2b01617db33962f46d5889608df79d3734d0dc9a0f9ac7R18-R21): Added a call to `getWorkoutsHealthDataDelta` in the `WorkoutChartDataController` constructor to initialize health data fetching.
Dependency updates:
* [`lib/features/dashboards/state/workout_chart_controller.dart`](diffhunk://#diff-3502a1418b6ea04b8b2b01617db33962f46d5889608df79d3734d0dc9a0f9ac7R8): Added import for `health_import.dart` to …

feat: bring back workout import

---

lib/features/sync/matrix/send_message.dart
pubspec.yaml

This pull request includes several changes to improve error handling in the `MatrixService` and a version bump in the `pubspec.yaml` file. The most important changes include adding exceptions for various error conditions in the `send_message.dart` file.
Error handling improvements in `send_message.dart`:
* Added an exception for unverified Matrix devices. (`lib/features/sync/matrix/send_message.dart`)
* Added an exception for missing configuration. (`lib/features/sync/matrix/send_message.dart`)
* Added an exception for failed text message sending. (`lib/features/sync/matrix/send_message.dart`)
* Added an exception for failed file sending. (`lib/features/sync/matrix/send_message.dart`)
* Bumped the version in `pubspec.yaml` from `0.9.553+2824` to `0.9.554+2825`. …

feat: improve matrix service send & retry

---

ios/Runner.xcodeproj/project.pbxproj
ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
macos/Runner.xcodeproj/project.pbxproj
macos/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
macos/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
pubspec.lock
pubspec.yaml

From Copilot:
This pull request includes updates to several dependencies and version numbers across multiple files. The most important changes are as follows:
Dependency updates:
* [`ios/Runner.xcodeproj/project.pbxproj`](diffhunk://#diff-413fd2395fd4377132c8c1135c9bc9ab215c6f97322d27717a487223bd03e2c7L616-R616): Updated `whisperkit` dependency version from `0.10.1` to `0.10.2`.
* [`macos/Runner.xcodeproj/project.pbxproj`](diffhunk://#diff-ec40d5406d2e5b54c265f64285bf1f073febb06b92a906239f8905a6244e68efL711-R711): Updated `whisperkit` dependency version from `0.10.1` to `0.10.2`.
* [`pubspec.yaml`](diffhunk://#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25L48-R48): Updated `fl_chart` dependency version specification to `0.70.0` without the caret (^) symbol.
Version …

chore: upgrade Whisperkit and Flutter dependencies

---

lib/features/journal/state/entry_controller.dart
lib/features/tasks/ui/task_form.dart
lib/logic/persistence_logic.dart
pubspec.yaml

From Copilot:
This pull request includes several changes to the `EntryController`, `TaskForm`, `PersistenceLogic`, and `pubspec.yaml` files to improve task status handling and update the app version.
Improvements to task status handling:
* [`lib/features/journal/state/entry_controller.dart`](diffhunk://#diff-073fb67f5d87a4ca641101e845ee4b45cc2cdb2ee4a6cd4698bb94093921c235L184-L193): Removed the status update logic from the `updateTask` method and added a new `updateTaskStatus` method to handle status updates separately. [[1]](diffhunk://#diff-073fb67f5d87a4ca641101e845ee4b45cc2cdb2ee4a6cd4698bb94093921c235L184-L193) [[2]](diffhunk://#diff-073fb67f5d87a4ca641101e845ee4b45cc2cdb2ee4a6cd4698bb94093921c235R234-R249)
* [`lib/features/tasks/ui/task_form.dart`](diffhunk://#diff-c2f40a14894d9668c8 …

fix: update task status in task form when changed via sync

---

lib/blocs/journal/journal_page_cubit.dart
lib/database/database.dart
lib/database/database.drift
lib/database/database.g.dart
lib/features/journal/ui/widgets/journal_card.dart
lib/l10n/app_en.arb
lib/widgets/app_bar/journal_sliver_appbar.dart
pubspec.yaml
test/features/journal/ui/pages/entry_detail_page_test.dart
test/features/journal/ui/pages/infinite_journal_page_test.dart
test/features/journal/ui/widgets/editor/editor_widget_test.dart
test/features/journal/ui/widgets/entry_details/delete_icon_widget_test.dart
test/features/journal/ui/widgets/entry_details/entry_datetime_widget_test.dart
test/features/journal/ui/widgets/entry_details/entry_detail_footer_test.dart
test/features/journal/ui/widgets/entry_details/entry_detail_header_test.dart
test/features/journal/ui/widgets/entry_details/measurement_summary_test.dart
test/features/journal/ui/widgets/entry_details/share_button_widget_test.dart
test/features/journal/ui/widgets/entry_details/survey_summary_test.dart
test/features/journal/ui/widgets/entry_details/workout_summary_test.dart
test/features/journal/ui/widgets/journal_card_test.dart
test/features/journal/ui/widgets/tags/tag_add_test.dart
test/features/journal/ui/widgets/tags/tag_widget_test.dart
test/features/journal/ui/widgets/tags/tags_modal_widget_test.dart
test/features/journal/ui/widgets/tags/tags_view_widget_test.dart
test/widgets/journal/journal_card_test.dart

From Copilot:
This pull request introduces several changes to the `Journal` feature, focusing on adding category filtering capabilities and renaming test files for better organization. The most important changes include updates to the database queries to support category filtering, adjustments to the UI to display category information, and renaming test files to reflect their new locations.
* [`lib/blocs/journal/journal_page_cubit.dart`](diffhunk://#diff-33f77896ed78898e42dd43a1ddeb6fda349c8ca55068b2ec7c71a45a6aa833b3R361-R362): Added logic to include category IDs in the query parameters for fetching journal entries.
* [`lib/database/database.dart`](diffhunk://#diff-58403ca793c79f9cac8520ba22f0b9cb3527232f194f5feefdda0a1089aff2b1R254): Updated the `JournalDb` class to handle category IDs …

feat: add category filter in Logbook tab

---

lib/features/ai/state/ollama_task_summary.dart
lib/features/ai/state/ollama_task_summary.g.dart
lib/features/ai/ui/ai_popup_menu.dart
lib/features/ai/ui/task_summary/ai_task_summary_list_tile.dart
lib/features/ai/ui/task_summary/ai_task_summary_view.dart
lib/l10n/app_en.arb
lib/themes/theme.dart
pubspec.lock
pubspec.yaml

This PR contains using a different Ollama client that allows image analysis when using a multimodal model such as `llama3.2-vision:latest`. For now the task summary is hidden though as this doesn't work yet when a task contains multiple images, such as screenshots. The feature will be enabled in a future PR. For now, I just want to get using the [`ollama`](https://pub.dev/packages/ollama) into main. Also contains a styling change for better contrast between cards and background.
From Copilot:
This pull request includes several changes focused on enhancing the AI task summary functionality and adding support for processing images. The most important changes include updating the `AiTaskSummaryController` to handle images, modifying the UI to support image processing, and updating the …

feat: create ollama task summary with images WIP

---

lib/features/calendar/ui/pages/day_view_page.dart
lib/features/journal/ui/widgets/editor/editor_toolbar.dart
pubspec.yaml

This PR fixes an issue with underlining text where saving would fail by removing the underline button from the editor toolbar. Personally, I never noticed because I never feel the need to underline text, and it#s not supported in Markdown anyway. Also improves the app bar style in the calendar view.
From Copilot:
This pull request includes changes to the UI components and version update of the `lotti` application. The most important changes include updates to the `DayViewWidget` and `ToolbarWidget` for improved UI consistency, and a version increment in the `pubspec.yaml` file.
UI improvements:
* [`lib/features/calendar/ui/pages/day_view_page.dart`](diffhunk://#diff-7016e6cb4d6c181db092e926d0bd9d094abd1c1e54f5d58ca7d8f26ce1c276ffL125-R137): Modified the header style to use the primary …

fix: save issue when underlining text

---

lib/features/ai/state/ollama_image_analysis.g.dart
lib/features/journal/repository/clipboard_repository.dart
lib/features/journal/repository/clipboard_repository.g.dart
lib/features/journal/state/entry_controller.g.dart
lib/features/journal/state/image_paste_controller.dart
lib/features/journal/state/image_paste_controller.g.dart
lib/features/journal/ui/widgets/create/create_entry_action_modal.dart
lib/features/journal/ui/widgets/create/paste_image_list_tile.dart
lib/l10n/app_en.arb
lib/logic/image_import.dart
pubspec.yaml
test/features/journal/state/image_paste_controller_test.dart
test/features/journal/ui/widgets/create/paste_image_list_tile_test.dart

This PR adds pasting images from the clipboard.
From Copilot:
This pull request introduces a new feature for handling image pasting from the clipboard and includes several related changes across multiple files. The main changes involve adding the capability to read images from the clipboard, updating the UI to include an option for pasting images, and adding tests for the new functionality.
* [`lib/features/journal/repository/clipboard_repository.dart`](diffhunk://#diff-ee1ac8ffe911d22eb1527daf932b23cabc61d59c256269fc033dffa697c98806R1-R10): Introduced a new repository for accessing the system clipboard using `SystemClipboard`.
* [`lib/features/journal/state/image_paste_controller.dart`](diffhunk://#diff-53bb7ef0b19f0a4ad93ad83cfac32f47b9b9dd04b9f54231401770a96d894ff7R1-R54): Added …

feat: paste image from clipboard

---

lib/features/surveys/tools/run_surveys.dart
lib/utils/modals.dart
pubspec.yaml
test/utils/modals_test.dart

From Copilot:
This pull request includes several changes to improve the `ModalUtils` class and its usage in the project, along with a version update in the `pubspec.yaml` file. The most important changes include fixing a context parameter, updating modal background color, adding comprehensive tests for `ModalUtils`, and updating the project version.
* [`lib/features/surveys/tools/run_surveys.dart`](diffhunk://#diff-bbdfc5301a494b4cc6f2e8fa41f36f3d85f16078db9613dc401ced74500d0280L24-R24): Fixed the context parameter in the `pageListBuilder` method to use the correct context.
* [`lib/utils/modals.dart`](diffhunk://#diff-4ac64a38abf5cd5347344b350fdbe625465bb437bb80e553bc3de1f2ccbcfebbL29-R29): Updated the modal background color to use `surfaceContainerHigh` instead of `surfaceContainerLow`. …

fix: illegible text in modal due to wrong background color

---

pubspec.lock
pubspec.yaml

This pull request includes minor version updates and a dependency downgrade in the `pubspec.yaml` file.
* Updated the version of the `lotti` package from `0.9.567+2875` to `0.9.567+2876`.
Dependency changes:
* Downgraded the `matrix` dependency from `^0.37.0` to `^0.36.0`.

chore: revert matrix upgrade for testing

---

lib/database/maintenance.dart
lib/l10n/app_en.arb
lib/pages/settings/advanced/maintenance_page.dart
pubspec.yaml

This PR adds a workaround for audio model files occasionally getting corrupted, in which case every attempt to run speech recognition results in a hard crash. It would be better to properly handle this on the Swift side, but deleting the entire folder is easier right now and also solves the issue. Once deleted, the audio models need to be downloaded again, which can take a while.
From Copilot:
This pull request includes several changes to add a new feature for purging audio models and updating the localization files. Additionally, there are some minor updates to dependencies and versioning. The most important changes include the addition of the `purgeAudioModels` method, updates to the settings page to include this new feature, and localization updates.
* …

chore: add maintenance task for purging audio models

---

lib/features/ai/ui/ai_popup_menu.dart
lib/features/ai/ui/ai_response_summary.dart
lib/features/ai/ui/image_analysis/ai_image_analysis_list_tile.dart
lib/features/ai/ui/task_summary/ai_task_summary_list_tile.dart
lib/features/categories/ui/widgets/category_field.dart
lib/features/categories/ui/widgets/select_color_field.dart
lib/features/journal/ui/widgets/create/create_entry_action_modal.dart
lib/features/journal/ui/widgets/entry_detail_linked.dart
lib/features/journal/ui/widgets/entry_details/entry_datetime_widget.dart
lib/features/journal/ui/widgets/entry_details/header/extended_header_modal.dart
lib/features/speech/ui/widgets/speech_modal/speech_modal.dart
lib/features/speech/ui/widgets/transcription_progress_modal.dart
lib/features/sync/ui/re_sync_modal.dart
lib/utils/modals.dart
lib/widgets/app_bar/journal_sliver_appbar.dart
lib/widgets/date_time/datetime_bottom_sheet.dart
lib/widgets/date_time/datetime_field.dart
lib/widgets/search/task_filter_icon.dart
lib/widgets/settings/dashboards/dashboard_category.dart
pubspec.yaml
test/utils/modals_test.dart

This PR replaces one more occurrence of `showModalBottomSheet` with `ModalUtils.showSinglePageModal`. Eventually, they should all use the latter.
From Copilot:
This pull request includes several updates to the `ModalUtils.showSinglePageModal` method across multiple files to specify a return type of `void`. Additionally, there are changes to the `ModalUtils` class to include new parameters for `padding` and `navBarHeight`. Below are the most important changes:
Updates to `ModalUtils.showSinglePageModal` method:
* [`lib/features/ai/ui/ai_popup_menu.dart`](diffhunk://#diff-ffcb87d546496ab34540b9a3dd2913bdf15b2a0b948883c5100399372ad2e673L24-R24): Updated `ModalUtils.showSinglePageModal` to specify a return type of `void`.
* [`lib/features/ai/ui/ai_response_summary.dart`](diffhunk://#diff-5ede4 …

chore: replace show modal bottom sheet in date picker

---

lib/features/sync/matrix/client.dart
lib/features/sync/matrix/send_message.dart
lib/features/sync/outbox/outbox_service.dart
pubspec.lock
pubspec.yaml

This PR adds some logging around an intermittent sync issue. Not entirely certain what the issue might me. Could also be an issue on the server side.
From Copilot:
This pull request includes several changes to improve the functionality and error handling of the Matrix client and to update dependencies. The most important changes include modifying the `sendMatrixMsg` method to return a boolean, adding error handling in the `sendFile` method, and updating the `pubspec.yaml` file to use a newer version of the `matrix` dependency.
Improvements to error handling and functionality:
* [`lib/features/sync/matrix/send_message.dart`](diffhunk://#diff-4f804bc4768a191df8103ec9f2940225bff8df498406580833aa73b7b69d80fdL35-R35): Modified the `sendMatrixMsg` method to return a boolean instead of void, and …

fix: debug send issue

---

lib/features/categories/ui/widgets/category_field.dart
lib/features/journal/ui/widgets/entry_details/header/entry_detail_header.dart
pubspec.lock
pubspec.yaml

From Copilot:
This pull request includes several changes to the `category_field.dart` and `entry_detail_header.dart` files to enhance the category selection functionality. Additionally, there's a minor version update in the `pubspec.yaml` file.
Enhancements to category selection functionality:
* [`lib/features/categories/ui/widgets/category_field.dart`](diffhunk://#diff-f646f96452ba3bda944c07b4b941c34f47ae66283f4532f413d9fd05b4478fdcR185-R220): Added a new `CategorySelectionIconButton` class to allow users to select a category through a modal dialog. This class uses the `entryControllerProvider` to update the category ID.
* [`lib/features/journal/ui/widgets/entry_details/header/entry_detail_header.dart`](diffhunk://#diff-daa5674187c7a4aff0ab5f34c4342f4d9c9ad504ca9cd6a9b4cb55b5c7108ad6L94-R …

feat: assign entry category

---

lib/features/calendar/ui/widgets/time_by_category_chart_legend.dart
lib/features/categories/ui/widgets/category_color_icon.dart
lib/features/categories/ui/widgets/category_field.dart
lib/features/categories/ui/widgets/category_selection_icon_button.dart
lib/features/categories/ui/widgets/category_selection_modal_content.dart
lib/features/categories/ui/widgets/category_type_card.dart
lib/features/categories/ui/widgets/select_color_field.dart
lib/features/dashboards/ui/widgets/dashboards_card.dart
lib/features/habits/ui/widgets/habit_completion_card.dart
lib/features/habits/ui/widgets/habit_completion_color_icon.dart
lib/features/journal/ui/widgets/entry_details/habit_summary.dart
lib/features/journal/ui/widgets/entry_details/header/entry_detail_header.dart
lib/features/journal/ui/widgets/journal_card.dart
lib/features/tasks/ui/time_recording_icon.dart
lib/pages/settings/categories/categories_page.dart
lib/widgets/settings/dashboards/dashboard_category.dart
lib/widgets/settings/dashboards/dashboard_definition_card.dart
lib/widgets/settings/habits/habits_type_card.dart
lib/widgets/settings/settings_card.dart
pubspec.yaml
test/features/categories/ui/widgets/categories_type_card_test.dart
test/features/habits/ui/widgets/habit_completion_color_icon_test.dart
test/pages/settings/categories/categories_page_test.dart

From Copilot:
This pull request includes several changes to the category-related widgets and their usage across different parts of the project. The main changes involve the creation of new widgets for category color icons and selection modals, as well as the refactoring of existing widgets to use these new components.
* [`lib/features/categories/ui/widgets/category_color_icon.dart`](diffhunk://#diff-fac6a9218346e3c9f2976edc9e7c7fabe9b85c33c9478e5a311764141af1c721R1-R51): Introduced `ColorIcon` and `CategoryColorIcon` widgets to handle category color display.
* [`lib/features/categories/ui/widgets/category_field.dart`](diffhunk://#diff-f646f96452ba3bda944c07b4b941c34f47ae66283f4532f413d9fd05b4478fdcL2-L14): Replaced the inline `ColorIcon` implementation with the new `CategoryColorIcon` …

feat: show favorite categories first

---

lib/features/ai/ui/ai_response_summary.dart
lib/features/journal/state/entry_controller.dart
lib/features/journal/state/entry_controller.g.dart
lib/features/journal/state/linked_entries_controller.dart
lib/features/journal/state/linked_entries_controller.g.dart
lib/features/journal/ui/widgets/editor/editor_widget.dart
lib/features/journal/ui/widgets/entry_details/duration_widget.dart
lib/features/journal/ui/widgets/entry_details/entry_datetime_widget.dart
lib/features/journal/ui/widgets/entry_details/entry_detail_footer.dart
lib/features/journal/ui/widgets/entry_details/header/entry_detail_header.dart
lib/features/journal/ui/widgets/entry_details/save_button.dart
lib/features/journal/ui/widgets/entry_details_widget.dart
lib/features/speech/ui/widgets/audio_player.dart
pubspec.yaml
test/features/journal/ui/widgets/editor/editor_widget_test.dart
test/features/journal/ui/widgets/entry_details/entry_detail_footer_test.dart
test/features/journal/ui/widgets/entry_details/entry_detail_header_test.dart
test/widget_test_utils.dart

From Copilot:
This pull request includes several changes to improve the user experience and functionality of the journal feature. The most important changes involve the handling of the editor toolbar visibility, padding adjustments, and the addition of a save button in specific contexts.
* [`lib/features/journal/state/entry_controller.dart`](diffhunk://#diff-073fb67f5d87a4ca641101e845ee4b45cc2cdb2ee4a6cd4698bb94093921c235R44-R47): Updated the `EntryController` to manage the visibility of the editor toolbar more effectively by setting `_shouldShowEditorToolBar` to false when the focus is lost and the entry is not dirty. [[1]](diffhunk://#diff-073fb67f5d87a4ca641101e845ee4b45cc2cdb2ee4a6cd4698bb94093921c235R44-R47) [[2]](diffhunk://#diff-073fb67f5d87a4ca641101e845ee4b45cc2cdb2ee4a6cd4698bb94 …

feat: reorganize entry layout

---

lib/features/journal/ui/widgets/entry_details/duration_widget.dart
pubspec.yaml

From Copilot:
This pull request includes changes to the `DurationWidget` class in the `entry_details` widget and an update to the `pubspec.yaml` file. The most important changes are focused on improving the visibility logic for the recording icon in the `DurationWidget`.
Enhancements to `DurationWidget`:
* [`lib/features/journal/ui/widgets/entry_details/duration_widget.dart`](diffhunk://#diff-b271557ef3d9d6531ae6da7eff4b642aeea17b456be0081f01b835fac7fc1fcaL80-R80): Modified the visibility condition for the record icon to combine multiple checks into a single condition, ensuring the icon is only shown when `isRecent`, `showRecordIcon`, and `!isRecording` are all true.
General updates:
* [`pubspec.yaml`](diffhunk://#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25L4-R4): …

fix: hiding running time record icon

---

lib/features/tasks/state/checklist_controller.dart
lib/features/tasks/state/checklist_controller.g.dart
lib/features/tasks/ui/checklists/checklist_widget.dart
lib/features/tasks/ui/checklists/checklist_wrapper.dart
lib/widgetbook.dart
lib/widgetbook/mock_data.dart
pubspec.yaml

This PR changes the checklist display to always show the progress bar & add counts, e.g. `5/6`.
From Copilot:
This pull request includes several changes to the `ChecklistWidget` and a version update in the `pubspec.yaml` file. The most important changes involve refactoring the progress bar implementation and updating the widget structure.
Refactoring and widget structure updates:
* [`lib/features/tasks/ui/checklists/checklist_widget.dart`](diffhunk://#diff-255c40de059be69649e497177d75c60f5f9e0d8ea515e0cd98639bb18d7ab1f2L84-R86): Changed `secondChild` from `Row` to `Column` to accommodate the new progress bar.
* [`lib/features/tasks/ui/checklists/checklist_widget.dart`](diffhunk://#diff-255c40de059be69649e497177d75c60f5f9e0d8ea515e0cd98639bb18d7ab1f2R108-R120): Added a `ProgressBar` widget …

feat: always show checklist progress bar

---

lib/features/journal/ui/widgets/entry_details/entry_detail_footer.dart

The issue where the duration was displayed for both images and audio entries, has been resolved.

fix: duration widget

---

lib/features/dashboards/ui/pages/dashboard_page.dart
lib/features/dashboards/ui/widgets/charts/time_series/time_series_bar_chart.dart
lib/features/dashboards/ui/widgets/charts/time_series/time_series_line_chart.dart
lib/features/dashboards/ui/widgets/charts/time_series/utils.dart
lib/features/journal/ui/widgets/entry_details/measurement_summary.dart
lib/features/journal/ui/widgets/journal_card.dart
pubspec.yaml
test/features/journal/ui/widgets/entry_details/measurement_summary_test.dart

From Copilot:
This pull request includes multiple updates to the dashboard and chart features, focusing on improving the user interface and enhancing the data formatting.
* Removed unnecessary import `platform.dart` from `dashboard_page.dart`.
* Changed the default `timeSpanDays` value from 30 or 14 to 180 days.
* Added new segments `[180, 365]` to the `TimeSpanSegmentedControl`.
* Modified the tooltip formatting to include two decimal places for better precision.
* Added imports for `dart:math` and `intl` packages.
* Calculated and set `minY` and `maxY` values dynamically based on the data points. [[1]](diffhunk://#diff-dbd828720e6b9ac95f1d30e2b1d7b097daa075ed4a8c811133dabd6b35db5347R50-R53) [[2]](diffhunk://#diff-dbd828720e6b9ac95f1d30e2b1d7b097daa075ed4a8c811133dabd6b35db5347R149-R150) …

feat: improve dashboard chart legends & tooltips

---

lib/features/journal/state/entry_controller.dart
lib/features/journal/ui/widgets/editor/editor_widget.dart
lib/features/tasks/ui/task_form.dart
pubspec.yaml
test/features/journal/ui/widgets/editor/editor_widget_test.dart

This pull request includes several changes to improve the handling of focus and state management in the journal and task form features. The most important changes include adding an optional `requestFocus` parameter to the `setDirty` method, removing redundant focus requests, and updating tests accordingly.
* [`lib/features/journal/state/entry_controller.dart`](diffhunk://#diff-073fb67f5d87a4ca641101e845ee4b45cc2cdb2ee4a6cd4698bb94093921c235L324-R331): Added an optional `requestFocus` parameter to the `setDirty` method to control focus behavior when the dirty state is set.
* [`lib/features/tasks/ui/task_form.dart`](diffhunk://#diff-c2f40a14894d9668c8c244d4676b1ddb55c8e552328ee00bca18e5d0e12096aaL74-R77): Updated the `onChanged` callback in the `_TaskFormState` class to pass `requestFocus: …

fix: focus issue in editor

---

lib/features/ai/state/latest_summary_controller.dart
lib/features/journal/state/entry_controller.dart
lib/features/tasks/ui/checklists/checklist_widget.dart
lib/features/tasks/ui/title_text_field.dart
lib/widgets/events/event_form.dart
pubspec.yaml
test/features/journal/state/entry_controller_test.dart

From Copilot:
This pull request includes several changes to improve focus management and clean up unused code in various parts of the codebase. The most important changes include adding a `FocusNode` to the `TitleTextField` widget, cleaning up unused focus-related methods, and ensuring focus is requested appropriately when saving checklist items.
Focus management improvements:
* [`lib/features/tasks/ui/title_text_field.dart`](diffhunk://#diff-2bc39c091eb38967f3fca0ede006745549ea85b24839350c6084f367986b663aR12): Added an optional `FocusNode` parameter to the `TitleTextField` widget and ensured focus is requested when saving. [[1]](diffhunk://#diff-2bc39c091eb38967f3fca0ede006745549ea85b24839350c6084f367986b663aR12) [[2]](diffhunk://#diff-2bc39c091eb38967f3fca0ede006745549ea85b24839350c6084f …

fix: focus issues

---

lib/pages/settings/advanced/conflicts_page.dart
pubspec.yaml

From Copilot:
This pull request includes changes to the `ConflictDetailRoute` class in the `conflicts_page.dart` file to improve the handling of resolved vector clocks and adds a new button for resolving with the remote version. Additionally, there is a minor version update in the `pubspec.yaml` file.
Improvements to vector clock handling and conflict resolution:
* [`lib/pages/settings/advanced/conflicts_page.dart`](diffhunk://#diff-72352166409b550e97d1a8cf99d27df60464a2e522f0bb75783d4f5d02177248L186-R190): Renamed `withResolvedVectorClock` to `localWithResolvedVectorClock` and added `remoteWithResolvedVectorClock` for better clarity and handling of local and remote vector clocks. [[1]](diffhunk://#diff-72352166409b550e97d1a8cf99d27df60464a2e522f0bb75783d4f5d02177248L186-R190) …

feat: resolve sync conflict with remote version

---

ios/Podfile.lock
lib/blocs/settings/habits/habit_settings_cubit.dart
lib/features/ai/ui/ai_response_summary_modal.dart
lib/pages/settings/habits/habit_details_page.dart
pubspec.yaml

When editing habit details, setting the reminder time would erase the "Show From" time and vice versa. This was caused by the setShowFrom and setAlertAtTime methods creating new HabitSchedule objects without preserving existing values.

fix: time picker values being overwritten in habit settings

---

lib/features/sync/matrix/save_attachment.dart
lib/logic/image_import.dart
pubspec.yaml

This pull request includes changes to file handling and a version update. The most important changes include ensuring files are created recursively before writing data to them and updating the project version.
File handling improvements:
* [`lib/features/sync/matrix/save_attachment.dart`](diffhunk://#diff-378944b3f34329cd3294623a31175effaf0d4e22e9aba1f6f5bc33c1b00b6685L45-R46): Modified the `writeToFile` method to create the file recursively before writing bytes to it.
* [`lib/logic/image_import.dart`](diffhunk://#diff-1655f19893cbede94f77d77d222e83403d993733ea862f1f80f5dc9345be9d23L154-R154): Updated the `importPastedImages` method to create the file recursively before writing bytes to it.
* [`pubspec.yaml`](diffhunk://#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e …

fix: create directory for JSON attachments

---

lib/features/ai/repository/ai_input_repository.dart
lib/features/ai/repository/prompts.dart
lib/features/ai/state/action_item_suggestions.dart
lib/features/ai/state/action_item_suggestions.g.dart
lib/features/ai/state/action_item_suggestions_prompt.dart
lib/features/ai/state/action_item_suggestions_prompt.g.dart
lib/features/ai/state/latest_summary_controller.dart
lib/features/ai/state/latest_summary_controller.g.dart
lib/features/ai/state/ollama_image_analysis.dart
lib/features/ai/state/ollama_image_analysis.g.dart
lib/features/ai/state/task_summary_controller.dart
lib/features/ai/state/task_summary_controller.g.dart
lib/features/ai/state/task_summary_prompt.dart
lib/features/ai/state/task_summary_prompt.g.dart
pubspec.yaml
test/features/ai/repository/ai_input_repository_test.dart
test/features/ai/state/action_item_suggestions_prompt_test.dart
test/features/ai/state/task_summary_prompt_test.dart

This pull request introduces significant changes to the AI input handling and prompt generation in the `lotti` application. The main changes include the creation of new prompt generation methods, the removal of redundant code, and updates to the state controllers to use the new prompt generation methods.
* [`lib/features/ai/repository/ai_input_repository.dart`](diffhunk://#diff-dc8c7eb5401a5a4bf69e58e3db6ce50b90d6a2f491cad09f25aa889096aa1ccaR129-R150): Added a new method `buildPrompt` to generate prompts based on AI input and response type.
* [`lib/features/ai/repository/prompts.dart`](diffhunk://#diff-16344e54d34573c1cc91d3477b5e4793e5ae30b07cb28a20a6139b5b6a66ea3fR1-R66): Implemented two new functions, `createActionItemSuggestionsPrompt` and `createTaskSummaryPrompt`, to generate …

fix: remove invalidateSelf & refactoring

---

lib/database/journal_db/config_flags.dart
lib/features/ai/state/action_item_suggestions.dart
lib/features/ai/state/image_analysis.g.dart
lib/features/ai/state/latest_summary_controller.dart
lib/features/ai/state/latest_summary_controller.g.dart
lib/features/ai/state/task_summary_controller.dart
lib/features/ai/state/task_summary_controller.g.dart
lib/features/ai/ui/latest_ai_response_summary.dart
lib/pages/settings/flags_page.dart
lib/utils/consts.dart
pubspec.yaml
test/database/database_test.dart

This pull request includes multiple changes to improve the functionality and performance of the AI state management in the application. The most important changes include the addition of a timer to periodically check for outdated summaries, updates to the inference status handling, and various refactorings to optimize the codebase.
Improvements to AI state management:
* [`lib/features/ai/state/latest_summary_controller.dart`](diffhunk://#diff-b37cf4347da8e4ffa6b4b883684bd50bb0d1a18c0f122061a160307e3ad17eeaL83-R126): Added a timer in the `IsLatestSummaryOutdatedController` class to periodically check for outdated summaries and trigger updates if necessary.
* [`lib/features/ai/state/latest_summary_controller.dart`](diffhunk://#diff-b37cf4347da8e4ffa6b4b883684bd50bb0d1a18c0f122061a160307e3ad1 …

feat: automatically update task TLDR every 5s when outdated

---

lib/features/journal/ui/widgets/entry_details/header/entry_detail_header.dart
lib/features/journal/ui/widgets/entry_details/header/extended_header_items.dart
lib/features/journal/ui/widgets/entry_details/header/extended_header_modal.dart
lib/features/journal/ui/widgets/entry_details/header/initial_modal_page_content.dart
lib/features/journal/ui/widgets/tags/tag_add.dart
lib/features/speech/ui/widgets/speech_modal/speech_modal.dart
lib/features/speech/ui/widgets/speech_modal/transcribe_button.dart
lib/utils/modals.dart
pubspec.yaml
test/features/journal/ui/widgets/entry_details/header/extended_header_items_test.dart
test/features/journal/ui/widgets/entry_details/header/extended_header_modal_test.md
test/features/journal/ui/widgets/entry_details/header/initial_modal_page_content_test.dart
test/features/journal/ui/widgets/tags/tag_add_test.dart
test/features/speech/ui/widgets/speech_modal/speech_modal_test.dart

This pull request includes several changes to the journal entry details UI, focusing on enhancing the modal functionality and improving the user experience. The most important changes include the addition of new modal pages, updates to existing list tiles, and the introduction of new test cases.
* **New Modal Pages:**
- Added `InitialModalPageContent`, `TagsModal`, `SpeechModalContent`, and `TranscriptionProgressModalContent` to handle different modal views. (`lib/features/journal/ui/widgets/entry_details/header/initial_modal_page_content.dart`, [lib/features/journal/ui/widgets/entry_details/header/initial_modal_page_content.dartR1-R84](diffhunk://#diff-4e01f3b5809c6f8bfaa511ebfe118a3288db9fb3a06f9a33ec2ff55caeb8b2d0R1-R84))
- Updated `ExtendedHeaderModal` to use `WoltModalSheet` for …

feat: improve entry actions modal to use single modal with  transitions

---

lib/database/database.dart
lib/features/journal/ui/widgets/entry_details/duration_widget.dart
lib/features/journal/ui/widgets/entry_details/entry_datetime_modal.dart
lib/features/journal/ui/widgets/entry_details/entry_datetime_widget.dart
lib/services/time_service.dart
pubspec.yaml

This pull request includes several changes to improve the functionality and user experience of the journal entry features. The most significant changes include the addition of a new method to watch journal entities by ID, the introduction of a modal for editing entry date and time, and updates to the `TimeService` class to use the new watch method.
* Added a new method `watchJournalEntityById` to the `JournalDb` class to stream updates of a specific journal entity by its ID.
* Updated the `DurationWidget` to use a `GestureDetector` to show the `EntryDateTimeModal` when tapped. [[1]](diffhunk://#diff-b271557ef3d9d6531ae6da7eff4b642aeea17b456be0081f01b835fac7fc1fcaL63-R69) [[2]](diffhunk://#diff-b271557ef3d9d6531ae6da7eff4b642aeea17b456be0081f01b835fac7fc1fcaR112)
* Introduced the …

fix: updating start date did not update running timer

---

lib/features/ai/ui/ai_popup_menu.dart
lib/features/ai/ui/image_analysis/ai_image_analysis_list_tile.dart
lib/features/ai/ui/image_analysis/ai_image_analysis_view.dart
lib/features/ai/ui/task_summary/action_item_suggestions_list_tile.dart
lib/features/ai/ui/task_summary/action_item_suggestions_view.dart
lib/features/ai/ui/task_summary/ai_task_summary_list_tile.dart
lib/features/ai/ui/task_summary/ai_task_summary_view.dart
lib/features/journal/ui/widgets/entry_details/header/entry_detail_header.dart
lib/features/tasks/ui/checklists/checklist_suggestions_widget.dart
pubspec.yaml
test/features/ai/ui/ai_popup_menu_test.dart
test/features/ai/ui/image_analysis/ai_image_analysis_list_tile_test.dart
test/features/ai/ui/image_analysis/ai_image_analysis_view_test.dart
test/features/ai/ui/task_summary/action_item_suggestions_list_tile_test.dart
test/features/ai/ui/task_summary/ai_task_summary_list_tile_test.dart

This pull request includes several changes to the AI-related UI components in the project. The most important changes involve refactoring the `AiPopUpMenu` class, updating related list tiles, and modifying the views for task summary and image analysis.
* [`lib/features/ai/ui/ai_popup_menu.dart`](diffhunk://#diff-ffcb87d546496ab34540b9a3dd2913bdf15b2a0b948883c5100399372ad2e673R4-R12): Refactored `AiPopUpMenu` to use a new `AiModal` class for displaying modal sheets and updated the `journalEntity` parameter to be non-nullable. [[1]](diffhunk://#diff-ffcb87d546496ab34540b9a3dd2913bdf15b2a0b948883c5100399372ad2e673R4-R12) [[2]](diffhunk://#diff-ffcb87d546496ab34540b9a3dd2913bdf15b2a0b948883c5100399372ad2e673L17-R107)
* [`lib/features/ai/ui/image_analysis/ai_image_analysis_list_tile.dart`](diff …

feat: improve AI modal

---

ios/Podfile.lock
lib/features/speech/state/asr_service.dart
lib/features/speech/state/recorder_cubit.dart
macos/Flutter/GeneratedPluginRegistrant.swift
macos/Podfile.lock
pubspec.lock
pubspec.yaml

This pull request removes the dependency on `ffmpeg_kit_flutter` and updates audio file handling in the `AsrService` and `AudioRecorderCubit` classes. It also includes minor version updates and cleanup in the `pubspec.yaml` file.
Removal of `ffmpeg_kit_flutter`:
* [`lib/features/speech/state/asr_service.dart`](diffhunk://#diff-01cf561c7fcb33e54fbee2be986cd90095156473dfa7cbd8bef074e0b5f9fa85L6-L7): Removed the import and usage of `ffmpeg_kit_flutter` for audio file conversion. Updated the transcribe method to use the original audio file path directly. [[1]](diffhunk://#diff-01cf561c7fcb33e54fbee2be986cd90095156473dfa7cbd8bef074e0b5f9fa85L6-L7) [[2]](diffhunk://#diff-01cf561c7fcb33e54fbee2be986cd90095156473dfa7cbd8bef074e0b5f9fa85L106-R109) …

fix: remove dependency on FFmpeg, use m4a instead of aac

---

lib/beamer/locations/journal_location.dart
lib/beamer/locations/settings_location.dart
lib/beamer/locations/tasks_location.dart
lib/features/journal/repository/journal_repository.dart
lib/features/journal/ui/pages/entry_details_page.dart
lib/features/journal/ui/widgets/entry_details/duration_widget.dart
lib/features/journal/ui/widgets/journal_app_bar.dart
lib/features/tasks/ui/pages/task_details_page.dart
lib/features/tasks/ui/task_app_bar.dart
lib/services/time_service.dart
pubspec.yaml
test/features/journal/ui/pages/entry_details_page_test.dart
test/features/tasks/ui/pages/task_details_page_test.dart

This pull request includes several changes aimed at improving the `lotti` application by refactoring class names, updating imports, and enhancing functionality. The most important changes include renaming `EntryDetailPage` to `EntryDetailsPage`, updating paths and identifiers in `TasksLocation`, and adding new classes for better UI management.
* [`lib/features/journal/ui/pages/entry_details_page.dart`](diffhunk://#diff-d32e1aafdc3cba360a85b50733ac339715c6ef74ce58fa1d92f58306ea903f72L6-R21): Renamed `EntryDetailPage` to `EntryDetailsPage` and updated the corresponding state class. [[1]](diffhunk://#diff-d32e1aafdc3cba360a85b50733ac339715c6ef74ce58fa1d92f58306ea903f72L6-R21) [[2]](diffhunk://#diff-d32e1aafdc3cba360a85b50733ac339715c6ef74ce58fa1d92f58306ea903f72L35-R34)
* …

feat: task details page

---

lib/database/journal_db/config_flags.dart
lib/pages/settings/flags_page.dart
lib/utils/consts.dart
pubspec.lock
test/database/database_test.dart

This pull request removes the `allowInvalidCertFlag` configuration flag from the codebase. The changes span across multiple files to ensure the flag is completely removed.
* [`lib/database/journal_db/config_flags.dart`](diffhunk://#diff-39bb266ee30b590e88152913951d305211880bf2f73d076f1f2c6361a09ef9a5L22-L28): Removed the insertion of the `allowInvalidCertFlag` configuration flag.
* [`lib/pages/settings/flags_page.dart`](diffhunk://#diff-26b45654cc5cd447bb728098110332c878a360b41ad9b55a44c3ccbe23b1682dL32): Removed the `allowInvalidCertFlag` from the list of flags displayed on the settings page.
* [`lib/utils/consts.dart`](diffhunk://#diff-ae9c77db8d06976197004d884d06f46d46ee048af40208727501d44e346d8cc2L3): Removed the constant definition for `allowInvalidCertFlag`.
* …

chore: remove unused config flag

---

lib/pages/settings/flags_page.dart
lib/pages/settings/sliver_box_adapter_page.dart

fix: adjust header height and improve flag page scroll.
- Adjusted the height of the showcase header to ensure proper layout.
- Enabled scrolling on the config flag page to make all flags visible, including those at the bottom.

fix: adjusted the height from the showcase appbar header

---

test/features/journal/state/linked_entries_controller_test.dart
test/features/journal/state/linked_from_entries_controller_test.dart

This pull request introduces comprehensive unit tests for the `LinkedFromEntriesController` in the `test/features/journal/state/linked_from_entries_controller_test.dart` file. The tests aim to ensure the controller's functionality and reliability by mocking dependencies and simulating various scenarios.
Key additions include:
* Added mock classes for `JournalRepository`, `UpdateNotifications`, and `JournalEntity` to simulate the behavior of these dependencies.
* Implemented tests for loading linked entities on initialization, updating state when affected IDs are notified, disposing of subscriptions correctly, handling empty results, and overriding the controller with a mock implementation.
These changes ensure that the `LinkedFromEntriesController` behaves as expected under different …

test: add tests in features/journal

---

lib/pages/settings/flags_page.dart
test/pages/settings/flags_page_test.dart

fix: create a fixed order for the flags
- Use a predefined list of flag names in the exact order for them to appear
- Create a lookup table  to match the flag names with the actual flag data

fix: create a fixed order for the flags

---

lib/blocs/journal/journal_page_cubit.dart
lib/blocs/journal/journal_page_state.dart
lib/blocs/journal/journal_page_state.freezed.dart
lib/features/journal/ui/pages/infinite_journal_page.dart
pubspec.lock
pubspec.yaml
test/features/journal/ui/pages/infinite_journal_page_test.dart
test/mocks/mocks.dart

This pull request refactors the `JournalPageCubit` to improve paging functionality, updates dependencies, and enhances the user interface for infinite scrolling. Key changes include replacing the paging controller initialization logic, making the paging controller nullable, and updating the UI to handle the new paging controller state.
* The paging controller is now initialized after the `JournalPageCubit` is constructed, and the `_fetchPage` method has been updated to return a list of items instead of directly interacting with the controller. This simplifies the logic and delegates state management to the controller. [[1]](diffhunk://#diff-33f77896ed78898e42dd43a1ddeb6fda349c8ca55068b2ec7c71a45a6aa833b3L33-R35) [[2]](diffhunk://#diff-33f77896ed78898e42dd43a1ddeb6fda349c8ca55068b2ec7c71a45 …

chore: update infinite_scroll_pagination to 5.0.0

---

test/features/ai/ui/settings/prompt_input_type_selection_test.dart

This pull request introduces a comprehensive test suite for the `PromptInputTypeSelection` widget in the `test/features/ai/ui/settings/prompt_input_type_selection_test.dart` file. It includes a new `FakePromptFormController` for testing, helper methods for creating test widgets, and multiple test cases covering widget rendering, modal interactions, and state updates.
* Added `FakePromptFormController` to simulate `PromptFormController` behavior in tests, including methods to prime initial states, update live states, and track changes to required input data.
* Introduced helper methods (`createTestWidget`, `pumpWidget`, and `openModal`) to streamline test setup and interactions. These methods ensure consistent widget initialization and modal handling.
* Verified that the widget renders a …

test: add tests for input type selection

---

lib/features/journal/state/entry_controller.dart
pubspec.lock
pubspec.yaml
test/features/journal/state/entry_controller_test.dart
test/features/speech/repository/speech_repository_test.dart

This pull request includes changes to enhance the functionality of the `updateCategoryId` method in the `EntryController` class and updates the version number in the `pubspec.yaml` file. Below are the key changes:
* [`lib/features/journal/state/entry_controller.dart`](diffhunk://#diff-073fb67f5d87a4ca641101e845ee4b45cc2cdb2ee4a6cd4698bb94093921c235L169-R184): Updated the `updateCategoryId` method to ensure that linked entries with a `null` `categoryId` are also updated with the new `categoryId`. This change ensures consistency across linked entries.
* [`pubspec.yaml`](diffhunk://#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25L4-R4): Incremented the app version from `0.9.607+3042` to `0.9.607+3043`.

feat: assign category to linked entry

---

lib/database/database.dart
lib/database/maintenance.dart
lib/features/sync/ui/unverified_devices_page.dart
lib/widgets/sync/matrix/status_indicator.dart
lib/widgets/sync/matrix/unverified_devices.dart
pubspec.lock
pubspec.yaml
test/database/database_test.dart

This pull request focuses on simplifying the codebase by removing unused methods and streamlining functionality in the database and related classes. Additionally, a minor version update and cleanup of test cases were included.
* Removed unused methods such as `watchJournalEntityById`, `entryIdsByTagId`, `getJournalEntityIds`, `_selectJournalEntityIds`, `getTasksIds`, `_selectTaskIds`, `getSortedLinkedEntityIds`, and `setConfigFlag` from `JournalDb` to reduce code complexity and improve maintainability. [[1]](diffhunk://#diff-58403ca793c79f9cac8520ba22f0b9cb3527232f194f5feefdda0a1089aff2b1L247-L260) [[2]](diffhunk://#diff-58403ca793c79f9cac8520ba22f0b9cb3527232f194f5feefdda0a1089aff2b1L291-L310) [[3]](diffhunk://#diff-58403ca793c79f9cac8520ba22f0b9cb3527232f194f5feefdda0a1089aff2b1L353-L383 …

refactor: cleanup

---

lib/features/ai/state/consts.dart
lib/features/ai/ui/settings/ai_config_list_page.dart
lib/features/ai/ui/settings/preconfigured_prompt_selection_modal.dart
lib/features/ai/ui/settings/prompt_form.dart
lib/features/ai/util/preconfigured_prompts.dart
lib/l10n/app_en.arb
lib/l10n/app_localizations.dart
lib/l10n/app_localizations_de.dart
lib/l10n/app_localizations_en.dart
lib/l10n/app_localizations_es.dart
lib/l10n/app_localizations_fr.dart
lib/l10n/app_localizations_ro.dart
pubspec.yaml
test/features/ai/ui/settings/ai_config_list_page_test.dart
test/features/ai/ui/settings/preconfigured_prompt_selection_modal_test.dart
test/features/ai/util/preconfigured_prompts_test.dart

This pull request introduces several enhancements and refactors related to AI response types and preconfigured prompts. The most significant changes include the removal of the `type` field from `PreconfiguredPrompt`, the addition of an `icon` getter to `AiResponseType`, and improvements to localization support for prompt-related UI elements.
* Removed the `type` field from the `PreconfiguredPrompt` class, simplifying its structure. The `aiResponseType` field now directly handles response type-specific functionality. (`[[1]](diffhunk://#diff-afbd44c0f099151b685659a715ac044166654453365f23cbc7edd62bc52194b4L20)`, `[[2]](diffhunk://#diff-afbd44c0f099151b685659a715ac044166654453365f23cbc7edd62bc52194b4L31)`, `[[3]](diffhunk://#diff-afbd44c0f099151b685659a715ac044166654453365f23cbc7edd62bc52194b …

fix: ai config

---

ios/Podfile.lock
lib/features/ai/repository/cloud_inference_repository.dart
pubspec.lock
pubspec.yaml

This pull request includes updates to the `CloudInferenceRepository` class to fix the image URL format and changes to the `pubspec.yaml` file to increment the version number.
**Updates to image URL format:**
* [`lib/features/ai/repository/cloud_inference_repository.dart`](diffhunk://#diff-64ddb4da404a5c1b05d6a6ebedfb69a1008cf17d70c0067a368753dfc068413fL73-R73): Modified the `url` field in `ChatCompletionMessageImageUrl` to use the correct MIME type (`image/jpeg`) instead of the previous incorrect format (`image`).
**Version increment:**
* [`pubspec.yaml`](diffhunk://#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25L4-R4): Updated the version number from `0.9.611+3059` to `0.9.611+3062` for tracking changes.

fix: image analysis with Gemini

---

lib/beamer/beamer_app.dart
lib/features/ai/ui/settings/ai_settings_filter_state.dart
lib/features/ai/ui/settings/ai_settings_page.dart
lib/features/ai/ui/settings/enhanced_prompt_form.dart
lib/features/ai/ui/settings/model_management_modal.dart
lib/features/ai/ui/settings/prompt_edit_page.dart
lib/features/ai/ui/settings/prompt_form_select_model.dart
lib/features/ai/ui/settings/widgets/ai_settings_filter_chips.dart
lib/features/ai/ui/settings/widgets/ai_settings_fixed_header.dart
lib/features/ai/ui/settings/widgets/ai_settings_floating_action_button.dart
lib/features/ai/ui/settings/widgets/ai_settings_tab_bar.dart
lib/l10n/app_en.arb
lib/l10n/app_localizations.dart
lib/l10n/app_localizations_de.dart
lib/l10n/app_localizations_en.dart
lib/l10n/app_localizations_es.dart
lib/l10n/app_localizations_fr.dart
lib/l10n/app_localizations_ro.dart
pubspec.yaml
test/features/ai/ui/settings/enhanced_prompt_form_test.dart
test/features/ai/ui/settings/prompt_edit_page_test.dart
test/features/ai/ui/settings/prompt_form_select_model_test.dart
test/features/ai/ui/settings/widgets/ai_settings_filter_chips_test.dart
test/features/ai/ui/settings/widgets/ai_settings_fixed_header_test.dart
test/features/ai/ui/settings/widgets/ai_settings_floating_action_button_test.dart
test/features/ai/ui/settings/widgets/ai_settings_tab_bar_test.dart
test/features/ai/ui/settings/widgets/provider_type_selection_modal_test.dart

This pull request introduces several improvements to the AI settings and related UI components, focusing on localization, enhanced user experience, and code consistency. The key changes include replacing hardcoded strings with localized messages, adding a new extension for localized display names, and improving the prompt editing workflow.
* Replaced hardcoded strings with localized messages across various components, such as titles, descriptions, and helper texts in `ai_settings_page.dart`, `enhanced_prompt_form.dart`, and `prompt_edit_page.dart`. [[1]](diffhunk://#diff-89a0d67762cc251a9f6ee2077212c03a246f15adb3c0ea73f32d90affc5fa4d0L191-R192) [[2]](diffhunk://#diff-89a0d67762cc251a9f6ee2077212c03a246f15adb3c0ea73f32d90affc5fa4d0L265-R266) …

feat: prompt form fields

---

ios/Podfile.lock
lib/features/dashboards/config/dashboard_health_config.dart
lib/logic/health_import.dart
pubspec.lock
pubspec.yaml

This pull request includes updates to the health data configuration, authorization flow, and dependencies, along with a version bump for the application. Below is a summary of the most significant changes:
* Renamed several health data keys and their associated configurations in `dashboard_health_config.dart` to align with updated naming conventions:
- `'HealthDataType.SLEEP_ASLEEP_CORE'` → `'HealthDataType.SLEEP_LIGHT'`
- `'HealthDataType.SLEEP_ASLEEP_DEEP'` → `'HealthDataType.SLEEP_DEEP'`
- `'HealthDataType.SLEEP_ASLEEP_REM'` → `'HealthDataType.SLEEP_REM'`
* Refactored the health data authorization logic in `health_import.dart` to store the result of `requestAuthorization` in a variable (`allowed`) for reuse, ensuring consistent behavior.
* Updated the `health` package dependency from …

fix: sleep import data types & updated library

---

lib/features/ai/model/ai_config.dart
lib/features/ai/model/ai_config.freezed.dart
lib/features/ai/model/ai_config.g.dart
lib/features/ai/model/inference_model_form_state.dart
lib/features/ai/repository/cloud_inference_repository.dart
lib/features/ai/repository/unified_ai_inference_repository.dart
lib/features/ai/state/inference_model_form_controller.dart
lib/features/ai/state/inference_model_form_controller.g.dart
lib/features/ai/ui/settings/enhanced_model_form.dart
lib/features/ai/ui/settings/inference_model_edit_page.dart
lib/features/ai/ui/settings/widgets/form_components/form_error_extension.dart
lib/features/ai/util/known_models.dart
pubspec.lock
pubspec.yaml
test/features/ai/model/inference_model_form_state_test.dart
test/features/ai/repository/cloud_inference_repository_test.dart
test/features/ai/state/inference_model_form_controller_test.dart
test/features/ai/util/known_models_test.dart

This change appears to be needed with Anthropic with a fresh API key, where my limits were only 4K output tokens per minute, leading to some API error code that the limit was breached or something like that. Interestingly, I cannot reproduce this any longer since my limit got upgraded to 80K output tokens per minute with a bigger plan and/or more spending on tokens. But then another issue appeared, with some ping messages in between actual messages on the output stream, specific to Anthropic. This PR fixes that, and introduces the configurable field for maximum output tokens per request.
From copilot:
This pull request introduces a new `maxCompletionTokens` field to the `AiConfig` model and updates the related codebase to support this addition. The changes include modifications to the …

feat: add maxOutputTokens field & fix anthropic issue

---

lib/features/ai/repository/unified_ai_inference_repository.dart
pubspec.yaml
test/features/ai/repository/unified_ai_inference_repository_test.dart

This pull request introduces updates to the `UnifiedAiInferenceRepository` to include a new `provider` parameter in various methods, ensures that AI response entries are only created for non-audio entities, and updates the handling of AI transcription metadata. Additionally, the `pubspec.yaml` version is incremented, and corresponding test cases are updated to reflect the changes.
* Added a new `provider` parameter to methods such as `createAiResponseEntry` and `_handlePostProcessing` to support specifying the AI inference provider. (`lib/features/ai/repository/unified_ai_inference_repository.dart`, [[1]](diffhunk://#diff-d25b560d0f463875c11fd6d65917173029ac35d858e911af54b422b664a07884R144) [[2]](diffhunk://#diff-d25b560d0f463875c11fd6d65917173029ac35d858e911af54b422b664a07884R280) …

feat: don't create AI response entry for transcripts

---

integration_test/matrix_service_test.dart
lib/features/sync/matrix/client.dart
lib/get_it.dart
pubspec.yaml

This pull request introduces changes to integrate the `flutter_vodozemac` package into the project and refactors its initialization logic. Additionally, there is a minor version bump in `pubspec.yaml`. The most important changes include adding `flutter_vodozemac` initialization to the dependency injection setup and removing redundant initialization calls from individual components.
* [`integration_test/matrix_service_test.dart`](diffhunk://#diff-e5a55efa9a1b47bf1cfbc486a12993b5ce794be50641fbd1abbda132b7ddbe7fR8): Added `flutter_vodozemac` import and initialized it during the `setUpAll()` phase of the integration tests. [[1]](diffhunk://#diff-e5a55efa9a1b47bf1cfbc486a12993b5ce794be50641fbd1abbda132b7ddbe7fR8) [[2]](diffhunk://#diff-e5a55efa9a1b47bf1cfbc486a12993b5ce794be50641fbd1abbda132b7d …

refactor: adapt matrix integration test

---

lib/features/speech/repository/audio_recorder_repository.dart
lib/features/speech/state/recorder_controller.dart
lib/features/speech/state/recorder_controller.g.dart
lib/features/speech/state/recorder_state.dart
lib/features/speech/state/recorder_state.freezed.dart
lib/features/speech/ui/widgets/recording/README.md
lib/features/speech/ui/widgets/recording/analog_vu_meter.dart
lib/features/speech/ui/widgets/recording/audio_recording_modal.dart
pubspec.yaml
test/features/speech/state/recorder_controller_test.dart
test/features/speech/ui/widgets/recording/analog_vu_meter_test.dart
test/features/speech/ui/widgets/recording/audio_recording_indicator_test.dart
test/features/speech/ui/widgets/recording/audio_recording_modal_test.dart

This pull request introduces significant updates to the audio recording functionality, focusing on improving the VU meter visualization and adding RMS-based calculations for audio levels. Key changes include replacing the `decibels` field with `vu` and `dBFS` fields, implementing a sliding window for RMS calculations, and enhancing the configuration options for the VU meter.
* [`lib/features/speech/state/recorder_controller.dart`](diffhunk://#diff-2823dea1121b945ffd49b99b1ffbe251b8951845ac4c88adcb2d71937a20396bL17-R25): Added a circular buffer and RMS calculation logic for VU meter values, introduced `vuReferenceLevelDbfs` and `defaultVuWindowMs` constants, and updated the amplitude listener to calculate `vu` and `dBFS` values. [[1]](diffhunk://#diff-2823dea1121b945ffd49b99b1ffbe251b895184 …

fix: calculation of VU as RMS of dBFS with 0 VU as -18 dBFS avg

---

lib/beamer/beamer_app.dart
lib/features/speech/state/recorder_controller.g.dart
lib/main.dart
pubspec.yaml
test/beamer/beamer_delegates_test.dart
test/beamer/locations/calendar_location_test.dart
test/beamer/locations/dashboards_location_test.dart
test/beamer/locations/habits_location_test.dart
test/beamer/locations/journal_location_test.dart
test/beamer/locations/settings_location_test.dart
test/beamer/locations/tasks_location_test.dart

This pull request introduces several enhancements and modifications to the `beamer_app.dart` file and related tests, focusing on improving dependency injection, configurability, and test coverage for Beamer-based navigation. The changes include adding optional dependencies for better flexibility, updating the test suite to validate navigation behavior, and upgrading a development dependency.
* [`lib/beamer/beamer_app.dart`](diffhunk://#diff-350ebc719538001d1544da4250b6cf3bc2390b3308862d2232af08e8f69b1f34L32-R37): Added optional parameters (`journalDb`, `navService`, `themingCubit`, `outboxCubit`, `audioPlayerCubit`, `userActivityService`) to `AppScreen` and `MyBeamerApp` for improved configurability. These parameters default to `getIt` instances when not provided. …

test: add missing tests in router

---

lib/features/journal/ui/widgets/create/modern_create_entry_items.dart
lib/features/journal/ui/widgets/entry_detail_linked_from.dart
lib/features/journal/ui/widgets/entry_details_widget.dart
lib/features/journal/ui/widgets/list_cards/animated_modern_task_card.dart
lib/features/journal/ui/widgets/list_cards/modern_journal_card.dart
lib/widgets/modal/animated_modal_item.dart
lib/widgets/modal/animated_modal_item_with_icon.dart
lib/widgets/settings/animated_settings_cards.dart
pubspec.yaml
test/features/journal/ui/widgets/create/modern_create_entry_items_test.dart
test/features/journal/ui/widgets/entry_detail_linked_from_test.dart
test/features/journal/ui/widgets/entry_details_widget_test.dart

This pull request introduces several enhancements across the codebase, focusing on improving UI consistency, adding navigation functionality, and refining shadow behavior for card components. Additionally, it includes a minor version update in the `pubspec.yaml` file.
* [`lib/features/journal/ui/widgets/entry_detail_linked_from.dart`](diffhunk://#diff-21b7fb6475a891c47ebb336dd0c0c8ebbe3d5b4d52cd50fad843a0dbcfd6154eL43-R59): Added padding to `ModernJournalImageCard` and `ModernJournalCard` components to ensure consistent spacing.  
* [`lib/features/journal/ui/widgets/entry_details_widget.dart`](diffhunk://#diff-93ad37855c712656d71406176b0b0815f16d66de387ecedcd35ef18d990fa51aL63-R69): Wrapped `ModernJournalCard` in a `Padding` widget to improve visual alignment and added support for …

feat: improve task cards
